### PR TITLE
Restructure side dialog ui to flow from top to bottom

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Fix for Issue #2868

screen shot 2016-02-23 at 12 12 28 pm
screen shot 2016-02-23 at 12 12 35 pm
screen shot 2016-02-23 at 12 10 22 pm
screen shot 2016-02-23 at 12 10 30 pm

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Also fixed parameter editor dialog to be a QGCFlickable

**Comment by LorenzMeier** [comment]
I'm wondering if UI-wise a left-aligned checkbox on a slightly offset background (like the bar on top) might blend in visually easier compared to the line?

I don't want to over-do it, just a suggestion.

**Comment by DonLakeFlyer** [comment]
Yeah, I'm not super happy with the visual. I tried left aligned and it looked like crap. I'll fix when it makes me crazy enough since it's crappy.

**Comment by LorenzMeier** [comment]
@kd0aij FYI

**Comment by kd0aij** [comment]
Thanks. What prevents you from sizing the menu box to fit the controls? Scattering buttons and checkboxes across mostly empty space is unusual.

**Comment by DonLakeFlyer** [comment]
> What prevents you from sizing the menu box to fit the controls?

No idea what you are talking about. Can you provide a visual to explain?

**Pull request merged**
