### PR TITLE
Support for V3 flashing

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
@dagar Can you code review? I don't have any V3 boards so I can't test fully. Do you have a V3 board to test as well?

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Fix for #4440

**Comment by DonLakeFlyer** [comment]
Also can someone point me to an actual V3 board. Not quite sure what those are.

**Comment by DonLakeFlyer** [comment]
Appveyor seems confused. Re-runnning builds

**Comment by mhkabir** [comment]
image

Doesn't work yet.

**Comment by DonLakeFlyer** [comment]
Thanks @mhkabir. Working on it.

**Comment by DonLakeFlyer** [comment]
@mhkabir Can you give it another shot?

**Comment by mhkabir** [comment]
@DonLakeFlyer Works perfectly now! I checked on both v2 and v3 Pixhawks, and behaviour is as expected. The correct version is flashed, and bootloader detection is correct.

**Comment by DonLakeFlyer** [comment]
Thanks for testing @mhkabir

**Pull request merged**
