### PR TITLE
ArduPilot: Rover Frame setup support, Copter advanced tuning

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Screen Shot 2019-04-28 at 3 54 41 PM

Screen Shot 2019-04-28 at 4 16 44 PM

### CODE REVIEW

**Comment by bys1123** [comment]
Hope there has an advanced tuning page have PID table like Mission Planner.

**Comment by DonLakeFlyer** [comment]
> Hope there has an advanced tuning page have PID table like Mission Planner.

That is coming...

**Comment by DonLakeFlyer** [comment]
Looks like this:

40254789-abafc4ac-5a99-11e8-9e94-b820db5c22d2

**Comment by bys1123** [comment]
@DonLakeFlyer Thanks, I didn't try this with ardupilot yet, but when I use PX4 firmware and open this page, I always get an error about missing parameter with YAW axis.

**Comment by DonLakeFlyer** [comment]
> I and my friends always get an error about missing parameter with YAW axis

I'll take a look and fix.

**Pull request merged**
