### PR TITLE
Video Streaming URL Changed

### PR DESCRIPTION
**Pull request by mohanbabi**
**Title**: Video Streaming URL Changed

**Description**  
Updated the video streaming URL in the documentation to improve accessibility and ensure the latest information on setting up video streaming with QGroundControl.

**Test Steps**  
1. Click on the updated **Video Streaming** link.
2. Confirm that it opens the correct information at the updated URL.
3. Verify that the content is accessible and matches the intended information.

**Checklist**  
- [x] [Review Contribution Guidelines](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CONTRIBUTING.md)
- [x] [Review Code of Conduct](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CODE_OF_CONDUCT.md)
- [x] I have tested my changes.

**Related Issue**  
- None.

### CODE REVIEW

**Comment by HTRamsey** [comment]
I think what you are looking for is actually in VideoManager/VideoReceiver/GStreamer/README.md

**Comment by mohanbabi** [comment]
yes, 

I’m replacing the current URL:

- [https://github.com/mavlink/qgroundcontrol/blob/master/src/VideoReceiver/README.md](https://github.com/mavlink/qgroundcontrol/blob/master/src/VideoReceiver/README.md)

image

with the updated URL:

- [https://github.com/mavlink/qgroundcontrol/blob/master/VideoReceiverApp/README.md](https://github.com/mavlink/qgroundcontrol/blob/master/VideoReceiverApp/README.md)

image

**Comment by HTRamsey** [comment]
What I'm saying is that is also the incorrect URL. It should be this:
https://github.com/mavlink/qgroundcontrol/blob/master/src/VideoManager/VideoReceiver/GStreamer/README.md

**Comment by mohanbabi** [comment]
Thank you, for your information,  I replaced URL. Which is given by you.

https://github.com/mavlink/qgroundcontrol/blob/master/src/VideoManager/VideoReceiver/GStreamer/README.md

**Pull request merged**
