### PR TITLE
Reworked Video settings

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
* Reworked video settings to better fix new style
* Fix for video build on OSX. @zdanek Can you take a look at the CMakeLists.txt change

Screenshot 2024-01-23 at 14 47 48

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
This pull will stomp on #10974. So I'll wait till that goes in and then update this one to it.

**Comment by zdanek** [comment]
> * Fix for video build on OSX. @zdanek Can you take a look at the CMakeLists.txt change
Sure. I will do it today afternoon (CET time).

**Comment by zdanek** [comment]
LGTM

**Review by zdanek — APPROVED** [review]
LGTM

**Pull request merged**
