### PR TITLE
Improve category log menu

### PR DESCRIPTION
**Pull request by patrickelectric**
- Add Set all button
- Add search category

Video: https://streamable.com/0k4gf9

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Love the search. But don't see whan anyone would ever use Set All?

**Comment by patrickelectric** [comment]
Well, we never know, at least is an option.

**Comment by DonLakeFlyer** [comment]
I'd rather not have it there. The reason is that I spend a lot of time asking people to turn on various logging options to debug things remotely. I've had many cases where folks then do this from the command line and don't do what I ask and just turn on all logging. Which then makes it next to impossible for me to find the information I'm looking for. Making this too easy from the UI will likely make that problem for me even worse. If you really, really need to do that you can still do it from the command line.

**Comment by patrickelectric** [comment]
@DonLakeFlyer "Set all" removed

**Comment by patrickelectric** [comment]
Ping

**Comment by DonLakeFlyer** [comment]
If you put all of this inside the flickable it will work much better on small screens like phones. Those just don't have much vertical real estate to devote something which sticks on the top.

**Comment by patrickelectric** [comment]
@DonLakeFlyer done

**Pull request merged**
