### PR TITLE
Survey: Preset selection in wizard mode

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
If the user has saved Presets then there is a second step to wizard mode.

First step continues to be polygon setup:
Screen Shot 2020-02-13 at 9 30 00 AM

But if you have any presets defined then when you click Done With Polygon you go here:
Screen Shot 2020-02-13 at 9 30 15 AM
(yellow button is a fluke of where I had the mouse when I captured).

Then when you click Done Adjusting you have completed the wizard.

Fix for #8296 (Survey only at this point).

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@antiheavy Can you test/verify for usability when this comes through. Then after things are good, I'll move to the other Patterns as well.

**Comment by Antiheavy** [comment]
> @Antiheavy Can you test/verify for usability when this comes through. Then after things are good, I'll move to the other Patterns as well.

yes, excited to test!  I feel like we've discussed this before, but is the [Apply Preset] button really necessary, or can choosing a drop-down option just make that the selection?

**Comment by DonLakeFlyer** [comment]
> I feel like we've discussed this before, but is the [Apply Preset] button really necessary, or can choosing a drop-down option just make that the selection?

Doing it that way is more complex to implement. I think also kinds of screws up the Apply/Delete button usage. I can look at some point but I"m trying to do simple things without affecting stable at this point. This new code just reuses existing stuff so it's pretty safe.

**Comment by Antiheavy** [comment]
I did a quick sanity test and this is working as advertised.  thanks!  I'll come back to my thoughts about the drop down menu and "apply" buttons in a separate issue for future reference.

**Comment by DonLakeFlyer** [comment]
Thanks for checking Todd.

**Pull request merged**
