### PR TITLE
Guided value slider

### LINKED ISSUE #10743: Guided Altitude Slider Linear Slider with Snapping
This is a continuation of a short discussion on Discord, and is my concept for an improvement to the guided altitude slider.
This is something I have modified in a custom build already, but I am making this issue to discuss whether it would benifit others and would be appropriate for integrating into master.

## Background
The current exponential altitude slider is designed to "allows for fine adjustment around the current altitude, but also allows the upper/lower end of the range to hit a full range adjustment" see #5150 for background.

## The issues with the current design
My suggestions are based on my experience of deploying a fleet of multirotors flown exclusively with guided mode through qgroundcontrol (On a 10" tablet). The drones are flown between 0 and 120m. We have found the following issues with the current behavior:
- The exponential slider makes it difficult to precisely make large altitude changes, as the resolution decreases away from center. While it is very easy to "go up 1.5m" it is hard to precisely "go to 80m" which at least in our case is a more common scenario.
- The non linearity makes for a less predictable experience and requires the user to concentrate quite hard to dial in specific altitudes.
- The change altitude slider behaves differently from the takeoff slider

## Solution Mockup
In my custom build, I have written the following: The slider snaps to the tickmarks and the red section shows the minimum guided height, below which you cant drag the slider. I find it works quite well. This is similar to what was suggested in #5795.
image

## When would this not work?
While I appreciate that there may be scenarios in which the exponential slider is a better option for this, I believe they are the minority of use cases. I believe the solution I am proposing would not work when:
- High altitude precision is required - eg the ability to go to 43m exactly, rather than being content with coarser altitude steps
- A very large altitude range is in use, beyond the normal 0-120m
- The vehicle needs to fly below the home point

## My suggestion for integration
- Under the guided command settings section, a drop down to select linear vs exponential slider (default whatever is deemed appropriate for most users)
- a tickbox to enable snapping on the linear slider if desired (default enabled)
- a setting for slider snap resolution, ie a setting of 10 will snap to the nearest of 10 values. We can setup the defaults for this setting to be low for mobile builds, and high for desktop builds. eg a value of 16 is what is used in my example above and is practical on desktop/laptop, but on a phone a value of 8 eg 50ft resolution would probably be more usable. (we could also limit the maximum allowed value depending on platform)

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Fixes #10743

See Issue for details

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
I'm lost. Creating a new pull didn't make it go away as well.

**Comment by HTRamsey** [comment]
can you rebase locally and see what happens?

**Comment by DonLakeFlyer** [comment]
I already re-pulled the version you rebase tossing my old one

**Comment by DonLakeFlyer** [comment]
Let me try making a whole new branch

**Comment by HTRamsey** [comment]
I would drop my rebase and do a merge just to see if one of the older commits didn't rebase well

**Comment by DonLakeFlyer** [comment]
Stupid https://github.com/appveyor/ci/issues/3585

**Comment by HTRamsey** [comment]
So I have no idea why the android builds fails to find gstreamer sometimes, but rerunning it works I think, I will look at it tonight

**Comment by HTRamsey** [comment]
That's one of the things I will add to #11639

**Comment by arnaudjuin** [comment]
> That's one of the things I will add to #11639 Edit: Nvm a quick google search gave me the answer. I can fix later today

Any success or hint ?

**Comment by HTRamsey** [comment]
> > That's one of the things I will add to #11639 Edit: Nvm a quick google search gave me the answer. I can fix later today
> 
> Any success or hint ? 
> 

Sorry I've been working 15hrs the past few days and ran out of time. I will be able to do it tomorrow at the latest

**Comment by DonLakeFlyer** [comment]
@jmare Can you retest?

* Tick marks which are above/below allowed values are grey
* Indicator is always centered
* Fixed problem with setting below min alt

**Comment by JMare** [comment]
Nice!
Away from my computer for a few days, will test on Monday

**Comment by Davidsastresas** [comment]
I added a few commits addressing some issues testing with Ardupilot.

The only one I think should be discussed is the last commit, about changing altitudeAMSL to altitudeRelative. Before this one, the slider would represent the altitude AMSL, even though the label says "alt (rel)" and it always represented relative altitude. @DonLakeFlyer was this a mistake or this brokes PX4 functionality? From what I saw in the code the issue explained above should affect PX4 as well, but I could have missed something.

Other than that I think it should be fine now.

The new slider looks amazing by the way, great job, thank you!

**Comment by DieBorr** [comment]
Hi, I have been taking a look to the slider, I really like it, seems really nice with the actual UI. However there is something that at least for me does not make sense and is that the horizontal flickable is visible when there is a width resize, I don't know if it has been made on purpose, I have a commit ready to push if you confirm that if it wasn't intentional. Correct me if I wrong but I can't figure out a case where the horizontal flickable needs to be visible in the slider.

image

**Comment by DonLakeFlyer** [comment]
> horizontal flickable is visible when there is a width resize

Ah, right that is screwed up. It isn't tracking contentWidth correctly on the flickable

**Comment by DieBorr** [comment]
https://github.com/mavlink/qgroundcontrol/pull/11663 solves overlap and makes some margin between text and slider border.

**Comment by DonLakeFlyer** [comment]
I'm gonna merge this in and then fix the horizontal thing in another pull...

**Comment by JMare** [comment]
@DonLakeFlyer, Tested, and fixed the issue I saw previously - looks good.

The only thought I wanted to raise - which isn't specifically related to this change is:
When doing a change alt, QGroundControl sends the new altitude as an offset from the current altitude.
This offset is calculate by taking the new desired altitude and subtracting the current altitude.

One consequence of that is that if the vehicle is climbing or descending while you do the altitude change, there is an inaccuracy.
For instance, in Ardupilot SITL, if you do a changealt to 25.0m while you are climbing, you may find the vehicle actually settle at 25.5m. I can imagine this would be worse with high climb rates or low telemetry rates.

Its a minor thing but do you know if there is any reason the normal relative altitude couldn't be sent rather than an offset?

**Comment by DonLakeFlyer** [comment]
> Its a minor thing but do you know if there is any reason the normal relative altitude couldn't be sent rather than an offset?

If I remember correctly it's because PX4 firmware side does change alt as a delta offset. Let me look at the code again. Maybe better to send absolute all the way till it gets to mavlink and then adjust there. That way at least ArduPilot would get a good alt.

**Comment by DonLakeFlyer** [comment]
Yeah, I looked at the code. I can reverse this so that an absolutely altitude flows through until the last minute instead of an offset. That way at least ArduPilot can get a solid alt change in the case described above.

**Comment by JMare** [comment]
Nice yes I think that would be a good change, happy to help with testing. (or coding, but it sounds like you have it covered)

**Comment by DonLakeFlyer** [comment]
I had this backwards. It's ArduPilot that needs the offset change not PX4. Let me see if there is some different command I could send to get an absolute altitude change.

**Pull request merged**
