### PR TITLE
Move ArduPilot PreArm handling to generic

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
* PreArm duplicated messages are filtered such that they are spoken only if more than 10 seconds from last time spoken.
* PreArm messages do not pop up a QGC message box
* PreArm messages still show up in message dropdown
* PreArm messages show up in the center of the flight map. If no PreArm message shows up again for 10 second it will be removed from the flight map.

@dagar Can you test this with PX4?

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dagar Can you test?

**Comment by dagar** [comment]
Great! I'll give it a try.

Could we also do this for anything that contains "PREFLIGHT"? https://github.com/PX4/Firmware/blob/master/src/modules/commander/PreflightCheck.cpp#L131

On the PX4 side I'd still like to change them eventually, but that would get us through the transition.

**Comment by dagar** [comment]
Which MAV_SEVERITY do you think these should be?

**Comment by dagar** [comment]
I'm thinking about treating it differently if the check is done periodically vs as a result of the user requesting to arm.

**Comment by DonLakeFlyer** [comment]
Rebase went bonkers.

**Pull request closed without merging**
