### PR TITLE
Text cleanup

### PR DESCRIPTION
**Pull request by LorenzMeier**
@DonLakeFlyer This addresses the low hanging fruits in terms of usability.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
I'm doing a run through on this:
- The Level button doesn't disable when all the other buttons do. Needs to be added to _startVisualCalibration and _stopCalibration
- The set rotation dialog which comes up after mag cal is out of whack.
screen shot 2015-05-21 at 10 26 50 am

**Comment by DonLakeFlyer** [comment]
The second interior Column element you added isn't working correctly. I'm not exactly sure why. I'd just use the outer Column even if the spacing isn't as nice.

**Comment by DonLakeFlyer** [comment]
Last thing: I can't get "Level" to work. It keeps telling me excess roll or excess pitch and fails. I tried re-cal of accel and level again. Same thing.

**Comment by LorenzMeier** [comment]
Then you don't have the autopilot level?

**Comment by LorenzMeier** [comment]
Its not designed to compensate for large rotations. Its fine-tuning.

**Comment by DonLakeFlyer** [comment]
> Then you don't have the autopilot level?

As level as I can get it. It maybe be off by tiny bit.

Just tried it again with a new board I pulled out of a box. But I could level because it requires gyro cal to be complete first? enabled: checkAcc.value != 0 && checkGyro.value != 0. Why do I need a gyro connected to do level cal?

**Comment by LorenzMeier** [comment]
Because levelling the attitude estimate requires the complete attitude estimator inputs to be calibrated.

**Comment by DonLakeFlyer** [comment]
Tried a different board which I could lay flat on my desk and it worked. Tried the other board which is mounted in 3dr bixler mounting thing. Can't get it to work. I'm holding it as level as I can. Noticed more error text:
not enough measurements taken
excess roll angle

**Comment by LorenzMeier** [comment]
ah, now it makes a lot more sense. I can fix that.

**Comment by LorenzMeier** [comment]
I fixed the mag layout I think. Trying to fix the level button led to crashes - please have a look at: The last commit is the offending one.
https://github.com/mavlink/qgroundcontrol/tree/text_cleanup_crash

**Comment by DonLakeFlyer** [comment]
I don't seem to be seeing that commit.

**Comment by LorenzMeier** [comment]
Direct link:
https://github.com/mavlink/qgroundcontrol/commit/c6bce7510b9a1f85aca6ad631fdfcdf061b43313

**Comment by DonLakeFlyer** [comment]
Just making sure you see this:
Need to push level button into controller here:

            onCompleted: {
                controller.factPanel = viewPanel
                controller.statusLog = statusTextArea
                controller.progressBar = progressBar
                controller.compassButton = compassButton
                controller.gyroButton = gyroButton
                controller.accelButton = accelButton
                controller.airspeedButton = airspeedButton
                controller.cancelButton = cancelButton
                controller.orientationCalAreaHelpText = orientationCalAreaHelpText
            }

**Comment by LorenzMeier** [comment]
Fixed, should behave now.

**Comment by LorenzMeier** [comment]
To be more precise: I tested it and it works. It should work for you now, too.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Calibration should work with HEAD of release_v1.0.0 also in your Bixler now. And it should provide better error messages and abort early on the first fatal error.

**Pull request merged**
