### PR TITLE
GuidedValueSlier: Click on value to type into text field

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
https://github.com/user-attachments/assets/8a90ecf8-74d0-4f68-893f-c6f2e7048fc4

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@DieBorr Can you look through this?

**Comment by DieBorr** [comment]
Ok, I will check it right now.

**Comment by DieBorr** [comment]
Okay, the textField label itself is very well integrated, however I can see a glitch while moving the slider with or without the textField enabled, here is a video:

https://github.com/user-attachments/assets/1b297eec-4784-4b94-9179-0d010863ef73

The problem is in :
`return Math.min(Math.max(value.toFixed(decimalPlaces), _sliderMinVal), _sliderMaxVal).toFixed(decimalPlaces)` 
at _clampedSliderValue function, math.min returns an int when you send a float number with non significant decimal numbers so I suggest to replace that line with:

`Math.min(Math.max(value.toFixed(decimalPlaces), _sliderMinVal), _sliderMaxVal).toFixed(decimalPlaces)`

I could make a pull request but with just this little fix it does not make sense
Thank you !

**Comment by DieBorr** [comment]
Finally I have made a pull request because there was some more things that I think that will improve the user experience

**Comment by DonLakeFlyer** [comment]
Yup, that is screwed up. Fixed.

**Pull request merged**
