### PR TITLE
DeltaQuad meta data

### PR DESCRIPTION
**Pull request by sanderux**
Meta data for DeltaQuad

### CODE REVIEW

**Comment by sanderux** [comment]
@DonLakeFlyer some travis failure here
https://travis-ci.org/mavlink/qgroundcontrol/jobs/214864949

**Comment by dagar** [comment]
We should probably just automated the metadata import. The packaged builds already pull in the latest metadata from firmware master.

**Comment by DonLakeFlyer** [comment]
Can't quite figure what is wrong here. The failure is not related to your change but just to try something can you rebase? If it still screws up I'll just slam through.

**Comment by sanderux** [comment]
done

**Comment by sanderux** [comment]
Still failing
```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
```

**Comment by dagar** [comment]
It's the branch build (DeltaQuad-meta) failing. The other travis-ci is the result of merging this and it's working fine.

**Pull request merged**
