### PR TITLE
Fixed cmake for android

### PR DESCRIPTION
**Pull request by alexeylysenko**
CMakeLists.txt is already in src folder, src/Taisync is invalid path.

### CODE REVIEW

**Comment by alexeylysenko** [comment]
@dagar could you please take a look?

**Comment by patrickelectric** [comment]
@alexeylysenko can you fix the indentation ?
image

**Comment by dagar** [comment]
Sorry didn't see this one. Can you fix the indentation and I'll merge right away? Please rebase and make sure it still works on current master.

**Comment by dagar** [comment]
Fixed in https://github.com/mavlink/qgroundcontrol/pull/8745.

**Pull request closed without merging**
