### PR TITLE
Save coordinates on every, settled viewport change

### PR DESCRIPTION
**Pull request by remster**
Addresses: https://github.com/mavlink/qgroundcontrol/issues/9219

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Yup destructor is wrong. Why complicate this with a timer though? Just add the save to the set* methods.

**Comment by remster** [comment]
> Yup destructor is wrong. Why complicate this with a timer though? Just add the save to the set* methods.

I did initially - it's called repetitively as the pan progresses - i thought to spare the disk these useless write requests and wait for the user to stop dragging the map. Sure - the OS will probably handle this way better. Up to you - just say the word.

**Comment by DonLakeFlyer** [comment]
Hmm, yeah. Qt itself has its own internal buffering prior to writing to disk though and then you have to OS itself. So I still think simpler is better for now.

**Comment by remster** [comment]
Done: https://github.com/mavlink/qgroundcontrol/pull/9220/commits/ce08f690aa5a9f9adad0852e4350c68bbf22b41b

**Comment by DonLakeFlyer** [comment]
Great. Thanks for the fix @remster

**Comment by aib** [comment]
`QSettings` calls `sync` in its destructor, absolutely destroying performance where it is honored. See #10070.

**Pull request merged**
