### PR TITLE
Firmware-specific fact metadata

### PR DESCRIPTION
**Pull request by jaxxzer**
Point being to change labels like 'airspeed' and 'altitude' to speed and depth, or whatever's appropriate.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
I understand the need for this. But I would much rather have some sort of generic mechanism where the plugin can replace meta data. Which at this point is not thought through. I don't want a bunch of ```if vehicletype``` stuff in Vehicle.

**Comment by jaxxzer** [comment]
Ok, back to the drawing board. Thanks @DonLakeFlyer.

**Comment by DonLakeFlyer** [comment]
Can you enter an Issue for this and I'll put some thought into it.

**Comment by jaxxzer** [comment]
https://github.com/mavlink/qgroundcontrol/issues/5685

**Pull request closed without merging**
