### PR TITLE
Only show close button when full screen

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Related to #12091

### CODE REVIEW

**Comment by NiklasVoigt** [comment]
@DonLakeFlyer can you provide an appimage?

**Comment by DonLakeFlyer** [comment]
YOu can get it here: https://github.com/mavlink/qgroundcontrol/actions/runs/11863725486?pr=12099

**Comment by HTRamsey** [comment]
@DonLakeFlyer I've realized this close button bypasses the "Are You Sure" checks when you are connected

**Comment by NiklasVoigt** [comment]
> @NiklasVoigt Can you give this a try on a SteamDeck once it builds?
It works as intended: In fullscreen mode, a close button is available; otherwise, there is no close button.

**Comment by DonLakeFlyer** [comment]
OK, I’ll fix that

**Comment by DonLakeFlyer** [comment]
@NiklasVoigt Can you test this again when it finishes building. I fixed the close sequence to always do the shutdown checks.

**Comment by NiklasVoigt** [comment]
The functionality is as expected. On PC, no button is visible, whereas on the Steam Deck, a close button appears when in fullscreen mode.

**Comment by DonLakeFlyer** [comment]
Great, thanks so much for helping out

**Pull request merged**
