### PR TITLE
Show the user some positive feedback when parameters load from cache.…

### PR DESCRIPTION
**Pull request by NaterGator**
… For #3114.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Awesome Nate, thanks.

**Comment by julianoes** [comment]
Yay, thanks!

**Comment by NaterGator** [comment]
A quick note on this: we'll need to test with multiple components reporting their params... right now I suspect the progress bar may spaz out / flicker for a second if multiple devices / components sync params at the same time.

**Comment by DonLakeFlyer** [comment]
> I suspect the progress bar may spaz out / flicker for a second if multiple devices / components sync params

I think it did that before as well

**Pull request merged**
