### PR TITLE
Use major version for xcode because Apple just keeps persisting. Move…

### PR DESCRIPTION
**Pull request by foobarnum**
Use major version for xcode because Apple just keeps persisting. Move config vars to the top and add a little explanatory text.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Can you look at this. This is your script right?

**Comment by dogmaphobic** [comment]
This is no longer needed for Qt > 5.6

**Comment by DonLakeFlyer** [comment]
Closing since our new base is 5.7

**Comment by foobarnum** [comment]
I started over and built with qt 5.7. With xcode 8 I still ran into the "xcode not installed properly" issue. (Common issue covered in StackOverflow et al)
Fixed by editing 5.7/clang_64/mkspecs/features/mac/default_pre.prf
changed `isEmpty($$list($$system("/usr/bin/xcrun -find xcrun 2>/dev/null")))`
to `isEmpty($$list($$system("/usr/bin/xcrun -find xcodebuild 2>/dev/null")))`
 
Build compiled normally after that one change. I'm not sure if/how the project might want to cover this case. Seems best handled by qt with a case statement in defaut_pre.prf. @DonLakeFlyer @dogmaphobic

**Comment by DonLakeFlyer** [comment]
Strange I could have sworn I didn't tweak that in my last 5.7 install.

**Comment by dogmaphobic** [comment]
I just installed 5.7 for the first time on my laptop and it all just worked.

**Comment by DonLakeFlyer** [comment]
What does that file look like?

**Comment by dogmaphobic** [comment]
Yep, the test is already correct in `default_pre.prf`.

```
    # Make sure Xcode is set up properly
    isEmpty($$list($$system("/usr/bin/xcrun -find xcodebuild 2>/dev/null"))): \
        error("Xcode not set up properly. You may need to confirm the license agreement by running /usr/bin/xcodebuild.")
```

This is the original file from Qt.

```
~/local/Qt/5.7/clang_64/mkspecs/features/mac$ ls -l
total 64
-rw-r--r--  1 gus  staff  4783 Dec  1 05:46 asset_catalogs.prf
-rw-r--r--  1 gus  staff  1366 Dec  1 05:46 default_post.prf
-rw-r--r--  1 gus  staff  2391 Dec  1 05:46 default_pre.prf
-rw-r--r--  1 gus  staff   372 Dec  1 05:46 objective_c.prf
-rw-r--r--  1 gus  staff   555 Dec  1 05:46 rez.prf
-rw-r--r--  1 gus  staff  2480 Dec  1 05:46 sdk.prf
-rw-r--r--  1 gus  staff   146 Dec  1 05:46 toolchain.prf
drwxr-xr-x  3 gus  staff   102 Mar 10 16:17 unsupported
```

**Comment by foobarnum** [comment]
🤷‍♂️  I used the dmg from the Qt site this morning.

`Roberts-MBP:qgroundcontrol tucker$ ls -lah ~/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/
total 40
drwxr-xr-x   8 tucker  staff   272B Mar 11 09:28 .
drwxr-xr-x  96 tucker  staff   3.2K Mar 11 08:19 ..
-rw-r--r--   1 tucker  staff   1.5K Jun 10  2016 default_post.prf
-rw-r--r--   1 tucker  staff   2.3K Mar 11 09:28 default_pre.prf
-rw-r--r--   1 tucker  staff   372B Jun 10  2016 objective_c.prf
-rw-r--r--   1 tucker  staff   555B Jun 10  2016 rez.prf
-rw-r--r--   1 tucker  staff   2.4K Jun 10  2016 sdk.prf
drwxr-xr-x   3 tucker  staff   102B Mar 11 08:18 unsupported`

**Comment by dogmaphobic** [comment]
Somehow you managed to install an old version. Run the maintenance tool and update it. The current version is 5.7.1:

screen shot 2017-03-11 at 1 33 15 pm

**Comment by foobarnum** [comment]
After debugging the maintenance tool and updating. The app built normally. Seems OK now. Thanks!

**Pull request closed without merging**
