### PR TITLE
iOS Build Work (and other stuff)

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dogmaphobic** [comment]
The failure was due to some error while building the Android version. I found a path issue with ```update_android_version.sh```, which I'm sending a fix for it shortly.
```
jarsigner command failed.
  -- Run with --verbose for more information.
make[1]: *** [release/libqgroundcontrol.so] Error 15
```
```
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
VersionCode: 
VersionName: 
Error versionCode empty
Error versionName empty
```

The others run but did not upload:
```
Skipping a deployment with the s3 provider because this branch is not permitted
Skipping a deployment with the s3 provider because a custom condition was not met
```

While at it, I noticed this warning:
```
S3 client configured for "us-east-1" but the bucket "qgroundcontrol" is in "us-west-2"; Please configure the proper region to avoid multiple unecessary redirects and signing attempts
```

**Comment by dagar** [comment]
The builds are
https://s3-us-west-2.amazonaws.com/qgroundcontrol/buildWork/qgroundcontrol.dmg
https://s3-us-west-2.amazonaws.com/qgroundcontrol/buildWork/qgroundcontrol.tar.bz2

**Comment by dagar** [comment]
The pr build is the result of merging the pull request, the other is just the branch on it's own. 

Only installer non pull request builds are uploaded.

**Comment by dogmaphobic** [comment]
> The builds are
> https://s3-us-west-2.amazonaws.com/qgroundcontrol/buildWork/qgroundcontrol.dmg
> https://s3-us-west-2.amazonaws.com/qgroundcontrol/buildWork/qgroundcontrol.tar.bz2

Indeed they are and they are fine. I had downloaded from the links from qgroundcontrol.org and those were not right. Hopefully this Android path issue will deal with the failure and we should be done.

**Comment by dogmaphobic** [comment]
By the way, what started this whole thing was getting iOS ready for the App Store. That however, won't be able to be automated. I will have to make the submissions manually and a lot less frequently.

**Comment by dagar** [comment]
Apple Testflight sounds similar to the Android beta testing experience.
https://developer.apple.com/testflight/

We only need to submit the stable release builds to the full app stores.

**Comment by dogmaphobic** [comment]
> Apple Testflight sounds similar to the Android beta testing experience.

Ha! I missed that altogether. I was only aware of the internal testing, which is quite restricted:
>Get feedback quickly by sharing your beta builds with your internal team. Each app can be tested by up to 25 members of your team who have been assigned the Technical or Admin role in iTunes Connect. Each member can test on up to 10 devices.


That indeed changes things. Thanks for pointing it out...

**Comment by dagar** [comment]
I made some lazy assumptions for the output of the android build that are currently breaking. I'll fix it.

**Comment by dagar** [comment]
The windows build also didn't upload. Appveyor likes to fail silently. Looking.

**Comment by dogmaphobic** [comment]
> The windows build also didn't upload. Appveyor likes to fail silently. Looking.

Yep. I booted up a Windows clunker and run a build there. The generated Makefiles are not respecting the dependency for the QtLocation plugin. It's building the app first and it fails to link with the plugin as it hasn't been built yet. I might as well ditch the whole *subdirs* template for everything. It's been a nightmare.

**Pull request merged**
