### PR TITLE
QtCreator now default build environment

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
@NaterGator FYI

### CODE REVIEW

**Comment by dagar** [comment]
You can remove jombuild from appveyor too.
https://github.com/mavlink/qgroundcontrol/blob/master/.appveyor.yml#L17

**Comment by DonLakeFlyer** [comment]
I'll add that to this.

**Comment by DonLakeFlyer** [comment]
I'll do it in a separate. had this in my windows vm and it was't really onthe right branch

**Comment by DonLakeFlyer** [comment]
@dagar Appveyor keeps crapping out on nsis install. Trying re-run for third time.

**Comment by dagar** [comment]
I'll try reporting it to appveyor.

**Comment by DonLakeFlyer** [comment]
Same thing. Merging with Windows run. need to move forward.

**Pull request merged**
