### PR TITLE
set QGC version from git

### PR DESCRIPTION
**Pull request by dagar**
Blocked on https://github.com/mavlink/qgroundcontrol/issues/1802

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Thanks Daniel

**Comment by dagar** [comment]
Resurrecting this once teamcity is disabled.

**Comment by dagar** [comment]
@DonLakeFlyer this should be good to go. I know you don't want PRs at the moment, but I'm assuming this will be completely out of your way.

Both appveyor and travis-ci report `QGroundControl version v2.7.1-443-g6867683` for this PR. This means no more manual versioning or switching between Dev/Stable and will allow me to work towards the build system auto deploying to Google play and launchpad.

**Comment by DonLakeFlyer** [comment]
Sounds great. is this ready to merge?

**Comment by dagar** [comment]
Yep

**Pull request merged**
