### PR TITLE
Unknown airframe icon

### PR DESCRIPTION
**Pull request by dogmaphobic**
New unknown airframe icon
Fix proper SVG rendering

Screen Shot 2019-04-28 at 10 28 01 PM

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Love it!

**Comment by hamishwillee** [comment]
Me too! I'll steal for PX4 docs too.

**Comment by hamishwillee** [comment]
@dogmaphobic Who did you get to do this? For the docs the spaceship needs to be dark rather than white.

**Comment by dogmaphobic** [comment]
I put it together. Here is a version in black. Just remove the `.txt` (Github wouldn't allow uploading an .svg)

[AirframeUnknown.svg.txt](https://github.com/mavlink/qgroundcontrol/files/3129580/AirframeUnknown.svg.txt)

**Comment by hamishwillee** [comment]
Thanks @dogmaphobic - looks great: https://dev.px4.io/master/en/airframes/airframe_reference.html#quadrotor-asymmetric

**Pull request merged**
