### PR TITLE
Google mapping

### PR DESCRIPTION
**Pull request by dogmaphobic**
Adding a ~~Google~~ Generic Maps Qt Location Services plugin.

This is a first cut at integrating Qt Location Services in QGC. The plugin has its own separate project and as such, I had to create a *super* project that handles both the plugin and the QGC application. The original ```qgroundcontrol.pro``` is now named ```qgcsystem.pro``` and the new ```qgroundcontrol.pro``` is now the super project.

For now, you can see it as an option to the Primary Flight Display (as an experiment). It will eventually replace the Open Pilot mapping library.

As this is quite a large change to the way things are built, I wonder how the TC build system will handle it.

Tested in all 3 platforms.

screen shot 2015-04-04 at 5 20 05 pm

### CODE REVIEW

**Comment by dogmaphobic** [comment]
Not sure what went wrong with TC. I need help from @DonLakeFlyer. My own unit tests passed and the error in Windows seem to be related to a missing .qmake.conf, which is there. Local Windows (and Mac, and Linux) build worked fine both Debug and Release.

**Comment by DonLakeFlyer** [comment]
Gus: I have a feeling you’re not running unit tests with the QT_FATAL_WARNINGS=1 environment variable set. Whereas TC does. That causes all qWarning output to assert.

I’ll have to look at the other stuff some more. Likely needs build mods to get it to work under TC.

**Comment by dogmaphobic** [comment]
> Gus: I have a feeling you’re not running unit tests with the QT_FATAL_WARNINGS=1

Indeed, I am not. Starting a run now...

**Comment by DonLakeFlyer** [comment]
I won’t be getting back to TC till tomorrow.

**Comment by dogmaphobic** [comment]
No problem. We deal with it when you have a chance. I run the unit tests again, this time with the proper QT_FATAL_WARNINGS variable set and caught an assert, though I have no idea why:

```
0	__pthread_kill	__pthread_kill		0x7fff99a2e286	
1	pthread_kill	pthread_kill		0x7fff9242842f	
2	abort	abort		0x7fff996f5b53	
3	qt_message_fatal(QtMsgType, QMessageLogContext const&, QString const&)	qt_message_fatal(QtMsgType, QMessageLogContext const&, QString const&)		0x101500d29	
4	qt_message_output(QtMsgType, QMessageLogContext const&, QString const&)	qt_message_output(QtMsgType, QMessageLogContext const&, QString const&)		0x101505ca6	
5	QDebug::~QDebug()	QDebug::~QDebug()		0x101649b64	
6	QQmlInspectorService::updateState()	QQmlInspectorService::updateState()		0x102711bd2	
7	QQuickWidgetPrivate::init(QQmlEngine*)	QQuickWidgetPrivate::init(QQmlEngine*)		0x103a12e0e	
8	QGCQuickWidget::QGCQuickWidget(QWidget*)	QGCQuickWidget.cc	39	0x1003f3e9d	
9	QGCQuickWidget::QGCQuickWidget(QWidget*)	QGCQuickWidget.cc	41	0x1003f3f8d	
10	Ui_QGCQmlWidgetHolder::setupUi(QWidget*)	ui_QGCQmlWidgetHolder.h	37	0x1003f7143	
11	QGCQmlWidgetHolder::QGCQmlWidgetHolder(QWidget*)	QGCQmlWidgetHolder.cpp	32	0x1003f6ae1	
12	MainToolBar::MainToolBar(QWidget*)	MainToolBar.cc	64	0x1004099d3	
13	MainToolBar::MainToolBar(QWidget*)	MainToolBar.cc	98	0x10040bb5d	
14	MainWindow::MainWindow(QSplashScreen*)	MainWindow.cc	175	0x1001f002c	
```

The last lines of the output were:

```
********* Start testing of MainWindowTest *********
Config: Using QtTest library 5.4.1, Qt 5.4.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 6.0 (clang-600.0.54) (Apple))
PASS   : MainWindowTest::initTestCase()
QDEBUG : MainWindowTest::_connectWindowClosePX4_test() QML Debugger: Waiting for connection on port 61711...
QWARN  : MainWindowTest::_connectWindowClosePX4_test() QQmlInspector: No plugin available for view ' QQuickWidget '.
```

I now noticed that you seem to be using Qt 5.4.0 and I am using 5.4.1. Should I go back to 5.4.0?

**Comment by dogmaphobic** [comment]
Weird, master is asserting in the exact same place when I run unit test with QT_FATAL_WARNINGS enabled...

**Comment by DonLakeFlyer** [comment]
Ok, wait a minute QT_FATAL_WARNINGS is turned off in TC windows builds only for another reason (I’d have to look up the issue). Look like because of that another issue crept in. Sorry for the misinformation it is turned on in other OS. Windows is running into some sort of setup issue.

**Comment by DonLakeFlyer** [comment]
TC seems to have decided to mark the qgc settings file read only which is causing the failures. Not sure how that happened. Cleaned thing up and trying again.

**Comment by DonLakeFlyer** [comment]
It seems like there may be something missing along these lines: http://lists.qt-project.org/pipermail/development/2014-May/016939.html? I think that's at least on of the problems.

**Comment by dogmaphobic** [comment]
Don't know. The plugin builds and loads just fine in all 3 platforms in my local system. Let me dig some more...

**Comment by DonLakeFlyer** [comment]
I get the same error on my OS X machine that is showing up in some of the TC builds when I tried to qmake using my own built version of Qt. That is not what TC uses, but there must be some relationship.

**Comment by DonLakeFlyer** [comment]
What is the location-private module versus location module?

**Comment by DonLakeFlyer** [comment]
On linux do you have Qt on a PATH? TC builds by referencing qmake directly. The Ubunto qmake command is exactly this:
/opt/qt54/bin/qmake qgroundcontrol.pro -r -spec linux-g++-64 CONFIG+=x86_64 CONFIG+=debug CONFIG+=WarningsAsErrorsOn
If you aren't building this way, can you try this and see if you get the same error as TC.

**Comment by dogmaphobic** [comment]
I'm a bit scattered as I'm preparing dinner while doing all this :) No, I don't use a system installed Qt in any of the platforms. I build using Qt Creator, which handles all the paths for the build using a local (home) installation of Qt. The basis for the plugin was the (current, 5.4.1) nokia Qt Location plugin sources.

Which TC error are you referring specifically? TC's Mac OS release build completed fine. The debug build had issues with unit test, which I don't have, even with the QT_FATAL_WARNINGS set. The TC Windows build is failing because it can't find ```.qmake.conf```, which should be there (otherwise the Mac OS build would fail as well). The log files are only for Windows and Mac so I can't compare my Linux build.

I will go through the logs and see if I can see any difference with my local build...

**Comment by DonLakeFlyer** [comment]
I”m talking about trying to fix the Linux build. Let me look at to why your not getting Linux log files.

**Comment by DonLakeFlyer** [comment]
All logs are working now. I'm looking at the OS X problem. I'm hoping you can repro the linux problem.

**Comment by DonLakeFlyer** [comment]
When I do a make build I end up with some extra files that get created and show up in git:

MacPro:qgroundcontrol Don$ git status
On branch dogmaphobic-googleMapping
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	libs/QtLocationGoogle/lib/
	libs/QtLocationGoogle/mkspecs/

nothing added to commit but untracked files present (use "git add" to track)

Something wrong, or .gitignore needs update?

**Comment by dogmaphobic** [comment]
Those files should be in the build directory, not in the source. Hold on... too many things at once. I just followed to the letter the instructions to install Qt 5.4 on Ubuntu (system level). It worked right off the bat, not doing anything special:

```
ubuntu:~/github$ mkdir build
ubuntu:~/github$ cd build
ubuntu:~/github/build$ qmake ../qgroundcontrol/qgroundcontrol.pro -r -spec linux-g++-64 CONFIG+=x86_64 CONFIG+=debug CONFIG+=WarningsAsErrorsOn
Reading /home/gus/github/qgroundcontrol/libs/QtLocationGoogle/QtLocationGoogle.pro [/home/gus/github/build/libs/QtLocationGoogle]
Reading /home/gus/github/qgroundcontrol/qgcsystem.pro [/home/gus/github/build]
Project MESSAGE: Qt version 5.4.1
Project MESSAGE: Linux build
Project MESSAGE: Debug flavor
Project MESSAGE: BASEDIR /home/gus/github/qgroundcontrol DESTDIR /home/gus/github/build/debug TARGET QGroundControl
Project WARNING: No MAVLink dialect specified, only common messages supported.
Project MESSAGE: Including support for OpenSceneGraph
Project MESSAGE: Skipping support for XBee API (64-bit Linux builds not supported)
Project WARNING: Skipping support for 3DConnexion mice (missing libraries, see README)
Project MESSAGE: Skipping support for RT-LAB (unsupported platform)
Project MESSAGE: Including support for speech output
ubuntu:~/github/build$ make -j24

<--- zillion lines of building stuff --->

echo Copying files && cp -f -R /home/gus/github/qgroundcontrol/flightgear /home/gus/github/build/debug
Copying files
make[1]: Leaving directory `/home/gus/github/build'
ubuntu:~/github/build$
```

The build completes with no warning or errors and it runs fine:

screen shot 2015-04-05 at 4 42 45 pm

Nothing is written to the source directory:

```
ubuntu:~/github/build$ cd ../qgroundcontrol/
ubuntu:~/github/qgroundcontrol (googleMapping)$ git status
On branch googleMapping
Your branch is up-to-date with 'origin/googleMapping'.

nothing to commit, working directory clean
ubuntu:~/github/qgroundcontrol (googleMapping)$ 
```

**Comment by DonLakeFlyer** [comment]
TC doesn't build exactly like a typical user (nor do I). The reason is because I have multiple versions of Qt on my machine. If you have multiple version of Qt on your machine you don't reference qmake from a path. You run it directly like this:
/opt/qt54/bin/qmake qgroundcontrol.pro -r -spec linux-g++-64 CONFIG+=x86_64 CONFIG+=debug 

Can you try running it directly like I'm doing. Also make sure you don't have any pro.user files hanging around that qtcreator puts in your directory. That may be changing your build as well. QTCreator sets thing up to build outside the qgroundcontrol directory. While just vanilla makes puts the build files as subduers of qgroundcontrol. Make sure you qgroundcontrol directory is fully clean of any extra stuff in there.

**Comment by DonLakeFlyer** [comment]
Also note how there is no separate build directory. TC and I qmake right from the qgroundcontrol dir. You're building from a side directory so all you build files end up there. That isn't the only way to do it.

**Comment by DonLakeFlyer** [comment]
The OS X failure is this: http://www.qtcentre.org/threads/62133-QNetworkAccessManager-get-generates-SSL-qWarning-output-when-no-SSL-is-used?p=275327#post275327

**Comment by dogmaphobic** [comment]
I don't ever build within the source tree. That's just an old habit and it prevents messing the tree if something goes out of whack.

I installed everything from scratch, including a brand new git clone of my fork.

If you don't have Qt in your path, how does qmake find everything else? What is your QTDIR pointing to? For me running with a full path or not makes no difference as it is in my $PATH. If I don't define PATH or QTDIR, nothing works.

**Comment by dogmaphobic** [comment]
> The OS X failure is this: http://www.qtcentre.org/threads/62133-QNetworkAccessManager-get-generates-SSL-qWarning-output-when-no-SSL-is-used?p=275327#post275327

Yes, I've noticed that but this has been the case forever. The Open Pilot mapping uses the same set of functions and they too cause those SSL warnings. At least it has always been the case for me. I just had never used QT_FATAL_WARNINGS before. That also explains why I'm no longer getting these errors. These last few times I run, it all worked because the maps were all already in the cache so no network calls were made...

**Comment by DonLakeFlyer** [comment]
You shouldn't need to define any extra environment variables to build. I have none of those set on any of my OS. If you reference qmake with a full path, it will use the qmake location to pull all the rest of the stuff it needs. This way you can have multiple versions of Qt installed at once and just use them in whatever way you want. No messing with environment variables.

**Comment by DonLakeFlyer** [comment]
It’s a timing and cache thing I believe. So you don’t hit it all the time. At least you didn’t used to. But not it seems to come up all the time, at least in unit tests.

**Comment by dogmaphobic** [comment]
> You shouldn't need to define any extra environment variables to build.

Interesting. I never bothered to figure that out. I just started a new console session with no environment variables set and run as you do. It all worked though...

```
ubuntu:~/github/build$ rm -rf *
ubuntu:~/github/build$ echo $QTDIR

ubuntu:~/github/build$ /opt/qt54/bin/qmake ../qgroundcontrol/qgroundcontrol.pro -r -spec linux-g++-64 CONFIG+=x86_64 CONFIG+=debug CONFIG+=WarningsAsErrorsOn
Reading /home/gus/github/qgroundcontrol/libs/QtLocationGoogle/QtLocationGoogle.pro [/home/gus/github/build/libs/QtLocationGoogle]
Reading /home/gus/github/qgroundcontrol/qgcsystem.pro [/home/gus/github/build]
Project MESSAGE: Qt version 5.4.1
Project MESSAGE: Linux build
Project MESSAGE: Debug flavor
Project MESSAGE: BASEDIR /home/gus/github/qgroundcontrol DESTDIR /home/gus/github/build/debug TARGET QGroundControl
Project WARNING: No MAVLink dialect specified, only common messages supported.
Project MESSAGE: Skipping support for OpenSceneGraph (manual override from user_config.pri)
Project MESSAGE: Skipping support for XBee API (64-bit Linux builds not supported)
Project WARNING: Skipping support for 3DConnexion mice (missing libraries, see README)
Project MESSAGE: Skipping support for RT-LAB (unsupported platform)
Project MESSAGE: Skipping support for speech output (manual override from user_config.pri)
```

Note that by now I disabled OpenSceneGraph (it has issues with my OpenGL drivers) and sound (it has issues with my sound driver). That however, should make no difference to the above test.

**Comment by DonLakeFlyer** [comment]
There's some difference between what I have on my Ubuntu box and what you have on yours. I'll have to dig into it to try to figure it out. As far as I can tell I have all the correct set of location stuff. What are all the packages you have installed that have the word location in them?

**Comment by dogmaphobic** [comment]
This is a fresh Ubuntu install I did just a couple of weeks ago. I installed Qt today for the first time (system wide), following the exact instructions in:

 https://github.com/mavlink/qgroundcontrol/blob/master/README.md.

Here are all the files with *location* in the name:

```
ubuntu:~/github/build$ find /opt/qt54/ -name "*location*"
/opt/qt54/qml/QtLocation/libdeclarative_location.so
/opt/qt54/share/qtcreator/qml-type-descriptions/qtmobility-location.qmltypes
/opt/qt54/mkspecs/modules/qt_lib_location.pri
/opt/qt54/mkspecs/modules/qt_lib_location_private.pri
/opt/qt54/examples/widgets/tools/settingseditor/locationdialog.h
/opt/qt54/examples/widgets/tools/settingseditor/locationdialog.cpp
/opt/qt54/examples/location
/opt/qt54/examples/location/places/qml_location_places
/opt/qt54/examples/location/location.pro
/opt/qt54/examples/positioning/flickr/qmllocationflickr.cpp
/opt/qt54/include/QtLocation/qlocation.h
/opt/qt54/include/QtLocation/qtlocationversion.h
/opt/qt54/include/QtLocation/qlocationglobal.h
/opt/qt54/include/QtMultimedia/5.4.1/QtMultimedia/private/qmediastoragelocation_p.h
/opt/qt54/include/QtPositioning/5.4.1/QtPositioning/private/qdeclarativegeolocation_p.h
/opt/qt54/include/QtPositioning/5.4.1/QtPositioning/private/qgeolocation_p.h
/opt/qt54/include/QtPositioning/5.4.1/QtPositioning/private/qlocationutils_p.h
/opt/qt54/include/QtPositioning/qgeolocation.h
/opt/qt54/include/QtXmlPatterns/5.4.1/QtXmlPatterns/private/qsourcelocationreflection_p.h
/opt/qt54/include/QtXmlPatterns/qsourcelocation.h
/opt/qt54/include/qbs/tools/codelocation.h
ubuntu:~/github/build$ 
```

**Comment by DonLakeFlyer** [comment]
My Ubuntu was out of whack. Just reinstalled all packages from readme. Hopefully that will fix Linux build. Kicked off new TC run.

**Comment by DonLakeFlyer** [comment]
Ok. It got a little further this time. Can you change the TARGET = line in qgcsystem.pro to be all lower case qgroundcontrol? The mixed case now generates mixed case app names which is nice but it breaks all my TC scripts.

**Comment by dogmaphobic** [comment]
>The mixed case now generates mixed case app names which is nice but it breaks all my TC scripts.

Is it true for all platforms or just Linux?

**Comment by DonLakeFlyer** [comment]
All platforms. Only breaking Linux github builds right now I believe. But it will break all installer builds.

**Comment by DonLakeFlyer** [comment]
I turned off QT_FATAL_WARNINGS on OS X tests.

**Comment by DonLakeFlyer** [comment]
When I try to build windows I get:
C:\qgroundcontrol>\Qt\Qt5.4.0\5.4\msvc2013_opengl\bin\qmake.exe qgroundcontrol.p
ro -tp vc
WARNING: Ignored (not found) 'C:/qgroundcontrol/libs/QtLocationGoogle\qtgeoservi
ces_google.vcxproj'
Project MESSAGE: Qt version 5.4.0
Project MESSAGE: Windows build
Project MESSAGE: Release flavor
Project MESSAGE: BASEDIR C:/qgroundcontrol DESTDIR C:/qgroundcontrol/release TAR
GET qgroundcontrol
Project WARNING: No MAVLink dialect specified, only common messages supported.
Project WARNING: Skipping support for OpenSceneGraph (missing libraries, see REA
DME)
Project MESSAGE: Including support for XBee API
Project MESSAGE: Including support for 3DConnexion mice
Project WARNING: Skipping support for RT-LAB (missing libraries, see README)
Project MESSAGE: Including support for speech output

C:\qgroundcontrol>

**Comment by DonLakeFlyer** [comment]
Linux and OS X are clean now.

**Comment by dogmaphobic** [comment]
> When I try to build windows I get:

Let me go through the steps we did for Linux and see if I can find the difference...

**Comment by dogmaphobic** [comment]
Yep. I had never tried creating a Visual Studio project. I always just used the default, which creates a Makefile base build. By default, qmake will create only one single Visual Studio project and it ignores all the logic in the .pro file related to multiple projects (the ```TEMPLATE = subdir``` and such). Those are only for Makefile base projects.

To create a proper Visual Studio *Solution*, with multiple, dependent sub-projects, you need to add a ```-r``` command as (poorly) explained in http://doc.qt.io/qt-5/qmake-platform-notes.html. The command looks like:

```
qmake.exe groundcontrol.pro -r -tp vc
```

I run that and it created a proper solution:

```
C:\data\github>mkdir build
C:\data\github>cd build
C:\data\github\build>\usr\QtOffLine\Qt5.4.1\5.4\msvc2013_opengl\bin\qmake.exe ..\qgroundcontrol\qgroundcontrol.pro -r -tp vc
Reading C:/data/github/qgroundcontrol/libs/QtLocationGoogle/QtLocationGoogle.pro [C:/data/github/build/libs/QtLocationGoogle]
Reading C:/data/github/qgroundcontrol/qgcsystem.pro [C:/data/github/build]
Project MESSAGE: Qt version 5.4.1
Project MESSAGE: Windows build
Project MESSAGE: Release flavor
Project MESSAGE: BASEDIR C:/data/github/qgroundcontrol DESTDIR C:/data/github/build/release TARGET qgroundcontrol
Project WARNING: No MAVLink dialect specified, only common messages supported.
Project WARNING: Skipping support for OpenSceneGraph (missing libraries, see README)
Project MESSAGE: Including support for XBee API
Project MESSAGE: Including support for 3DConnexion mice
Project WARNING: Skipping support for RT-LAB (missing libraries, see README)
Project MESSAGE: Including support for speech output
C:\data\github\build>
```
That however, was not enough. I added a missing DLL file to the copy phase (QGCSetup.pri). It took forever though as it takes 10 times longer to build with Visual Studio and each time I tried something, the whole shebang had to be done from scratch. It now builds everything and it runs fine.

With that said, there were a few warnings that I couldn't make sense of and it didn't seem to be an issue:

```
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(935,5): warning MSB8027: Two or more files with the name of moc_qgeocodereplygoogle.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are .moc\debug\moc_qgeocodereplygoogle.cpp, .moc\release\moc_qgeocodereplygoogle.cpp.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(935,5): warning MSB8027: Two or more files with the name of moc_qgeocodingmanagerenginegoogle.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are .moc\debug\moc_qgeocodingmanagerenginegoogle.cpp, .moc\release\moc_qgeocodingmanagerenginegoogle.cpp.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(935,5): warning MSB8027: Two or more files with the name of moc_qgeomapreplygoogle.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are .moc\debug\moc_qgeomapreplygoogle.cpp, .moc\release\moc_qgeomapreplygoogle.cpp.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(935,5): warning MSB8027: Two or more files with the name of moc_qgeoserviceproviderplugingoogle.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are .moc\debug\moc_qgeoserviceproviderplugingoogle.cpp, .moc\release\moc_qgeoserviceproviderplugingoogle.cpp.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(935,5): warning MSB8027: Two or more files with the name of moc_qgeotiledmappingmanagerenginegoogle.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are .moc\debug\moc_qgeotiledmappingmanagerenginegoogle.cpp, .moc\release\moc_qgeotiledmappingmanagerenginegoogle.cpp.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(935,5): warning MSB8027: Two or more files with the name of moc_qgeotilefetchergoogle.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are .moc\debug\moc_qgeotilefetchergoogle.cpp, .moc\release\moc_qgeotilefetchergoogle.cpp.
```

**Comment by DonLakeFlyer** [comment]
I won't get back to this till tomorrow. Heading up to Canada for a hockey game and trying to clean a couple other things off my plate before I leave.

**Comment by dogmaphobic** [comment]
In the mean time, I've been continuing development. I replaced my *hardcoded* URL factory to the one used by Open Pilot mapping. As this is no longer a Google specific plugin, I renamed it to QGC (it now also provides maps from Bing).

**Comment by DonLakeFlyer** [comment]
Linux is broken because of a real case sensitivity bug. Windows is broken because of the way TC is setup. The sequence is like this:
- git repository is in OSX and is updated with each pull
- source code is copied from OS X repository to each VM
- The builds happen in the VM

The only reason I think this is confusing things is that since git pull happens in OS X file endings are in LF only. Which then gets copied to a windows box. I do this to limit my network hits. This all used to work fine. Not any more. If I clone my own repository on the windows side, qmake works fine. This is going to take a little while because I'm going to gave to figure out how to restructure how TC gets the source to the VMs.

**Comment by dagar** [comment]
@DonLakeFlyer instead of copying the initial clone can you just clone from it? That should be effectively the same as each machine cloning from github.

**Comment by DonLakeFlyer** [comment]
Hmm, let me try that.

**Comment by DonLakeFlyer** [comment]
Ok. It's a little closer. Gus: You've been able to build and run from inside visual studio? I can build it now from visual studio if I do it manually. But I can't run from inside VS. It wants to run the lib instead of the exe. TC still not happy but I"m getting closer.

**Comment by dogmaphobic** [comment]
Yes, after the qmake steps above, I loaded the *solution* with Visual Studio and built from there. It built it all and run fine.

**Comment by DonLakeFlyer** [comment]
Exactly how do you run it from inside VS. What menu command?

**Comment by dogmaphobic** [comment]
I right-click on the root *Solution* and select *Build*. I'm in the middle of migrating Windows from the VM to an actual PC so I can't see it right now...

**Comment by DonLakeFlyer** [comment]
Right, build works. I can't get it to run from inside VS after the build is finished. It tries to run the lib instead of the exe when I use the Run thing in the toolbar.

**Comment by dogmaphobic** [comment]
Oh, within Visual Studio, if you *Run* something, it will run the current selected *Project*. You have to select the qgc project (I think I named it qgcsystem), right-click and select *Set as Current Project*, or something along those lines...

**Comment by DonLakeFlyer** [comment]
That's it, "Set as Startup Project". Can you update README? VS users will need to do that. TC modified. OS X and Windows both build and pass now. Just need Linux fix and should be good to go.

**Comment by DonLakeFlyer** [comment]
Also there are still some .gitignores that need adding. May also need to check that clean works correctly and deletes the right stuff from below.

C:\qgroundcontrol>git status
On branch dogmaphobic-googleMapping
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        libs/QtLocationGoogle/
        libs/QtLocationQGC/lib/
        libs/QtLocationQGC/mkspecs/
        libs/QtLocationQGC/plugins/
        qgroundcontrol_plugin_import.cpp
        qgroundcontrol_qml_plugin_import.cpp
        qupgrade/

nothing added to commit but untracked files present (use "git add" to track)

**Comment by dogmaphobic** [comment]
> Can you update README? VS users will need to do that.

Yes, I was planning on doing that once we had it all figured out.

**Comment by dogmaphobic** [comment]
> Also there are still some .gitignores that need adding.

I would strongly suggest to build outside of the source tree instead. That's just asking for trouble.

**Comment by DonLakeFlyer** [comment]
It's a supported and useful way of doing things. It should be cleaned up. Up until now it has been a very safe way of doing things. There were no co-mingled files mixed into the source. Built files all go into build-debug and build-release. Created application then goes into debug and release directory. If you want to clean you just delete build-debug, build-release, debug and release and you have cleaned everything. Very handy when you have multiple enlistments. Everything is inside the enlistment so you know where it came from. Is there any way to get the location stuff to put it's build artifacts in the top level location qgroundcontrol instead of under libs? Also to not drop .cpp files in the top level directory.

**Comment by DonLakeFlyer** [comment]
Just to be clear, the QGC build was set up the above way on purpose to make building from inside the source tree a safe thing to do. The only reason it's safe is because of the way it was implemented.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic I can clean up the build artifact location part if you want, after this goes through. I cleaned up the whole build system a while back with regards to the artifact directories so it may be easier for me to deal with that part since I'm familiar.

**Comment by dogmaphobic** [comment]
Well, that's the only option for now as I'm in the middle of fighting Windows :)

**Comment by DonLakeFlyer** [comment]
I'll deal with it after this is done. Can you fix the one Linux typo and then this should be ready to merge:

[16:37:29][Step 8/20] In file included from src/qgeotilefetcherqgc.h:52:0,
[16:37:29][Step 8/20]                  from src/qgeotiledmappingmanagerengineqgc.cpp:54:
[16:37:29][Step 8/20] src/OpenPilotMaps.h:35:18: fatal error: Qpoint: No such file or directory
[16:37:29][Step 8/20]  #include <Qpoint>
[16:37:29][Step 8/20]                   ^
[16:37:29][Step 8/20] compilation terminated.
[16:37:29][Step 8/20] In file included from src/qgeomapreplyqgc.cpp:50:0:
[16:37:29][Step 8/20] src/OpenPilotMaps.h:35:18: fatal error: Qpoint: No such file or directory
[16:37:29][Step 8/20]  #include <Qpoint>
[16:37:29][Step 8/20]                   ^
[16:37:29][Step 8/20] compilation terminated.
[16:37:29][Step 8/20] In file included from src/qgeotilefetcherqgc.h:52:0,
[16:37:29][Step 8/20]                  from src/qgeotilefetcherqgc.cpp:52:
[16:37:29][Step 8/20] src/OpenPilotMaps.h:35:18: fatal error: Qpoint: No such file or directory
[16:37:29][Step 8/20]  #include <Qpoint>
[16:37:29][Step 8/20]                   ^
[16:

**Comment by dogmaphobic** [comment]
On a side note, as I wait for Windows to reboot for the 1,283,467,384th time, I've implemented a secondary cache for maps. I noticed that the primary cache implemented within Qt is not that great. It will be all transparent to the user. Later I need to add an utility (GUI) to allow you to select what you want to cache for offline use (as Open Pilot mapping did but with a different UI).

**Comment by dogmaphobic** [comment]
> Can you fix the one Linux typo and then this should be ready to merge

Let me take a look...

**Comment by DonLakeFlyer** [comment]
This looks like it's going to work this time. It has to! I've modified TC such that everything else will fail until this goes through.

**Comment by DonLakeFlyer** [comment]
Phew!

**Comment by dogmaphobic** [comment]
Ha! :)

Now the not too small task of implementing the entire mission stuff on top of these maps :)

**Comment by DonLakeFlyer** [comment]
The way the subdirs thing works is that now qgroundcontrol.pro and QtLocation.Pro are completely separate builds right. Nothing shared between? Reason I ask, is that means compiler settings and so forth are not shared across if that is the case.

**Comment by dogmaphobic** [comment]
Correct. They are two, completely independent projects with no shared files. The only dependency is that QGC links with the resulting library produced by the QTLocation project.

**Pull request merged**
