### PR TITLE
Vagrant: use Qt5.11.0 deps

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@peterbarker Sorry to hose you hear but we are literally a pull away from switching to Qt 5.11. Could you changes this to that?

**Comment by DonLakeFlyer** [comment]
https://github.com/mavlink/qgroundcontrol/pull/6529

**Comment by peterbarker** [comment]
@DonLakeFlyer update to 5.11.0.

After @dogmaphobic 's patches this now builds a binary in the Vagrant VM which I can then run on my laptop's native system image.

**Comment by DonLakeFlyer** [comment]
Thanks for the pull Peter.,

**Pull request merged**
