### PR TITLE
PX4 MC PID tuning page

### PR DESCRIPTION
**Pull request by bkueng**
This brings the PID tuning page into a minimally working state.

qgc_pid_tuning_wifi

And over a telemetry link:
qgc_pid_tuning_telem
Unfortunately the update rate is not sufficient (around 10Hz) for it to be useful.

I removed the attitude, since that is generally not required to be tuned for MC.

### TODO
Before merging:
-  [x] make the advanced the default, remove hover & min throttle sliders
-  [x] make sure things are still corrrect for other vehicle types
-  [x] fix overlapping text for slider
-  [ ] descriptions can probably be improved

For later:
- disable graph over telemetry link (e.g. if update rate is < 20Hz)
- keep data when switching between axis (graph + clipboard)
- add ability to lock roll+pitch sliders together
- start graph on arming if not already running
- mouse zooming might be useful
- potentially show `MC_ROLLRATE_MAX` in the graph

Apart from tuning, I think an additional behavior tab would be useful, with sliders for max velocity and responsiveness (jerk limits, max acceleration, which ideally is a combined slider).

@DonLakeFlyer feel free to push the branch for further changes/improvements.

### CODE REVIEW

**Review by LorenzMeier — APPROVED** [review]

**Comment by DonLakeFlyer** [comment]
master branch is on hold for Stable. I'm not letting anything in other than bug fixes at this point. Is this pull in a state which is close enough for going into Stable?

**Comment by bkueng** [comment]
Yes I think so. The only addition I'd like to have for a release is: disable graph over telemetry link (e.g. if update rate is < 20Hz). I can look into that if you want me to.

**Comment by DonLakeFlyer** [comment]
I think that's fine for now then

**Comment by TheLegendaryJedi** [comment]
Hi @bkueng, thanks for your awesome work. Yesterday I tested it using the Crazyflie 2.1 board and it seems that all is working smoothly regarding the PID graphics and tunning (I didn't test much of the tunning)

**Comment by jafrado** [comment]
I agree, this is stellar work. Thank you @bkueng !

**Comment by jstrebel** [comment]
Hi, Thank you for this great extension.
I triad with the Build: 2021-01-13 18:48
I do not get any Graphic Ruler display. Just shows graphic curves of "roll" or "pitch" or "yaw"

I see the messages in the log

[I] at C:\projects\qgroundcontrol\src\FactSystem\ParameterManager.cc:829 - "Attemping load from cache"
[I] at C:\projects\qgroundcontrol\src\FactSystem\ParameterManager.cc:919 - "Parameters cache match failed C:/Users/jakob/AppData/Roaming/QGroundControl.org/ParamCache/1_1.v2"
[D] at C:\projects\qgroundcontrol\src\Vehicle\Vehicle.cc:2063 - "_parametersReady true"
[E] at qrc:/qml/QGroundControl/Controls/PIDTuning.qml:-1 - "qrc:/qml/QGroundControl/Controls/PIDTuning.qml: ReferenceError: param is not defined"
[E] at qrc:/qml/QGroundControl/Controls/PIDTuning.qml:247 - "qrc:/qml/QGroundControl/Controls/PIDTuning.qml:247: ReferenceError: param is not defined"
[E] at qrc:/qml/QGroundControl/Controls/PIDTuning.qml:247 - "qrc:/qml/QGroundControl/Controls/PIDTuning.qml:247: ReferenceError: param is not defined"
[E] at qrc:/qml/QGroundControl/Controls/PIDTuning.qml:247 - "qrc:/qml/QGroundControl/Controls/PIDTuning.qml:247: ReferenceError: param is not defined"
[E] at qrc:/qml/QGroundControl/Controls/PIDTuning.qml:222 - "qrc:/qml/QGroundControl/Controls/PIDTuning.qml:222:13: Unable to assign QJSValue to QQmlListModel*"
[E] at qrc:/qml/QGroundControl/Controls/PIDTuning.qml:227 - "qrc:/qml/QGroundControl/Controls/PIDTuning.qml:227:13: Unable to assign QJSValue to QQmlListModel*"
[E] at qrc:/qml/QGroundControl/Controls/PIDTuning.qml:232 - "qrc:/qml/QGroundControl/Controls/PIDTuning.qml:232:13: Unable to assign QJSValue to QQmlListModel*"

**Comment by bkueng** [comment]
@jstrebel which PX4 version do you use?

**Comment by jstrebel** [comment]
My controller is pixhawk4
FW: PX4 FMU v5
Model: Fixed Wing
I tried with version 1.11.3 and developer master

**Comment by bkueng** [comment]
master should definitely work. Can you check if you have the above displayed parameters? I.e. MC_ROLLRATE_K

**Comment by jstrebel** [comment]
If I look for "MC_" I see only "MC_Airmode" disabled 
 Under Summary: / Airframe / 1.11.0rc
 Under Summary: / Airframe / Airframe Type standard Plane

**Comment by jstrebel** [comment]
@bkueng It looks to me PID tuning works with Generic Quadcopter, but not with Fixed Wing (Standard Plane or Bormatec Maya)

**Comment by bkueng** [comment]
> @bkueng It looks to me PID tuning works with Generic Quadcopter, but not with Fixed Wing (Standard Plane or Bormatec Maya)

Yes that is correct and expected - fixed wing will need a different UI/parameters.

**Comment by mortenfyhn** [comment]
I tried this out yesterday. It's very useful! I have some notes:

It would be neat:

* If the gain slider limits were wider, or adjustable. The were often narrower than what I needed. (Might be connected to the current tuning gain param limits, which I think are based on parallel, not standard form PID.)
* With a button that saves a screenshot the current plot (whether it's stopped or not). I was taking screenshots manually.
* With a longer plot duration (or maybe just an option for it).
* If a horizontal line at 0 deg/s was visible in the plot at all times.
* If the roll/pitch/yaw radio button setting is remembered when I leave the PID tuning view and later come back.

**Comment by jstrebel** [comment]
> > @bkueng It looks to me PID tuning works with Generic Quadcopter, but not with Fixed Wing (Standard Plane or Bormatec Maya)
> 
> Yes that is correct and expected - fixed wing will need a different UI/parameters.

@bkueng is this feature planned for Fixed Wing?

**Comment by bkueng** [comment]
Thanks for the feedback.

> If the gain slider limits were wider, or adjustable. The were often narrower than what I needed. (Might be connected to the current tuning gain param limits, which I think are based on parallel, not standard form PID.)

Can you be specific? What range do you need and what is your existing P gain?

> With a longer plot duration (or maybe just an option for it).

You mean zooming?

> Edit: Also, if I remember correctly, I think the "clipboard values" don't update after moving the slider, I have to switch to another view (e.g. "Parameters") and then switch back. (But then I have to remember to select the correct roll/pitch/yaw radio button setting.)

They store the previous value to revert back, so I'm not sure I understand.

> Edit 2: Maybe the yawrate D gain should give a small warning/note in the yaw tuning view if it's not zero? The PID tuning guide says it should be zero, and there is no slider for it, but the parameter itself may indeed be nonzero.

Potentially yes, but that means someone explicitly set it, and the same reasoning applies to e.g. feed-forward terms.

> @bkueng is this feature planned for Fixed Wing?

Yes we should, but I don't have enough FW experience to do so.

Keeping track here: https://github.com/mavlink/qgroundcontrol/issues/9356

**Comment by mortenfyhn** [comment]
> > If the gain slider limits were wider, or adjustable. The were often narrower than what I needed. (Might be connected to the current tuning gain param limits, which I think are based on parallel, not standard form PID.)
> 
> Can you be specific? What range do you need and what is your existing P gain?

Absolutely. My roll-/pitchrate K is roughly 0.2 (the slider starts at 0.3). My roll-/pitchrate D is roughly 0.02 (the slider stops at 0.01). This is a quad that weighs a few kilos.

> > With a longer plot duration (or maybe just an option for it).
> 
> You mean zooming?

Zooming out, I suppose. Specifically I'd like to have the horizontal axis span, say, 10 seconds instead of the current 3.

> > Edit: Also, if I remember correctly, I think the "clipboard values" don't update after moving the slider, I have to switch to another view (e.g. "Parameters") and then switch back. (But then I have to remember to select the correct roll/pitch/yaw radio button setting.)
> 
> They store the previous value to revert back, so I'm not sure I understand.

My bad, I didn't realize the clipboard was used to store the old values so you can easily revert. Maybe it could be retitled as "Previous values" or something such. The buttons save to / restore from clipboard are probably sufficient to make clear the clipboard functionality.

**Comment by jstrebel** [comment]
On the testing side we could help. What kind of experience do you need?

**Pull request merged**
