### PR TITLE
FactSliderPanel.qml: Correct brackets position

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I have a hunch what you are fixing here, but could you be more specific?

**Comment by DonLakeFlyer** [comment]
Looks like someone had bad tab stops maybe. @patrickelectric No real change in here right?

**Comment by patrickelectric** [comment]
@LorenzMeier @DonLakeFlyer sorry for that. Yes, no real change, only correcting indentation level.

**Comment by DonLakeFlyer** [comment]
Great, thanks. I'll merge in once I'm double sure 3.2 is fully out the door.

**Pull request merged**
