### PR TITLE
Add Mission Items to Fly View

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Just limited information/functionality at this point but it's a start. Thanks to @dogmaphobic MavManager implementation going all the way down to Waypoints it's fairly easy to add the new Qml to the map.

Directionally the Plan View is going to be for editing only, Not editing and showing the active flight. The Fly View is for showing active flights.

screen shot 2015-08-31 at 4 02 31 pm

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
My plan is to finish Fly View, then re-implement Plan View.

**Comment by LorenzMeier** [comment]
Nice! When you want to draw lines between the points I would recommend a spline, since that's what the vehicles will actually do.

**Comment by dogmaphobic** [comment]
Hey, those waypoint views on the bottom look great! Question though: How do I get my Video back? :)

**Comment by DonLakeFlyer** [comment]
Video is only the Primary Flight Display. Trying to keep things simple. Let me know if you think that is bad. I think I may have broken the menu there. Nee dot re-hook to the Options button.

**Comment by dogmaphobic** [comment]
OK, I think I've been away for too long. So, what is the *Fly* panel now? I can see that I can go to the *Primary Flight Display* using the *Advanced Menu*, which still has the video option. I'm assuming the current *Fly* panel is in transition?

**Comment by DonLakeFlyer** [comment]
Give me a couple hours to get video back in the Options menu. Working on finishing another pull.

**Comment by dogmaphobic** [comment]
No worries, and no rush. I was just trying to understand it. I'm trying to get the current vehicle position so I can figure out the graphics for it. Waiting for a GPS signal down in my office... :)

**Comment by DonLakeFlyer** [comment]
I was also thinking about using a see through version of the vehicle with just the outline to put around the waypoint indicator on the map to show yaw setting.

**Pull request merged**
