### PR TITLE
CI: Upload stable release artifacts

### PR DESCRIPTION
**Pull request by mrpollo**
fixes one of the todos on #9946 for uploading stable releases to S3 with GitHub Actions

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
That's not how releases are done in QGC though. They are based on tags which I think are different from a github action standpoint. I'll try to find some time to document the releases process int he dev guide such that someone could automate it.

**Comment by mrpollo** [comment]
Tags are fine, we can manually convert a tag to a release, which should work with this change, or I can change this PR to watch for the created tags event, and regex for semver.

**Comment by mrpollo** [comment]
@DonLakeFlyer, I just realized what you are saying is that we don't make "release builds" like this, and we need a separate release build workflow.

I will wait for your documented instructions and work on a separate CI workflow just for stable releases

**Comment by DonLakeFlyer** [comment]
Basically the stable builds need to kick off based on a "v*" matching tag. And then they need to push to the "latest" directory on S3 which you can see the url structure from the doc links.

**Comment by DonLakeFlyer** [comment]
Also the CONFIG+=DailyBuild needs to be remove when it's a stable build.

**Pull request closed without merging**
