### PR TITLE
appveyor fix nsis install

### PR DESCRIPTION
**Pull request by dagar**
I just noticed appveyor is failing every build due to nsis problems. I'll try to fix it here.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Started last night. Forgot to ping you about it

**Comment by dagar** [comment]
I'm not entirely sure what the difference is between the nsis and nsis.install chocolatey packages, but nsis.install seems to be working.

**Comment by DonLakeFlyer** [comment]
Woohoo! Good to merge?

**Comment by DonLakeFlyer** [comment]
I'm going to merge an re-run the existing pulls as test runs.

**Pull request merged**
