### PR TITLE
Enable ROIModeCapability for ArduPilot vehicles

### PR DESCRIPTION
**Pull request by sypaq-nexton**
Addresses #10640.

### CODE REVIEW

**Comment by booo** [comment]
Please add a comment to the commit message about the fact that some builds don't support ROI features. And/or link the issue with the discussion.

**Comment by sypaq-nexton** [comment]
> Please add a comment to the commit message about the fact that some builds don't support ROI features. And/or link the issue with the discussion.

Done.

**Comment by booo** [comment]
Thanks a lot. 

Do you know if the `MAV_RESULT_UNSUPPORTED` pops up somewhere so the user know about the missing support?

**Comment by sypaq-nexton** [comment]
> Do you know if the `MAV_RESULT_UNSUPPORTED` pops up somewhere so the user know about the missing support?

Yeah, there's a popup that appears on the Fly View.

**Pull request merged**
