### PR TITLE
Update to MAVLink 2.0

### PR DESCRIPTION
**Pull request by LorenzMeier**
@DonLakeFlyer This flicks the switch for MAVLink 2.0 and likely will need compile and runtime fixes. Most notably it needs to be configured to default to MAVLink 1. Probably not for v3.0, but I kind of start to need this to keep development going.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
What exactly does this do? Is master mavlnk 1.0 now set to run 2.0 instead or something?

**Comment by LorenzMeier** [comment]
Yep. You are getting the 2.0 headers which also support 1.0. I already switched PX4 to this.

**Comment by DonLakeFlyer** [comment]
So can this be merged pre-3.1 or not? Or does this pull need to wait?

**Comment by LorenzMeier** [comment]
Once it builds and is tested it can go in any time. It seems to work fine and is a decent update

**Comment by DonLakeFlyer** [comment]
I assume ok to close?

**Pull request closed without merging**
