### PR TITLE
updated logo assignment

### PR DESCRIPTION
**Pull request by shadan-sarfaraz**

### CODE REVIEW

**Comment by zdanek** [comment]
@shadan-sarfaraz can you please write which Issue is connected with this PR?
Or what is the purpose of this PR?

**Comment by Davidsastresas** [comment]
I see in there some logos of a company. I really think @shadan-sarfaraz did this PR by mistake. I am closing it, we can reopen it if some more information is provided.

**Comment by shadan-sarfaraz** [comment]
ye i have made this changes because I was given the task to change it

**Comment by Davidsastresas** [comment]
I understand, but you are aware you are making this PR to the public repository of QGC right? Was this your intention?

**Comment by zdanek** [comment]
That was my guess too so I asked @shadan-sarfaraz what is the purpose 🙂

**Comment by shadan-sarfaraz** [comment]
No, I am not.

**Comment by Davidsastresas** [comment]
Understood, then I guess we can leave this closed.

**Comment by shadan-sarfaraz** [comment]
Yes

**Pull request closed without merging**
