### PR TITLE
Port to master remaining items from 4.4

### PR DESCRIPTION
**Pull request by Davidsastresas**
This PR brings to master some items that were pushed to 4.4 but were still missing in master. It includes:

New gimbal controls: https://github.com/mavlink/qgroundcontrol/pull/11264
Some aditional fixes and improvements: https://github.com/mavlink/qgroundcontrol/pull/11276
Some extra fixes: 4fc99bc 748d185 5218925 69b3ec2

I only tested the changes related to gimbal controls, and they seem to be working the same as in 4.4.

@julianoes, I realized your fixes to camera manager were not present in master, so I brought them from 4.4 too. I think it should be fine, but It would be good if you want to double check. Thanks!

@rmackay9, Even though I tested in SITL the gimbal controls it would be good if you can double check. Thanks!

The following is a list of the commits that were meant to be brought to master, indicating the ones present here as "done" and the ones not brought to this PR indicated:

```
not needed * 08d6c050c - (2 days ago) Updated GPS submodule - Julian Oes (HEAD -> Stable_V4.4, upstream/Stable_V4.4)
not needed * 17f7d8008 - (3 months ago) Update PX4 Firmware metadata Fri Apr 12 19:40:38 UTC 2024 - PX4BuildBot
not needed * 15bdfd5f1 - (6 weeks ago) Revert ".github: Don't upload to S3, just for this particular branch, see details:" - Julian Oes (tag: v4.4.0)
done * 8d72421a9 - (7 weeks ago) QGCCameraManager.cc: change log from qWarning to CameraManagerLog: - davidsastresas (tag: v4.4.0rc5)
done * c1a85b023 - (7 weeks ago) VehicleMapItem.qml: fix qml warning - davidsastresas
not needed * a2d7d1812 - (7 weeks ago) OfflineMap.qml: Fix menu - davidsastresas
already applied * f1ba395bf - (4 months ago) Using GST structure to confirm video decoding stream format. - IanBrace2
done * 9359fc4c1 - (7 weeks ago) QGeoMapReplyQGC: disable noisy warning - Julian Oes
done * 6eb0e4253 - (7 weeks ago) Camera: video stream request fixup - Julian Oes
done * 4b50ece3d - (7 weeks ago) QGeoMapReplyQGC: ignore SSL without OpenSSL 1.x - Julian Oes
not applied, .actions have changed * 750f1f224 - (7 weeks ago) CI: upload artifacts to release - Julian Oes
done * a02e74a47 - (7 weeks ago) Vehicle: fix unit tests after camera change - Julian Oes (tag: v4.4.0rc4)
done * f20f05e87 - (7 weeks ago) Camera: allow camera managed by an autopilot - Julian Oes
done * b02c0dd17 - (7 weeks ago) Camera: switch to new REQUEST_MESSAGE commands - Julian Oes
done * 9b00dc039 - (8 weeks ago) qmake: fix Android version code for RCs - Julian Oes
not needed * a753a8684 - (8 weeks ago) VideoReceiver: bump gstreamer version - Julian Oes (tag: v4.4.0rc3)
not needed * 76cf18080 - (9 weeks ago) .github: fix mac build - davidsastresas (tag: v4.4.0rc2)
not needed * 345ddba88 - (9 weeks ago) .github: Update android gstreamer to 1.18.6: - davidsastresas
done * efa109cfc - (9 weeks ago) GimbalController: Limit how fast we send gimbal status message request: - davidsastresas
done * dd166855d - (9 weeks ago) GimbalController: start handshake only after parameters are donwloaded: - davidsastresas
not needed * ab7c716b0 - (3 months ago) .github: Don't upload to S3, just for this particular branch, see details: - davidsastresas (tag: v4.4.0rc1)
not needed * d9df61e7a - (3 months ago) .github/android_release.yml: remove ext11 to fix build - davidsastresas
not needed * 404545fae - (3 months ago) Revert "MainRootWindow.qml: remove unused viewSwitch() function" - Julian Oes
done * 00fbb1a73 - (3 months ago) SendMavCommandWithSignallingTest.cc: ignore MAV_CMD_REQUEST_MESSAGE: - davidsastresas
done * 7f6a912f5 - (3 months ago) RequestMessageTest.cc: disable vehicle gimbal controller on this test: - davidsastresas
done * 56e05f4a5 - (3 months ago) Vehicle: independent function to delete gimbal controller, needed for tests: - davidsastresas
done * ec2273666 - (4 months ago) FlyViewVideo.qml, OnScreenGimbalController.qml: fix conflict with tracking feature after rebase - davidsastresas
done * 9d3125242 - (4 months ago) GimbalIndicator.qml: Add Acquire/release control button - davidsastresas
done * 390571fbf - (4 months ago) GimbalControllerSettings: Add setting to show or not Acquire/release control button - davidsastresas
done * 29003c4f9 - (4 months ago) GimbalController.cc: send NAN instead of 0 when rates are not used - davidsastresas
done * 24481c888 - (4 months ago) FlyViewMap.qml: connect roilocationitem to vehicle roiCoordChanged: - davidsastresas
done * 23dfa6570 - (4 months ago) Vehicle: add roiCoordChanged signal: - davidsastresas
done * 02370dee9 - (4 months ago) FlyViewMap.qml: ROI edit click area ocupying all the label: - davidsastresas
done * 78ee54ee9 - (4 months ago) Joystick: fix gimbal control and add some new button actions for gimbal control - davidsastresas
done * eb36c29e7 - (4 months ago) InstrumentValueIcons: add 2 new icons for gimbal telemetry, artwork by Alex de la Torre - davidsastresas
done * 96292f0d3 - (4 months ago) FlyviewVideo.qml: add OnScreenGimbalController for gimbal mouse actions control - davidsastresas
done * 91b050d88 - (4 months ago) OnScreenGimbalController.qml: first commit, process onscreen mouse actions for gimbal control - davidsastresas
done * b9f23b375 - (4 months ago) VehicleMapItem.qml: add gimbal yaw indicator over map - davidsastresas
done * 3329ef8d1 - (4 months ago) FirmwarePlugin.cc: add gimbalIndicator to toolIndicators - davidsastresas
done * e88303f61 - (4 months ago) GimbalIndicator.qml: first commit - davidsastresas
done * 26ef825a0 - (4 months ago) qgcresources.qrc: add new icon for gimbal indicator - davidsastresas
done * 5cc5b76f6 - (4 months ago) resources: add new icon for gimbal indicator, artwork by Alex de la Torre - davidsastresas
done * c0d70cbc8 - (4 months ago) Vehicle: add gimbalController, and move gimbal functionality there: - davidsastresas
done * 13ed85703 - (4 months ago) qgroundcontrol.pro: add GimbalController and GimbalControllerSettings - davidsastresas
done * 0e4435f71 - (4 months ago) QGCApplication.cc: add GimbalController and register to qml - davidsastresas
done * e44445ce7 - (4 months ago) GimbalController and GimbalControllerSettings: first commit - davidsastresas
not needed * 6e152ec14 - (4 months ago) FlyViewMap.qml: fix previous c1364dad3 commit after backport to 4.3 from master: - davidsastresas
not needed * 3c39c108b - (5 months ago) Add ROI editing menu - Don Gagne
not needed * e1d4b61c2 - (5 months ago) Add support to pass click position through signal - Don Gagne
not needed * 72e9d7491 - (5 months ago) Remove ROI Indicator from toolbar - Don Gagne
done * 607879a51 - (4 months ago) ToolStrip.qml: expose fontSize for ToolStripHoverButton - davidsastresas
done * c2009ef5e - (4 months ago) MainRootWindow.qml: indicator popup, allow to not dim background - davidsastresas
done * 156be6678 - (4 months ago) QGCButton.qml: add fontWeight property - davidsastresas
```

### CODE REVIEW

**Comment by Davidsastresas** [comment]
It seems it is failing because I missed to update the CMake files. I might have some time to fix that in the following days, but if anybody familiar with CMake wants to help It would be great. I think it is only needed for the new GimbalController class.

**Comment by julianoes** [comment]
Thanks @Davidsastresas. Sounds like we should do a v4.4.1 release soon.

**Comment by rmackay9** [comment]
Great to see this!

of course I'll help with testing and if we want to do that 4.4.1 release then I'll help organise that like last time

**Comment by HTRamsey** [comment]
I suppose we don't need QGeoTiledMapReplyQGC::setIgnoreSSLErrorsIfNeeded in Qt6 since it already uses OpenSSL3, but it doesn't hurt to have it either

**Comment by Davidsastresas** [comment]
> I suppose we don't need QGeoTiledMapReplyQGC::setIgnoreSSLErrorsIfNeeded in Qt6 since it already uses OpenSSL3, but it doesn't hurt to have it either

Good catch! At first I thought the same, but then I realized it is useful too for the other way around, for Qt6 in systems that have OpenSSL1 instead. I think it doesn't hurt either, so I would vote for leaving it there. Thanks for the review!

**Comment by HTRamsey** [comment]
@Davidsastresas Fixed CMake

**Comment by Davidsastresas** [comment]
> @Davidsastresas Fixed CMake

Amazing, thank you very much! Let's give it a few days in case Julian and Randy come up with some modification needed before merging. I will remove the draft label too. Thank you!

**Comment by rmackay9** [comment]
I tried to test this today on my Windows machine and it wouldn't even start.

I suspect that the issue is not actually related to this PR so I tried to install the "Daily Build" but was not able to find an installer.  The [link on the Daily Builds page](https://docs.qgroundcontrol.com/master/en/qgc-user-guide/releases/daily_builds.html)** seems broken ([click here to see what I mean](https://d176tv9ibo4jno.cloudfront.net/builds/master/QGroundControl-installer.exe))

**Comment by Davidsastresas** [comment]
Sorry to hear that @rmackay9, if you had your previous build environment setup for QGC 4.4, for master you need qt6, and I am not sure if for windows you need different visual studio toolchain too. There are lots of changes on the build setup right now for QGC 4.4 vs master.

The builds corresponding to this PR should be here ( I found them searching manually in actions ):
Linux: https://github.com/mavlink/qgroundcontrol/actions/runs/10068063218
macos: https://github.com/mavlink/qgroundcontrol/actions/runs/10068063221
windows: https://github.com/mavlink/qgroundcontrol/actions/runs/10068063226
android: https://github.com/mavlink/qgroundcontrol/actions/runs/10068063231

Let me know if that fixes the situation for the moment!

**Comment by HTRamsey** [comment]
Oh you'll have to try again on the latest build because of this #11678, it works fine now.

**Comment by HTRamsey** [comment]
You can always just grab it from [the latest run](https://github.com/mavlink/qgroundcontrol/actions/runs/10189636795). But yeah I guess the daily windows link needs to be updated

**Comment by rmackay9** [comment]
Hi @HTRamsey @Davidsastresas,

Thanks for that.  So the daily build [using this installer](https://github.com/mavlink/qgroundcontrol/actions/runs/10189636795) does work and I think this means that this PR does not but hopefully that is just because it needs to be rebased (I'm guessing of course)

**Comment by HTRamsey** [comment]
@Davidsastresas a followup to my QGeoMapReplyQGC comment, you can just use QGCFileDownload::setIgnoreSSLErrorsIfNeeded which is the exact same function.

**Comment by Davidsastresas** [comment]
> Also @Davidsastresas you said you found those links manually from actions, if I'm understanding you correctly just FYI you can also just click details on the builds results below where it says All checks have passed.

@HTRamsey  For some reason doing that I can only see the job, but not the artifact to download! Does it work for you to download the artifact too? I am using google chrome in case that matters.

Thanks for fixing build for Windows. I haven't had the chance to build because I need to setup cmake, I was still using qmake, it is probably not a big deal but I need to spare an hour or two to understand everything for the next time. 

Thanks!

**Comment by Davidsastresas** [comment]
> setIgnoreSSLErrorsIfNeeded

Please note the branch is in mavlink repo, so you can directly commit to it. Please feel free to change that if you see fit. As it is now it works for me on a machine with OpenSSL 1 on Ubuntu 20.04. Thanks!

**Comment by Davidsastresas** [comment]
@julianoes for awareness, I just pushed here your commits from this PR https://github.com/mavlink/qgroundcontrol/pull/11706 So hopefully we can keep master updated with what we are doing in QGC 4. Thanks!

**Comment by HTRamsey** [comment]
@Davidsastresas after clicking details you have to click Summary at the top left

**Comment by Davidsastresas** [comment]
> @Davidsastresas after clicking details you have to click Summary at the top left

No way.... I've been for ages thinking it was a github bug. Thank you for enlightening me! :)

**Comment by rmackay9** [comment]
I tested this today on my windows PC and it seems to work fine.  I connected my desktop CubeRed + SiyiA8 to my PC via USB and confirmed the following worked

1. gimbal control menu appeared (but only after having connected with MP or manually setting the SR0_xxx parameters)
2. "Center and "Tilt 90" buttons worked
3. Yaw Lock / Yaw Follow worked correctly.  In particular when in Yaw Lock, the gimbal maintained its heading regardless of the autopilot's heading.  In Yaw Follow the gimbal's yaw rotated with the vehicle
4. Click-to-point on the video stream resulted in the gimbal pointing to a reasonable angle (I did not have the FOV set perfectly but it seemed correct)
5. "Point Home" and "Retract" buttons worked

By the way, not related directly to this testing but this gave me the opportunity to test the camera and gimbals controls (FYI @DonLakeFlyer):

- The zoom slider worked!
- The take-picture button did not work sadly
- The record video control was not visible

Also not related to this PR but it seems that QGC Daily is not proactively requesting data from the autopilot.  It seems to be passively waiting for the drone to start sending mavlink messages.  This seems like a change in behaviour vs QGC4.4.  I guess it is intentional?  BTW, I think that AP obeys the mavlink spec and we've documented here on [this AP wiki page how GCSs, companion computers can request data be sent by the autopilot](https://ardupilot.org/dev/docs/mavlink-requesting-data.html) which includes three basic methods:

1. Using SRx Parameters
2. Using REQUEST_DATA_STREAM
3. Using SET_MESSAGE_INTERVAL

**Review by rmackay9 — APPROVED** [review]
I've done my testing and it seems to work just like in QGC4.4

Thanks again for this great enhancement!

**Comment by Davidsastresas** [comment]
Thanks @rmackay9 for the confirmation. I will hold on a couple days more, as we found a bug that was preventing AP to work correctly on that "point home" action, so next week I will add that and merge this if @julianoes is alright with the changes.

Regarding the default rates, indeed the default behavior changed vs 4.4, but you can change the setting so QGC asks the rates to the autopilot, here:
Screenshot from 2024-08-09 16-51-59

Is this super problematic for AP? I thought by default in AP we had some kind of default for those SRX parameters. Let me know your thoughts!

**Comment by julianoes** [comment]
@Davidsastresas ok, so we should disable it again in v4.4? PX4 has some default rates. AP requires it to be configured, right?

**Comment by rmackay9** [comment]
Hi @Davidsastresas,

Thanks for the feedback on the rates.  I think it will be a large problem for AP copter users.  Copter does not set the stream rates by default (Plane and Rover do).  So if possible I think for AP users QGC should ask for the streams it wants by default

**Comment by HTRamsey** [comment]
Seems strange that it isn't consistent, any idea why it's like that? I always have to turn this setting off on Copter because it messes with my intended message rates that I set via a message interval config file.

**Comment by DonLakeFlyer** [comment]
> The difference is that this setting was enabled by default in 4.4, but it is not by default in master.

Why the difference between an older stable and master?

**Comment by julianoes** [comment]
> Why the difference between an older stable and master?

I'm just trying not to break stuff with v4.4. If I broke something between v4.3 to v4.4, then I'd want to fix it. Then when it comes to master/v5, I understand that there will be surprises/changes/breaks, all that.

**Comment by rmackay9** [comment]
Hi @HTRamsey, re "strange that it is consistent" I guess you're talking about AP and the difference between Copter and Plane/Rover?  We could/should make them consistent and we've removed many other inconsistencies but this one is sticky and I don't think we will have it fixed in time for the next QGC release (QGC4.5?).

BTW, I think that message interval is a better idea than using stream rates and AP supports message interval messages sent by the GCS so my ideal solution would be for QGC to request what it needs.

**Comment by Davidsastresas** [comment]
So, maybe for the moment, on a different PR, we can address this and leave it as it was in 4.x? And maybe over time we can implement individual messages instead, and make a nice interface to select the messages we want to address.

I like this option more as it is now in master, leaving AP in charge of it, because as @HTRamsey I also forgot a lot of times this is default and it messed with other telemetry settings I had set. But if @rmackay9  confirms this is nicer for AP, I think we could leave this settings as it used to be and re evaluate in the future when AP makes this default in Copter too.

**Comment by rmackay9** [comment]
@Davidsastresas, that sounds fine to me.  From my point of view, this PR seems ready to go (and I've approved it above).  Thanks!

**Comment by DonLakeFlyer** [comment]
So what's the state of the streaming controlled by vehicle for AP in this pull? It should be off by default. Also @julianoes I would consider if 4.4 has this on by default changing it back to off. This is going to catch a bunch of people by surprise. If in copter they haven't setting up stream rate params then QGC will simply seem to not work. I expect many support problem from that. That's a bad change in behavior.

**Comment by DonLakeFlyer** [comment]
> BTW, I think that message interval is a better idea than using stream rates and AP supports message interval messages sent by the GCS so my ideal solution would be for QGC to request what it needs.

Maybe we should create an Issue to discuss this? I don't quite see how a ground station supports firmware which doesn't stream things to it by default I'm a user friendly way. It's more than what QGC needs to run. There is much information in the default streams that are useful to look at when you need them. Having to turn on individual telemetry values one at a time as you need doesn't seem very user friendly.

**Comment by rmackay9** [comment]
@DonLakeFlyer,

I can't answer all your questions but this PR doesn't change how the telemetry streaming works in latest/daily.  The change in behaviour is already in latest/daily.  So from my point of view, QGC4.4 is OK and it's latest/daily that has been changed.

From a tester/user point of view, I think this PR is ready to merge

**Comment by DonLakeFlyer** [comment]
Thanks @rmackay9. This is fine then.

**Comment by DonLakeFlyer** [comment]
@Davidsastresas Can you rebase, fix conflicts and I'll merge.

**Comment by Davidsastresas** [comment]
Thanks @DonLakeFlyer, it seems @HTRamsey did the rebaseThi yesterday ( thank you! ) and everything was clear to rebase, so I went ahead. 

As far as I know, this should leave master with all the features 4.4 currently has. We can follow on that other thread about the default stream rates issue.

thank you everybody!

**Comment by ChaoYuChang** [comment]
I downloaded the newest version QGC on github, and I Build it with the QT Creator version 14.0.2 , QT 6.7.3 and Visual Studio 2022. When I changed the video input method to RTSP, I received the error  : VideoReceiverLog: Failed and VideoReceiverLog: Stop Called on empty URI. I had search for the information about the error and I found that may be the problem of QT5 -> QT6. Can anyone help me about this problem.

**Pull request merged**
