### PR TITLE
QGC: Solve problem with limitAngleToPMPId when angle is bigger than PI

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Should this go into Stable 3.3 as well?

**Comment by patrickelectric** [comment]
I believe so, this function should return values from 0-2pi

**Comment by DonLakeFlyer** [comment]
Ok. Can you submit the change against Stable_V3.3 branch as well then?

**Comment by DonLakeFlyer** [comment]
I'm going to hold this from merging until there is the same pull on the Stable side. That way it won't get lost.

**Comment by patrickelectric** [comment]
@DonLakeFlyer done.

**Comment by patrickelectric** [comment]
@DonLakeFlyer This commit will be cherry-pick to master (or rebased) ?

**Comment by DonLakeFlyer** [comment]
I'll do a merge from Stable to master at some point. So we are all good.

**Pull request merged**
