### PR TITLE
[DO NOT MERGE, WIP] Mission stats

### PR DESCRIPTION
**Pull request by birchera**
This PR will eventually solve https://github.com/mavlink/qgroundcontrol/issues/3802.

The idea is to display the mission specific values on the right, while waypoint specific values are listed on the left, where they used to be. It always shows total mission distance and time, as well as max telemetry distance. In case of a vtol connected, it also shows the splits for cruise and hover.

If the active waypoint element is a survey item, the left side contains the expected number of camera shots and the covered area. To this end, the unit of area can be chosen in general settings.

### CODE REVIEW

**Comment by birchera** [comment]
screenshot from 2016-07-18 08 28 13

**Comment by DonLakeFlyer** [comment]
Fantastic work! Give me some time today to look at it.

**Comment by DonLakeFlyer** [comment]
I'd like to see this pull split up into multiple pulls. This will make things easier to review and then we can merge in a part at a time. I'd propose the grouping:
1) Settings changes for area units and fact meta data changes for the new translations.
2) Plumb the properties for the calculated values through MissionController and ComplexMissionItem. Initially with just test values. Expose in the status display as you have it. I think that is good enough for now. 
3) Then a separate pull for the calculation of each value. Except for ones that are trivial enough to put together.

FYI: I'll be refactoring ComplexMissionItem into a base class and SurveyItem. I'd like to get that done soon, but we'll have to coordinate the timing since you will be in there.

**Comment by DonLakeFlyer** [comment]
Also should have mentioned that this all looks to be heading int he correct direction. So I see no reason for those multiple pulls to be merged in once they pass CI.

**Comment by birchera** [comment]
This PR gets replaced by multiple smaller ones.

**Pull request closed without merging**
