### PR TITLE
Removing unused Main Flight Display widget.

### PR DESCRIPTION
**Pull request by dogmaphobic**
It used to be a *Docking* window that is no longer used or needed.
Also removed all its resources.
Bumped settings version in case you had it saved with it open.

### CODE REVIEW

**Comment by dogmaphobic** [comment]
Unittest failed but I have no idea how I could have caused it:

`MissionManagerTest::_testReadFailureHandlingAPM()`

Was it really something I did?

**Comment by DonLakeFlyer** [comment]
Rebase to master

**Comment by dogmaphobic** [comment]
That didn't seem to help...

**Comment by DonLakeFlyer** [comment]
Wait that's a different failure than I expected. That's probably an autoconnect break.

**Pull request merged**
