### PR TITLE
main: Allow user to open QGC

### PR DESCRIPTION
**Pull request by patrickelectric**
Some users report that our check does work

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by bkueng** [comment]
Why would you want to allow this? There's multiple files like caches that will be accessed by both instances.

**Comment by patrickelectric** [comment]
@bkueng check: https://px4.slack.com/archives/C629RE9H7/p1661268112226079

**Review by bkueng — CHANGES_REQUESTED** [review]
Ok this isn't the right way to resolve this then. We need to find the root cause.

**Comment by patrickelectric** [comment]
@bkueng @mrpollo, so, there is the tradeoff of not allowing users to open QGC under windows 11 or merging the temporary fix until we find the root of the problem.

**Comment by bkueng** [comment]
You can also check if it's running on windows 11. But that's still a pretty bad user experience.

**Comment by junwoo091400** [comment]
> @bkueng check: https://px4.slack.com/archives/C629RE9H7/p1661268112226079

Screenshot of the discussion archived here, as it will get removed soon

image

**Comment by booo** [comment]
What do we do about this change?

I second that we should find the root cause rather than fixing the symptoms.

**Comment by booo** [comment]
I will close this one for now because of lack of activity and because two people think it's not the right way to resolve the problem.

Please reopen if you think this should be merged e.g. temporary as fix.

**Pull request closed without merging**
