### PR TITLE
fix linux unittests failure

### PR DESCRIPTION
**Pull request by dagar**
On travis-ci linux the unit tests assert because QStandardPaths::DocumentsLocation is `/home/travis/Documents` which doesn't exist. Can we just remove the assert?
`documentsDir.mkpath(_defaultSavedFileDirectoryName)` will create the parent directory if it's missing.

    QDir documentsDir(documentsLocation);
    //Q_ASSERT(documentsDir.exists());

    bool pathCreated = documentsDir.mkpath(_defaultSavedFileDirectoryName);

### CODE REVIEW

**Comment by dagar** [comment]
I have no explanation for this, but even if I create the directories manually travis-ci still hits this assert. If I remove the assert the tests run and pass.

    ASSERT: "documentsDir.exists()" in file src/QGCApplication.cc, line 393
    /home/travis/build.sh: line 41: 14186 Aborted                 ./debug/qgroundcontrol --unittest

We could just remove the assert because mkpath will create the parent directory (documentsDir).

        QDir documentsDir(documentsLocation);
        //Q_ASSERT(documentsDir.exists());

        bool pathCreated = documentsDir.mkpath(_defaultSavedFileDirectoryName);

**Comment by DonLakeFlyer** [comment]
I think this can happen when you have a permission problem. Some folks have hit it when the ran QGC under sudo and then ran it without sudo and it fails. That said it should be a qWarning not an assert (in general I"m moving almost all ASSERTs to qWarning).. But it probable still needs to be figure out. Tests likely run because we don't have any that use the value yet. But if at some point we do, they will begin to fail as well.

**Comment by dagar** [comment]
I replaced the assert with qwarning and the linux debug build unit tests are running properly.

**Comment by DonLakeFlyer** [comment]
That's only a temp fix. The unit tests shoudl be running with QT_FATAL_WARNINGS as an evironment variable set. Sorry forgot to tell you about that. I think for now we could leave Linux and maybe Windows with QT_FATAL_WARNINGS off, and only it turn it on for OSX. OSX tends to be the most stable and we'll caught most issue with just one OS.

**Comment by dagar** [comment]
Added QT_FATAL_WARNINGS for osx.

**Comment by DonLakeFlyer** [comment]
I think I stumbled across the mavlink thing by accident. It may have been memory corruption. I might have fixed it in here: https://github.com/mavlink/qgroundcontrol/pull/1847

**Comment by dagar** [comment]
QT_FATAL_WARNINGS removed

**Pull request merged**
