### PR TITLE
[WIP] Add support for message DEBUG_ARRAY

### PR DESCRIPTION
**Pull request by jlecoeur**
Adds support for message DEBUG_ARRAY

- [x] display DEBUG_ARRAY with same formatting as DEBUG_VECT in analyze widget
- [ ] update mavlink version once https://github.com/mavlink/mavlink/pull/734 is in

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@jlecoeur Compilation errors all over the place.

**Comment by jlecoeur** [comment]
Yes, it relies on a message which is not merged in mavlink.
Should I temporarily modify the mavlink submodules URL and commits?

**Comment by DonLakeFlyer** [comment]
You'll need to wait for the mavlink changes to go through first. Then update the submodule in this pull as well.

**Comment by jlecoeur** [comment]
Ok!

**Comment by DonLakeFlyer** [comment]
@jlecoeur What is going on with this?

**Comment by jlecoeur** [comment]
@DonLakeFlyer  this is still waiting on the mavlink PR, there is no answer there.

Otherwise I have used a custom QGC build with this PR and it works flawlessly, I just hope it can make it to master eventually.

**Comment by DonLakeFlyer** [comment]
Closing since this has been sitting here forever

**Comment by TSC21** [comment]
This can now be rebooted since https://github.com/mavlink/mavlink/pull/734 was merged.

**Pull request closed without merging**
