### PR TITLE
Usability fixes:

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
- Only show clear trim dialog once
- Remove animation from bars
- Move additional setup down with bar

@LorenzMeier Can you try this one out?

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Will do and report back. Thanks!

**Comment by LorenzMeier** [comment]
@DonLakeFlyer BTW: I liked the bar animation - just not during calibration 8).

**Comment by DonLakeFlyer** [comment]
Yup, my idea as well. Not enough time right now to make it work correctly. So off for now.

**Comment by DonLakeFlyer** [comment]
Merging in so it will show up in tonights dailies. We can fix any issues after the fact.

**Comment by LorenzMeier** [comment]
looking good, thanks!

**Pull request merged**
