### PR TITLE
Fix Joystick instantitation from settings

### PR DESCRIPTION
**Pull request by LorenzMeier**
@tumbili @devbharat This should put your joystick issues to rest. Please test and let us know.

### CODE REVIEW

**Comment by devbharat** [comment]
QGC dies as soon as sitl starts communicating with QGC

**Comment by LorenzMeier** [comment]
Delete your build dir. That sounds like a flaky build. Make sure that you *know* what the actual build dir is.

**Comment by LorenzMeier** [comment]
@devbharat @tumbili Fixed and tested. This should work and not crash.

**Comment by tumbili** [comment]
@LorenzMeier Tested, works!

**Pull request merged**
