### PR TITLE
Qmlglsink: Gstreamer Build Fixes

### PR DESCRIPTION
**Pull request by HTRamsey**
This gets gstreamer to link correctly via cmake, and removes the unnecessary gst-plugins-good submodule since we only need the few files of the one plugin. Video is working fine on a Oneplus 9 pro streaming a 8mp 30fps rtsp camera.

### CODE REVIEW

**Comment by HTRamsey** [comment]
@zdanek this look good to you?

**Comment by julianoes** [comment]
Hm, so you're just copying in some gstreamer files? I'm not sure I like that in terms of maintainability. Or did I misunderstand this?

**Comment by HTRamsey** [comment]
> Hm, so you're just copying in some gstreamer files? I'm not sure I like that in terms of maintainability. Or did I misunderstand this?

Most of this is fixing the cmake part that links to gstreamer. The part where I copied gstreamer files in is because QGC has used custom modified gstreamer files for a long time now and the only reason this is still needed is because Linux distros like Ubuntu 22.04 still use an older gstreamer that doesn't support Qt6. The submodule we were using [here](https://github.com/mavlink/gst-plugins-good/tree/5ff0a6af0e1fd29bafc9f6644e728d24349d0ce7) was forked from [here](https://github.com/GStreamer/gst-plugins-good) which is now defunct. Only a single plugin (qt) was ever used from the entire gst-plugins-good, so I removed 99% of the gst-plugins-good that was unused in the submodule, and copied over the only code that's actually important. Either way we are still using custom gstreamer files rather than pulling directly from gstreamer.

**Comment by julianoes** [comment]
> because Linux distros like Ubuntu 22.04 still use an older gstreamer that doesn't support Qt6

I see, what a pain.

Fine with me then.

**Comment by DonLakeFlyer** [comment]
Regarding streamer on Linux. Should we move away from using the OS provided version of streamer on linux and instead use the same version used everywhere else and include it in the appimage?

**Comment by HTRamsey** [comment]
That's a decent option, but I have no idea how significantly it will affect the build time or appimage size

**Comment by HTRamsey** [comment]
@DonLakeFlyer Can you test video on mac?

**Comment by DonLakeFlyer** [comment]
Yes, I can do basic video testing on Mac using PX4 SITL.

**Comment by HTRamsey** [comment]
[of course](https://bugreports.qt.io/browse/QTBUG-114635)

**Comment by DonLakeFlyer** [comment]
I don't really know what Wayland is. But could we drop support for it for now until they fix this somehow?

**Pull request merged**
