### PR TITLE
Stupid proof Linux serial port use

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Fix for Issue #2609, #2608

@LorenzMeier @dogmaphobic Can you guys look this over. Especially for wording.

### CODE REVIEW

**Comment by dogmaphobic** [comment]
Missing:
```
#include <unistd.h>
#include <sys/types.h>
```

**Comment by dagar** [comment]
I like the root and dialout group check, but I'm not sure about including Ubuntu specific instructions. Can that part at least be hidden behind an Ubuntu check? Even if Ubuntu is the only distro you want to officially support I know there are current users on Fedora, Arch, etc. 

You can determine if it's Ubuntu by looking at /etc/os-release

    NAME="Ubuntu"
    VERSION="14.04.3 LTS, Trusty Tahr"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 14.04.3 LTS"
    VERSION_ID="14.04"
    HOME_URL="http://www.ubuntu.com/"
    SUPPORT_URL="http://help.ubuntu.com/"
    BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Comment by DonLakeFlyer** [comment]
What is Ubuntu specific?

**Comment by dagar** [comment]
This is only valid on Ubuntu and Debian

    sudo usermod -a -G dialout $USER
    sudo apt-get remove modemmanager

**Comment by DonLakeFlyer** [comment]
Ah, didn't realize that. We use those same instructions on both the QGroundControl and PX4 web site without mention of Ubuntu. I'd rather not get too fancy since that stuff just tends to break in weird ways. How about just modify the text to mention Ubuntu and/or Debian?

**Comment by dagar** [comment]
Yes that should be fine.

**Comment by LorenzMeier** [comment]
Mentioning Ubuntu should be fine. You only get the union of ```stupid user ∪ Linux``` for Ubuntu and not so much for other Linux systems.

**Pull request merged**
