### PR TITLE
Fix more QTime deprecated functions

### PR DESCRIPTION
**Pull request by patrickelectric**
- This fix a bunch of warning messages related to QTime functions that will be deprecated

### CODE REVIEW

**Comment by patrickelectric** [comment]
@DonLakeFlyer @dogmaphobic this removed a bunch of warning messages, this is also part of my plan to remove all warnings in QGC, probably it'll be finished in more 2 patchs after this one

**Comment by DonLakeFlyer** [comment]
What is being deprecated and when?

**Comment by patrickelectric** [comment]
https://code.woboq.org/qt5/qtbase/src/corelib/time/qdatetime.h.html#209

**Comment by patrickelectric** [comment]
```
/home/patrick/git/blue/qgroundcontrol/src/Camera/QGCCameraManager.cc:240:49: warning: ‘int QTime::elapsed() const’ is deprecated: Use QElapsedTimer instead [-Wdeprecated-declarations]                      [30/315]
  240 |                 if(pInfo->lastHeartbeat.elapsed() > 5000) {                                                                                                                                                  
      |                                                 ^                                                                                                                                                            
In file included from /usr/include/qt/QtCore/QDateTime:1,                                                                                                                                                            
                 from /home/patrick/git/blue/qgroundcontrol/src/comm/LinkInterface.h:13,                                                                                                                             
                 from /home/patrick/git/blue/qgroundcontrol/src/comm/LinkManager.h:21,                                                                                                                               
                 from /home/patrick/git/blue/qgroundcontrol/src/QGCApplication.h:18,                                                                                                                                 
                 from /home/patrick/git/blue/qgroundcontrol/src/Camera/QGCCameraManager.cc:8:                                                                                                                        
/usr/include/qt/QtCore/qdatetime.h:230:54: note: declared here                                                                                                                                                       
  230 |     QT_DEPRECATED_X("Use QElapsedTimer instead") int elapsed() const;                                                                                                                                        
      |                                                      ^~~~~~~                                                                                                                                                 
/home/patrick/git/blue/qgroundcontrol/src/Camera/QGCCameraManager.cc: In member function ‘virtual void QGCCameraManager::_stepZoom(int)’:                                                                            
/home/patrick/git/blue/qgroundcontrol/src/Camera/QGCCameraManager.cc:462:32: warning: ‘int QTime::elapsed() const’ is deprecated: Use QElapsedTimer instead [-Wdeprecated-declarations]                              
  462 |     if(_lastZoomChange.elapsed() > 40) {                                                                                                                                                                     
      |                                ^                                                                                                                                                                             
In file included from /usr/include/qt/QtCore/QDateTime:1,                                                                                                                                                            
                 from /home/patrick/git/blue/qgroundcontrol/src/comm/LinkInterface.h:13,                                                                                                                             
                 from /home/patrick/git/blue/qgroundcontrol/src/comm/LinkManager.h:21,                                                                                                                               
                 from /home/patrick/git/blue/qgroundcontrol/src/QGCApplication.h:18,                                                                                                                                 
                 from /home/patrick/git/blue/qgroundcontrol/src/Camera/QGCCameraManager.cc:8:                                                                                                                        
/usr/include/qt/QtCore/qdatetime.h:230:54: note: declared here                                                                                                                                                       
  230 |     QT_DEPRECATED_X("Use QElapsedTimer instead") int elapsed() const;                                                                                                                                        
      |                                                      ^~~~~~~                                                                                                                                                 
/home/patrick/git/blue/qgroundcontrol/src/Camera/QGCCameraManager.cc:463:31: warning: ‘void QTime::start()’ is deprecated: Use QElapsedTimer instead [-Wdeprecated-declarations]                                     
  463 |         _lastZoomChange.start();                                                                                                                                                                             
      |                               ^                                                                                                                                                                              
In file included from /usr/include/qt/QtCore/QDateTime:1,                                                                                                                                                            
                 from /home/patrick/git/blue/qgroundcontrol/src/comm/LinkInterface.h:13,                                                                                                                             
                 from /home/patrick/git/blue/qgroundcontrol/src/comm/LinkManager.h:21,                                                                                                                               
                 from /home/patrick/git/blue/qgroundcontrol/src/QGCApplication.h:18,                                                                                                                                 
                 from /home/patrick/git/blue/qgroundcontrol/src/Camera/QGCCameraManager.cc:8:                                                                                                                        
/usr/include/qt/QtCore/qdatetime.h:228:55: note: declared here
  228 |     QT_DEPRECATED_X("Use QElapsedTimer instead") void start();
      |                                                       ^~~~~
/home/patrick/git/blue/qgroundcontrol/src/Camera/QGCCameraManager.cc: In member function ‘virtual void QGCCameraManager::_stepCamera(int)’:
/home/patrick/git/blue/qgroundcontrol/src/Camera/QGCCameraManager.cc:498:34: warning: ‘int QTime::elapsed() const’ is deprecated: Use QElapsedTimer instead [-Wdeprecated-declarations]
  498 |     if(_lastCameraChange.elapsed() > 1000) {
      |                                  ^
In file included from /usr/include/qt/QtCore/QDateTime:1,
                 from /home/patrick/git/blue/qgroundcontrol/src/comm/LinkInterface.h:13,
                 from /home/patrick/git/blue/qgroundcontrol/src/comm/LinkManager.h:21,
                 from /home/patrick/git/blue/qgroundcontrol/src/QGCApplication.h:18,
                 from /home/patrick/git/blue/qgroundcontrol/src/Camera/QGCCameraManager.cc:8:
/usr/include/qt/QtCore/qdatetime.h:230:54: note: declared here
  230 |     QT_DEPRECATED_X("Use QElapsedTimer instead") int elapsed() const;
      |                                                      ^~~~~~~
/home/patrick/git/blue/qgroundcontrol/src/Camera/QGCCameraManager.cc:499:33: warning: ‘void QTime::start()’ is deprecated: Use QElapsedTimer instead [-Wdeprecated-declarations]
  499 |         _lastCameraChange.start();
      |                                 ^
In file included from /usr/include/qt/QtCore/QDateTime:1,
                 from /home/patrick/git/blue/qgroundcontrol/src/comm/LinkInterface.h:13,
                 from /home/patrick/git/blue/qgroundcontrol/src/comm/LinkManager.h:21,
                 from /home/patrick/git/blue/qgroundcontrol/src/QGCApplication.h:18,
                 from /home/patrick/git/blue/qgroundcontrol/src/Camera/QGCCameraManager.cc:8:
/usr/include/qt/QtCore/qdatetime.h:228:55: note: declared here
  228 |     QT_DEPRECATED_X("Use QElapsedTimer instead") void start();
      |                                                       ^~~~~
/home/patrick/git/blue/qgroundcontrol/src/Camera/QGCCameraManager.cc: In member function ‘virtual void QGCCameraManager::_stepStream(int)’:
/home/patrick/git/blue/qgroundcontrol/src/Camera/QGCCameraManager.cc:512:34: warning: ‘int QTime::elapsed() const’ is deprecated: Use QElapsedTimer instead [-Wdeprecated-declarations]
  512 |     if(_lastCameraChange.elapsed() > 1000) {
      |                                  ^
In file included from /usr/include/qt/QtCore/QDateTime:1,
                 from /home/patrick/git/blue/qgroundcontrol/src/comm/LinkInterface.h:13,
                 from /home/patrick/git/blue/qgroundcontrol/src/comm/LinkManager.h:21,
                 from /home/patrick/git/blue/qgroundcontrol/src/QGCApplication.h:18,
                 from /home/patrick/git/blue/qgroundcontrol/src/Camera/QGCCameraManager.cc:8:
/usr/include/qt/QtCore/qdatetime.h:230:54: note: declared here
  230 |     QT_DEPRECATED_X("Use QElapsedTimer instead") int elapsed() const;
      |                                                      ^~~~~~~
/home/patrick/git/blue/qgroundcontrol/src/Camera/QGCCameraManager.cc:513:33: warning: ‘void QTime::start()’ is deprecated: Use QElapsedTimer instead [-Wdeprecated-declarations]
  513 |         _lastCameraChange.start();
      |                                 ^
In file included from /usr/include/qt/QtCore/QDateTime:1,
                 from /home/patrick/git/blue/qgroundcontrol/src/comm/LinkInterface.h:13,
                 from /home/patrick/git/blue/qgroundcontrol/src/comm/LinkManager.h:21,
                 from /home/patrick/git/blue/qgroundcontrol/src/QGCApplication.h:18,
                 from /home/patrick/git/blue/qgroundcontrol/src/Camera/QGCCameraManager.cc:8:
/usr/include/qt/QtCore/qdatetime.h:228:55: note: declared here
  228 |     QT_DEPRECATED_X("Use QElapsedTimer instead") void start();

```

**Comment by patrickelectric** [comment]
https://github.com/mavlink/qgroundcontrol/pull/8352

**Comment by patrickelectric** [comment]
Ping @DonLakeFlyer

**Comment by patrickelectric** [comment]
Ping @DonLakeFlyer

**Pull request merged**
