### PR TITLE
Flight View Work

### PR DESCRIPTION
**Pull request by dogmaphobic**
* New plumbing dealing the *Fly View* content. Now everything is loaded by *Loaders*.
* Added *Picture In Picture* to switch views between Map and Video (only present if video is enabled)
* New flight data widgets. For now only *Attitude* and *Compass* are done.

I've also changed the way the *Help Screen* in the mission editor is displayed. The idea there is to eventually create some control that *Drops Down* from the top of the window and offer *Modal* content such as this help screen, settings, etc. Yet to be done...

Known Issues:

* Font size for the Pitch Indicator on Android is out of whack
* When you switch between Video and Map, the Video display goes crazy for a second or so until it resyncs.

This is a first pass. I'm making this commit because I've accumulated too many changes and it would be prone to merge conflicts if I held on to it.

Work in progress...

### CODE REVIEW

**Comment by dogmaphobic** [comment]
screen shot 2015-10-26 at 2 21 50 pm

**Comment by dogmaphobic** [comment]
s

Fixed Android sizes. Screen grab shows interface when video is NOT enabled (no PIP).

**Comment by LorenzMeier** [comment]
This looks super cool! On the user model side it would be great to have the altitude over ground also prominently. You can start using the negated LOCAL_POS.z value, but I'm introducing a new altitude message right now. Maybe filling the compass plane indicator, reducing it in size and filling the space with a big altitude number would help?

**Comment by LorenzMeier** [comment]
Also to wrap a bit up:

  * Altitude over ground (key for managing the flight, as not observable on the map)
  * Velocity (default m/s, but configurable to km/h and mph)
  * Flight time (time since arming?)

**Comment by dogmaphobic** [comment]
The various speeds, altitudes, etc. will go into a vertical widget on the right side of the screen above the existing *Instrument Panel*. Just let me know what should make it there and I will add it.

**Comment by sacc1** [comment]
Hi It's the first time for me with qgroundcontrol and I will ask you if there is a way to store Altitude data and Compass data.
thank you so much

**Comment by DonLakeFlyer** [comment]
Please use one of the suppor forms shown here: http://qgroundcontrol.com/#resources

**Pull request merged**
