### PR TITLE
Add manual entry option for enumerated and bitmask parameters

### PR DESCRIPTION
**Pull request by jaxxzer**
Addresses https://github.com/mavlink/qgroundcontrol/issues/4534

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Can you change this as follows:

If you run with PX4 stack you will see an Advanced section to the editor dialog:
screen shot 2017-03-11 at 9 40 55 am

 If you check the box and additional section opens up with an additional PX4 only option:
screen shot 2017-03-11 at 9 41 03 am

Can you make the advanced section be available to all firmwares. Then make it show when it is needed (default to closed). And then move your thing down there. Remove the (advanced user) text.

**Comment by jaxxzer** [comment]
Ok, can do. I am out of town for the next ten days so updates from me may be infrequent until I return

**Comment by jaxxzer** [comment]
screenshot 2017-03-22 16 32 10



screenshot 2017-03-22 16 31 13

**Comment by DonLakeFlyer** [comment]
Sorry @jaxxzer. Didn't realize you had fixed this up. Thanks.

**Pull request merged**
