### PR TITLE
Add missing mapControl property setting

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Fix for #6625

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@feemi Could you see if this fixes the problem? For some reason it doesn't repro for me.

**Comment by feemi** [comment]
i am on it

**Comment by feemi** [comment]
@DonLakeFlyer it seems the problem fixed for mission points and geofence but it is not working for rally points

app output:

qrc:///qml/QGroundControl/FlightMap/MissionItemIndicatorDrag.qml:55: TypeError: Cannot call method 'toCoordinate' of undefinedqrc:///qml/QGroundControl/FlightMap/MissionItemIndicatorDrag.qml:55: TypeError: Cannot call method 'toCoordinate' of undefined
qrc:///qml/QGroundControl/FlightMap/MissionItemIndicatorDrag.qml:55: TypeError: Cannot call method 'toCoordinate' of undefined

**Comment by DonLakeFlyer** [comment]
I must have screwed one up. I'll fix it.

**Pull request merged**
