### PR TITLE
PID tuning usability

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
* Bump update rates for vehicle values used in charts to make them useful
* Tweaks to charting to make tick marks better

### CODE REVIEW

**Comment by bys1123** [comment]
Amazing, I gonna try this later.

**Comment by DonLakeFlyer** [comment]
FYI: This is still not quite usable. Works fine on SITL, but realized it doesn't work over SiK radio since the telemetry rates are too low. Getting there...

**Comment by bys1123** [comment]
How to make this work? Through a Raspberry Pi?

**Comment by DonLakeFlyer** [comment]
No I just need to tell the firmware to up the telemetry rates on certain mavlink messages while PID tuning. Working on it...

**Comment by bys1123** [comment]
Thanks, that will be awesome!

**Comment by bys1123** [comment]
Tried open this page with ardupilot, get warning "Get message interval command not suported"

**Comment by DonLakeFlyer** [comment]
@peterbarker I believe Peter added that. Maybe only in dev builds?

**Comment by bys1123** [comment]
@DonLakeFlyer Tested on ArduCopter-master, shows "lost parameter: -1:TUNE_HIGH -1:TUNE_LOW"

**Comment by bys1123** [comment]
https://github.com/ArduPilot/ardupilot/commit/8b74ab32a307150dd6620c4985299c37b6710bd3
Yes, it's only on master.
Lots of good feature is only on master, maybe waiting for 3.7.0

**Pull request merged**
