### PR TITLE
Wind rose solution

### PR DESCRIPTION
**Pull request by patrickelectric**
This will not allow the scroll of PlanView while using wind rose

### CODE REVIEW

**Comment by patrickelectric** [comment]
Need more work on it.

**Comment by patrickelectric** [comment]
@DonLakeFlyer Finished.

**Comment by DonLakeFlyer** [comment]
Why is it off for Mobile?

**Comment by patrickelectric** [comment]
I thought that putting the rose only to desktop users make more sense, but I can add this to mobile too.

**Comment by DonLakeFlyer** [comment]
I think it is way more useful on mobile where typing numbers for angle is hard, as opposed to desktop where typing numbers is way easier to do.

**Comment by patrickelectric** [comment]
@DonLakeFlyer I think that everything is correct now.

**Comment by DonLakeFlyer** [comment]
Still not quite right. As you can see from here 0 degrees shows up as 90 degrees:
screen shot 2017-08-08 at 11 46 27 am

Everything else seems to be working fine.

**Comment by DonLakeFlyer** [comment]
Ah, I see.

**Comment by DonLakeFlyer** [comment]
Let me take on more quick code review look and this is ready to go.

**Comment by DonLakeFlyer** [comment]
Ok, all good. Thanks Patrick. Great new feature.

**Pull request merged**
