### PR TITLE
CameraManager: Remove two bugs, resolve issue #7689

### PR DESCRIPTION
**Pull request by olliw42**
this resolves two bugs:

1) resolves issue #7869: Video stop broken

The MouseArea of the shutter button is enabled/disabled depending on the boolean _canShoot, which was determined as

`property bool   _canShoot:              !_videoRecording && _cameraPhotoIdle && ((_storageReady && _camera.storageFree > 0) || _storageIgnored)
`

Therefore, when a video was recording, and _videoRecording = true, the MouseArea is disabled, and cannot be clicked anymore, which is however what one has to do to stop the video. 

The same issue also exists for taking photos, where it however only bites for timelapses, not for single shot.

The PR corrects this by removing the dependence on _videoRecording and _cameraPhotoIdle.

Note: The bug is IMHO very clearly due to a wrong logic. It was previously argued that things are working fine for many other systems and that issue #7869 is an edge case or issue with my specific configuration. This seems to be not the case. Also, very strangely I admit, things seemed to have worked several months back, despite the same logical flaw being present. I really don't understand this, and only can speculate. But as said, I think the above logic is just wrong. And correcting it as described makes things nicely working for me.

2) Photo Idle

photo idle was determined as 

` property bool   _photoIdle:             _camera && _camera.photoStatus === QGCCameraControl.PHOTO_CAPTURE_IDLE`

However, the photo status can also be >= QGCCameraControl.PHOTO_CAPTURE_LAST, it especially is set to PHOTO_CAPTURE_STATUS_UNDEFINED at startup which obviously also indicates an idle photo. The PR corrects the condition to take this into account. This avoids strange conditions during the initialization state of the CameraManager.

COMMENT: This PR has also applied the PRs  #7963 and #7965.

### CODE REVIEW

**Comment by dogmaphobic** [comment]
This will take a while to digest. I will take a look tomorrow. I have not kept track of this camera widget. Instead, I've been using the custom build version:
https://github.com/mavlink/qgroundcontrol/blob/master/custom-example/res/CustomCameraControl.qml

**Comment by olliw42** [comment]
> Instead, I've been using the custom build version:
https://github.com/mavlink/qgroundcontrol/blob/master/custom-example/res/CustomCameraControl.qml

ahhh ... so it would have been more convenient if I would have based on this too?
If it's so to say the better "default", wouldn't it be more convenient to kind of have that example merged/moved over to the default place?
Your's look more advanced on a quick glance, and it's maybe not convenient to have two things to be worked on as default

**Comment by olliw42** [comment]
PR #7971 added to here, as suggested over there

**Comment by dogmaphobic** [comment]
> ahhh ... so it would have been more convenient if I would have based on this too?
> If it's so to say the better "default", wouldn't it be more convenient to kind of have that example merged/moved over to the default place?
> Your's look more advanced on a quick glance, and it's maybe not convenient to have two things to be worked on as default

No, they are both equality important. I just have neglected the camera widget in the "normal" QGC given that no one seemed to be using. The custom build produces a different UI/UX for QGC. It's more camera centric and meant to be user focused. The "normal" QGC is primarily a development tool with a plethora of options that don't exactly concern to a user interested in simply flying (and taking pictures/recording videos).

**Comment by olliw42** [comment]
many thx for the clarifications

>  The "normal" QGC is primarily a development tool with a plethora of options that don't exactly concern to a user interested in simply flying (and taking pictures/recording videos).

well, but the "normal" QGC is what is mostly used by "average-Joe" ! At least anyone I've heard off using QGC doesn't use a custom made one. And also "average-Joe" wants to benefit from cool stuff ... :)

anyway, I guess, I may conclude that it's not totally useless to go on with spending effort on the normal camera support :) :)
(this PR is then actually kind of a must, since the can't-stop-Video issue really made things useless)

BTW: How can I compile the said custom example? I couldn't figure that out. I would be curious to see this other UI.

**Comment by dogmaphobic** [comment]
> well, but the "normal" QGC is what is mostly used by "average-Joe" ! At least anyone I've heard off using QGC doesn't use a custom made one. And also "average-Joe" wants to benefit from cool stuff ... :)

It's not yet complete. Eventually I want to have both versions built and available.

>BTW: How can I compile the said custom example? I couldn't figure that out. I would be curious to see this other UI.

Just rename "custom-example" to "custom", delete your existing build directory and build it all from scratch. The build automatically picks up the "custom" directory and integrates it into the build. I normally just keep a symlink to it (`ln -s custom-example custom`).

**Comment by olliw42** [comment]
since this has become kind of the "bug" thread, I've added removal of another (tiny) bug 
:)

(_isCamera and _camera are not true for the same conditions, hence when _camera is used one should check for _camera, not _isCamera)

**Comment by olliw42** [comment]
> Just rename "custom-example" to "custom", delete your existing build directory and build it all from scratch. 

just as feedback: I did as you described and this nicely made the compile run thorugh. Thx for the explanation. However, the exe doesn't work. When done from within QtCreator it complains that the exe can't be accessed because of privileges or because it is not existing. When started from the explorer QGC pops up with a somewhat screwed layout, but disappers after some seconds with an error message. So doesn't appear to work on Win7. I thought I just let you know. :)

**Comment by dogmaphobic** [comment]
You need to restart QtCreator when switching from "normal" to "custom". As to starting QGC from Explorer on Windows, this only works for release builds.

**Comment by olliw42** [comment]
> You need to restart QtCreator when switching from "normal" to "custom". As to starting QGC from Explorer on Windows, this only works for release builds.

ah, ok ... I'll try that :). Thx for explaining. You may realize I'm not very good with this build system stuff in general :) :)

**Pull request merged**
