### PR TITLE
Making tile cache description not mandatory.

### PR DESCRIPTION
**Pull request by dogmaphobic**
For the time being, I'm making sure the description is not empty (so it will continue to work with existing databases).

### CODE REVIEW

**Comment by dogmaphobic** [comment]
Build timed out because it took forever to download GStreamer. Restarting...

**Comment by dagar** [comment]
If that keeps happening I'll move all the dependencies to s3.

**Comment by dogmaphobic** [comment]
> If that keeps happening I'll move all the dependencies to s3.

It's the first time I see it. It must have been a network issue.

**Comment by DonLakeFlyer** [comment]
OSX streamer package download just went in last week. So not much time to watch it screw up.

**Comment by DonLakeFlyer** [comment]
@dagar I think it make sense to move it to s3 no matter what though. It will likely speed up builds.

**Comment by dogmaphobic** [comment]
Weird, timed out again?

**Comment by dagar** [comment]
Wow, these are some slow downloads. They'll be on s3 shortly.

**Pull request merged**
