### PR TITLE
Add high latency handle

### PR DESCRIPTION
**Pull request by patrickelectric**
Add HIGH_LATENCY message handle

### CODE REVIEW

**Comment by patrickelectric** [comment]
@DonLakeFlyer

**Comment by DonLakeFlyer** [comment]
What's the difference between these two messages? Is there something lost from using the old one?

**Comment by patrickelectric** [comment]
Hi Don, sorry I was OOO from the last couple of days.
Yes, we lose a bit of information like failure2Sensor, vdop, hdop and others non so important info, this message is a bit simpler but has the basic variables to allow mission status in QGC.

**Comment by dagar** [comment]
The original `HIGH_LATENCY` should have been marked WIP, but we weren't doing that at the time.

**Pull request merged**
