### PR TITLE
MessageIndicator: Enable copy/paste of messages

### PR DESCRIPTION
**Pull request by booo**
Requested by user here:

https://github.com/mavlink/qgroundcontrol/issues/4503

I'm not sure about the `SelectionColor` and `SelectedTextColor` values.

### CODE REVIEW

**Comment by julled** [comment]
Did you test this if onefinger and twofinger scroll guestures still work on android?

**Comment by booo** [comment]
No. If someone could test this that would be great!

**Comment by booo** [comment]
This is what the current change looks like:

screenshot_20221111_143820

**Comment by booo** [comment]
@DonLakeFlyer can you take a look at this. I think it is super handy for sharing actual error messages. Maybe it should be integrated in your recent changes to the GUI element? Thanks a lot.

**Comment by DonLakeFlyer** [comment]
Looks good to me

**Pull request merged**
