### PR TITLE
Add millisec to video file name for better sync with flight logs

### PR DESCRIPTION
**Pull request by tzuriel-spearuav**

### CODE REVIEW

**Comment by mrpollo** [comment]
Thanks for the clean PR @tzuriel-spearuav I'll bring this up with the dev team

**Comment by mrpollo** [comment]
@tzuriel-spearuav the PR looks clean, what is the reason behind this change request?

**Comment by DonLakeFlyer** [comment]
This doesn't make sense to me since it adds a ton of noise to filenames.

**Review by LorenzMeier — CHANGES_REQUESTED** [review]
Adding milliseconds here seems to trying to solve a different problem and is adding complexity.

**Pull request closed without merging**
