### PR TITLE
Add highLatency property to LinkConfiguration

### PR DESCRIPTION
**Pull request by acfloria**
- Add a highLatency variable to the LinkConfiguration and set the variable in the LinkInterface accordingly.
- Wenn manually connecting a link there is now a checkbox for UDP, TCP, and serial links to specify if the new link is a high latency link.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dogmaphobic You two guys should discuss this. Since it differs from how Gus and I discussed how to plumb the hgh latency bit. With the fact that a real high latency implementation needs a custom link implementation.

**Comment by DonLakeFlyer** [comment]
The concept is whether it is possible to support high latency without needing to implementation a custom link

**Comment by DonLakeFlyer** [comment]
We may need a Skype discussion to talk throught this.

**Comment by acfloria** [comment]
I would vote that it should be possible to use high latency without implementing a custom link if a standard link could be used for the high latency communication. If everyone implements their custom link probably the same work is done multiple time which is a waste of resources.

I agree that a Skype call would be the best way to find a common solution.

**Comment by acfloria** [comment]
UDP:
udp
Serial:
serial
Log Replay:
log_replay

**Comment by DonLakeFlyer** [comment]
Can you move the checkbox to be at the bottom of the settings instead of the top?

**Comment by acfloria** [comment]
Ok, I moved the checkbox to the bottom of the configurations. You can see the updated screenshots below.

Serial new:
serial_new

TCP new:
tcp_new

**Pull request merged**
