### PR TITLE
travis-ci s3 deploy

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
Everything currently working except appveyor s3 deploy.

**Comment by dagar** [comment]
@DonLakeFlyer please review this when you have a chance. I moved the mac and linux package output location to package/ because travis-ci can only deploy a folder to s3. This will probably break your teamcity daily builds so it either needs to be adjusted or we could completely switch to travis-ci for linux & mac.

I'm still fighting appveyor to get windows builds uploaded to s3.

**Comment by DonLakeFlyer** [comment]
It's fine, but merge will have to wait. I'm on the road for two weeks so can't tweak TC To match this till I get back home. Then at some point we can turn off TC

**Comment by dagar** [comment]
@dogmaphobic Do you have any idea what's causing these qt android warnings on travis-ci? Using the **exact** same android sdk, ndk, and qt I don't have this problem locally.

    Warning: QML import could not be resolved in any of the import paths: HelperWidgets
    Warning: QML import could not be resolved in any of the import paths: Qt.test.qtestroot
    Warning: QML import could not be resolved in any of the import paths: QmlDesigner
    Warning: QML import could not be resolved in any of the import paths: widgets
    Warning: QML import could not be resolved in any of the import paths: bb.cascades
    Warning: QML import could not be resolved in any of the import paths: QtCompositor
    Warning: QML import could not be resolved in any of the import paths: Example

https://travis-ci.org/mavlink/qgroundcontrol/jobs/80750246#L957

**Comment by dogmaphobic** [comment]
No idea. I don't recognize any of the offending modules either. There seems to be an active bug logged against 5.5.0 that sort of looks like this (I'm using 5.4.2 for Android locally):

https://bugreports.qt.io/browse/QTBUG-46336

**Comment by dogmaphobic** [comment]
No, that isn't it. That bug is a total failure to build on OSX. This one looks more like it:

https://bugreports.qt.io/browse/QTBUG-47389

**Pull request merged**
