### PR TITLE
Mavlink protocol version negotiation fixes

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Related to #7427

Fixed protocol negotation when the vehicle does not support MAV_CMD_REQUEST_PROTOCOL_VERSION.

Here is how the negotation now works:
* Start with the assumption that the capability bits are known
* Send MAV_CMD_REQUEST_PROTOCOL_VERSION to the vehicle
* Start a timeout on the COMMAND_ACK for MAV_CMD_REQUEST_PROTOCOL_VERSION
  * If GCS receives COMMAND_ACK.result != MAV_RESULT_ACCEPTED or times out waiting for the COMMAND ACK then set the link to Mavlink 2 if the capability bits say it is supported
  * If GCS receives COMMAND_ACK.result == MAV_RESULT_ACCEPTED start a timeout waiting to receive a PROTOCOL_VERSION messsage
    * If PROTOCOL_VERSION is never received then set the link to Mavlink 1
    * If PROTOCOL_VERSION message is received set the link accordingly to 1 or 2

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@peterbarker I believe this should work for ArduPilot. Can you verify that against what you know about how it works.
@hamishwillee This differs from existing docs.

**Comment by DonLakeFlyer** [comment]
I still need to do some more testing with ArduPilot in various cases but I think this is good.

**Comment by peterbarker** [comment]
On Sat, 15 Jun 2019, Don Gagne wrote:

> I still need to do some more testing with ArduPilot in various cases but I think this is good.

Just tested in the same way I recall testing before - and it all seems to 
work, which is fantastic!

But please, do test it yourself :-)

Thanks,

Peter

**Comment by DonLakeFlyer** [comment]
Ah, good news. Thanks for testing @peterbarker. This is in the latest daily builds now. So you can use those.

**Comment by hwang12345** [comment]
> Related to #7427
> 
> Fixed protocol negotation when the vehicle does not support MAV_CMD_REQUEST_PROTOCOL_VERSION.
> 
> Here is how the negotation now works:
> 
> * Start with the assumption that the capability bits are known
> * Send MAV_CMD_REQUEST_PROTOCOL_VERSION to the vehicle
> * Start a timeout on the COMMAND_ACK for MAV_CMD_REQUEST_PROTOCOL_VERSION
>   
>   * If GCS receives COMMAND_ACK.result != MAV_RESULT_ACCEPTED or times out waiting for the COMMAND ACK then set the link to Mavlink 2 if the capability bits say it is supported
>   * If GCS receives COMMAND_ACK.result == MAV_RESULT_ACCEPTED start a timeout waiting to receive a PROTOCOL_VERSION messsage
>     
>     * If PROTOCOL_VERSION is never received then set the link to Mavlink 1
>     * If PROTOCOL_VERSION message is received set the link accordingly to 1 or 2

I found QGroundControl can not receive protocol_version message even vehicle has send protocol version message.i can not found the reason.

**Pull request merged**
