### PR TITLE
QtLocation Plugin Improvements

### PR DESCRIPTION
**Pull request by HTRamsey**
- Add QGeoTiledMap & QGeoFileTileCache overrides
- Improve control of maps caching
- Add engineReady signal
- Add improved network request control for downloading tiles
- Reduce total amount of network access managers created
- Add logging capability to each existing file and new ones
- Implement fetching enabled and fetching initialized
- Removed timer and uses internal QNetworkRequest timeout
- Fixes handling of file resources in QGeoMapReplyQGC
- Fixes finished/error signals in QGeoMapReplyQGC
- Simplify elevation handling in QGeoMapReplyQGC
- Removed unused geocoding
- Converted many dynamic object to static
- Prep for reading custom maps from user provided json file
- Allow Map Provider specific cameracapbilities (like bing limited to 20x zoom)
- Moved a couple of generic functions to QGCApplication
- Optimized parameters with QStringView
- Consolidated QGCMapEngineManager with MapEngineManager Singleton and removed tool inheritance

Future TODO:
- Hook QGCTileCacheWorker into QGeoTileFetcherQGC and QGeoFileTileCacheQGC
- Allow user provided json of custom maps
- Custom tile downloader with QGCNetworkAccessManager
- Custom Qml Map with QGCqdeclarativegeomap, provides access to plugin
- QGCCacheWorker optimizations?
- Hook terrain queries & 3dviewer into existing tile classes
- Override/utitilize remaining functions and signals/slots from QtLocationPlugin classes
- QDeclarativeCircleMapItem for geofence

### CODE REVIEW

**Comment by mrpollo** [comment]
I'm wondering if you have a few minutes to review this one @bkueng

**Comment by bkueng** [comment]
Sorry, I currently don't have the time to give this the proper review it deserves.
I very much appreciate the good work you're doing @HTRamsey

**Comment by HTRamsey** [comment]
@bkueng Is this something that I should break down into smaller PRs and this PR would be the eventual end goal, or is this just something out of scope? Either way works for me, I only provided it as I've personally used something similar for years without issue and it provides some cool possibilities to expand on it.

**Comment by bkueng** [comment]
Yes splitting it up would help, but I'm not really familiar with that part of the code.

**Pull request closed without merging**
