### PR TITLE
Ubuntu package

### PR DESCRIPTION
**Pull request by dagar**
Opening as a PR now because I need to get input for setting the correct package copyright, etc.
See deploy/debian/copyright

Files: *
Copyright: 2013-2015 Mike Drone
License: GPL-3+

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Sorry Daniel. Haven't had time to look at this yet. Too many other fires to put out right now.

**Comment by dagar** [comment]
No rush. I'll get it up on launchpad and then we can tweak it.

**Comment by DonLakeFlyer** [comment]
Ok. Finally getting to this. Don't know much about packaging. Should the copyright be the same as the copyright that is in the source files? @LorenzMeier Copyright?

**Comment by LorenzMeier** [comment]
Copyright should probably reference to "QGC Developers" and could link to the Github contributors page?

**Comment by dagar** [comment]
Making progress with the ppa.
https://launchpad.net/~dagar/+archive/ubuntu/qgc/

On Ubuntu 14.04
sudo add-apt-repository ppa:beineri/opt-qt541-trusty
sudo add-apt-repository ppa:dagar/qgc
sudo apt-get update && sudo apt-get install qgroundcontrol

**Comment by dagar** [comment]
I think everything is working in the package. Now I just need to figure out how to handle the versioning so  the ppa can be updated by the build.

**Comment by dagar** [comment]
Alright I set the copyright to QGroundControl Developers https://github.com/mavlink/qgroundcontrol/graphs/contributors.

@DonLakeFlyer This should be ready to merge if you're okay with the qgroundcontrol.desktop file where it is and the icon that's a copy of macx_128x128x32.png. Once this is in master I can configure launchpad to autobuild a package daily in a ppa.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer I've reviewed this and took the liberty to merge this for once while you're traveling to unblock the PPA integration / build this weekend.

@dagar please go ahead with the PPA - it would be awesome to be able to install via apt-get soon.

**Comment by DonLakeFlyer** [comment]
All seems fine to me.

**Comment by dagar** [comment]
Stable 2.3 uploaded
https://launchpad.net/~qgroundcontrol/+archive/ubuntu/ppa

Still needs testing on a clean Ubuntu 14.04 install.

**Pull request merged**
