### PR TITLE
[WIP] git email and org mapping for contributor reports

### PR DESCRIPTION
**Pull request by mrpollo**
The following files can be used to provide an accurate contributors report as well as a report that can show the number of commits per registered company.

- [ ] Validate the mail map data with developers
- [ ] Validate the organizational data with developers
- [ ] provide a way to track developer contributions attributing the right company over time

examples

Contributor list (clean) 1 year
```
git log --pretty='%aN <%aE>' --since="1 year" | sort | uniq -c | sort -rn

1015 Don Gagne <don@thegagnes.com>
 370 Gus Grubba <gus@grubba.com>
  82 PX4 Jenkins Bot <bot@px4.io>
  41 Beat Küng <beat-kueng@gmx.net>
  40 Patrick José Pereira <patrickelectric@gmail.com>
  33 Andreas Bircher <bircher@gmx.ch>
  21 Jacob Walser <jwalser90@gmail.com>
  20 Florian Achermann <florian.achermann@mavt.ethz.ch>
  20 Daniel Agar <daniel@agar.ca>
  14 Nick Anthony <nickexists@hotmail.com>
   9 Lorenz Meier <lorenz@px4.io>
   7 mak <maktrefa@gmail.com>
   4 dheideman <dheideman@socal.rr.com>
   4 Philipp Oettershagen <philipp.oettershagen@mavt.ethz.ch>
   3 Sebastian Verling <sverling@student.ethz.ch>
   3 Jonas Vautherin <jonas.vautherin@gmail.com>
   3 Anthony Lamping <lamping.ap@gmail.com>
   3 Andre Kjellstrup <andre.kjellstrup@gmail.com>
   3 Ahmet Fehmi Ozcan <fehmi.ozcan@maxwell-innovations.com>
   2 yaoling <165577564@qq.com>
   2 Willian Galvani <williangalvani@gmail.com>
   2 Thomas Mantel <thomas.mantel@mavt.ethz.ch>
   2 Thomas Gubler <thomas@auterion.com>
   2 SungTae Moon <munhoney@gmail.com>
   2 Sander Smeets <sander@droneslab.com>
   2 Ramón Roche <mrpollo@gmail.com>
   2 Peter Barker <pbarker@barker.dropbear.id.au>
   2 Julien Lecoeur <julien.lecoeur@gmail.com>
   2 Julian Oes <julian@oes.ch>
   2 Hamish Willee <hamishwillee@gmail.com>
   2 G_I_V_D <gigorvd@gmail.com>
   2 Barza Nisar <nisarb@student.ethz.ch>
   2 Amy Wagoner <arwagoner@gmail.com>
   1 Vavooon <vavooon@gmail.com>
   1 Sam Duff <sam@samduff.com>
   1 Pritam Ghanghas <pritam.ghanghas@senserobotics.com>
   1 Pierre Kancir <khancyr@gmail.com>
   1 Oleg Kalachev <okalachev@gmail.com>
   1 Nathan Tsoi <nathan@vertile.com>
   1 Luis Vale Gonçalves <luisvale@gmail.com>
   1 Jin Chengde <jinchengde@gmail.com>
   1 Jared Szechy <jared.szechy@gmail.com>
   1 Holger Steinhaus <hsteinhaus@gmx.de>
   1 Friedrich Beckmann <friedrich.beckmann@gmx.de>
   1 David Sidrane <david_s5@nscdg.com>
   1 Daniele Pettenuzzo <daniele@px4.io>
   1 Adrian Schröter <adrian@suse.de>
```

Organization list 1 year
```
git log --pretty='%aN <%aE>' --since="1 year" | git -c mailmap.file=.organizationmap check-mailmap --stdin | sort | uniq -c | sort -rn

1140 Unaffiliated <no@organization.net>
 428 Auterion <contact@auterion.com>
  82 PX4 Jenkins Bot <bot@px4.io>
  36 Wingtra <contact@wingtra.com>
  26 ETH Zurich <contact@student.ethz.ch>
   4 dheideman <dheideman@socal.rr.com>
   2 Yuneec Research <contact@yuneecresearch.com>
   2 Willian Galvani <williangalvani@gmail.com>
   2 Vertical Technologies <contact@verticaltechnologies.com>
   2 G_I_V_D <gigorvd@gmail.com>
   2 EPFL <contact@epfl.ch>
   2 Dronecode <contact@dronecode.com>
   2 DIU <contact@diu.(none)>
   1 Sam Duff <sam@samduff.com>
   1 Pritam Ghanghas <pritam.ghanghas@senserobotics.com>
   1 Luis Vale Gonçalves <luisvale@gmail.com>
   1 Holger Steinhaus <hsteinhaus@gmx.de>
   1 Friedrich Beckmann <friedrich.beckmann@gmx.de>
   1 Copter Express <contact@copterexpress.com>
   1 Adrian Schröter <adrian@suse.de>
```

### CODE REVIEW

**Comment by patrickelectric** [comment]
Hi @mrpollo, can I ask why is this important ?

**Comment by mrpollo** [comment]
It's important to the open source community because it allows us to measure our progress, in particular this PR was made in an attempt to create a yearly report for every Dronecode project, where we will capture what the community is working on, who are the top contributors, how much time is spent in between releases, which organizations are contributing to the community, etc... 

All of that said, I will close this PR since we are no longer using this tool.

**Comment by patrickelectric** [comment]
@mrpollo 	thank you for complete answer, much appreciate it !

**Comment by mrpollo** [comment]
Thank **you** for your awesome contributions :clap:, keep them coming!

**Pull request closed without merging**
