### PR TITLE
Remove Firmware Update from tablet build

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Also removes qextserialport. A bit of a hack at the moment since the firmware button will still be there and do nothing. I'll make it better later/

### CODE REVIEW

**Comment by dogmaphobic** [comment]
At some point I need to do a PR for iOS. I have it so both define *MobileBuild* and that's what I use to exclude these things as it applies to all mobile devices. I haven't yet because since we moved the main project file to a master project building two projects, iOS builds no longer work. The generated Makefiles can't deal with the QRC resources for some reason.

**Comment by DonLakeFlyer** [comment]
This should be MobileBuild then. I'll fix that.

**Comment by dogmaphobic** [comment]
This is how my QGCCommon.pri looks like:
```
linux {
    linux-g++ | linux-g++-64 {
        message("Linux build")
        CONFIG += LinuxBuild
    } else : android-g++ {
        message("Android build")
        CONFIG += AndroidBuild
        CONFIG += MobileBuild
        warning("Android build is experimental and not fully functional")
    } else {
        error("Unsuported Linux toolchain, only GCC 32- or 64-bit is supported")
    }
} else : win32 {
    win32-msvc2010 | win32-msvc2012 | win32-msvc2013 {
        message("Windows build")
        CONFIG += WindowsBuild
    } else {
        error("Unsupported Windows toolchain, only Visual Studio 2010, 2012, and 2013 are supported")
    }
} else : macx {
    macx-clang | macx-llvm {
        message("Mac build")
        CONFIG += MacBuild
        QMAKE_CXXFLAGS += -fvisibility=hidden
    } else {
        error("Unsupported Mac toolchain, only 64-bit LLVM+clang is supported")
    }
} else : ios {
    message("iOS build")
    CONFIG += iOSBuild
    CONFIG += MobileBuild
} else {
    error("Unsupported build platform, only Linux, Windows, and Mac are supported")
}
```

**Comment by DonLakeFlyer** [comment]
I see what you are saying now. You haven't pushed the new QGCommon.pri. I'll wait for that and redo this pull.

**Comment by dogmaphobic** [comment]
You can go ahead and merge this as is. It does not conflict with the Android side of things. It will be a long while before I'm ready to do an iOS PR. Once I do that, these things will come with it.

**Comment by DonLakeFlyer** [comment]
I just pushed the typo fix to this as well then. I'll wait for it to come around and merge.

**Comment by dogmaphobic** [comment]
No problem. It should merge fine.

**Pull request merged**
