### PR TITLE
Android joystick

### PR DESCRIPTION
**Pull request by gregd72002**
Replacing existing PR (https://github.com/mavlink/qgroundcontrol/pull/3596)
- this is just to sync the PR with the current master & some re-organization in my fork

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@gregd72002 Just an update on this. I'm working towards getting the 3.1 stable release out in a week or so. After that I will move to Qt 5.8 and then this stuff can finally go through.

**Comment by nanthony21** [comment]
Is this ready to be merged? If not, what needs to happen first?

**Comment by DonLakeFlyer** [comment]
Need to switch to Qt 5.8 first. I'm currently working on that.

**Comment by DonLakeFlyer** [comment]
@gregd72002 We've switched to Qt5.8 now. So you should be able to get this working now.

**Comment by gregd72002** [comment]
Thanks. I will look into refreshing the PR

**Comment by gregd72002** [comment]
This should now be working fine and ready to be merged.

Tested on my Android tablet and PS3 & PS4 controller.

- no support for hot-plugging 
- would benefit from a little bit of house keeping for cleaner code
	- make JoystickManager.cc architecture independent
	- push any architecture dependent code to Joystick.cc

**Comment by DonLakeFlyer** [comment]
Awesome thanks @gregd72002. @jaxxzer Can you review since your kinda the joystick guy?

**Comment by DonLakeFlyer** [comment]
Just when you thought it was safe. We have a show-stopper bug in Qt5.8: #4705. If we don't get a response to this with a fix or workaround ina reasonable timeframe we are going to have to go back to 5.5.

**Comment by jaxxzer** [comment]
@DonLakeFlyer I can look at this. Will this not work on 5.5?

**Comment by DonLakeFlyer** [comment]
Requires somehting about 5.5. Not exactly sure what.

**Comment by DonLakeFlyer** [comment]
We are moving back to Qt 5.7 so not sure if this is hosed again now.

**Comment by DonLakeFlyer** [comment]
@gregd72002 Does this work on 5.7?

**Comment by gregd72002** [comment]
It should but i have not had chance to test it.

**Comment by gregd72002** [comment]
It does work on 5.7.1

**Comment by DonLakeFlyer** [comment]
Ok, finally!

**Pull request merged**
