### PR TITLE
SRR QGC Multi-Camera Stream Switching Support

### PR DESCRIPTION
**Pull request by FrauBluher**
Introduces heading azimuth feature.
Adds support for quick switching between cameras.
Instruct QGC to start streaming immediately upon connection.
Default head of srr-qgc doesn't seem to actually present decoded frames, added 38d38e2 which brings in the video streaming pipeline from QGC v4.0, though this pipeline seems to have much worse decode latency out-of-the-box.

Builds on 18.04 and 20.04 host, tested running on x86_64 target.

### CODE REVIEW

**Comment by FrauBluher** [comment]
The video pipeline out-of-the-box has worse streaming decode latency than what was previously in the srr-qgc branch, but the decode pipeline at the head of srr-qgc wasn't decoding video out-of-the-box.

**Comment by FrauBluher** [comment]
Invoking QGC via: `GST_DEBUG=GST_SCHEDULING:5 ./qgroundcontrol-start.sh` to obtain gstreamer timing log, and parsing it via: `grep 0:00:17.539883343 gst_log2 |sed "s/ .*</ /"|sed "s/:sink.*$//"`, where the timestamp is a frame PTS, and gst_log2 is the name of the console output saved to a file shows:
```
0:00:25.897599065 parser
0:00:25.897636343 typefind
0:00:25.897669197 h264parse3
0:00:25.929891566 capsfilter3
0:00:25.929936134 src_0:proxypad16> calling chainfunction &gst_proxy_pad_chain_default with buffer buffer: 0x7f521400d120,
0:00:25.929974010 src_0:proxypad17> calling chainfunction &gst_proxy_pad_chain_default with buffer buffer: 0x7f521400d120,
0:00:25.930008986 tee4
0:00:25.930045240 queue4
0:00:26.676206746 decoder
0:00:26.676225659 typefind
0:00:26.676242649 h264parse4
0:00:26.676294613 capsfilter4
0:00:26.676315294 avdec_h264-1
0:00:26.681498884 src_0:proxypad18> calling chainfunction &gst_proxy_pad_chain_default with buffer buffer: 0x7f521400d6c0,
0:00:26.681528397 videosink
0:00:26.681546590 glupload
0:00:26.681787430 glcolorconvert
0:00:26.682148368 qmlglsink
```

Here we can clearly see the latency in the GST pipeline is due to the queue after the tee holding onto the slices.
```
0:00:25.930045240 queue4
0:00:26.676206746 decoder
```

Currenly looking into a workaround for this, unfortunately it doesn't look like the easy path of limiting the buffer size via `g_object_set(queue, "max-size-buffers", 0, NULL);` helps at all.

**Comment by FrauBluher** [comment]
This actually might just be time time through the decoder segment of the pipeline, as GST_SCHEDULING:5 timestamps sink pad writes.

**Comment by FrauBluher** [comment]
With 91d6343, latency is now good, and srr-qgc tracks head of master's implementation of the video decode / presentation stack.

**Comment by DonLakeFlyer** [comment]
Closing, abandoned

**Pull request closed without merging**
