### PR TITLE
Qt readme 5.4

### PR DESCRIPTION
**Pull request by jgoppert**
I didn't have any luck with Qt 5.3 on ubuntu 14.04, so I tried 5.4 and it works.I got the black box issue again on 5.3.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Should we just require 5.4 on all platforms?

**Comment by DonLakeFlyer** [comment]
This is off of latest master?

**Comment by jgoppert** [comment]
Yes, off of master.

**Comment by DonLakeFlyer** [comment]
Ok. Let me try myself on Ubuntu to see if I can repo. There was a specific fix to make this work. It may have broken with the last setup pull. I'll try moving to 5.4 as well to see what happens.

**Comment by jgoppert** [comment]
qquickwidget was reporting an error about an empty screen graph.

**Comment by DonLakeFlyer** [comment]
It happens when the main QML item has a size of 0, 0. The black screen was clicking on "Setup" or black screens after clicking a setup button like Firmare?

**Comment by jgoppert** [comment]
black buttons on right menu of setup, mains screens worked correctly

**Comment by DonLakeFlyer** [comment]
Can you attach a screen shot?

**Comment by DonLakeFlyer** [comment]
Also if you are building yourself can you try modifying src/VehicleSetup/SetupViewButtons.qml to include:
    width: 100
    height: 600

Right after:
    id: topLevel

And see what happens?

**Comment by jgoppert** [comment]
I uninstalled qt53 for now, so it would take me awhile to set up.

**Comment by DonLakeFlyer** [comment]
Lets try this. In the shot below was the Firmware button invisible? How about the right hand side with instructions and Next button and so forth? Or both invisible?
screen shot 2015-02-07 at 5 34 38 pm

**Comment by jgoppert** [comment]
I'm installing qt5.3 again to test it out. But the firmware button was invisible. The rest was visible, if I remember.

**Comment by DonLakeFlyer** [comment]
Ok, that's what I thought. On Ubuntu 14.10 with Qt 5.3.0 it working fine. So not super helpful.

**Comment by jgoppert** [comment]
After suggested fix of 

     width: 100
     height: 600

     Right after:
     id: topLevel

No change in behavior as described below:

Firmware button is fine, goes black after connection:

screenshot from 2015-02-07 20 47 10
screenshot from 2015-02-07 20 48 30

**Comment by jgoppert** [comment]
I'm tempted to just require qt5.4 for ubuntu 14.04. It is just as easy to install the 5.4 ppa as it is to install the 5.2 ppa.

**Comment by DonLakeFlyer** [comment]
Goes black after connection. Didn’t realize that. That’s different. Let me look a little. 5.4 may still be the right move anyway since it’s the latest release. If so, will want to move all OS forward likely.

**Comment by dogmaphobic** [comment]
I can confirm the problem. I have both 5.3 and 5.4 installed with Ubuntu 14.04. With 5.3, you get black boxes where the Setup buttons (left pane) should be. It all works when built with 5.4. I noticed that yesterday but didn't give much thought until I saw this...

**Comment by dogmaphobic** [comment]
Here is a screen grab showing it (Ubuntu 14.04, Qt 5.3):

screen shot 2015-02-08 at 9 55 45 am

**Comment by Susurrus** [comment]
I'd like to avoid another Qt jump if we can. What version of 5.3 are people seeing the problem on? Because there has been a 5.3.1 bugfix release.

**Comment by jgoppert** [comment]
I tried this on my laptop and I got the black screen again after params were transmitted and this error, using Qt5.4 this time, which is scarry:

UASParameterCommsMgrLog: emitting parameterListUpToDate
Default compId:  50
qrc:/qml/SensorsComponentSummary.qml:18: TypeError: Cannot read property 'value' of undefined
qrc:/qml/SensorsComponentSummary.qml:29: TypeError: Cannot read property 'value' of undefined
qrc:/qml/SensorsComponentSummary.qml:40: TypeError: Cannot read property 'value' of undefined
^C


It seems these new qml components are very unstable. Maybe we should consider sticking with normal Qt if they cause so many problems.

**Comment by jgoppert** [comment]
Screenshot on my laptop on Qt 5.4 ubuntu 14.04 after parameter update.

screenshot from 2015-02-08 14 06 58

**Comment by DonLakeFlyer** [comment]
It's just a sizing issue. There is a path where the size of the top level item is 0,0 and the resizing seems to work differently on different OS. You can fix it by manually sizing the item yourself even Qt is supposed to do it for you.

**Comment by Susurrus** [comment]
From what @DonLakeFlyer has said, it sounds like this should not be merged and we should figure out a better way to deal with resizing the widgets.

**Comment by jgoppert** [comment]
Agreed. We need to figure out all the quirks of the qml.

**Comment by DonLakeFlyer** [comment]
I’ll be working on this tomorrow. My hope is to fix the black as well as target 1024x768 min resolution and get that all fixed up.

**Comment by DonLakeFlyer** [comment]
Wait I didn’t see this down the thread. This is just a regular old bug in the qgc qml code not an os specific quirk.

**Comment by jgoppert** [comment]
@DonLakeFlyer ah, good to know it isn't just my system.

**Comment by DonLakeFlyer** [comment]
@jgoppert I just need to figure out the sequence which causes it. Looks like a possible connect/disconnect/connect bug. I tried something simple but it didn't happen. Can you give me exact steps to repro? Then I can fix and add unit test to make sure it doesn't happen again.

**Comment by Susurrus** [comment]
From looking at the code quickly it looks like the `autopilot.parameters[]` array is not initialized properly.

**Comment by DonLakeFlyer** [comment]
Yup, that's the symptom. But need to find the code path that causes it.

**Comment by DonLakeFlyer** [comment]
Tracking whether we need this pull in Issue #1207

**Comment by DonLakeFlyer** [comment]
This is replaced by Pull #1249.

**Pull request closed without merging**
