### PR TITLE
Sd card prompt

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Fix for Issue #2663

screen shot 2016-01-21 at 10 44 35 am

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Bad merge

**Comment by lvale** [comment]
Hi.

This new feature is giving me the absent SD when I plugin the PixHawk, although it can reach the card to retrieve logs....

I tested in several ways.

PixHawk off: Plugin USB cable - warning appears almost immediately (less than 5 seconds)

PixHawk powered via Power module and already ready (boot process complete verified by the leds): Same thing

PixHawk off: QGC not launched, Plugin USB cable wait for boot to complete, Launch QGC, eventually detects the PixHawk and the SD warning appears almost immediately.

screen shot 2016-01-23 at 21 44 28

**Comment by DonLakeFlyer** [comment]
@lvale Can you move this to a separate issue?

**Comment by lvale** [comment]
done

**Pull request closed without merging**
