### PR TITLE
Remove RC_CHANNELS_RAW support

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
* Remove handling of `RC_CHANNELS_RAW` relying o n`RC_CHANNELS` only. Handling both was causing incorrect channel counts to be sent to Radio Cal. This fixes *#8853 
* Fixed flash find board loop

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
The RC_CHANNELS change should go to Stable as well

**Comment by AndKe** [comment]
When compiled, RC15 and RC16 (in radio settings) is just in the middle. (1500us)  - while the RC_CHANNELS toggle between 1000 and 2000. 
This was verified by connecting AP2 and checking "mavlink inspector" widget.
Visualization of the channels 1..14 seems normal.

**Comment by DonLakeFlyer** [comment]
Can you capture a telemetry log while you are wiggling 15 and 16? You'll have to turn on take log while not armed in settings.

> when did compilation output directory change from build/release to build/staging?

Recently to work around a Qt bug on OSX.

**Comment by AndKe** [comment]
@DonLakeFlyer  
[RC15_16_wiggle_wiggle_yeah!.zip](https://github.com/mavlink/qgroundcontrol/files/4891729/RC15_16_wiggle_wiggle_yeah.zip)

**Pull request merged**
