### PR TITLE
Convex survey support

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
* Fixed dog slow loading of complex KML
* Complicated concave KML loads for generating survey grids was causing bad transect generation
* Change survey grid generation such that the polygon is no longer converted to convex
* New transect intersection algorithm which works with convex polygons

Examples:
screen shot 2018-03-13 at 3 39 14 pm

This .mov shows how it all work while dynamically changing the grid angle of a survey generated from a complex concave KML load:
https://s3-us-west-2.amazonaws.com/qgroundcontrol/DonLakeFlyer/ConvexGrid.mov

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@antiheavy I'm going to need you help testing this rather large bug fix! I've hammered on it pretty well, but an extra set of eyes will help. It's actual quite a simple code change, but right in the middle of grid generation so important to not screw up.

**Comment by DonLakeFlyer** [comment]
This came about from having a hard time fixing the code which converted from concave to convex polygons. It was buggy and failed in various cases. While thinking about that, I stumbled across an idea for a new way to interect transects against convex polygons. Which turned out to be simple and it even seems to work!

**Comment by Antiheavy** [comment]
The convex problem is much trickier than it seems at first!  Happy to help test.

**Comment by Antiheavy** [comment]
Ping me once it is in Master, or send me a build.

**Comment by Antiheavy** [comment]
been playing around with this for a few days and it seems to work pretty well.
image

image

image

image

**Comment by DonLakeFlyer** [comment]
Thanks a ton for hammering on this Todd.

**Pull request merged**
