### PR TITLE
MissionItemStatus: Make waypointValuesDisplay with variable width

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by patrickelectric** [comment]
canto
canto2

**Comment by DonLakeFlyer** [comment]
Did you check that when it reaches maximum width the scrolling still works?

**Comment by DonLakeFlyer** [comment]
Can you make it show Home if there is only a home position? I think that may make it less confusing to folks as to what the thing is used for.

**Comment by patrickelectric** [comment]
Here a gif of this PR. About the home item, I'll take a look on it.
itemstatus

**Comment by patrickelectric** [comment]
image

**Comment by DonLakeFlyer** [comment]
Looks perfect @patrickelectric. Thank you so much.

**Pull request merged**
