### PR TITLE
Pr tweaks toolstrip qmltest

### PR DESCRIPTION
**Pull request by stefandunca**
Improve QmlTest and ToolStrip

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Can you include before/after screenshots for things like this so we can see what the ui change looks like?

**Comment by dogmaphobic** [comment]
> Can you include before/after screenshots for things like this so we can see what the ui change looks like?

It doesn't invalidate the request, but note that this PR is meant for the new QtQuick branch, not master. Once this branch is ready, there will be a great deal of explaining, screen shots, etc.

**Comment by stefandunca** [comment]
#### ToolStrip:
Before: before_7389
After: after_7389

#### QmlTest:
Before: before_palette
After: after_palette

**Comment by dogmaphobic** [comment]
CI errors are to be expected. Not only Jenkins is not setup properly, unit test is disabled for the time being. Feel free to merge (to qgc4)

**Comment by DonLakeFlyer** [comment]
Ah, I didn't catch this was in qgc4. Sorry

**Pull request merged**
