### PR TITLE
[APM] [Copter] Ch6 tune

### PR DESCRIPTION
**Pull request by Rudi3**
Issue: https://github.com/mavlink/qgroundcontrol/issues/3675
I couldn't run the unittests on my pc but Travis should do that now...

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Not sure if this would make more sense on the Tuning page?

**Comment by DonLakeFlyer** [comment]
Other question is what ArduPilot variants support this: Copter, Plane, Rover, all?

**Comment by Rudi3** [comment]
Well its a channel option and a tuning option.. I'm not sure either...

**Comment by Rudi3** [comment]
Copter at least i'll check for the rest now...

**Comment by DonLakeFlyer** [comment]
I looked. This is Copter only. Also after looking at the UI I think this should go into Tuning. There is already a Copter specific tuning page: APMTuningComponentCopter.qml. I'd put it to the right of AutoTune:

screen shot 2016-06-30 at 11 11 17 am

**Comment by Rudi3** [comment]
Ok I'm on it...

**Comment by DonLakeFlyer** [comment]
Thanks @Rudi3

**Comment by Rudi3** [comment]
@DonLakeFlyer I'm ready for merge if you are happy with the results :smile:

**Comment by DonLakeFlyer** [comment]
I haven't had time to look at this yet.

**Comment by DonLakeFlyer** [comment]
Testing looks good. Two things:
1) Can you change the label "In flight tuning" to be "In Flight Tuning"?
2) Can you squash the commit down into a single commit?

**Comment by Rudi3** [comment]
I should be done... lets wait for the checks!

**Comment by DonLakeFlyer** [comment]
Perfect. Thanks for the pull @Rudi3

**Comment by Rudi3** [comment]
No problem! I'm glad I could help!

**Pull request merged**
