### PR TITLE
WIP: Remove mavlink fork of gst-plugins-good

### PR DESCRIPTION
**Pull request by patrickelectric**
Uses original repository of gst-plugins-good.
Tested under android and linux.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
If I remember correctly the reason for this fork is that it contains windows fixes which are not in the normal repo.

**Comment by andrewvoznytsa** [comment]
Confirming - if you need to get it working properly in case of multiple
video streams on Windows then you have to use this fork.

**Comment by DonLakeFlyer** [comment]
> if you need to get it working properly in case of multiple video streams

And multiple video stream is part of the camera mavlink spec isn't it?

**Comment by andrewvoznytsa** [comment]
> > if you need to get it working properly in case of multiple video streams
> 
> And multiple video stream is part of the camera mavlink spec isn't it?

Unfortunately - I don't know - mavlink is still black box for me.

**Comment by DonLakeFlyer** [comment]
> Confirming - if you need to get it working properly in case of multiple video streams on Windows then you have to use this fork.

Which is either something already supported or if not, requested as a feature. So it seems bad to lose these fixes. @patrickelectric  What's the underlying reason to remove the way it is now?

**Comment by andrewvoznytsa** [comment]
BTW, there were some activities on qmlglsink/gstreamer side regarding Windows support recently. I think they have the fix in the master. At some point it will be possible to drop this qmlglsink maintenance.

**Comment by holden-zenith** [comment]
@patrickelectric The fix for the windows bug @DonLakeFlyer mentioned is included in [1.19.2](https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/merge_requests/1032) and can be found in this gst-plugins-good [here](https://github.com/GStreamer/gst-plugins-good)

**Comment by holden-zenith** [comment]
@patrickelectric The fix for the windows bug @DonLakeFlyer mentioned is included in [1.19.2](https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/merge_requests/1032) and can be found in this gst-plugins-good [here](https://github.com/GStreamer/gst-plugins-good)

**Comment by DonLakeFlyer** [comment]
@zdanek Maybe something else you can look into with the video stuff?

**Comment by zdanek** [comment]
I will take a look

**Comment by HTRamsey** [comment]
As of 1.19.x gst-plugins-good is no longer separate from the base repo, and since only a single plugin is used from this I think it is better to use the approach used in #11258

**Pull request closed without merging**
