### PR TITLE
ULog Geotagging Support

### PR DESCRIPTION
**Pull request by mhkabir**
This adds support for geotagging from ULogs.

For more details, see this PX4 pull request : https://github.com/PX4/Firmware/pull/7201

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@mhkabir Can you please fix the Linux build errors?

**Comment by DonLakeFlyer** [comment]
Why does this pull includes changes to the Survey item?

**Comment by mhkabir** [comment]
@DonLakeFlyer It had been misusing the Mavlink API to control triggering : https://github.com/PX4/Firmware/pull/7201#issuecomment-300068666

**Comment by DonLakeFlyer** [comment]
> It had been misusing the Mavlink API to control triggering

It has been implemented to match how ArduPilot has been "misusing" the mavlink api for years now. Which is that a 0 value for TRIGGER_DISTANCE turns off camera triggering. Whomever implements to mavlink api first wins the definition of the spec.

Can you remove the changes to survey from this pull? I have made a separate issue for DIGICAM_CONTROL versu IMAGE_START_CAPTURE (https://github.com/mavlink/qgroundcontrol/issues/5119). I will need to figure out what is right there with respect to making it work cross-firmware.

**Comment by mhkabir** [comment]
> Can you remove the changes to survey from this pull?

That would break the Firmware branch I have been developing on.

**Comment by DonLakeFlyer** [comment]
One last time: Your changes to Survey break existing survey functionality. Survey's will no longer work with ArduPilot. That means this pull will will never be merged.

**Comment by mhkabir** [comment]
Continued in https://github.com/mavlink/qgroundcontrol/pull/5133

**Pull request closed without merging**
