### PR TITLE
Correct altitude usage for Change Altitude

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Fix for #4171

### CODE REVIEW

**Comment by dagar** [comment]
@julianoes correct me if I'm wrong here, but for reposition (guided mode change altitude) I think you were asking to make the slider range from -50 - +50 meters and start centered, instead of 0 - 100 starting at 0.

@DonLakeFlyer FYI your git email address doesn't seem to be associated with your github account anymore.

**Comment by DonLakeFlyer** [comment]
> I think you were asking to make the slider range from -50 - +50 meters and start centered, instead of 0 - 100 starting at 0.

That would be inconsistent with the way ArduPilot works.

**Comment by dagar** [comment]
How so? I'm talking about changing altitude while already in the air and being able to decrease it. It looks like Ardupilot is just being sent an offset. Why can't it be negative?

**Comment by DonLakeFlyer** [comment]
Trying to match tower/mission planner feature so users don’t get confused when moving to new GCS.

On Nov 15, 2016, at 10:09 AM, Daniel Agar <notifications@github.com<mailto:notifications@github.com>> wrote:


How so? I'm talking about changing altitude while already in the air and being able to decrease it. It looks like Ardupilot is just being sent an offset. Why can't it be negative?

**Comment by dagar** [comment]
I think we're talking about slightly different things and confusing relative to home and relative to vehicle (offset).

There are basically 2 options, and I'm happy with either.

1. The slider changes altitude relative to the vehicle's home position (0 = home). If we go this route the slider should be placed at the current altitude and add an additional 100m or so on top.

2. The slider changes altitude relative to the vehicle's position (0 = current altitude). Positive or negative, and if we wanted to be clever the negative could be limited to not allow commanding something below home altitude.

Right now the slider appears as 0-100m and changes the altitude relative to the vehicle's current altitude. It only allows you to increase the altitude.

**Comment by julianoes** [comment]
@dagar: I like both 1 or 2 but 1 seems to be most intuitive.

**Comment by DonLakeFlyer** [comment]
@dagar Can you add an Issue for #1?

**Pull request merged**
