### PR TITLE
Fixed calibration predialog text collapse problem.

### PR DESCRIPTION
**Pull request by feemi**
#4989 issued problem resolved.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Thanks @feemi 

Hmm, this is some pretty old Qml code. All spacing should be based off of ratio of ScreenTools.defaultFontPixelHeight or Width depending on direction. Fixed pixels don't work across different device sizes.

Could you instead find a good font ratio to use here?

**Comment by feemi** [comment]
"ScreenTools.defaultFontPixelWidth / 2" looks fine I think.

**Comment by DonLakeFlyer** [comment]
Perfect

**Comment by feemi** [comment]
I just ammended the code again

**Pull request merged**
