### PR TITLE
Use MAV_COMP_ID_AUTOPILOT1 instead of MAV_COMP_ID_MISSIONPLANNER

### LINKED ISSUE #2907: Wrong target component ID
Target component should be the vehicle's comp_id (same as received on its heartbeat) and not MAV_COMP_ID_MISSIONPLANNER.

Example:
https://github.com/mavlink/qgroundcontrol/blob/master/src/MissionManager/MissionManager.cc#L123

MAV_COMP_ID_MISSIONPLANNER is the component ID for the GCS MissionPlanner.

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Fixes #2907

### CODE REVIEW

**Comment by hamishwillee** [comment]
@edwinhayes You might want to test this change in tomorrow's daily build - see if it fixes #2907

**Comment by edwinhayes** [comment]
@hamishwillee Thanks.  Should be able to confirm on Monday.

**Comment by edwinhayes** [comment]
@hamishwillee Still seems to be broken, but the date in the titlebar is still 2018-09-06.  Are the 'daily build' downloads actually built daily?  Can I check the build status somehow?  I'm on a Mac FYI, so could be specific to that?

**Comment by hamishwillee** [comment]
@edwinhayes I don't know! @DonLakeFlyer may be able to confirm whether there is something odd going on with the builds.

**Comment by DonLakeFlyer** [comment]
@dagar Just saw the OSX daily build drops moved to Jenkins. Looks like they are not updating maybe.

**Comment by edwinhayes** [comment]
Tested and working.  Thanks guys.

**Comment by hamishwillee** [comment]
Thanks for testing @edwinhayes !!

@DonLakeFlyer Thanks very much. Nice to see Feb 2016 bug getting fixed :-)

**Pull request merged**
