### PR TITLE
[Hold for 4.2] deploy: windows: Moving files into common distribution directory

### PR DESCRIPTION
**Pull request by thopiekar**
The general goal is to tidy up the project folder and give better focus on other contents of the project.
As a first iteration, I would like to tidy up files, which are Windows related. Technically seen I'm pretty sure that we won't notice any differences, since some libraries and images have been moved and some config files cleaned up.

Signed-off-by: Thomas Karl Pietrowski <thopiekar@gmail.com>

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Useful cleanup, but doesn't fix anything wrong in 4.1. So holding for 4.2

**Comment by thopiekar** [comment]
Ready to be reviewed.
Depending on the outcome of this PR, I'm willing to do further clean up for the other platforms, too.

Looking forward for your feedback and discussion if needed :)

**Comment by thopiekar** [comment]
Alright. Are you interested in further work for the other platforms, too?

**Comment by DonLakeFlyer** [comment]
Yes, but before going there let me get past 4.1 stable. And then I'll have time to take a good look at this for comments which may affect further work.

**Comment by thopiekar** [comment]
Roger that

**Comment by mrpollo** [comment]
@DonLakeFlyer looks like we are finally ready to get this merged, let us know if you need additional details here.

**Comment by thopiekar** [comment]
Updated the branch and luckily no conflicts :wink:

**Comment by DonLakeFlyer** [comment]
I'[ve finally looked through this. Looks fine. Can you rebase into one or more atomic commits and I'll merge? For example QGC_INSTALLER_SCRIPT usage being in two separate commits seems bad.

**Comment by thopiekar** [comment]
Ok. Squashed all together via soft reset. We should get green lights here soon! :slightly_smiling_face:

**Comment by thopiekar** [comment]
@mrpollo Any chance to get this up, too? It has already been reviewed and needed some commits to be squashed together. Prepared everything as requested and should be ready to be merged. :slightly_smiling_face:

**Comment by thopiekar** [comment]
image

**Comment by thopiekar** [comment]
Some files have been moved or removed from master branch. Therefore rebasing (to get a rid of the merges) didn't work.
Hope you don't mind if we keep the two merge commits, @DonLakeFlyer :slightly_smiling_face:

**Comment by thopiekar** [comment]
According to what I see here, it should be ready to be merged for you.
Please press the button before it gets too late..

image

**Pull request merged**
