### PR TITLE
AutoPilotPlugins: PX4: Fix bind to temporary constructor

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
As a coding style I have moved away from this sort of thing. The reason being unless you are doing this in a loop which is run 10 million times there is no measurable impact on perf. And by just using things raw, the code readabilty goes up. Same thing for using raw `"c-string"` with a QString or QStringLiteral wrapper.

**Comment by DonLakeFlyer** [comment]
I could certainly be convinced out of it with good reason. But I'm not sure there is one at this point.

**Comment by patrickelectric** [comment]
It does not compile with the latest GCC.

**Comment by patrickelectric** [comment]
gcc (GCC) 11.1.0
```
home/patrick/git/blue/qgroundcontrol/src/AutoPilotPlugins/PX4/PX4AdvancedFlightModesController.cc: In member function ‘void PX4AdvancedFlightModesController::_init()’:             
/home/patrick/git/blue/qgroundcontrol/src/AutoPilotPlugins/PX4/PX4AdvancedFlightModesController.cc:104:25: error: loop variable ‘attitudeParam’ of type ‘const QString&’ binds to a t
emporary constructed from type ‘const char* const’ [-Werror=range-loop-construct]                                                                                                    
  104 |     for (const QString &attitudeParam : {"RC_MAP_THROTTLE", "RC_MAP_YAW", "RC_MAP_PITCH", "RC_MAP_ROLL", "RC_MAP_FLAPS", "RC_MAP_AUX1", "RC_MAP_AUX2"}) {                    
      |                         ^~~~~~~~~~~~~                                                                                                                                        
/home/patrick/git/blue/qgroundcontrol/src/AutoPilotPlugins/PX4/PX4AdvancedFlightModesController.cc:104:25: note: use non-reference type ‘const QString’ to make the copy explicit or 
‘const char* const&’ to prevent copying                                                                                                                                              
/home/patrick/git/blue/qgroundcontrol/src/AutoPilotPlugins/PX4/PX4AdvancedFlightModesController.cc: In member function ‘void PX4AdvancedFlightModesController::_validateConfiguration
()’:                                                                                                                                                                                 
/home/patrick/git/blue/qgroundcontrol/src/AutoPilotPlugins/PX4/PX4AdvancedFlightModesController.cc:173:24: error: loop variable ‘thresholdParam’ of type ‘const QString&’ binds to a 
temporary constructed from type ‘const char* const’ [-Werror=range-loop-construct]                                                                                                   
  173 |     for(const QString &thresholdParam : {"RC_ASSIST_TH", "RC_AUTO_TH", "RC_ACRO_TH", "RC_POSCTL_TH", "RC_LOITER_TH", "RC_RETURN_TH", "RC_OFFB_TH"}) {                        
      |                        ^~~~~~~~~~~~~~                                                                                                                                        
/home/patrick/git/blue/qgroundcontrol/src/AutoPilotPlugins/PX4/PX4AdvancedFlightModesController.cc:173:24: note: use non-reference type ‘const QString’ to make the copy explicit or 
‘const char* const&’ to prevent copying                                                                                                                                              
cc1plus: all warnings being treated as errors                                                                                                                                        
make: *** [Makefile:126141: PX4AdvancedFlightModesController.o] Error 1                                                                                                              
make: *** Waiting for unfinished jobs....                                                                                                                                            
/home/patrick/git/blue/qgroundcontrol/src/AutoPilotPlugins/PX4/PX4RadioComponent.cc: In member function ‘virtual bool PX4RadioComponent::setupComplete() const’:                     
/home/patrick/git/blue/qgroundcontrol/src/AutoPilotPlugins/PX4/PX4RadioComponent.cc:46:28: error: loop variable ‘mapParam’ of type ‘const QString&’ binds to a temporary constructed 
from type ‘const char* const’ [-Werror=range-loop-construct]                                                                                                                            46 |         for(const QString &mapParam : {"RC_MAP_ROLL", "RC_MAP_PITCH", "RC_MAP_YAW", "RC_MAP_THROTTLE"}) {                                                                          |                            ^~~~~~~~                                                                                                                                          /home/patrick/git/blue/qgroundcontrol/src/AutoPilotPlugins/PX4/PX4RadioComponent.cc:46:28: note: use non-reference type ‘const QString’ to make the copy explicit or ‘const char* const&’ to prevent copying                                                                                                                                                              cc1plus: all warnings being treated as errors                                                                                                                                        make: *** [Makefile:127229: PX4RadioComponent.o] Error 1  
```

**Comment by DonLakeFlyer** [comment]
> It does not compile with the latest GCC.

That would be a good reason then :)

**Pull request merged**
