### PR TITLE
initial travis-ci

### PR DESCRIPTION
**Pull request by dagar**
Currently builds debug/release on linux. Working on getting it to run the unittests.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Let me know when/if you want me to merge this

**Comment by dagar** [comment]
For windows appveyor.com actually seems pretty nice. http://www.appveyor.com/docs/installed-software

Visual Studio 2008-2015
Qt 5.3-5.5

**Comment by dagar** [comment]
To summarize the current options

Linux desktop - https://travis-ci.org
Android - https://travis-ci.org or https://circleci.com
OSX desktop - https://travis-ci.org (invite dependant)
iOS - https://travis-ci.org (invite) or https://circleci.com
Windows desktop - http://www.appveyor.com

Sticking with https://travis-ci.org for everything except windows would be ideal.
I don't see another good OSX desktop option if we can't get a https://travis-ci.org multi os invite.

**Comment by DonLakeFlyer** [comment]
> Sticking with https://travis-ci.org for everything except windows would be ideal.

Definitely agree

**Comment by LorenzMeier** [comment]
Well, the more the merrier! The cloud based solutions seem easy to maintain and blazing fast, in particular if we can run them in parallel.

**Comment by dagar** [comment]
This could be merged now, it should be harmless next to teamcity. I still need to get the unittests running.
Once it's working reliably we can look into deploying builds, the ppa, etc.

I've moved adding appveyor to PR #1812.

**Comment by DonLakeFlyer** [comment]
If I merge now will i screw up the existing TeamCity build break reporting? For example I'm not seeing TC results on this pull now.

**Comment by dagar** [comment]
I'm expecting there to be separate checks added for travis-ci and teamcity, but we should wait and see.

**Comment by DonLakeFlyer** [comment]
I could have sworn it wasn't showing both checks, but now it is! So we're ok.

**Pull request merged**
