### PR TITLE
Detect video stream.

### PR DESCRIPTION
**Pull request by dogmaphobic**
I'm now detecting when a video stream is present. If there is no video coming in (or it stopped), the screen goes black and a notice is presented telling you so.

screen shot 2015-10-28 at 12 44 52 am

### CODE REVIEW

**Comment by dogmaphobic** [comment]
It looks like MissionManagerTest is having a bad day :)

**Comment by DonLakeFlyer** [comment]
It always has a bad day!

**Comment by DonLakeFlyer** [comment]
This is rebases to latest master? Those problems look like the one I already fixed.

**Comment by dogmaphobic** [comment]
> This is rebases to latest master? Those problems look like the one I already fixed.

I'm pretty sure it was. I will try again...

**Pull request merged**
