### PR TITLE
Add auto connect support for the PX4 NXPHlite v3.x

### PR DESCRIPTION
**Pull request by dogmaphobic**
From #6679 

@davids5 I've added the info for auto connect. I didn't mess with the firmware upload.

### CODE REVIEW

**Comment by davids5** [comment]
@dogmaphobic is there Windows build artifact I can grab and test?

**Comment by davids5** [comment]
@dogmaphobic - I build and test it on a linux VM and it segfaults on insertion.

_prgFirmware is null.

image

I have a fix [here](https://github.com/mavlink/qgroundcontrol/pull/6700)

**Comment by davids5** [comment]
@dogmaphobic @DonLakeFlyer @LorenzMeier  - where is the repo/src for the windows inf file in the driver package for windows located?

**Comment by davids5** [comment]
@LorenzMeier 

As this sits it will allowing users to select a file local FW file to upload on linux and mac.

For Windows we need to update the inf file in px4driver.msi  - Where is the src to that?

For the long term the deployment URLS will need to be added in qgc.

**Comment by LorenzMeier** [comment]
@dogmaphobic Looks like a build failure on AppVeyor.

**Comment by dogmaphobic** [comment]
> @dogmaphobic Looks like a build failure on AppVeyor.

AppVeyor keeps changing the version of Qt and removing the old ones. It's a rat's race to keep track of it. I'll do the switch for Windows only.

**Comment by dogmaphobic** [comment]
> For Windows we need to update the inf file in px4driver.msi - Where is the src to that?

I have no idea. @DonLakeFlyer, do you know?

**Comment by davids5** [comment]
This is still open

@LorenzMeier

As this sits it will allow users to select a file local FW file to upload on linux and mac.

For Windows we need to update the inf file in px4driver.msi - Where is the src to that?

For the long term the deployment URLS will need to be added in qgc.

**Comment by DonLakeFlyer** [comment]
The Windows drivers comes Michael Oborne and Mission Planner. I coped it from there. Not sure where the source is for that.

**Pull request merged**
