### PR TITLE
github: Add feature request

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by patrickelectric** [comment]
Hi @hamishwillee, can you kindly review this PR ?
It's a good thing to have a feature request : )

**Comment by tcanabrava** [comment]
+1

**Comment by DonLakeFlyer** [comment]
This needs a lot more asking for info related to firmware version/type or vehicle type if needed. Especially firmware type. My first question is always is this ArduPilot or PS4 which may be info needed. Hopfully hamish can help with wording.

**Comment by patrickelectric** [comment]
Thanks for you inputs, sadly I'll be out for the next week. Amazon jungle here I go !

**Comment by hamishwillee** [comment]
@patrickelectric I very much liked the simplicity of your post. I don't think we need to ask people to update to the latest version as this is feature, not bug (and they won't do it). 
@DonLakeFlyer Is this closer to what you want?


```
---
name: Feature request
about: Tell us about your new idea

---

Tell us a bit about the feature:
- What problem does it solve?
- What does it do?
- What flight stacks must it work with? (All, PX4, ArduPilot)
- Relevant vehicle types? (All, multirotor, fixed-wing, VTOL, submarine, etc.)
- Are there other systems that have this feature?
- What communication/integration standards does the feature rely on (e.g. MAVLink commands etc.)

Any additional context you can provide will make the feature easier to evaluate (e.g. mockups, detailed specification, etc.)
```

**Comment by DonLakeFlyer** [comment]
Yeah, perfect

**Comment by hamishwillee** [comment]
FYI, I didn't update the source, so you merged the original version. Changed to my suggestion by https://github.com/mavlink/qgroundcontrol/commit/ec0c06251ba1721eda93994ff3e6fd909a2f003f

**Comment by DonLakeFlyer** [comment]
> so you merged the original version.

Duh!

**Pull request merged**
