### PR TITLE
Changed Home Position Manager to Flying Field Manager

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
This was done to reduce confusion around the fact that you don't really have a home position when you are editing offline. You are only simulating.

- naming changes
- Flying Field positions show up with "F" instead of "H". This is quick hack to differtiate between a live home position and a simulated flying field on.
- Fixed a bunch of button checked/right panel visible state problems. I think they all do the right thing now at the right time.

Just to reiterate what happen once you are connected to vehicle:
- the "F" indicator will go away and change to a real "H" home position indicator
- The Flying Field Manager will no longer be visible, instead you get static display of home position lat/lon/alt

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Take a look at this. Try editing missions connected and disconnected, as well as starting disconnected, editing and then transition to connected to see what iy does. Then send me the feedback for anything to make it better.

**Comment by LorenzMeier** [comment]
Just building on tablet to test this.

**Comment by DonLakeFlyer** [comment]
Looking for feedback on the concept. The editing of Flying Areas sucks, I know that.

**Comment by LorenzMeier** [comment]
Well, it generally worked. I just found these two:
https://github.com/mavlink/qgroundcontrol/issues/1991
https://github.com/mavlink/qgroundcontrol/issues/1992

**Comment by DonLakeFlyer** [comment]
Did it sort of make sense?

**Comment by LorenzMeier** [comment]
Yes, it sort of made sense. I think its easier if we polish the waypoints first. I look more at the workflow and not so much at details, and so getting it 80% right overall first will help me to give better recommendations.

**Comment by DonLakeFlyer** [comment]
Agree. Flying Field is a bit power user anyway. last on the list

**Pull request merged**
