### PR TITLE
Joystick: Use find_package for mac and linux

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix cmake build in macOS

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by patrickelectric** [comment]
@dagar more love for cmake

**Comment by DonLakeFlyer** [comment]
cmake isn't really being used anywhere. And I'm also not super interested in keeping it up to date. It's hard enough for me to support a single build system. It's impossible to support two. Unless cmake becomes the standard for the CI system for all OS (which it can't as far as I understand) then I don't seen any reason for it to exist.

**Comment by tcanabrava** [comment]
Of course it can, cmake is the industry default for ages and qmake is being
deprecated, qt itself is moving to cmake.

**Comment by DonLakeFlyer** [comment]
Then prove it and put together a pull which switches all CI environments over to cmake and supports all of the custom build features in the current system and also convinces Gus that he can use it to create iOS builds which can be pushed to the iOS store. Until then for me cmake is just an annoyance which I don't have time to deal with.

> qt itself is moving to cmake.

That doesn't really mean anything. Qt doesn't release to all the places we do.

**Comment by patrickelectric** [comment]
> Then prove it and put together a pull which switches all CI environments over to cmake and supports all of the custom build features in the current system and also convinces Gus that he can use it to create iOS builds which can be pushed to the iOS store. Until then for me cmake is just an annoyance which I don't have time to deal with.

If all PRs that improve the cmake build system get merged this will be possible.. 
There is two options, **remove cmake** entirely from QGC or **merge the PRs that improve and fix cmake**.

**Comment by dagar** [comment]
For cmake we need to either figure out the workflow for Android and iOS build/deploy/upload that's equivalent to QtCreator with qmake or wait until Qt switches over entirely. Once Android and iOS are in place I volunteer to fill in all the other gaps.

After that literally everything is better in the cmake world. Finding dependencies, creating packages, handling platform differences, and even build times.

@DonLakeFlyer  I thought gradually getting cmake support in place piece by piece would be the lazy way to switch over some day, but if it's a problem then please ignore it and defer to me.

**Comment by patrickelectric** [comment]
<3 @dagar

**Comment by DonLakeFlyer** [comment]
> I thought gradually getting cmake support in place piece by piece would be the lazy way to switch over some day, but if it's a problem then please ignore it and defer to me.

@dagar The problem is that gradually has equaled more than a year++. That's a bit more than gradual! I don't care much what system is used I just care that I'm not left cleaning up a mess of missing stuff. To me it's time to as they say "Shit or get off the pot!". The requirements are:
* Build all OS versions in CI, travis and appveyor
* Can build both Auterion and Sentera custom build as test cases for custom support
* Can build iOS and android builds which can be pushed to store
* Android build should be push to store from CI
* iOS build would still be some manual magic that Gus does. If cmake could automate that as well well even better. But were aren't there yet so that isn't a requirement.

**Comment by DonLakeFlyer** [comment]
Also any full switchover needs to wait until 4.0 goes out. But certainly switching right away after that would make sense.

**Comment by DonLakeFlyer** [comment]
The other thing is that for android using Qt Creator and the simulator is never used. But for iOS I also the Xcode build (Spit out by qmake) plus run QGC in the simulator all the time. So that support can't disappear either.

**Comment by dagar** [comment]
> > I thought gradually getting cmake support in place piece by piece would be the lazy way to switch over some day, but if it's a problem then please ignore it and defer to me.
> 
> @dagar The problem is that gradually has equaled more than a year++. That's a bit more than gradual! I don't care much what system is used I just care that I'm not left cleaning up a mess of missing stuff. To me it's time to as they say "Shit or get off the pot!". The requirements are:
> 
> * Build all OS versions in CI, travis and appveyor
> * Can build both Auterion and Sentera custom build as test cases for custom support
> * Can build iOS and android builds which can be pushed to store
> * Android build should be push to store from CI
> * iOS build would still be some manual magic that Gus does. If cmake could automate that as well well even better. But were aren't there yet so that isn't a requirement.

Actually I'm fairly confident most if not all of those particular areas will be saner. One of the reasons I started going down the cmake path is that handling all of these things with qmake and our own crappy scripts on the side was such a dumpster fire.

My only hesitation in pushing for a full switchover sooner was the out of box QtCreator device debug/deploy experience for Android and iOS. It's been quite a while since I've last tried (probably the "more than a year++" you mentioned) so maybe time to take another look.

@tcanabrava any comment or suggestions?

**Comment by DonLakeFlyer** [comment]
> was the out of box QtCreator device debug/deploy experience for Android and iOS

Yup. I missed the debug/deploy as important for Android as well.

**Pull request merged**
