### PR TITLE
mavlink WIND_COV -> windFactGroup

### PR DESCRIPTION
**Pull request by dagar**
Needs testing. No wind in SITL.

### CODE REVIEW

**Comment by dagar** [comment]
Sigh, no wind in HIL either. Can someone just check my math?

**Comment by dagar** [comment]
Fixes #3033

**Comment by NaterGator** [comment]
Math checks out

**Comment by DonLakeFlyer** [comment]
Daniel could you dump an issue on the firmware side for fake wind. At least to send this message, not really simulated? Would be handy for testing.

**Comment by dagar** [comment]
It looks like it was just the switch to EKF2 where it's not enabled quite yet.
https://github.com/PX4/ecl/blob/eaae95fdc4e48e3946a463941dfb9d5e495e975f/EKF/control.cpp#L744

**Pull request merged**
