### PR TITLE
Harden code for missing params, handle APM special case

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Fix for Issue #2515.

@pritamghanghas Can you try this again your Linux board which is missing the params?

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Also fixes Issue #2528

**Comment by pritamghanghas** [comment]
I checked it against my board. Doesn't crash but lot of overlap on top the
screen about missing parameters


On Mon, Jan 4, 2016 at 11:41 PM, Don Gagne <notifications@github.com> wrote:

> Fix for Issue #2515
> <https://github.com/mavlink/qgroundcontrol/issues/2515>.
>
> @pritamghanghas <https://github.com/pritamghanghas> Can you try this
> again your Linux board which is missing the params?
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/mavlink/qgroundcontrol/pull/2529
> Commit Summary
>
>    - Harden code for missing params, handle APM special case
>
> File Changes
>
>    - *M* src/AutoPilotPlugins/Common/RadioComponentController.cc
>    <https://github.com/mavlink/qgroundcontrol/pull/2529/files#diff-0>
>    (115)
>    - *M* src/AutoPilotPlugins/Common/RadioComponentController.h
>    <https://github.com/mavlink/qgroundcontrol/pull/2529/files#diff-1> (2)
>
> Patch Links:
>
>    - https://github.com/mavlink/qgroundcontrol/pull/2529.patch
>    - https://github.com/mavlink/qgroundcontrol/pull/2529.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mavlink/qgroundcontrol/pull/2529>.
>



-- 
Regards,
pritam

**Comment by DonLakeFlyer** [comment]
From which config screen Radio? Or others? And what parameters?

**Comment by pritamghanghas** [comment]
ok I replied to mail and attached a screen. I guess github doesn't take care of attaching the mail attachement. jostick config screen. 
overlapping message

**Pull request merged**
