### PR TITLE
[WIP] add PX4 airspeed mode

### PR DESCRIPTION
**Pull request by dagar**
-waiting for https://github.com/PX4/Firmware/pull/3861

-verify PX4_CUSTOM_MAIN_MODE in sync before merging

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
What about flight mode setup? Does that need to chagne as well?

**Comment by dagar** [comment]
I was thinking about making this only part of the new mode switch config.

**Comment by dagar** [comment]
This should probably wait until PX4/Firmware#3861 is accepted.

**Comment by DonLakeFlyer** [comment]
Should I revert it? Also just looking at it. Why isn't the new mode added to the end? By adding in the middle doesn't it cause old/new version problems? New QGC running against old firmware is going to set RATTITUDE instead of the new flight mode.

**Comment by dagar** [comment]
Yes it should be at the end, but ended up like this because PX4_CUSTOM_MAIN_MODE was missing RATTITUDE on one side.

**Pull request merged**
