### PR TITLE
Move video settings

### PR DESCRIPTION
**Pull request by tcanabrava**
This moves the video setting out of the GeneralSettings to a button inside of the Video Element.
This is needed for the move to multiple video streams.
This depends on #8672

### CODE REVIEW

**Comment by tcanabrava** [comment]
@dogmaphobic @DonLakeFlyer Please review. This is needed for streams.

**Comment by jaxxzer** [comment]
@tcanabrava how does this relate to https://github.com/mavlink/qgroundcontrol/pull/8411?

**Comment by tcanabrava** [comment]
> @tcanabrava how does this relate to #8411?

#8411 is old and it was neglected by the reviewers for months, so right now it's unreviewable and it has just too many conflicts with master to be minimally userful. This one is a new attempt that does part of #8411 did, in a better way.

**Comment by DonLakeFlyer** [comment]
This is all different now

**Comment by tcanabrava** [comment]
Yeah, after almost one year I believe that it’s different. Tells something
about how the maintainers handle contributions.

**Comment by DonLakeFlyer** [comment]
Maintainers plural! Hah, that would be fantastic. I used to have folks that help to maintain/develop video and review pulls. They are gone now. I used to have folks to help maintain/develop the new camera protocol/ui and review pulls. Also gone now. The "maintainers" are just me, nobody else. Now I'm left dealing with stuff I know nothing about by myself which was left hanging. So yes, it does tell you something.

**Comment by tcanabrava** [comment]
Don,
In all of the softwares that I have worked, opensource or not, qgc was the
one that I felt that the contributions are not really welcome.
Instead of closing those pull requests you could have pinged me to see if
the merge requests are still worth it, if you had the desire to merge.
After all, it’s developer time invested: they had a reason to do the code,
being a paid developer or a opensource one.

I understand why it’s only you maintaining: it’s impossible to deliver
things on qgc currently as most of the changes done by you don’t have
review, are just pushed to master without a real merge request or
discussion. Breaking assumptions and constantly breaking ready to merge
code - I have rebased some pull requests here countless times and some
months while still getting paid to work on qgc I had to basically work
rebasing work because the master keeps breaking my changes.

The git history is a complete mess, it’s impossible to use git bisect to
find a broken commit because the history doesn’t makes sense - just run a
git log —graph to analyze the result and you will see what I’m talking
about - I have found over 16 levels of indentation of merge commits.

I’m not targeting this at you - but at how qgc is as a project: it does not
feel that there is a desire to have contributors joining in, if I’m
mistaken, by all means: reopen the tickets that I worked on and I’ll
continue to them, but I need to be sure that the work will not be left
ready to merge for more for more than six months.

If there is only you as maintainer: invite more people that you trust, pay
attention to git history as it helps other developers, put other developers
to review your code instead of pushing everything to master directly, and
allow some experimentation on the software.

Again, just explaining some of my frustrations while working on the
project. And the reason I disappeared: I missed reviews and communication.

**Pull request closed without merging**
