### PR TITLE
Survey triggering: Support new enable / disable command without impacting the navigation pipeline [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by LorenzMeier**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Thanks Lorenz. Hoping to get some time to look through this tomorrow.

**Comment by DonLakeFlyer** [comment]
There is a bunch of associated changes needed for this. I'll use this pull as the starting point and then fix up the missiing parts.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Were you able to reproduce the crash i was seeing? 

Also FYI: I do have another pull for this but it is functionally the same as yours. Just handles some ArduPilot special casing. So this one is fine to test with. Don't want to put mine up till it's all tested to make it easier to cherry-pick to other repos.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer What is the status here?

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Ready for a rebase & test.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Finally looking at this again! So I looked through current master firmware and don't see any support for MAV_CMD_CONDITION_GATE in there.

**Comment by LorenzMeier** [comment]
https://github.com/PX4/Firmware/pull/7739

**Comment by DonLakeFlyer** [comment]
Closing this as stale.

**Pull request closed without merging**
