### PR TITLE
Solve some typos

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by dogmaphobic** [comment]
These fixes are really, truly appreciated but notice that about half of them are in third party code it could get updated/replaced in the future :)

**Comment by DonLakeFlyer** [comment]
@patrickelectric Can you put together a pull which limits these to the QGC source only? Only file under "src".

**Comment by patrickelectric** [comment]
@dogmaphobic, @DonLakeFlyer done

**Comment by DonLakeFlyer** [comment]
Fantastic

**Comment by DonLakeFlyer** [comment]
Thanks @patrickelectric

**Pull request merged**
