### PR TITLE
Add ARKV6X

### PR DESCRIPTION
**Pull request by AlexKlimaj**
This PR adds the ARKV6X PAB form factor flight controller. Starting it as a WIP PR to get CI to build a working version of QGC to test with.

I am currently using Auterions VID, which isn't ideal. Ideally we get a common Pixhawk VID.

https://arkelectron.com/product/arkv6x/

Xp9i8CtCTjakj7GU5trL_IMG_3800
rU27nbgvQLGVOuwWshKy_IMG_3799

### CODE REVIEW

**Comment by AlexKlimaj** [comment]
Can I get this reviewed and merged?

**Comment by mrpollo** [comment]
@AlexKlimaj can you try out the QGC version from this PR and check if you can flash PX4 on your board? you might need to change this file as well if you can't https://github.com/mavlink/qgroundcontrol/pull/10252

**Comment by AlexKlimaj** [comment]
> @AlexKlimaj can you try out the QGC version from this PR and check if you can flash PX4 on your board? you might need to change this file as well if you can't #10252

@mrpollo Good catch. Updated and pushed!

**Comment by mrpollo** [comment]
It's in!

**Pull request merged**
