### PR TITLE
USBBoardInfo.json: Adding missing mRo boards to be detected by Auto-C…

### PR DESCRIPTION
**Pull request by TOTON95**
This PR should fix the issue with mRo boards (using PX4) not connecting to QGC through Auto-Connect.

### CODE REVIEW

**Comment by TOTON95** [comment]
This fix is working for Linux, awaiting for Windows version to verify it.

**Comment by TOTON95** [comment]
Windows build works as intended with recently added boards

**Comment by TOTON95** [comment]
Thanks @HTRamsey

**Comment by rzappe** [comment]
@TOTON95 Can confirm it works great!

**Pull request merged**
