### PR TITLE
Update Ubuntu PPA instructions

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Thanks dagar.

**Comment by dagar** [comment]
I'm working on getting a qgroundcontrol ubuntu ppa together, but it's surprisingly difficult and poorly documented. You can't just upload a deb because it has to be built by launchpad.

**Comment by DonLakeFlyer** [comment]
That would be awesome. I think like I said before. If you can figure it out. Then let me know instructions and I might be able to automate TeamCity installers builds to do it for us on each build.

**Comment by dogmaphobic** [comment]
There is always the option of downloading the Qt Online installer, which allows you to have an installation on your home directory and not mess up the system. I find that a lot simpler and cleaner as it doesn't pollute the (root) system: http://www.qt.io/download-open-source

**Comment by DonLakeFlyer** [comment]
Gus: I'm a Linux newbie so I don't know what make sense or not. If you think this is a good option, could you update the readme to include that as well and why you would use one over the other?

**Comment by dogmaphobic** [comment]
How do you *preview* changes to README.md?

**Comment by DonLakeFlyer** [comment]
You hope for the best!

**Comment by dogmaphobic** [comment]
Thanks! :smirk:

**Comment by dagar** [comment]
If you edit it through the github web interface there's a preview tab.

**Comment by dogmaphobic** [comment]
> If you edit it through the github web interface there's a preview tab.

Brilliant! Thanks...

**Pull request merged**
