### PR TITLE
Breakpad support for android

### PR DESCRIPTION
**Pull request by DonLakeFlyer**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dagar The android build now builds with -g so it has symbols in there. Seems like if I put the linux dump_syms tool in the repo I could create the breakpad symbol file in travis. Upload that to S3 as well. And then there must be some tool I can run to strip the symbols from the .so before we push up to S3? That seems possible doesn't it?

**Comment by dagar** [comment]
@DonLakeFlyer 

    strip --strip-all release/libQGroundControl.so

**Comment by NaterGator** [comment]
@DonLakeFlyer @dagar this is relevant to #4445 too. If Android is getting breakpad support we should consider adding it for Windows... at least for CI builds.

**Comment by dagar** [comment]
It sounds like we should be able to use it everywhere?

Do we need something like Mozilla Socorro? https://wiki.mozilla.org/Breakpad

**Comment by DonLakeFlyer** [comment]
Yeah, trying on Android first since we have some unexplained crashes there. Then we can:
* Move to all OS
* Figure out an auto-upload mechanism/server

**Comment by DonLakeFlyer** [comment]
FYI: It's not really automatic to get this to work crossplatform. You need to figure each one out separately. So it's not just a matter of flipping a build switch.

**Comment by NaterGator** [comment]
Understood. If it is any consolation I already have it implemented in Windows.

**Comment by DonLakeFlyer** [comment]
If you guys could figure out how to get this working with upload and a server that would be awesome.

**Pull request merged**
