### PR TITLE
Fix acelerometer setup

### PR DESCRIPTION
**Pull request by tcanabrava**
some issues regarding APM setup on a local drone.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
I should have time to look at this sometime today

**Comment by tcanabrava** [comment]
Thanks.

**Comment by DonLakeFlyer** [comment]
You should just switch it to only check the offsets for the first accel. No need to leave the old stuff in an ifdef. Also no need for insUse variable at all or rgOffsets to have two dimensions any longer. Also APMSensorsComponent::setupCompleteChangedTriggerList should match the set of params that are now being used.

**Comment by DonLakeFlyer** [comment]
@tcanabrava Can you clean this up?

**Comment by tcanabrava** [comment]
seems broken because of a forced push.

**Pull request closed without merging**
