### PR TITLE
{Sponsored by Intelliterra} Made "Declare Emergency" button send MAV_CMD to set emergency

### PR DESCRIPTION
**Pull request by jnomikos**
Currently the "Declare Emergency" button does not actually set the OPEN_DRONE_ID_LOCATION status to emergency on PX4. I created a PR into mavlink [here](https://github.com/mavlink/mavlink/pull/2027) which adds a MAV_CMD_DO_SET_EMERGENCY command. My changes on this PR make it so that the Declare Emergency button sends that command.

As a note, I tested the MAVLink changes on QGroundControl by making the changes to the detached head submodule and building that first, since QGC currently is not on the most recent MAVLink build.

**Context**
Link to MAVLink PR: https://github.com/mavlink/mavlink/pull/2027

Link to PX4 PR: https://github.com/PX4/PX4-Autopilot/pull/21959

### CODE REVIEW

**Comment by jnomikos** [comment]
Build is failing because I did not add my MAVLink changes to this PR

**Comment by Davidsastresas** [comment]
It looks good to me, but we need to:

- Wait for Mavlink to merge this https://github.com/mavlink/mavlink/pull/2027
- In case Ardupilot doesn't support this yet, or ever, maybe it is a good idea to move that small addition to firmwareplugin instead, so it doesn't affect Ardupilot. Also would be good to at least confirm master PX4 uses it before merging this.

**Comment by jnomikos** [comment]
> It looks good to me, but we need to:
> 
> 
> 
> - Wait for Mavlink to merge this https://github.com/mavlink/mavlink/pull/2027
> 
> - In case Ardupilot doesn't support this yet, or ever, maybe it is a good idea to move that small addition to firmwareplugin instead, so it doesn't affect Ardupilot. Also would be good to at least confirm master PX4 uses it before merging this. Can you manage this @jnomikos ? Thanks!

I talked with PX4 devs a few months ago and they came to the conclusion that adding emergency button functionality isn't a necessity based on the RID requirements provided. They told me to keep my PRs up just so we have it in case anything changes.

**Comment by Davidsastresas** [comment]
Thanks for the answer. In that case we will close this one, we can reopen it in the future if the situation changes. Thanks!

**Pull request closed without merging**
