### PR TITLE
Mission manager errors now show up in UI

### PR DESCRIPTION
**Pull request by DonLakeFlyer**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dagar I'm getting this AppVeyor failure intermittenly. If you re-run it goes away. Seems like some sort of script of setup problem. I'll leave it here for now and not re-run.

**Comment by dagar** [comment]
To start with I'll only install nsis when we need it.
https://github.com/mavlink/qgroundcontrol/commit/a2448c15f4e4a032a86a72aae176fd2612feda45

**Comment by DonLakeFlyer** [comment]
@dagar Ok, to merge this now. or do you need to look at it more?

**Comment by dagar** [comment]
Yes go ahead. At the moment I don't really know much about NuGet or why it's occasionally failing like this with a completely unhelpful message. I'll keep an eye on it, and let me know when you see it fail.

    [NuGet] An error occurred while processing this request.

**Comment by DonLakeFlyer** [comment]
@dagar Is there some way to re-run a job on AppVeyor. I can't seem to find it.

**Comment by dagar** [comment]
Try again. Everyone in mavlink/Admins on github should now have admin access on appveyor.

**Comment by DonLakeFlyer** [comment]
@dagar Now I can't even look at the results. It says "project not found or access denied".

**Comment by dagar** [comment]
I renamed it so it displays mavlink/qgroundcontrol instead of dagar/qgroundcontrol.
https://ci.appveyor.com/project/mavlink/qgroundcontrol/build/master-260

**Comment by DonLakeFlyer** [comment]
Still don't see anything that would re-run the job. If you can see it, can you screen shot it or something to show me where it is?

**Comment by dagar** [comment]
It's at the top of the build, but if you can't find it I'm guessing I don't have the permissions set correctly.

screenshot from 2015-10-09 20 51 42

**Comment by DonLakeFlyer** [comment]
@dagar I'm logged in through GitHub:
screen shot 2015-10-09 at 5 58 57 pm

I guess for now, can you re-run it for me?

**Comment by DonLakeFlyer** [comment]
@dagar I logged out. Then when I logged back it it wanted me to chose from two accounts: mavlink and DonLakeFlyer. DonLakeFlyer didn't work, mavlink did. Not sure what that's all about.

**Pull request merged**
