### PR TITLE
QGCMapPolygon: Fix bug in center polygon item

### PR DESCRIPTION
**Pull request by patrickelectric**
When creating new points, center need to be updated.

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by patrickelectric** [comment]
Survey bug:
bug

Fix:
corrigido

**Comment by DonLakeFlyer** [comment]
Do you know why this code:
```
void QGCMapPolygon::_init(void)
{
    connect(&_polygonModel, &QmlObjectListModel::dirtyChanged, this, &QGCMapPolygon::_polygonModelDirtyChanged);
    connect(&_polygonModel, &QmlObjectListModel::countChanged, this, &QGCMapPolygon::_polygonModelCountChanged);
    connect(&_polygonModel, &QmlObjectListModel::countChanged, this, &QGCMapPolygon::_updateCenter);
}
```

Isn't working to update the center? The count should change which should trigger a call to _updateCenter.

**Comment by patrickelectric** [comment]
I'll check it.

**Comment by patrickelectric** [comment]
Done.

> Since `_updateCenter` uses `_polygonPath` to calculate new center point,
> it's necessary to connect `pathChanged` with `_updateCenter`

**Comment by DonLakeFlyer** [comment]
Just to make sure I understand. QmlObjectListModel::countChanged was signalled when the QmlObjectListModel changed, but before the path version of the polygon change. Hence _updateCenter was always working on old data?

**Comment by DonLakeFlyer** [comment]
The QGCMapPolygonTest unit test is failing Can you take a look?

**Comment by DonLakeFlyer** [comment]
Also would be awesome to include a new test which covers this case that was broken.

**Comment by patrickelectric** [comment]
> Just to make sure I understand. QmlObjectListModel::countChanged was signalled when the QmlObjectListModel changed, but before the path version of the polygon change. Hence _updateCenter was always working on old data?
Exactly !

**Comment by patrickelectric** [comment]
I'll check the tests asap.

**Comment by DonLakeFlyer** [comment]
It's failing because the centerChanged signal is being emitted twice when it thinks it should only be emitted one.

**Comment by patrickelectric** [comment]
@DonLakeFlyer This new approach will work in all cases and only call _updateCenter once.

**Comment by patrickelectric** [comment]
Is this the correct approach to solve the problem ?

**Comment by DonLakeFlyer** [comment]
Let me take a look. If it turns out to be a real pain to fix the double signalling we can live with it. The centerChanged signal isn't really cannot to anything which would propogate to other parts of the system causing possible perf problems due to running twice.

**Comment by patrickelectric** [comment]
@DonLakeFlyer Probably will, because is [the same thing that I have done..](https://github.com/mavlink/qgroundcontrol/pull/5684/files)

**Comment by DonLakeFlyer** [comment]
Not quite if you look at it. One change was missing.

**Comment by DonLakeFlyer** [comment]
Replaced by #5715

**Pull request closed without merging**
