### PR TITLE
Move VideoManager class from FligthDisplay to VideoStreaming

### PR DESCRIPTION
**Pull request by tcanabrava**
Makes more sense for it to be in VideoStreamer as it takes care of managing
the video streams.

### CODE REVIEW

**Comment by jaxxzer** [comment]
@tcanabrava will you rebase this please? Looks ok.

**Comment by tcanabrava** [comment]
rebasing / fixing for cmake

**Comment by tcanabrava** [comment]
There's a but on CMake, /home/tcanabrava/Projects/qgroundcontrol/src/VideoStreaming/VideoStreaming.cc:173: undefined reference to `gst_plugin_qgc_register' - unrelated to this patch. It's also happening in master. I'll create a different review for it.

**Comment by tcanabrava** [comment]
@dogmaphobic if you can take a look here, trying to move everything video related to the same folder to it's easy to create a demo-app.

**Comment by andrewvoznytsa** [comment]
> There's a bug on CMake, /home/tcanabrava/Projects/qgroundcontrol/src/VideoStreaming/VideoStreaming.cc:173: undefined reference to `gst_plugin_qgc_register' - unrelated to this patch. It's also happening in master. I'll create a different review for it.

Should be fixed by https://github.com/mavlink/qgroundcontrol/pull/8367

**Pull request merged**
