### PR TITLE
[WIP] travis-ci OSX

### PR DESCRIPTION
**Pull request by dagar**
Using this PR to get OSX support working.

### CODE REVIEW

**Comment by dagar** [comment]
OSX now building on travis. Is the default `brew install qt5` fine (qt 5.5) or should we lock down a specific version of qt?

**Comment by DonLakeFlyer** [comment]
We should lock down to the versions specified in the readme

**Comment by dagar** [comment]
Qt 5.4 doesn't appear to be available via homebrew. Maybe the installer specified in the readme can be automated?
Anyone with a Mac know of a way to install Qt 5.4 on the command line?

**Comment by LorenzMeier** [comment]
I tried a bunch of ways, but none worked so far.

**Comment by dogmaphobic** [comment]
The online installer (https://github.com/mavlink/qgroundcontrol#alternate-qt-creator-ide-build-type-any-os) has a command line interface, which allows you to install and maintain Qt (get updates, etc.) That's what I use for all platforms.

**Comment by LorenzMeier** [comment]
@dogmaphobic I figured this one out via Homebrew. Just need to build the bottle and we're good.

**Comment by dagar** [comment]
Successfully building on OSX with Qt 5.4.2. Thanks @LorenzMeier 

Now having trouble with the unittests. Does anyone know what's wrong with the unittest in this build?
https://travis-ci.org/mavlink/qgroundcontrol/jobs/78332331

**Comment by DonLakeFlyer** [comment]
Since the qtlogging.ini is not there, it is doing full logging which is blowing out a size limit I believe. Can you force a qtlogging.ini onto the machine before you build with all logging turned off?

**Comment by dogmaphobic** [comment]
That logging seem awfully verbose:
'''
QDEBUG : FactSystemTestGeneric::parameter_default_component_id_test() ParameterLoaderLog: _waitingReadParamIndexMap: QMap((323, 0)(324, 0)(325, 0)(326, 0)(327, 0)(328, 0)(329, 0)(330, 0)(331, 0)(332, 0)(333, 0)(334, 0)(335, 0)(336, 0)(337, 0)(338, 0)(339, 0)(340, 0)(341, 0)(342, 0)(343, 0)(344, 0)(345, 0)(346, 0)(347, 0)(348, 0)(349, 0)(350, 0)(351, 0)(352, 0)(353, 0)(354, 0)(355, 0)(356, 0)(357, 0)(358, 0)(359, 0)(360, 0)(361, 0)(362, 0)(363, 0)(364, 0)(365, 0)(366, 0)(367, 0)(368, 0)(369, 0)(370, 0)(371, 0)(372, 0)(373, 0)(374, 0)(375, 0)(376, 0)(377, 0)(378, 0)(379, 0)(380, 0)(381, 0)(382, 0)(383, 0)(384, 0)(385, 0)(386, 0)(387, 0)(388, 0)(389, 0)(390, 0)(391, 0)(392, 0)(393, 0)(394, 0)(395, 0)(396, 0)(397, 0)(398, 0)(399, 0)(400, 0)(401, 0)(402, 0)(403, 0)(404, 0)(405, 0)(406, 0)(407, 0)(408, 0)(409, 0)(410, 0)(411, 0)(412, 0)(413, 0)(414, 0)(415, 0)(416, 0)(417, 0)(418, 0)(419, 0)(420, 0)(421, 0)(422, 0)(423, 0)(424, 0)(425, 0)(426, 0)(427, 0)(428, 0)(429, 0)(430, 0)(431, 0)(432, 0)(433, 0)(434, 0)(435, 0)(436, 0)(437, 0)(438, 0)(439, 0)(440, 0)(441, 0)(442, 0)(443, 0)(444, 0)(445, 0)(446, 0)(447, 0)(448, 0)(449, 0)(450, 0)(451, 0)(452, 0)(453, 0)(454, 0)(455, 0)(456, 0)(457, 0)(458, 0)(459, 0)(460, 0)(461, 0)(462, 0)(463, 0)(464, 0)(465, 0)(466, 0)(467, 0)(468, 0)(469, 0)(470, 0)(471, 0)(472, 0)(473, 0)(474, 0)(475, 0)(476, 0)(477, 0)(478, 0)(479, 0)(480, 0)(481, 0)(482, 0)(483, 0)(484, 0)(485, 0)(486, 0)(487, 0)(488, 0)(489, 0)(490, 0)(491, 0)(492, 0)(493, 0)(494, 0)(495, 0)(496, 0)(497, 0)(498, 0)(499, 0)(500, 0)(501, 0)(502, 0)(503, 0)(504, 0)(505, 0)(506, 0)(507, 0)(508, 0)(509, 0)(510, 0)(511, 0)(512, 0)(513, 0)(514, 0)(515, 0)(516, 0)(517, 0)(518, 0)(519, 0)(520, 0)(521, 0)(522, 0)(523, 0)(524, 0)(525, 0)(526, 0)(527, 0)(528, 0)(529, 0))
'''

**Comment by DonLakeFlyer** [comment]
Full logging really means full logging!

**Comment by DonLakeFlyer** [comment]
It's just verbose enough if you are trying to debug a parameter missing problem which are a nightmare!

**Pull request merged**
