### PR TITLE
fix implicitly defined properties in Connections

### PR DESCRIPTION
**Pull request by booo**
Implicitly defined properties are deprecated in newer Qt versions.
This changes the syntax of the property functions to the new style.

### CODE REVIEW

**Comment by booo** [comment]
I'm not sure if this changes is ok for qt version 5.12. See https://stackoverflow.com/questions/62297192/qml-connections-implicitly-defined-onfoo-properties-in-connections-are-deprecat

**Comment by patrickelectric** [comment]
That's a great PR to start Qt5.15 migration

**Comment by DonLakeFlyer** [comment]
Awesome, thanks

**Comment by booo** [comment]
I think there are still a few missing. Maybe I can fix them in another run later on.

**Comment by DonLakeFlyer** [comment]
Yeah, there is still a pretty big pile left. For now I've turned off the warning.

**Pull request merged**
