### PR TITLE
Exclude shapelib and zlib from cmake install process

### PR DESCRIPTION
**Pull request by s-lisovenko**
Modify CMakeLists for shapelib and zlib fetch process to exclude them from install procedure

### CODE REVIEW

**Comment by HTRamsey** [comment]
I assume this removes all the extra shapelib executables? Also I believe zlib has the skip_install options we can use instead

**Comment by s-lisovenko** [comment]
> skip_install

Zlib was fixed.
About shapelib, yes all targets will be remove from install procedure. Do we need something from shapelib inside install folder?

**Comment by HTRamsey** [comment]
Not that I know of. I believe shapelib 1.7.0 will have better cmake options to control install but this should be fine for now

**Review by HTRamsey — APPROVED** [review]

**Comment by s-lisovenko** [comment]
Better way is to use cmake 3.28 with ECLIDE_FROM_ALL parameters for FetchContent_Declare function. But I don’t know if this acceptable now.

**Comment by s-lisovenko** [comment]
But maybe more better way i think is to use ExternalProject_add and build and install then use find_package. Like Mavsdk team do it.

**Comment by HTRamsey** [comment]
We can always come back and do it more like that later. At least at the moment this will work and it will guarantee everyone is using the same versions dependencies

**Comment by DonLakeFlyer** [comment]
Is this fix related to me hitting this:
```
don@Donalds-Mac-Pro build % cmake --install .                                                     
-- Install configuration: "Release"
-- Installing: /Users/don/repos/qgroundcontrol/build/staging/lib/libz.1.3.1.dylib
-- Installing: /Users/don/repos/qgroundcontrol/build/staging/lib/libz.1.dylib
-- Installing: /Users/don/repos/qgroundcontrol/build/staging/lib/libz.dylib
CMake Error at _deps/zlib-build/cmake_install.cmake:87 (file):
  file INSTALL cannot find
  "/Users/don/repos/qgroundcontrol/build/_deps/zlib-build/libz.a": No such
  file or directory.
Call Stack (most recent call first):
  src/Compression/cmake_install.cmake:42 (include)
  src/cmake_install.cmake:82 (include)
  cmake_install.cmake:47 (include)
```

**Comment by HTRamsey** [comment]
I believe this PR removes the static lib so it should help with that, although I don't understand why you would get that in the first place

**Comment by HTRamsey** [comment]
By the way, if you are using QtCreator you can go to Run -> Add Deploy Step -> CMake Install to automate that step

**Comment by s-lisovenko** [comment]
> By the way, if you are using QtCreator you can go to Run -> Add Deploy Step -> CMake Install to automate that step

Yes, this PR should fix this error

**Comment by s-lisovenko** [comment]
> I believe this PR removes the static lib so it should help with that, although I don't understand why you would get that in the first place

No, This PR jyst remove it from install process. The problem is that by default zlib use dynamic library
Screenshot from 2024-04-09 21-55-09

**Pull request merged**
