### PR TITLE
ArduPilot: Support perflight barometer/airspeed calibration

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Fix for #5274

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@jaxxzer Can you look at this with respect to pressure cal changes?

**Comment by jaxxzer** [comment]
@DonLakeFlyer Yes

**Comment by jaxxzer** [comment]
Looks good, should work for all apm vehicles.

**Comment by DonLakeFlyer** [comment]
Thanks

**Comment by hamishwillee** [comment]
@jaxxzer , @DonLakeFlyer - is this a new screen? If so, can I have some screenshots for the docs? Normally I show the sidebar option, any screens that require user input, and possibly an "end shot".

**Pull request merged**
