### PR TITLE
Pinch Zoom Fix

### PR DESCRIPTION
**Pull request by ben-draper-ascent**
The MouseArea fix was dominating the PinchHandler. Figured we should stick to the QML intended implementation of the Map and just disable the views if the tool drawer is open

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
I had tried that and it didn't work. Even with the fly view invisible, the DragHandler was bleeding through and causing the map to move around. The only way I could get it to work in all cases was to not use it.

**Comment by ben-draper-ascent** [comment]
> I had tried that and it didn't work. Even with the fly view invisible, the DragHandler was bleeding through and causing the map to move around. The only way I could get it to work in all cases was to not use it.

Yes visibility is not enough which is why I changed the Enable property. I tested on my android and did a control test where it did not work and then loaded the new apk to prove it resolved.

**Comment by DonLakeFlyer** [comment]
Ah, I missed that. That's the magic thing! What a pain.

**Comment by DonLakeFlyer** [comment]
What about the Plan View drags bleeding down to the Fly View?

**Comment by DonLakeFlyer** [comment]
Also can you add a comment to the places you enable based on visibility explaining why? That way, years down the road someone doesn't remove them thinking they aren'y really needed.

**Comment by HTRamsey** [comment]
@DonLakeFlyer I could have sworn I remember you adding a StackView to the MainRootWindow to swap between the views, which would have prevented this too I would think

**Comment by ben-draper-ascent** [comment]
> What about the Plan View drags bleeding down to the Fly View?

I tested this as well and its why I added the enabled property in the PlanView item as well. I'll add those comments now

**Comment by s-lisovenko** [comment]
https://github.com/mavlink/qgroundcontrol/pull/11257

**Pull request merged**
