### PR TITLE
Changing file encoding(UTF8 to UTF8 with BOM) to fix compiling error

### PR DESCRIPTION
**Pull request by wuuhii**
Changing file encoding(UTF8 to UTF8 with BOM) to fix compiling error

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@wuuhii Don't quite get why only these two files are screwed up? Any ideas?

**Comment by wuuhii** [comment]
> 
> 
> @wuuhii Don't quite get why only these two files are screwed up? Any ideas?

May be these files contain non-ascii characters

**Comment by DonLakeFlyer** [comment]
> May be these files contain non-ascii characters

Hmm, they shouldn't. @dogmaphobic  any ideas here? Wondering if these files need to be cleaned out somehow from crap chars?

**Comment by dogmaphobic** [comment]
> @dogmaphobic any ideas here? Wondering if these files need to be cleaned out somehow from crap chars?

I don't see anything weird. No non ASCII characters are there:

Screen Shot 2019-12-31 at 2 58 09 PM

**Comment by wuuhii** [comment]
图片
Maybe I make a mistake. It is just a warning. But I don't know how to cancel the compiler option.

**Comment by dogmaphobic** [comment]
Do you have some editor that shows the hex dump of the file? Maybe something gets changed when you clone it? Trying looking at the place where the error occurs and see if there are indeed Unicode characters in there.

**Comment by wuuhii** [comment]
I'll try tomorrow

**Pull request closed without merging**
