### PR TITLE
Terrain: Cleanup Terrain Queries

### PR DESCRIPTION
**Pull request by HTRamsey**
Clean up and better structure Terrain files in prep for #11795
Fixes some QObject parenting
Finishes setting up unit tests

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Are you running some sort of lint thing on stuff before you checkin? Removing tabs and moving around the foo* bar to foo *bar generates all sorts of unnecessary diffs in the commit.

**Comment by DonLakeFlyer** [comment]
> I don't but it would be really nice to get everything standardized because with so many different contributors things have gotten to be a mess so I wanted to do it right and clean when I work on things.

Ok, all good then. I'll change to be closer to what most people like.

**Review by DonLakeFlyer — APPROVED** [review]
Are you going to pull out the old AirMap stuff in separate pull?

**Comment by HTRamsey** [comment]
> Are you going to pull out the old AirMap stuff in separate pull?

That or convert it to Copernicus if I can. Not sure why some stuff was converted to Copernicus but not everything.

**Pull request merged**
