### PR TITLE
convert SDL_GameControllerDB to submodule

### PR DESCRIPTION
**Pull request by holden-zenith**
This will keep joystick definitions up to date

### CODE REVIEW

**Comment by patrickelectric** [comment]
@holden-zenith please rebase over master.

**Comment by holden-zenith** [comment]
@patrickelectric

**Comment by mrpollo** [comment]
@holden-zenith i want to merge this ASAP can you help rebase one last time?

**Comment by patrickelectric** [comment]
Please rebase using git rebase over git merge.

**Pull request closed without merging**
