### PR TITLE
Log replay: Support changing speed of playback

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
* Removed support for .bin playback
* Related to #5730

Screen Shot 2019-08-15 at 2 54 21 PM

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Still a long way to go. But getting better.

**Comment by Antiheavy** [comment]
I'd like to test this.  Where did telemetry file replay move to?  I can't find it in the daily builds....

**Comment by DonLakeFlyer** [comment]
Turn it on from Settings/General

**Comment by Antiheavy** [comment]
> Turn it on from Settings/General

found it thanks!  since this is merged I'll post new issues for anything I find (I found some!)

**Pull request merged**
