### PR TITLE
Vehicle: Add Change Heading

### PR DESCRIPTION
**Pull request by HTRamsey**
Adds ability to change heading towards location on map, currently only for ardupilot (sub/copter)
image

### CODE REVIEW

**Comment by HTRamsey** [comment]
@DonLakeFlyer What's the best way to get this to only work for copter & sub on ardupilot?

**Comment by DonLakeFlyer** [comment]
If you look at firmware plugin you'll see capability bits. Add a new one for change heading. ArduPilot sets it, PX4 does not. The add a new virtual for the change heading implementation. Plumb that through to Vehicle. Plumb through an changedHeading supported through vehicle as well. Look at how ROI mode does this for an example. Replicate that.

**Comment by DonLakeFlyer** [comment]
Can you make this work for both ArduPilot and PX4? Mavlink command for both are here:
https://github.com/DonLakeFlyer/UAV-RT-TagTracker/blob/master/custom/src/CustomPlugin.cc#L657

Plumb difference through FirmwarePlugin and then you should need check for supported?

**Comment by HTRamsey** [comment]
I just realized it isn't added to PX4FirmwarePlugin::isCapable

**Comment by DonLakeFlyer** [comment]
> Also not sure if all vehicle's on px4 should be capable or not.

I would do the same copter/rover only thing. I've only used this myself on PX4 for multi rotor.

**Review by DonLakeFlyer — APPROVED** [review]
I tested this on PX4 SITL and it works

**Pull request merged**
