### PR TITLE
Vehicle: Remove centi-degrees conversion in MOUNT_CONTROL

### PR DESCRIPTION
**Pull request by nexton-winjeel**
Fixes: #11215

### CODE REVIEW

**Comment by rmackay9** [comment]
Thanks very much for this!

The incorrect use of centi-degrees was fixed in ArduPilot more than 18 months ago.  Thanks!

**Comment by nexton-winjeel** [comment]
@rmackay9: Can you confirm what version of ArduPilot this was fixed in?

@DonLakeFlyer: Are you happy with this fix as-is, or do you want to incorporate a version check so that it can use the legacy behaviour for old versions of ArduPilot?

**Comment by DonLakeFlyer** [comment]
Thanks for the change. It's going to need a version check for back-compat.

**Comment by rmackay9** [comment]
Hi @nexton-winjeel,

The ArduPilot fix was released with 4.3.0 which went out on 31-Oct-2022.  Since then we've also release 4.4 and we're getting close to releasing 4.5.  I still occasionally hear of users back on 4.2 and earlier but not often.  Most users are on 4.4 while companies tend to lag a bit but even most of them are on 4.3 or 4.4.

**Comment by DonLakeFlyer** [comment]
That's pretty far back then. I think it's fine without a version check then.

**Comment by rmackay9** [comment]
Thanks so much!

**Pull request merged**
