### PR TITLE
Topomap of Svalbard

### PR DESCRIPTION
**Pull request by AndKe**
Added another map by Statkart - with topographic maps of Svalbard.

### CODE REVIEW

**Comment by booo** [comment]
Could you please add a few lines of documentation to your commit message or code, e.g. what kind of map it is, who operates the map and is it free for public use.

Out of curiosity what do you do with UAVs in Svalbard? :cold_face: 

Thanks for your contribution.

**Comment by AndKe** [comment]
@booo 
This map provides topographic information for Svalbard.
We have been flying fixed wing to map how ice moves.
the past years, I've flown Multicopter (X8) , MTOW 50kg , AUW25kg with wideband radar to map snow layers, glacier cracks, and now (in a week) polar bear dens.
So it would be very helpful if my PR's got merged :) 
My other PR is about rangefinder-monitoring - which is useful where terrain height is .. unpredictable due to snow.
Ardupilot has been to the north pole with us as well, so Svalbard is not that far north :)

**Comment by booo** [comment]
Could you add the bits of information about the map to your commit message so they don't get lost? I would much appreciate that.

Unfortunately I only have permission to close tickets :/

I would like to contact you about your activities if that is fine with you. Our association has a request for similar activities in Alaska.

**Comment by booo** [comment]
Apart from my remark the change looks good to me!

**Comment by AndKe** [comment]
@booo  I think I fixed the comment.
Are you on the ArduPilot Discord server? my nickname is  "AndKe" - or - feel free to email me if you have/see my email already.

**Comment by booo** [comment]
I don't understand why we hard code so much configuration information here. Maybe it is nice to change that in the future and add a configuration somewhere editable by the user.

**Comment by AndKe** [comment]
@booo  Indeed, especially when MAVProxy has this super-clean way of adding maps - one line, done.  In comparsion: QGC takes 20lines across three files to achive the same.

Penultimately, we would love to see an option to specify different ESPG (projection) too.

**Comment by booo** [comment]
> @booo Indeed, especially when MAVProxy has this super-clean way of adding maps - one line, done. In comparison: QGC takes 20 lines across three files to achieve the same.
> 
> Penultimately, we would love to see an option to specify different ESPG (projection) too.

Could you add a feature request to the bug tracker for that? Would be great. PR is welcome as well :)

**Comment by AndKe** [comment]
The feature request I can do - clean up and add alternative projections is way beyond my skill level.

**Pull request merged**
