### PR TITLE
Add StreamingSource Fact

### PR DESCRIPTION
**Pull request by ricardotk**
Since this is a configuration option, it will become clearer this way.

### CODE REVIEW

**Comment by dogmaphobic** [comment]
Don't merge this yet. It removes the UVC video option. Now you only have UDP and RTSP. UVC needs to be added back in.

**Comment by dogmaphobic** [comment]
Also, I was under the impression *Facts* corresponded to parameters originating from the flight controller. Is it being used arbitrarily (I don't see an issue with it per se)? Or is it truly expected for the flight controller to provide this *Fact*?

**Comment by ricardotk** [comment]
> Don't merge this yet. It removes the UVC video option. Now you only have UDP and RTSP. UVC needs to be added back in.

Mmm, in branch master only two options appear for me: UDP and RTSP. But anyway, should I add UVC as a Fact here:?

**Comment by ricardotk** [comment]
> Also, I was under the impression Facts corresponded to parameters originating from the flight controller. Is it being used arbitrarily (I don't see an issue with it per se)? Or is it truly expected for the flight controller to provide this Fact?

Its being used arbitrarily, its not provided by a flight controller

**Comment by dogmaphobic** [comment]
> Mmm, in branch master only two options appear for me: UDP and RTSP. But anyway, should I add UVC as a Fact here:?

Yes, it only shows on the list when you have an UVC device connected. There is no *Fact*. It's a hardware query. This is where the ComboBox *model* is built:

https://github.com/mavlink/qgroundcontrol/blob/master/src/FlightDisplay/VideoManager.cc#L179

You added a new *model* (from your *Facts*) but did nothing about the existing code.

**Comment by dogmaphobic** [comment]
Basically there are two very different types of video source. One is digitally streamed from the vehicle and we use GStreamer to handle it. The other is some video capture device physically connected to the device QGC is running on. Usually an analog to digital video converter that takes an analog video input (coming from an analog video receiver) and piping that video through USB.

**Comment by ricardotk** [comment]
Mmm now that you showed me how the UVC part is implemented, I not sure if this patch is useful anymore. I would have to create a list containing the Facts and the cameras from UVC right?

**Comment by dogmaphobic** [comment]
It's not just that. How would you enter a manually configured video source (UDP or RTSP), which has no parameter coming from anywhere? As it is, you can only pick a video source for which a stream definition was provided through a parameter. That implies it only supports vehicles/systems which advertise their video capabilities in a standard fashion.

**Pull request closed without merging**
