### PR TITLE
Revert usage Qt5Compat module for QML ColorOverlay

### PR DESCRIPTION
**Pull request by s-lisovenko**
https://github.com/mavlink/qgroundcontrol/pull/11308

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@s-lisovenko This is missing a PostLinkInstaller change. Look through this to see the original change to make sure you have everything: https://github.com/mavlink/qgroundcontrol/pull/11259

**Comment by DonLakeFlyer** [comment]
Correct

**Comment by s-lisovenko** [comment]
I reverted it too

**Comment by DonLakeFlyer** [comment]
Thanks so much

**Pull request merged**
