### PR TITLE
[ObstacleDistanceOverlay] Fix 90 degree offset 

### PR DESCRIPTION
**Pull request by dakejahl**
Fixes issue where obstacle distances are displayed with a +90 degree offset. This is due to an error in the coordinate system math along with an error in calculating the degrees for the current distance index. The yaw angle theta is measured CW from North and therefore `r * cos(theta)` is negative Y axis and `r * sin(theta)` is positive X.

**Qt docs**
> The x values increase to the right and the y values increase downwards.
image

There's more still that needs to be done. The ObstacleDistanceOverlayVideo.qml probably needs this fix. There's also the VehicleObjectAvoidance class which seems to be entirely unused other than the `distances` array. This feature is currently broken in PX4 and I don't think anyone has used it in years. I want to resurrect the feature and make it all work again.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dakejahl Any updates on this. It's still marked Draft.

**Comment by dakejahl** [comment]
No not yet, I haven't come back to working on this. The first step is to get the feature working again in PX4.

**Comment by DonLakeFlyer** [comment]
@dakejahl Updates?

**Comment by dakejahl** [comment]
@Claudio-Chies has done a ton of work lately with avoidance in PX4 so he might know better than I

**Comment by Claudio-Chies** [comment]
@dakejahl wow awesome! This was on my to-do, didn't know you already solved it! Thanks a lot!
image
looks great, only the video overlay is still offset, as you mentioned above.

**Comment by Claudio-Chies** [comment]
image
Added a Fix for the Video Overlay, basically the problem is that the degrees are in FRD frame starting from Front rotating around Down, but plotting is done in XY Starting at the X line, clockwise, 
so I'm subtracting Pi/2 to fix the issue.

**Review by DonLakeFlyer — APPROVED** [review]

**Pull request merged**
