### PR TITLE
Qt5.8 [WIP - do not merge]

### PR DESCRIPTION
**Pull request by DonLakeFlyer**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dagar Is there something else I need to update in order to get AppImage working with 5.8?

**Comment by DonLakeFlyer** [comment]
With this passing we are ready to pull the trigger on 5.8

**Comment by NaterGator** [comment]
@DonLakeFlyer I think you're missing one or two things.

**Comment by DonLakeFlyer** [comment]
2013. Guess we should move to 15.

**Comment by DonLakeFlyer** [comment]
I also forgot to move the appveyor window qt image.

**Comment by NaterGator** [comment]
We'll be blocked on https://github.com/appveyor/ci/issues/1279 but I have the remaining bits worked out [here](https://github.com/NaterGator/qgroundcontrol/commit/869b8f3235c0ee834b5d3d3f2dd74eb5ade6020b).

**Comment by DonLakeFlyer** [comment]
Awesome Nate. If you could get the Windows side of this straightened out that would be awesome. Just take my changes here and stuff into your side.

**Comment by NaterGator** [comment]
See #4598

**Pull request closed without merging**
