### PR TITLE
Add GStreamer to OS X builds

### PR DESCRIPTION
**Pull request by DonLakeFlyer**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dagar Any ideas on how to deal with this log length problem?

**Comment by dagar** [comment]
I think there's just too much text. We could try `make --silent`.

**Comment by dagar** [comment]
Try rebasing on master https://github.com/mavlink/qgroundcontrol/commit/73d477cf0b7f072c5c94ee146e81ba9e0d17650e

**Comment by DonLakeFlyer** [comment]
If travis sees not output for 10 minutes it will terminate the build. Compiles take more than that.

**Comment by dagar** [comment]
Just saw.
Reverted.

**Comment by DonLakeFlyer** [comment]
It's quite the nightmare of crappy defaults.

**Comment by dagar** [comment]
Add `CONFIG += silent` to just the OSX build for now if you want to get passed this. It doesn't work on the windows build at the moment. https://github.com/mavlink/qgroundcontrol/pull/3145

**Comment by DonLakeFlyer** [comment]
Ok, got it

**Pull request closed without merging**
