### PR TITLE
Adding TTS to iOS

### PR DESCRIPTION
**Pull request by dogmaphobic**
In addition:
* Fixing code exclusion issues where Mac OS and iOS were both included when they shouldn't.
* Hardcoding warning text color on Fly View as that view does not respect the current palette.

### CODE REVIEW

**Comment by dogmaphobic** [comment]
Hmm...
Twice in a roll makes me doubt it as being a fluke but my local unittest (with QT_FATAL_WARNINGS=1) runs fine.

```
********* Finished testing of SetupViewTest *********
ALL TESTS PASSED
After app delete
Debugging has finished
```

**Comment by dogmaphobic** [comment]
@DonLakeFlyer Any ideas on what to do here? I can't reproduce this locally.

```
QWARN  : FactSystemTestPX4::parameter_default_component_id_test() PX4ParameterMetaDataLog: Invalid decimals value, name: "ctl_start_rate"  type: 5  decimals: ""  error: invalid number
/Users/travis/build.sh: line 41: 11831 Abort trap: 6           ./debug/qgroundcontrol.app/Contents/MacOS/qgroundcontrol --unittest
The command "if [[ "${TRAVIS_OS_NAME}" = "osx" && "${CONFIG}" = "debug" ]]; then ./debug/qgroundcontrol.app/Contents/MacOS/qgroundcontrol --unittest; fi" exited with 134.
Done. Your build exited with 1.
```

**Comment by DonLakeFlyer** [comment]
The parameter meta data is wrong. Likely that the version compiled into QGC has the problem. But when you run you're using the meta data from a previous flash. Clear you configure folder of the cached meta data and you'll likely see the same problem

**Comment by LorenzMeier** [comment]
I stuffed up. PR with fixed file coming.

**Pull request merged**
