### PR TITLE
Fix in serial communication on Android

### PR DESCRIPTION
**Pull request by birchera**
Fixes https://github.com/mavlink/qgroundcontrol/issues/4328.

**Proposed changes**:
* Replaces the QGCRingBuffer class with the QRingBuffer class in the serial communication module.
* This solves a bug in memory access when reading (could not figure out actual bug though).

@DonLakeFlyer can you have a look at it?

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Does this fix the USB crash?

**Comment by birchera** [comment]
Yes, it does for us.

**Comment by DonLakeFlyer** [comment]
Sorry I'm an idiot. Missed it.

**Comment by DonLakeFlyer** [comment]
This is more @dogmaphobic  since he brought across the android serial stuff.

**Comment by DonLakeFlyer** [comment]
Once this is ok'ed this needs to go into Stable_V3.2 as well.

**Comment by dogmaphobic** [comment]
The change seems logical. I don't remember where this came from originally. Serial connection under Android has always been sort of a bastard child any way. I really don't like that Java spaghetti mixed in. At some point that whole thing should be replaced with real code.

**Comment by DonLakeFlyer** [comment]
Ok, great. Big thanks @birchera for this fix. I'm going to use this to get a Stable_V3.2 pull as well before I merge this in.

**Pull request merged**
