### PR TITLE
PID Tuning: Make QtCharts usage desktop only

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Qt Charts doesn't work with our mobile code at the moment

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dogmaphobic The jenkins servers need to have Qt Charts installed for Linux and OSX builds now.

**Comment by dogmaphobic** [comment]
I can handle my macOS Jenkins slave. @dagar the Linux slave will need that too.

**Comment by dogmaphobic** [comment]
By the way, did you look through the https://github.com/mavlink/qgroundcontrol/tree/switchToQQuickView/src branch, which basically had the same objective?

**Comment by DonLakeFlyer** [comment]
> did you look through the...

I didn't. But I basically did the same thing for testing. Then decided to leave it out for now. I remember mobile being crazy flaky till we switched to full Qml. So, paranoid about taking a eve half step back towards that.

**Pull request merged**
