### PR TITLE
[WIP - do not commit] Mixer tuning - mavlink download and gui

### PR DESCRIPTION
**Pull request by crashmatt**
**DESCRIPTION**
QGC support for mixer parameter tuning through mavlink.

[To work with this PX4Firmware PR](https://github.com/PX4/Firmware/pull/6960)
[Old PX4Firmware PR](https://github.com/PX4/Firmware/pull/6357)

[Document describing the QGroundControl mixers implementation](https://docs.google.com/document/d/1348HNq4QUZC5x5s4pNYN3u9G_GdYblUu5YnWctfG-QY/edit?usp=sharing)
NEEDS UPDATE FOR NEW SYSTEM

[Dependent on this MAVLink PR](https://github.com/mavlink/mavlink/pull/694)

**COMPLETE**

- Mixer Manager downloads all parameters on opening the mixer tuning page
- A basic gui shows a list of parameters and allows selecting a parameter for editing
- Read only parameters will not edit
- Basic documentation done

**TODO**
**- PULL MAVLINK PR INTO UPSTREAM** 
- Review how this will work with different APs
- Download mixers is not reliable.  Need retries at all points.
- Some fault reporting
- Tidyup sketchy Qt messaging
- Testing??

**PLANNED FOR FUTURE RELEASE**
- UI polishing

**UI Screenshots**

A Multirotor example
image

A fixed wing example
image

**Sample screenshots**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Ok, so what is not working and how is it not working?

**Comment by crashmatt** [comment]
I can't get the table to show at all.  To reduce problems from elsewhere it now uses some mocked up [Fact data created in the controller constructor.](https://github.com/crashmatt/qgroundcontrol/blob/mixer/src/AutoPilotPlugins/Common/MixersComponentController.cc#L31)

I suspect the problem is that I am trying to use the QGCListView in a column.  
The list view wants vertical anchors but the column doesn't like that (according to debug)

So I think I need to get rid of column and write it in the style that ParameterEditor.qml is done.

So much guesswork...

**Comment by DonLakeFlyer** [comment]
Paste the debug output here that you are getting

**Comment by crashmatt** [comment]
I fixed the qml debug warnings by removing the vertical anchors. Is this a problem since the list has dynamic size and column doesn't know?

**Comment by crashmatt** [comment]
I cutdown the code to its absolute simplest for a list view and it doesn't work. This code was taken from this site:
http://doc.qt.io/qt-5/qtquick-modelviewsdata-modelview.html

I am 100% out of ideas now.  I am starting to waste days on this.  

`// Mixer Tuning setup page
SetupPage {
    id:             tuningPage
    pageComponent:  tuningPageComponent

    ListModel {
        id: fruitModel

        ListElement {
            name: "Apple"
            cost: 2.45
        }
        ListElement {
            name: "Orange"
            cost: 3.25
        }
        ListElement {
            name: "Banana"
            cost: 1.95
        }
    }

    Component {
        id: tuningPageComponent

        // mixersList
        ListView {
//            id:             mixerListView
//            clip:           true
            anchors.fill:   parent
//            orientation:    ListView.Vertical
            model:          fruitModel
            delegate: Row {
                Text { text: "Fruit: " + name }
                Text { text: "Cost: $" + cost }
            }
        } //ListView
    } // Component
} // SetupView`

**Comment by crashmatt** [comment]
I can't find any guidance on lists in components on the interweb.  Have come to the conclusion that the setup component wont do the job. 

Parameters and a few others use QGCView instead of setup component.  I know that should work with QGCList.  Mixers configuration is part of the airframe setup.  This is doing mixers tuning so it doesn't have to be a setup item.

**Comment by DonLakeFlyer** [comment]
Just a sec...

**Comment by DonLakeFlyer** [comment]
screen shot 2017-03-09 at 9 57 02 am

```
/****************************************************************************
 *
 *   (c) 2009-2016 QGROUNDCONTROL PROJECT <http://www.qgroundcontrol.org>
 *
 * QGroundControl is licensed according to the terms in the file
 * COPYING.md in the root of the source code directory.
 *
 ****************************************************************************/

import QtQuick              2.3
import QtQuick.Controls     1.2
import QtQuick.Layouts      1.2

import QGroundControl.FactSystem    1.0
import QGroundControl.FactControls  1.0
import QGroundControl.Palette       1.0
import QGroundControl.Controls      1.0
import QGroundControl.ScreenTools   1.0

// Mixer Tuning setup page
SetupPage {
    id:             tuningPage
    pageComponent:  tuningPageComponent

    Component {
        id: tuningPageComponent

        Item {
            width:      availableWidth
            height:     availableHeight

            FactPanelController { id: controller; factPanel: tuningPage.viewPanel }

            QGCPalette { id: qgcPal; colorGroupEnabled: true }

            ListModel {
                id: fruitModel

                ListElement {
                    name: "Apple"
                    cost: 2.45
                }
                ListElement {
                    name: "Orange"
                    cost: 3.25
                }
                ListElement {
                    name: "Banana"
                    cost: 1.95
                }
            }

            RowLayout {
                anchors.fill: parent

                Rectangle {
                    anchors.top:        parent.top
                    anchors.bottom:     parent.bottom
                    color:              qgcPal.windowShade
                    Layout.fillWidth:   true
                }

                /// Parameter list
                QGCListView {
                    id:                 mixerListView
                    anchors.top:        parent.top
                    anchors.bottom:     parent.bottom
                    width:              100
                    orientation:        ListView.Vertical
                    model:              fruitModel
                    cacheBuffer:        height > 0 ? height * 2 : 0
                    clip:               true

                    delegate: Rectangle {
                        anchors.left:   parent.left
                        anchors.right:  parent.right
                        height:         30
                        color:          "red"
                        border.color:   "white"

                        Row {
                            QGCLabel {
                                text:   name
                            }

                            QGCLabel {
                                text:   cost
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by crashmatt** [comment]
What did I get wrong?  color? layout? looking at the wrong side of the
screen?

**Comment by DonLakeFlyer** [comment]
Don't know since I don't know the actual code you were trying to run. In the original code in this pull the sizing of the list view was wrong since you had a bad anchor which I pointed out. I didn't try to run it or fully debug it since I could with your mavlink changes. The merge got wierd. So I just pulled you qml into a clean build.

**Comment by crashmatt** [comment]
Thanks Don.  

Just completed a successful rewrite to change it all from a component to a QGCView.  Entertaining in its own way but now ultimately pointless.  Will stash that in a branch and forget about it.

If I can get all of the right data on the screen then I can hand over to you for implementing something nicer.

**Comment by crashmatt** [comment]
@DonLakeFlyer Is there a way to make qml lists with multiple dimensions?
Mixers have submixers.  Mixers and submixers have connections.  The number of table rows for a mixer depends on all of the information it contains.
An alternative might be a new MixerFact type that inherits Fact and adds QObjectList for its submixers and connections.  This would be particularly nice since it would remove the QMap based structure that I have now together with the translations between these structures.  

Is it possible for qml to access a QObjectList within a Fact?

The alternative is a gui that looks more like a tree view.  You only get to see submixers or connections once the mixer is selected.  This doesn't give the option of a nice rich feeling gui.

**Comment by DonLakeFlyer** [comment]
Facts would only be the leaf nodes of your tree. The trunk and branches of the tree would just be regular QObjects. For creating list of things within a controller you have two options:
1) Use a QVariantList which contains QObjects. This is appropriate if whenever the list changes you can blow away the entire UI for the list and re-create it.
2) Use q QmlObjectListModel. This is appropriate if you need to incrementally update a big list by add/removing individual elements.

**Comment by crashmatt** [comment]
@DonLakeFlyer Next little problem - Nested ListView with QVariantList.  qml reports:

> qrc:/qml/MixersComponent.qml:153:53: Unable to assign [undefined] to QString qrc:/qml/MixersComponent.qml: 153

Data strucuture is:
QObjectList[]->QObject*->QVariantLis[].QVariant->QObject*->Fact

The first part to the root mixer works:

Taking AirframeComponentController as the example of how to wire up 

I did 
Q_DECLARE_METATYPE(Mixer*)
and 
qmlRegisterType<Mixer>                          ("QGroundControl.Controllers",          1, 0, "Mixer");

**Comment by DonLakeFlyer** [comment]
Haven't been tracking this. @crashmatt Do you have questions?

**Comment by crashmatt** [comment]
@DonLakeFlyer It's going quite well.  The right data is in structures that should work with qml.  I am maintaining the todo list together with the PR description at the top.

The next step is to get modified values from the gui back to the AP through mavlink.  For that I need a working gui.  I really need someone more experienced with qml to take over. 

To make it possible for someone else to write the qml I need to document what I have done.  I also need to fix the mavlink merge problem.

I have come to the conclusion that there will be too many differences between AP implementations.  It will need to move from common to being completely or partially AP specific.

**Comment by DonLakeFlyer** [comment]
The differences between firmwares shows up in the UI. Or just in the backend?

**Comment by crashmatt** [comment]
@DonLakeFlyer I predict that there will be differences in both but it might be minor.
The way that data is presented will depend on the style of the mixer implemented.  The mixer will be different for different PX4 mixer implementations, not just a difference between PX4 and ardupilot.

The data source for the mixer will change depending on the mixer implementation.  I am attempting to make the backend flexible for this.  It may be possible for the backend to auto detect and adapt to different data sources.  This capability discovery could be made part of the mixer data downloading.

The way that data is delivered to the gui should stay reasonably consistent but I have not yet seen all of the possibilities.  It may be that some implementations require a simple script editor only.

**Comment by crashmatt** [comment]
@DonLakeFlyer  

[Document describing the QGroundControl mixers implementation](https://docs.google.com/document/d/1348HNq4QUZC5x5s4pNYN3u9G_GdYblUu5YnWctfG-QY/edit?usp=sharing)

What else is needed to get help with the qml front end?

Merge conflict fixed but travis is rightfully complaining about my lazy code causing signed-unsigned errors.

**Comment by crashmatt** [comment]
Closed until mavlink update merge is solved. May re-open as a different PR.

**Pull request closed without merging**
