### PR TITLE
MAVLink: Add Signing

### LINKED ISSUE #8958: Add Support for MAVLink2 Message Signing
Tell us a bit about the feature:
- What problem does it solve?
Integrity checks and authentication of GCS and Vehicle prevent hijacking of a vehicle via MAVLink telemetry radio.

- What does it do?
Prevent rogue ground stations from forcing a vehicle to land or upload malicious missions etc.

- What flight stacks must it work with? (All, PX4, ArduPilot)
All

- Relevant vehicle types? (All, multirotor, fixed-wing, VTOL, submarine, etc.)
All

- Are there other systems that have this feature?
MAVLink2 contains this feature (https://mavlink.io/en/guide/message_signing.html) and Mission Planner seems to support it.

- What communication/integration standards does the feature rely on (e.g. MAVLink commands etc.)
MAVLink2

### PR DESCRIPTION
**Pull request by HTRamsey**
Todo: Probably should disable the enable switch until a valid key is entered? 
Closes #8958

image

image

### CODE REVIEW

**Comment by HTRamsey** [comment]
@DonLakeFlyer Should I go ahead and add a way to control this in the UI or is that something you want to do later?

**Comment by DonLakeFlyer** [comment]
> Should I go ahead and add a way to control this in the UI

Sure, go ahead. Just make it functional. And then if needed I can clean up visuals later so you don't need to deal with that stuff.

**Comment by HTRamsey** [comment]
@DonLakeFlyer Should this be enabled globally or per comm link?

**Comment by DonLakeFlyer** [comment]
So forwarding is disabled when you are using signing. Seems like there should also be some indicator in the forward setting to indicate that it won't work.

**Comment by HTRamsey** [comment]
I believe it's just the setup_signing message that isn't supposed to be forwarded, as per the documentation. I think the key could already be preconfigured on the forwarded device though, so signing should still work. I'll have to double check

**Review by DonLakeFlyer — APPROVED** [review]

**Pull request merged**
