### PR TITLE
Cut over 100% to new Map/Mission code

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
- Delete all old map/mission code

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@LorenzMeier All ready to go, if you're ok with current feature set

**Comment by LorenzMeier** [comment]
There are build errors, but with these resolved, sure!

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Huge thanks for all your work on the Qml Map that got us to this point.

**Comment by LorenzMeier** [comment]
Wohoo! Thanks everybody!

**Comment by dagar** [comment]
As a small bonus this also makes the appveyor build faster.

**Pull request merged**
