### PR TITLE
use CMD_MISSION_START to start mission and select waypoint

### PR DESCRIPTION
**Pull request by dagar**
This should be fine for startMission (in the PX4 plugin), but I'm not sure about setCurrentMissionSequence.

### CODE REVIEW

**Comment by Antiheavy** [comment]
We are seeing some issues where if a waypoint was manually selected on the flight immediately prior to the current one, Start Mission will jump to that waypoint instead of the Takeoff waypoint.  I wonder if this change would be one way to fix that.

**Comment by Antiheavy** [comment]
> We are seeing some issues where if a waypoint was manually selected on the flight immediately prior to the current one, Start Mission will jump to that waypoint instead of the Takeoff waypoint. I wonder if this change would be one way to fix that.

nevermind, it turns out using this command when trying to select another waypoint other than the takeoff waypoint when on the ground causes the system to try to takeoff to that waypoint, which is problematic! 

However, this might still be valid to be used by the "Start Mission" slider as a method to guarantee that the correct takeoff waypoint is selected when doing a Mission takeoff.

**Comment by dagar** [comment]
We can add an additional check on the firmware side for FW that prevents arming into a mission that's not on a takeoff waypoint when landed.

**Comment by DonLakeFlyer** [comment]
It's gonna take me a while to have time to think about this. Not back home till next Wed.

**Comment by DonLakeFlyer** [comment]
Is there anything with switching to this command which makes it PX4 version specific. Or do you old versions of PX4 support this command as well?

**Comment by dagar** [comment]
Not really, it's been for well over a year.

It's definitely better for mission start, but maybe for active waypoint select we should add something to prevent it from being used when landed.

**Comment by dagar** [comment]
I've split out the "Start Mission" portion here. https://github.com/mavlink/qgroundcontrol/pull/5741

**Pull request closed without merging**
