### PR TITLE
Add video popup

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by dogmaphobic** [comment]
This looks fine for desktop. Have you tried on mobile? I don't think this concept would work on mobile devices. You might need to have two separate implementations (QML files): the old one for mobile and the new one for desktop.

**Comment by patrickelectric** [comment]
Remove popup functionality in mobile application.

**Comment by DonLakeFlyer** [comment]
Up to Gus to sign off and merge. I'm fine with it.

**Comment by dogmaphobic** [comment]
Looks fine as is. Thanks!

**Pull request merged**
