### PR TITLE
Fix FactPanelController not exposing fixedwing property (for safety p…

### PR DESCRIPTION
**Pull request by NaterGator**
…anel icon)

@dagar can you test and confirm this fixes it? If so I'll merge

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
This is very odd exposure of a single value. Any explanation for it?

**Comment by NaterGator** [comment]
https://github.com/mavlink/qgroundcontrol/blob/master/src/AutoPilotPlugins/PX4/SafetyComponent.qml#L367 and associated are broken. Similarly done here: https://github.com/mavlink/qgroundcontrol/blob/b8d25964fd74f78713ff795547f12f8289890829/src/AutoPilotPlugins/PX4/SensorsComponentController.h#L47

**Comment by dagar** [comment]
@DonLakeFlyer with a pixhawk configured as a fixed wing the PX4 safety screen is showing multicopter icons and settings.

screenshot from 2016-05-23 13 03 45

**Comment by NaterGator** [comment]
It is probably an error to specify CONSTANT in the Q_PROPERTY decl per [exposing properties](http://doc.qt.io/qt-5/qtqml-cppintegration-exposecppattributes.html#exposing-properties)

**Comment by DonLakeFlyer** [comment]
```
bool SensorsComponentController::fixedWing(void)
{
    switch (_vehicle->vehicleType()) {
        case MAV_TYPE_FIXED_WING:
        case MAV_TYPE_VTOL_DUOROTOR:
        case MAV_TYPE_VTOL_QUADROTOR:
        case MAV_TYPE_VTOL_TILTROTOR:
        case MAV_TYPE_VTOL_RESERVED2:
        case MAV_TYPE_VTOL_RESERVED3:
        case MAV_TYPE_VTOL_RESERVED4:
        case MAV_TYPE_VTOL_RESERVED5:
            return true;
        default:
            return false;
    }
}
```

SensorComponentController shouldn't have it's own version of this code. It should just:
```
bool SensorsComponentController::fixedWing(void)
{
    return _vehicle->fixedWing();
}
```

This code may be old, prior to Vehicle::fixedWing being available.

I think the CONSTANT should be ok, since it works fine on Vehicle. At least it used to be working ok to not show airspeed cal for example on multirotor. Look for other places that use Vehicle::fixedWing to see if they are broken as well.

**Comment by NaterGator** [comment]
Constant is not ok and should not be on vehicle either since it is derived from a parameter which takes time to sync. Agreed SensorController should not duplicate the functionality offered by Vehicle.

**Comment by DonLakeFlyer** [comment]
Vehicle type comes in from the Vehicle constructor not a parameter. So it is always correct and fixed.

**Comment by NaterGator** [comment]
Fair. Then constant is only not okay on controllers that resolve the type from a member vehicle pointer that can change at any point.

**Comment by DonLakeFlyer** [comment]
> Then constant is only not okay on controllers that resolve the type from a member vehicle pointer that can change at any point.

It's ok on SensorsComponentController. FactPanelController's never have the vehicle change out from under them. That's not how they work. Vehicle is set in the constructor of a FactPanelController. Something else is wrong here. Did you step through to make sure the vehicle type was coming through correctly from the firmware?

**Comment by DonLakeFlyer** [comment]
Is there an Issue in for the problem so I can try to repro?

**Comment by dagar** [comment]
@DonLakeFlyer 
Just connect PX4 fixed wing and look at the safety screen. You'll see the multicopter icons and the MC only setting landing velocity.

**Comment by DonLakeFlyer** [comment]
Fixed: https://github.com/mavlink/qgroundcontrol/pull/3392

**Pull request closed without merging**
