### PR TITLE
Ready To Fly support based on MAV_SYS_STATUS_PREARM_CHECK

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
* Reworked toolbar to provide a main status text area
* New Ready To Fly indicator based on `SYS_STATUS` and `MAV_SYS_STATUS_PREARM_CHECK`
* If `MAV_SYS_STATUS_PREARM_CHECK` is not available ready to fly is based solely on all sensors healthy and all vehicle components reporting setup complete.

Disconnected
Screen Shot 2020-08-06 at 7 14 45 PM

Ready To Fly
Screen Shot 2020-08-06 at 7 08 20 PM

You can click on main status text to get health indicators
Screen Shot 2020-08-06 at 7 08 13 PM

Flying
Screen Shot 2020-08-06 at 7 22 52 PM

Comm lost
Screen Shot 2020-08-06 at 7 08 51 PM

Not Ready to fly
Screen Shot 2020-08-06 at 7 21 23 PM

Not ready to fly due to vehicle setup not complete
Screen Shot 2020-08-06 at 7 21 35 PM

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dagar Hence my issues on SYS_STATUS. QGC needs `MAV_SYS_STATUS_PREARM_CHECK` to be correct at all times based on all things which prevent a vehicle from flying.

**Comment by DonLakeFlyer** [comment]
There is something that will take follow on WIP type changes. But as it currently stands it is pretty usable.

**Comment by DonLakeFlyer** [comment]
In looking at the screen shots I posted I already don't like some stuff! Posted another commit to make all good status green when flying and remove a useless separator:
Screen Shot 2020-08-06 at 7 39 16 PM

**Comment by Antiheavy** [comment]
This is heading in a great direction!

**Pull request merged**
