### PR TITLE
Adjust to new parameters in Copter 3.6

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Includes support for battery 2 setup. Related to #6503. This pull does not yet fix the Tuning page problems with 3.6.

screen shot 2018-05-25 at 3 26 56 pm
screen shot 2018-05-25 at 3 27 01 pm

@AndKe, @wickedshell Can you guys give this a try. @AndKe If you can build yourself, do a quick sanity check then I'll merge and then Michael can try a daily.

### CODE REVIEW

**Comment by WickedShell** [comment]
Possibly worth changing "Battery Failsafe Triggers" to "Battery Failsafe", and "Battery low" to "Battery low action" if it fits. Param doc changes discussed on gitter are availble in https://github.com/ArduPilot/ardupilot/pull/8500

**Comment by DonLakeFlyer** [comment]
@WickedShell Yeah, makes sense. I forgot to call out the paremeter name conversions I have:
```
        remapV3_6["BATT_AMP_PERVLT"] = QStringLiteral("BATT_AMP_PERVOL");
        remapV3_6["BATT2_AMP_PERVLT"] = QStringLiteral("BATT2_AMP_PERVOL");
        remapV3_6["BATT_LOW_MAH"] = QStringLiteral("FS_BATT_MAH");
        remapV3_6["BATT_LOW_VOLT"] = QStringLiteral("FS_BATT_VOLTAGE");
        remapV3_6["BATT_FS_LOW_ACT"] = QStringLiteral("FS_BATT_ENABLE");
```

Did I miss any other battery related ones?

**Comment by WickedShell** [comment]
`BATT_LOW_TYPE` became `BATT_FS_VOLTSRC` (as well as getting a `BATT2_FS_VOLTSRC`). I'm not sure if you were offering a UI box for choosing that before though. Otherwise that looks like the set of changes.

**Comment by DonLakeFlyer** [comment]
Thanks @WickedShell. I don't think I use those yet. But can't hurt to put them in the remapping tables now.

**Comment by AndKe** [comment]
So I am 5 hours too late, maybe you already know it, but there are two config views that still complain:

Tuning:
screenshot from 2018-05-26 23-34-45


Camera:
screenshot from 2018-05-26 23-35-05

**Pull request merged**
