### PR TITLE
modify android build repo

### PR DESCRIPTION
**Pull request by jinchengde**
modify the build repo to http://repo1.maven.org/maven2

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dogmaphobic ?

**Comment by dogmaphobic** [comment]
I have no idea what that means. I can only assume he knows what he's doing...

**Comment by DonLakeFlyer** [comment]
@jinchengde Explanation please?

**Comment by jinchengde** [comment]
@DonLakeFlyer 
The Build issue:
A problem occurred configuring root project 'android-build'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:1.1.0.
     Required by:
         :android-build:unspecified
      > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/build/gradle/1.1.0/gradle-1.1.0.pom'.
         > peer not authenticated

I don't know whether is cause the jcenter is blocked in China?
just reference
http://androidmazes.blogspot.com/2015/06/error-solving-time-android-studio-peer.html

**Comment by jinchengde** [comment]
@DonLakeFlyer 
The Build issue:
A problem occurred configuring root project 'android-build'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:1.1.0.
     Required by:
         :android-build:unspecified
      > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/build/gradle/1.1.0/gradle-1.1.0.pom'.
         > peer not authenticated

I don't know whether is cause the jcenter is blocked in China?
just reference
http://androidmazes.blogspot.com/2015/06/error-solving-time-android-studio-peer.html

**Comment by DonLakeFlyer** [comment]
Are you trying to build in android studio?

**Comment by jinchengde** [comment]
No， build in QtCreator

**Comment by jinchengde** [comment]
I don't know anyothers have meet this build problem?

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Would the travis build (which passed) have pulled from this new url on the fly? Which would verify that this change works?

**Comment by dogmaphobic** [comment]
> Would the travis build (which passed) have pulled from this new url on the fly? Which would verify that this change works?

The download only happens the first time you build. If the build is cached, it would have used what it already had. If the build is from scratch each time, then yes, it would have downloaded from the new URL.

**Comment by DonLakeFlyer** [comment]
So travis starts from a new vm each time. So that would seem to indicate this was tested and passed on travis. So it seems like this is an ok change then. I'll merge. Easy to back out if it starts crapping out.

**Pull request merged**
