### PR TITLE
remove old qtlocation files

### PR DESCRIPTION
**Pull request by holden-zenith**
Removes QtLocation files for an older version of Qt.

### CODE REVIEW

**Comment by booo** [comment]
`git grep QtLocationPlugin` find quite a few references to the path you removed. Can you check on that?

And maybe add one or two lines of explanation to your commit message even tough it's quite obvious what we do.

Nice work!

**Comment by holden-zenith** [comment]
All I see are references to the parent directory QtLocationPlugin, instead of the subdirectory qtlocation that I deleted.

**Comment by booo** [comment]
> All I see are references to the parent directory QtLocationPlugin, instead of the subdirectory qtlocation that I deleted.

You are right. Sorry, I got confused by all the directories and subdirectories :)

**Comment by junwoo091400** [comment]
LGTM :thinking:

**Review by patrickelectric — APPROVED** [review]

**Pull request merged**
