### PR TITLE
Trigger camera in instrument panel page

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Sends a MAV_CMD_DO_DIGICAM_CONTROL with param5=1 to trigger camera.

screen shot 2017-02-27 at 7 26 59 pm

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@antiheavy

**Comment by DonLakeFlyer** [comment]
Simple start to camera support

**Comment by tops4u** [comment]
@DonLakeFlyer Hi, can you tell me how to get this Button onto QGC? Installed current Master of QGC and PX4 and like to trigger my Camera over this... Thanks.

**Comment by Antiheavy** [comment]
@tops4u if you click on the area of the screen under the artificial horizon it switching between 4 different "pages".  One of those pages has the Trigger Camera button.

**Comment by tops4u** [comment]
@Antiheavy thanks, I have installed latest Master of QGC yesterday, but I only get 3 "Pages" so the Camera Trigger is missing. Does this need any configuration?

**Comment by Antiheavy** [comment]
Are you using the released version from here:
http://qgroundcontrol.com/downloads/
if so the camera trigger button is not there.

I think you'd need to download a dailybuild version or compile your own version from github to get the camera trigger button to show up.  I don't know if you'd want to use the daily builds for flying though as they are not necessarily tested or considered stable for release.

**Comment by tops4u** [comment]
No I have installed the Package from here: https://s3-us-west-2.amazonaws.com/qgroundcontrol/latest/QGroundControl.dmg which is linked from the Daily Builds Page to the OS X Build. 

Actually it identifies itself as 3.1.3 and I was not able to find any additional Information about the Build Version or Date. Just tried again, and there are only 3 Bullets in this view.

**Comment by tops4u** [comment]
Ok... stupid me. I blindly clicked on the first Link on this page, without reading. It is marked as Stable Builds, and the Dailies are further down. Sorry!

**Comment by DonLakeFlyer** [comment]
What page are you getting that from? That is the wrong link and is not the link which is in here: https://donlakeflyer.gitbooks.io/qgroundcontrol-user-guide/content/download_and_install.html.

On Apr 2, 2017, at 10:40 AM, tops4u <notifications@github.com<mailto:notifications@github.com>> wrote:


No I have installed the Package from here: https://s3-us-west-2.amazonaws.com/qgroundcontrol/latest/QGroundControl.dmg which is linked from the Daily Builds Page to the OS X Build.

Actually it identifies itself as 3.1.3 and I was not able to find any additional Information about the Build Version or Date. Just tried again, and there are only 3 Bullets in this view.

**Comment by tops4u** [comment]
@DonLakeFlyer Noticed... took wrong link as I picked the first link on the Page that opened when I clicked that I want to download the Daily. Maybe this structure is a bit missleading...

**Pull request merged**
