### PR TITLE
Add NTRIP with VRS support

### PR DESCRIPTION
**Pull request by WTPENGUIN**
This pull request is based on earlier NTRIP-enabled pull request(https://github.com/mavlink/qgroundcontrol/pull/9493) from 2021. 

Thanks to @TobinHall  

It's only a draft right now.

This implementation is also quite crude. It may also not make sense to advanced developers.

I added RTK-VRS support to add and test the initial NTRIP functionality.

Enabling the RTK-VRS option sends the current location of the GCS to the corresponding NTRIP server.

After applying the draft, I was tested with a quadcopter equipped with Here3 GPS.

See that log : https://review.px4.io/plot_app?log=913215cc-7c0c-4eec-bfce-8ca0feaa452d

In my opinion, the following features should be implemented more (other opinions are welcome).

- [x] Add VRS Support
- [ ] Add UI
- [ ] Reconnection and Error Handling

Thank you for your comments and interest. (I used a translator because I am not good at English.)

### CODE REVIEW

**Comment by Davidsastresas** [comment]
Thank you. I think it doesn't make sense to review this until it is completely finished ( Adding UI and connecting to the rest of QGC, if I am not mistaken right now it is only declared, but it is not used ).

Keep us posted please. Thanks!

**Comment by swimmingseeds** [comment]
This pull request has been mentioned on **Discussion Forum, for PX4, Pixhawk, QGroundControl, MAVSDK, MAVLink**. There might be relevant details there:

https://discuss.px4.io/t/px4-community-q-a-february-15-2023/30744/1

**Comment by HOYS** [comment]
I'm new to the qgc codebase but would love to see this feature mainlined. What can I do to help?

**Comment by DonLakeFlyer** [comment]
Closing as stale

**Pull request closed without merging**
