### PR TITLE
Trajectory updates

### PR DESCRIPTION
**Pull request by NaterGator**
For #3698, @DonLakeFlyer I'm not getting leaks on Linux but would be grateful if you could test too.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Hmm, I'll try it this afternoon. That's exactly what I did and I couldn't get the lines to draw right.

**Comment by NaterGator** [comment]
The only quirk I've seen is there is a segment to 0,0 if the path list only contains 1 element. Easy fix if that's the only issue.

**Comment by DonLakeFlyer** [comment]
This has the same line drawing problem as when I tried it. Seems like it may be an OSX only bug. iOS seems to be fine. And you did Linux. I tried the 1 element change on my fix and it didn't work. I'm going to try fixed allocation of CoordinateVectors and still use QmlObjectListModel with multiple polylines like the old code. Hopefully that will fix leak and work around line drawing problems.

**Comment by DonLakeFlyer** [comment]
Closing since it doesn't work and there isn't actually a memory leak

**Pull request closed without merging**
