### PR TITLE
Mission: Switch back to item #, plus alt display

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Decided showing altitude in item indicator looked like crap. Back to showing item number in indicator. Instead adding altitude map to little distance between waypoint thingy. You can open and close it to get it out of the way.

screen shot 2015-12-07 at 7 58 28 pm

screen shot 2015-12-07 at 7 58 17 pm

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Son of a bitch! One of my new files went missing. Hope I have it somewhere.

**Comment by LorenzMeier** [comment]
Ugh! The bottom bar looks fantastic!

**Comment by DonLakeFlyer** [comment]
Nope it's gone. I'll have to rewrite it from scratch.

**Comment by DonLakeFlyer** [comment]
I think I resurrected it. May have missed something though. Lots of quirkiness with respect to handling relative/absolute alt and home position available or not.

**Pull request merged**
