### PR TITLE
Fixed tool button order

### LINKED ISSUE #2220: Tool order different on fly and edit views
On Fly map center is straight above map type, on edit the sync tool is in-between.

### PR DESCRIPTION
**Pull request by dogmaphobic**
This fixes #2220

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Looks like another commit crept in here?

**Comment by dogmaphobic** [comment]
Odd... I'm not at home. I'll take a look when I get back.

**Comment by dogmaphobic** [comment]
Got it. Daniel is running some tests directly on master (to test AppVeyor) and I got caught in the middle. I will wait until that's done before merging this.

**Comment by dogmaphobic** [comment]
Actually, it's easier to delete this and start over...

**Pull request closed without merging**
