### PR TITLE
Load AirMap dynamically to avoid loading unavailable components 

### PR DESCRIPTION
**Pull request by patrickelectric**
Avoid loading AirMap if the support does not exist

### CODE REVIEW

**Comment by patrickelectric** [comment]
It would be nice to have someone of AirMap to test it

**Comment by patrickelectric** [comment]
@keith-bennett-airmap ping

**Comment by keith-bennett-airmap** [comment]
Hi @patrickelectric ,

I recall from the conversation that you'd said an error message keeps popping up in builds without AirMap configured. When I build QGC with [`DISABLE_AIRMAP`](https://github.com/mavlink/qgroundcontrol/blob/0ed94504b265fb589d7c2bf974c7417bcdb94d54/QGCExternalLibs.pri#L231) defined during the configure step, I do not see any problem messages showing up during flight. This is with [a recent `master`](https://github.com/mavlink/qgroundcontrol/commit/0ed94504b265fb589d7c2bf974c7417bcdb94d54). I also went so far as to remove [the definition of `QGC_AIRMAP_ENABLED`](https://github.com/mavlink/qgroundcontrol/blob/0ed94504b265fb589d7c2bf974c7417bcdb94d54/QGCExternalLibs.pri#L269) and still did not encounter any error messages or issues that I could easily identify.

https://user-images.githubusercontent.com/72767521/130007596-50b9d79e-1d89-41eb-a48e-f9165737e479.mp4

Can you clearly describe the steps to reproduce the issue you were having? I'd like to better understand the problem that this PR tries to solve.

Thanks,
Keith

**Comment by DonLakeFlyer** [comment]
> Can you clearly describe the steps to reproduce the issue you were having? I'd like to better understand the problem that this PR tries to solve.

@patrickelectric ?

**Comment by patrickelectric** [comment]
The idea here is to disable the components in runtime since airmap will not exist when building QGC without airmap support.

**Comment by Davidsastresas** [comment]
As the removal of Airmap in the codebase is in master already I think this can be closed.

**Pull request closed without merging**
