### PR TITLE
gather linux libs

### PR DESCRIPTION
**Pull request by dagar**
Gathering a list of all linux deps to throw into the package. If anyone knows a better way to do this, or the "right" way please let me know.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Also need libsdl-dev and libudev-dev.

**Comment by dagar** [comment]
I'm not particularly thrilled with this solution, but it does allow running qgroundcontrol on a fresh ubuntu 14.04 without tracking down Qt. You have to start it with `qgroundcontrol-start.sh` to get all the paths set correctly.

**Comment by DonLakeFlyer** [comment]
If those are the exports can use those same onces to point to an online installer Qt?

**Comment by DonLakeFlyer** [comment]
The direction I'm heading is to just include a shell screen in the build you can use to run against the supported online installer version and install locations. Then users can also use this as an example if they want to do something strange like use a different version.

**Comment by DonLakeFlyer** [comment]
Should this be merged so we can cut a new stable? README needs to be udpated as well.

**Pull request closed without merging**
