### PR TITLE
Virtual joystick graphics

### PR DESCRIPTION
**Pull request by dogmaphobic**
Minor tweak to the virtual joystick graphics suggested by @dagar 

screen shot 2018-03-06 at 3 16 05 pm

### CODE REVIEW

**Comment by dagar** [comment]
I like it! I'm wondering if little arrows on the roll/pitch stick would also help?

**Comment by DonLakeFlyer** [comment]
Merge?

**Comment by DonLakeFlyer** [comment]
Merge?

**Comment by dagar** [comment]
@dogmaphobic can we merge this?

**Comment by dogmaphobic** [comment]
It's been done for ages. If everyone is happy with it, sure!

**Comment by dogmaphobic** [comment]
@dagar What about the gimbal control? Was that ever merged?

**Comment by dagar** [comment]
> What about the gimbal control? Was that ever merged?

No, https://github.com/mavlink/qgroundcontrol/pull/6138

If it rebases cleanly let's get it in.

**Comment by dogmaphobic** [comment]
I'll look into it...

**Pull request merged**
