### PR TITLE
Get mavlink_message_info_t from FirmwarePlugin

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
This allows MavlinkInspector to show APM stack messages

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@pritamghanghas Mavlink Inspector fix for firmware stack specific messages. Can you test with APM. It should all be working, but I'm not sure how to get APM to spit out one of those APM specific messages. Also note that the APM firmware plugin now uses the APM stack specific mavlink headers.

**Comment by LorenzMeier** [comment]
That won't be enough. You also need to use the specific decode routine, since the message spec is used to seed the message payload (so two messages with the same ID can't be accidentally decoded wrongly).

**Comment by DonLakeFlyer** [comment]
Not sure what you mean. Mavlink inspector doesn't use any decode routines. It does this: https://github.com/mavlink/qgroundcontrol/blob/master/src/ui/QGCMAVLinkInspector.cc#L547

**Comment by LorenzMeier** [comment]
It means the message decoder will trash the message because it seeds the CRC with 0 instead of the proper seed. You will not receive any APM messages as a consequence.

**Comment by DonLakeFlyer** [comment]
> message decoder will trash the message because it seeds the CRC with 0 instead of the proper seed

Where in the code?

**Comment by DonLakeFlyer** [comment]
Ok. So this won't work yet until we get a newer version of mavlink that can support multiple interfaces. Once that shows up this should start working. I don't believe this pull specifically needs any additional changes.

**Comment by pritamghanghas** [comment]
Yes, I tested it doesn't work yet.

On Mon, Oct 12, 2015 at 11:05 PM, Don Gagne <notifications@github.com>
wrote:

> Ok. So this won't work yet until we get a newer version of mavlink that
> can support multiple interfaces. Once that shows up this should start
> working. I don't believe this pull specifically needs any additional
> changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mavlink/qgroundcontrol/pull/1961#issuecomment-147470885>
> .
>



-- 
Regards,
pritam

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Any reason to not merge this. It won't work now. But it should start to work when the new mavlink stuff isin.

**Pull request closed without merging**
