### PR TITLE
Update PX4 Firmware metadata Fri Sep 28 14:14:57 UTC 2018

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
@dogmaphobic OSX failures look real (unrelated to this PR).

**Comment by dogmaphobic** [comment]
I wonder why it only happens in that system. I'm rebooting and updating Xcode...

**Comment by dogmaphobic** [comment]
It was a (new) warning within the Airmap SDK stuff. I assume the build is set to fail on warning? I wonder how it passes all those zillion warnings with mavlink.h. Either way, I "fixed" both here: https://github.com/mavlink/qgroundcontrol/pull/6903

**Comment by DonLakeFlyer** [comment]
If I remember correctly I thought only the Linux build is set to fail on warning because new clang awhile back turned on all sorts of random crap and it was spewing output.

**Pull request merged**
