### PR TITLE
cmake: Turn MICROHARD and TAISYNC disabled by default

### LINKED ISSUE #9729: Build failure: no member named 'microhardManager' in 'QGCToolbox'
I'm trying to build QGC (haven't succeeded yet) and getting this error:
```
In file included from /home/phma/src/qgroundcontrol/src/Microhard/MicrohardSettings.cc:13:
In file included from /home/phma/src/qgroundcontrol/src/QGCApplication.h:27:
In file included from /home/phma/src/qgroundcontrol/src/FirmwarePlugin/FirmwarePluginManager.h:14:
/home/phma/src/qgroundcontrol/src/FirmwarePlugin/FirmwarePlugin.h:334:44: warning: unused parameter 'vehicle' [-Wunused-parameter]
    virtual QString getHobbsMeter(Vehicle* vehicle) { return "Not Supported"; }
                                           ^
/home/phma/src/qgroundcontrol/src/Microhard/MicrohardSettings.cc:83:53: error: no member named 'microhardManager' in 'QGCToolbox'
        std::string userName = qgcApp()->toolbox()->microhardManager()->configUserName().toStdString() + "\n";
                               ~~~~~~~~~~~~~~~~~~~  ^
/home/phma/src/qgroundcontrol/src/Microhard/MicrohardSettings.cc:86:48: error: no member named 'microhardManager' in 'QGCToolbox'
        std::string pwd = qgcApp()->toolbox()->microhardManager()->configPassword().toStdString() + "\n";
                          ~~~~~~~~~~~~~~~~~~~  ^
/home/phma/src/qgroundcontrol/src/Microhard/MicrohardSettings.cc:92:34: error: no member named 'microhardManager' in 'QGCToolbox'
            qgcApp()->toolbox()->microhardManager()->setEncryptionKey();
            ~~~~~~~~~~~~~~~~~~~  ^
1 warning and 3 errors generated.
ninja: build stopped: subcommand failed.
```
## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu Focal
- QGC Version: Just pulled from git
- QGC build: not successfully built yet
- Flight Controller: n/a
- Autopilot (with version): n/a
- CMake: 3.16.3
- Ninja: 1.10.0
- Clang: 10.0.0-4ubuntu1

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix #9729

### CODE REVIEW

**Comment by phma** [comment]
GST is in fact not found, as far as I can tell, so I had to put the options after the endif. I still get a compile error.
```
GIT_EXECUTABLE-ADVANCED:INTERNAL=1
GST_CFLAGS:INTERNAL=
GST_CFLAGS_I:INTERNAL=
GST_CFLAGS_OTHER:INTERNAL=
GST_FOUND:INTERNAL=
GST_INCLUDEDIR:INTERNAL=
GST_LIBDIR:INTERNAL=
GST_LIBS:INTERNAL=
GST_LIBS_L:INTERNAL=
GST_LIBS_OTHER:INTERNAL=
GST_LIBS_PATHS:INTERNAL=
GST_MODULE_NAME:INTERNAL=
GST_PREFIX:INTERNAL=
GST_STATIC_CFLAGS:INTERNAL=
GST_STATIC_CFLAGS_I:INTERNAL=
GST_STATIC_CFLAGS_OTHER:INTERNAL=
GST_STATIC_LIBDIR:INTERNAL=
GST_STATIC_LIBS:INTERNAL=
GST_STATIC_LIBS_L:INTERNAL=
GST_STATIC_LIBS_OTHER:INTERNAL=
GST_STATIC_LIBS_PATHS:INTERNAL=
GST_VERSION:INTERNAL=
GST_egl_INCLUDEDIR:INTERNAL=
GST_egl_LIBDIR:INTERNAL=
GST_egl_PREFIX:INTERNAL=
GST_egl_VERSION:INTERNAL=
GST_gstreamer-1.0_INCLUDEDIR:INTERNAL=
GST_gstreamer-1.0_LIBDIR:INTERNAL=
GST_gstreamer-1.0_PREFIX:INTERNAL=
GST_gstreamer-1.0_VERSION:INTERNAL=
GST_gstreamer-gl-1.0_INCLUDEDIR:INTERNAL=
GST_gstreamer-gl-1.0_LIBDIR:INTERNAL=
GST_gstreamer-gl-1.0_PREFIX:INTERNAL=
GST_gstreamer-gl-1.0_VERSION:INTERNAL=
GST_gstreamer-video-1.0_INCLUDEDIR:INTERNAL=
GST_gstreamer-video-1.0_LIBDIR:INTERNAL=
GST_gstreamer-video-1.0_PREFIX:INTERNAL=
GST_gstreamer-video-1.0_VERSION:INTERNAL=
//ADVANCED property for variable: HGCOMMAND
```
```
if (GST_FOUND)
    add_definitions(
        -DQGC_GST_STREAMING
    )
endif()
option(QGC_GST_MICROHARD_ENABLED "Enable microhard" OFF)
option(QGC_GST_TAISYNC_ENABLED "Enable taisyng" OFF)
```

**Comment by phma** [comment]
GST is in fact not found, as far as I can tell, so I had to put the options after the endif. I still get a compile error.
```
GIT_EXECUTABLE-ADVANCED:INTERNAL=1
GST_CFLAGS:INTERNAL=
GST_CFLAGS_I:INTERNAL=
GST_CFLAGS_OTHER:INTERNAL=
GST_FOUND:INTERNAL=
GST_INCLUDEDIR:INTERNAL=
GST_LIBDIR:INTERNAL=
GST_LIBS:INTERNAL=
GST_LIBS_L:INTERNAL=
GST_LIBS_OTHER:INTERNAL=
GST_LIBS_PATHS:INTERNAL=
GST_MODULE_NAME:INTERNAL=
GST_PREFIX:INTERNAL=
GST_STATIC_CFLAGS:INTERNAL=
GST_STATIC_CFLAGS_I:INTERNAL=
GST_STATIC_CFLAGS_OTHER:INTERNAL=
GST_STATIC_LIBDIR:INTERNAL=
GST_STATIC_LIBS:INTERNAL=
GST_STATIC_LIBS_L:INTERNAL=
GST_STATIC_LIBS_OTHER:INTERNAL=
GST_STATIC_LIBS_PATHS:INTERNAL=
GST_VERSION:INTERNAL=
GST_egl_INCLUDEDIR:INTERNAL=
GST_egl_LIBDIR:INTERNAL=
GST_egl_PREFIX:INTERNAL=
GST_egl_VERSION:INTERNAL=
GST_gstreamer-1.0_INCLUDEDIR:INTERNAL=
GST_gstreamer-1.0_LIBDIR:INTERNAL=
GST_gstreamer-1.0_PREFIX:INTERNAL=
GST_gstreamer-1.0_VERSION:INTERNAL=
GST_gstreamer-gl-1.0_INCLUDEDIR:INTERNAL=
GST_gstreamer-gl-1.0_LIBDIR:INTERNAL=
GST_gstreamer-gl-1.0_PREFIX:INTERNAL=
GST_gstreamer-gl-1.0_VERSION:INTERNAL=
GST_gstreamer-video-1.0_INCLUDEDIR:INTERNAL=
GST_gstreamer-video-1.0_LIBDIR:INTERNAL=
GST_gstreamer-video-1.0_PREFIX:INTERNAL=
GST_gstreamer-video-1.0_VERSION:INTERNAL=
//ADVANCED property for variable: HGCOMMAND
```
```
if (GST_FOUND)
    add_definitions(
        -DQGC_GST_STREAMING
    )
endif()
option(QGC_GST_MICROHARD_ENABLED "Enable microhard" OFF)
option(QGC_GST_TAISYNC_ENABLED "Enable taisyng" OFF)
```

**Comment by patrickelectric** [comment]
You should not edit the patch, if GST is not found and the option is inside GST is that because microhard and taisync depends of GST. So **do not** enable such options (taisync and microhard) without GST and also I do not recommend to turn it on at all, since we know that is mostly broken.

**Comment by patrickelectric** [comment]
And as I suggested, you'll need to clean the build folder and recall cmake and maybe use ccmake to configure the project.

As you can see, the options are OFF, and that is what the patch is fixing (the default was ON by default)
image

**Comment by phma** [comment]
I *deleted* *all eight* build folders (the only one I actually used is ~/build/qgroundcontrol/cdbg) *twice* and reran `buildqgc` after each deletion. I then used cmake-gui and made sure the options are off. In CMakeCache.txt:
```
//Enable microhard
QGC_GST_MICROHARD_ENABLED:BOOL=OFF

//Enable taisyng
QGC_GST_TAISYNC_ENABLED:BOOL=OFF
```
The build still fails.

**Pull request merged**
