### PR TITLE
Mission item: CONDITION_YAW - added shortest direction

### PR DESCRIPTION
**Pull request by AndKe**
This adds the best option for Yaw changes in Copter  - the shortest way.
Tested, works fine.

### CODE REVIEW

**Comment by booo** [comment]
Please remove the change of the default value or make sure you explain the default  change in the commit. Preferably add the default change in another commit.

**Comment by AndKe** [comment]
@booo  : please find requested changes  - default will be another commit

**Comment by mrpollo** [comment]
@booo this PR now LGTM, I'm not merging until you approve

**Comment by mrpollo** [comment]
closing in favor of #10605

**Pull request closed without merging**
