### PR TITLE
travis-ci enable QT_FATAL_WARNINGS=1 for osx

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
@DonLakeFlyer 33 TESTS FAILED
https://travis-ci.org/mavlink/qgroundcontrol/jobs/87367421

**Comment by DonLakeFlyer** [comment]
Strange those aren't qWarning breaks. Those are just regular UT failures. Was your master up to date? Everything else has been running through fine.

**Comment by dagar** [comment]
Rebased.

**Comment by DonLakeFlyer** [comment]
I think something is broken on master. Looking...

**Comment by dagar** [comment]
@DonLakeFlyer passing now.

**Comment by DonLakeFlyer** [comment]
Yeah. I finally found the unit test bug.

**Pull request merged**
