### PR TITLE
Camera control. Experimental, not to merge.

### PR DESCRIPTION
**Pull request by dogmaphobic**
Control of arbitrary cameras through a *Camera Definition* standard (XML)

screen shot 2017-07-17 at 10 09 47 pm

### CODE REVIEW

**Comment by dogmaphobic** [comment]
Removing so I can cleanup and create a new PR.

**Comment by mafilipp** [comment]
Hey, I had a look at our PR and looks really cool and useful!
Do you have an idea when are you going to create the new PR?
Thank you very much!

**Comment by dogmaphobic** [comment]
I closed the PR and created a new branch. I'm still working on it but you can see it all here:

https://github.com/mavlink/qgroundcontrol/tree/cameraControl

**Comment by mafilipp** [comment]
Great, thank you very much!

**Pull request closed without merging**
