### PR TITLE
README: Remove obsolete badges

### PR DESCRIPTION
**Pull request by booo**
We use github actions for CI now. The travis and appveyor badges are obsolete.

Do people use gitter?

### CODE REVIEW

**Review by bkueng — APPROVED** [review]
Gitter can probably go as well.

**Comment by zdanek** [comment]
And why don't we use those badges any more? Is that because building was moved to Github Actions?

**Comment by booo** [comment]
Yes, for the build process we use github actions now. I mentioned that in the commit body.

**Comment by booo** [comment]
> Gitter can probably go as well.

I removed the gitter badge as well. Maybe we should remove/archive the gitter channel(s) and remove all reference from the documentation too?

**Review by patrickelectric — APPROVED** [review]

**Pull request merged**
