### PR TITLE
Ardupilot: Add Baro Alt Offset Compensation

### PR DESCRIPTION
**Pull request by HTRamsey**
Uses available pressure & temperature sensors to adjust altitude offset on drones for long flights using the params BARO_GND_TEMP & BARO_ALT_OFFSET. No current method of enabling, but the logic is there.

### CODE REVIEW

**Comment by mrpollo** [comment]
Is this ready for review/merge @HTRamsey ?

**Comment by HTRamsey** [comment]
let me do the one fix mentioned in my edit real quick, and rebase to fix the linux build issue.

**Review by mrpollo — APPROVED** [review]

**Comment by HTRamsey** [comment]
Is this okay to merge?

**Comment by TSC21** [comment]
> Is this okay to merge?

You might want to tag someone from the Ardupilot team here.

**Comment by HTRamsey** [comment]
@peterbarker had checked it out previously via discord

**Comment by TSC21** [comment]
> @peterbarker had checked it out previously via discord

I would say then it's good to go.

**Comment by TSC21** [comment]
The last commit currently seems to bring unrelated changes though... maybe you want to double check?

**Comment by HTRamsey** [comment]
I rebased onto master to make sure builds still pass

**Pull request merged**
