### PR TITLE
Raise min Qt version to 5.5+

### PR DESCRIPTION
**Pull request by LorenzMeier**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Appveyor restarted. Looks like a CI failure, not a failure of the actual build.

**Comment by DonLakeFlyer** [comment]
@dagar Does this one make any sense to you?

**Comment by NaterGator** [comment]
@DonLakeFlyer if you are referring to the appveyor build failure, that is when sourceforge is down or doing maintenance and we can't install NSIS.

**Comment by DonLakeFlyer** [comment]
I tried re-running it and it failed again. Hence I was confused since that usually works. Then close/reopen seemed to do the trick.

**Pull request merged**
