### PR TITLE
Add videoconvert step in gstreamer pipeline

### PR DESCRIPTION
**Pull request by aburgm**
I have a h264 video stream from a companion computer on the vehicle that does not show in QGC, but runs fine in both VLC and with a stand-alone gstreamer pipeline such as

```
gst-launch-1.0 udpsrc port=5000 ! application/x-rtp,encoding-name=H264,payload=96 ! rtph264depay ! h264parse ! queue ! avdec_h264 ! videoconvert | autovideosink sync=false async=false
```

However, when I remove the `videoconvert` step, the pipeline seems to run, but does not display anything. Adding the videoconvert does not seem to cost performance if the video format is already supported by the sink, so seems to be a safe thing to add to QGC in general.

I am running gstreamer 1.14.1 on a Gnome Shell desktop.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@jaxxzer Since you guys are an import user of video...

**Comment by jaxxzer** [comment]
This videoconvert step should not be necessary.

Can you give us more information?
- what camera are you using on companion computer?
- what does the pipeline on your companion computer look like?
- what gstreamer packages do you have installed on your desktop?

**Comment by aburgm** [comment]
> what camera are you using on companion computer?

It's a [FLIR BlackFly S GigE camera](https://www.ptgrey.com/blackfly-s-50-mp-color-gige-vision-sony-imx264).

> what does the pipeline on your companion computer look like?

```
gst-launch-1.0 gvspsrc ! bayer2rgb ! videoscale ! video/x-raw,width=608,height=512 ! videoconvert ! x264enc bitrate=1024 ! 'video/x-h264, stream-format=(string)byte-stream' ! h264parse ! rtph264pay config-interval=10 pt=96 ! udpsink host=127.0.0.1 port=5000 sync=false async=false
```

Where gvspsrc is a custom element that I have written to interface the camera to gstreamer. However, the issue can be reproduced with videotestsrc as well (see below).

> what gstreamer packages do you have installed on your desktop?
```
armin@dell-xps15:~$ pkg-config --list-all | grep gst
gstreamer-player-1.0             GStreamer Player - GStreamer Player convenience library
gstreamer-video-1.0              GStreamer Video Library - Video base classes and helper functions
gstreamer-riff-1.0               GStreamer RIFF Library - RIFF helper functions
gstreamer-1.0                    GStreamer - Streaming media framework
gstreamer-net-1.0                GStreamer networking library - Network-enabled GStreamer plug-ins and clocking
gstreamer-plugins-good-1.0       GStreamer Good Plugin libraries - Currently includes the photography interface library
gstreamer-pbutils-1.0            GStreamer Base Utils Library - General utility functions
gstreamer-codecparsers-1.0       GStreamer codec parsers - Bitstream parsers for GStreamer elements
gstreamer-app-1.0                GStreamer Application Library - Helper functions and base classes for application integration
gstreamer-audio-1.0              GStreamer Audio library - Audio helper functions and base classes
gstreamer-mpegts-1.0             GStreamer MPEG-TS - GStreamer MPEG-TS support
gstreamer-tag-1.0                GStreamer Tag Library - Tag base classes and helper functions
gstreamer-webrtc-1.0             GStreamer WebRTC - GStreamer WebRTC support
gstreamer-plugins-base-1.0       GStreamer Base Plugins Libraries - Streaming media framework, base plugins libraries
gstreamer-allocators-1.0         GStreamer Allocators Library - Allocators implementation
gstreamer-rtsp-1.0               GStreamer RTSP Library - RTSP base classes and helper functions
gstreamer-bad-video-1.0          GStreamer bad video library - Bad video library for GStreamer elements
gstreamer-check-1.0              GStreamer check unit testing - Unit testing helper library for GStreamer modules
gstreamer-base-1.0               GStreamer base classes - Base classes for GStreamer elements
gstreamer-fft-1.0                GStreamer FFT Library - FFT implementation
gstreamer-plugins-bad-1.0        GStreamer Bad Plugin libraries - Streaming media framework, bad plugins libraries
gstreamer-insertbin-1.0          GStreamer Insert Bin - Bin to automatically and insertally link elements
gstreamer-sdp-1.0                GStreamer SDP Library - SDP helper functions
gstreamer-rtp-1.0                GStreamer RTP Library - RTP base classes and helper functions
gstreamer-bad-audio-1.0          GStreamer bad audio library, uninstalled - Bad audio library for GStreamer elements, Not Installed
gstreamer-gl-1.0                 GStreamer OpenGL Plugins Libraries - Streaming media framework, OpenGL plugins libraries
gstreamer-controller-1.0         GStreamer controller - Dynamic parameter control for GStreamer elements
```

---

One interesting thing that I noticed is that the problem can be reproduced with videotestsrc by just replacing the source in the above pipeline, so:

```
gst-launch-1.0 videotestsrc ! bayer2rgb ! videoscale ! video/x-raw,width=608,height=512 ! videoconvert ! x264enc bitrate=1024 ! 'video/x-h264, stream-format=(string)byte-stream' ! h264parse ! rtph264pay config-interval=10 pt=96 ! udpsink host=127.0.0.1 port=5000 sync=false async=false
```

However, when removing the `bayer2rgb` element from that pipeline, it works without the videoconvert on the receiver side. I suppose in this case the `videotestsrc` is generating a different format. However, with the actual camera I need the bayer conversion.

**Comment by dogmaphobic** [comment]
What is the status of this? You can't use `videoconvert` as it will use arbitrary elements to deal with the stream. For some platforms, only the required (static) libraries are linked. If you need this, make sure to isolate it to Linux and macOS, or use an explicit module, find the exact dependencies and add to the list of libraries to link.

**Comment by dogmaphobic** [comment]
@aburgm Any news as to the above questions?

**Comment by aburgm** [comment]
I have looked into this a bit more and found out that the additional `videoconvert` element is not necessary when modifying the pipeline on the producer a bit:

```
gst-launch-1.0 videotestsrc ! bayer2rgb ! videoscale ! video/x-raw,width=608,height=512,format=I420 ! videoconvert ! x264enc bitrate=1024 ! 'video/x-h264, stream-format=(string)byte-stream' ! h264parse ! rtph264pay config-interval=10 pt=96 ! udpsink host=127.0.0.1 port=5000 sync=false async=false
```

This is probably the better way to go, so no changes to QGroundControl are needed. As far as I'm concerned the PR can be closed; and thanks for the assistance/pointers into the right direction!

**Pull request closed without merging**
