### PR TITLE
Fix instrument panel and editor layout

### PR DESCRIPTION
**Pull request by zdanek**
In fly view, set instrument values have custom color same as labels
Fix instrument panel editor layout properly according to selected Range type.

### CODE REVIEW

**Comment by zdanek** [comment]
Fixes this
image
and
image

into this
image
and 
image

**Comment by zdanek** [comment]
Also I've added check for icon file. If empty, skips setting icon source. Otherwise it reported error from QML.
Setting icon width fixes cutting right edge of the icon. Look carefully at second image.

**Comment by zdanek** [comment]
@DonLakeFlyer would you take a look?

**Comment by zdanek** [comment]
@Davidsastresas @DonLakeFlyer  or anybody, quick look?

**Review by patrickelectric — APPROVED** [review]

**Comment by zdanek** [comment]
@patrickelectric obrigado!

**Comment by DonLakeFlyer** [comment]
@zdanek Thanks for the pull. Sorry I was out of town and just back now.

**Comment by Davidsastresas** [comment]
sorry @zdanek , for some reason I wasn't aware that you mentioned me until now. Happy to see Patrick was quicker and everything is set now. Thank you for the PR!

**Comment by zdanek** [comment]
Thank you.

**Pull request merged**
