### PR TITLE
APMHeliComponent - update for Copter 4.0

### PR DESCRIPTION
**Pull request by ChristopherOlson**
@DonLakeFlyer this updates the Heli Setup for Copter 4.0

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Can you add screenshot(s)

**Comment by ChristopherOlson** [comment]
Sure, Don.
Full screen layout
imenjhhjoilejfhe

cejgfgmijkfpcfep

Medium screen layout
iknkjhkkeadibfpb

lepfmpodohiaccem

Small screen like smart phone goes to single-column.

Thanks!

**Comment by ChristopherOlson** [comment]
@DonLakeFlyer I also suggested to Bill to shorten some of the names of the @DisplayName in the metadata. Some of those are pretty long. I can get nicer grouping on the sizes of the boxes if some of those were shorter. But this gets everything working for the 4.0 beta testers using the Daily Builds.

**Comment by DonLakeFlyer** [comment]
So this is for Copter 4.0. Are any of the parameters new and in Copter 4.0 only? If so this is going to pop missing parameter warnings if run against version < 4.0.

**Comment by ChristopherOlson** [comment]
Don, yes 4.0 is TOTALLY different than 3.6. Even the names of the swashplate parameters were changed, some like LAND_COL_MIN were totally eliminated. Unfortunately, there is no possibility of backwards compatibility with 3.6 with this. The Parameters section will handle it, but the Heli Setup, where it calls for specific parameters is not compatible. Maybe I could make a note on the top of the page that this is only for helicopters running Copter 4.0 and newer? For older versions of Copter use Stable 3.5.1?

**Comment by ChristopherOlson** [comment]
@DonLakeFlyer the reason the swashplate params were changed is because there is a complete new swashplate library for heli in 4.0. Even the old servo position params are no longer used.

Realistically, many, if not most, users on Copter with heli are flying my ArduHeli builds instead of stock Copter, since the ArduHeli builds have all the latest stuff that's coming out in 4.0. ArduHeli 3.6.11 IS 100% compatible with this new setup page. Copter 3.6.11 is not compatible.

**Comment by DonLakeFlyer** [comment]
> Realistically, many, if not most, users on Copter with heli are flying my ArduHeli builds instead of stock Copter, since the ArduHeli builds have all the latest stuff that's coming out in 4.0.

Then this should be for ArduHeli 4.0 only then. You need to tweak the APMAutoPilotPlugin.cc such that it only gets added for 4.0 firmware.

**Comment by ChristopherOlson** [comment]
OK, not sure how to do that. But I'll take a look at it this evening and see if I can figure it out.

**Comment by DonLakeFlyer** [comment]
There are other examples in there that do a version compare before adding setup pages.

**Comment by ChristopherOlson** [comment]
Thanks Don! Will take a look this evening when I have more time to examine that.

**Comment by ChristopherOlson** [comment]
@DonLakeFlyer I included a commit that (from what I tested) blocks the Heli Setup from appearing if the version is not 4.0 or greater. I hope I did this right, but it seems to work fine here in my testing.

**Comment by DonLakeFlyer** [comment]
Perfect thanks for working to keep this up to date.

**Comment by ChristopherOlson** [comment]
@DonLakeFlyer I did some more testing with three different controllers and versions. The Version lockout for prior to 4.0 definitely works as expected.

Thanks for making this heli setup for us in the first place! I like the design - very easy to maintain.

**Pull request merged**
