### PR TITLE
Upgrade to 22.04

### PR DESCRIPTION
**Pull request by Ryanf55**
Many people are on 22.04 now, so I created a PR to upgrade. If this doesn't build cleanly, it suggests the build/CI system is dependent on the version of ubuntu and further changes may be needed.

### CODE REVIEW

**Comment by zdanek** [comment]
This is not good idea. 
Let's keep minimal Ubuntu at 20 as long as possible, or at least for nearest future.

**Comment by Ryanf55** [comment]
> This is not good idea. Let's keep minimal Ubuntu at 20 as long as possible, or at least for nearest future.

Ok. How do you recommend developers on Ubuntu 22 compile QGC?

**Comment by zdanek** [comment]
> Ok. How do you recommend developers on Ubuntu 22 compile QGC?

I am on Ubuntu 22.04. Developing, building, running on it. Using both Qt (PRO files) and Cmake files with success.
 What is your current issue? Can I help you?

**Comment by Ryanf55** [comment]
> > Ok. How do you recommend developers on Ubuntu 22 compile QGC?
> 
> I am on Ubuntu 22.04. Developing, building, running on it. Using both Qt (PRO files) and Cmake files with success. What is your current issue? Can I help you?

Yea, is there a better place to discuss the issue? Discord, discuss, etc?

**Comment by zdanek** [comment]
> > > Ok. How do you recommend developers on Ubuntu 22 compile QGC?
> > 
> > 
> > I am on Ubuntu 22.04. Developing, building, running on it. Using both Qt (PRO files) and Cmake files with success. What is your current issue? Can I help you?
> 
> Yea, is there a better place to discuss the issue? Discord, discuss, etc?

I'm on DroneCode's Discord #Qgroudcontrol 
https://discord.com/channels/1022170275984457759/1022185820683255908

**Comment by DonLakeFlyer** [comment]
Closing this since at this point we aren't moving to 22

**Pull request closed without merging**
