### PR TITLE
Turning off cache since it's breaking release builds (maybe!)

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Or at least testing to see if that is the problem

### CODE REVIEW

**Comment by NaterGator** [comment]
https://www.traviscistatus.com

We can also try nuking the cache from the project's Travis config page.

**Comment by DonLakeFlyer** [comment]
I'll try doing that if this passes

**Comment by DonLakeFlyer** [comment]
Clearing cache seemed to work.

**Comment by dagar** [comment]
You can temporarily disable ccache with `export CCACHE_DISABLE=1`

**Comment by DonLakeFlyer** [comment]
Good to know. I wonder if the cache will just blow up every once in a while and need clearing. Guess we'll see. Now I know how to clear it though.

**Comment by dagar** [comment]
We definitely should be able to trust it all the times. It's limited to 500MB, but travis-ci keeps different caches for branches, etc

I wasn't following things today, but it looks like travis-ci in general has been in pretty bad shape.

**Pull request closed without merging**
