### PR TITLE
Add The Peach K1/R1 USB Board info

### PR DESCRIPTION
**Pull request by ThePeach-kr**
Hi,

We developed a Flight Controller.
I would like to add USB Board info of our K1/R1 Flight Controller to the QGroundControl.

please check theses PR !
- PX4-user-guide: https://github.com/PX4/PX4-user_guide/pull/2034#event-7336074804
- PX4-Autopilot: https://github.com/PX4/PX4-Autopilot/pull/20176
- PX4-Bootloader: https://github.com/PX4/PX4-Bootloader/pull/219

Thanks

### CODE REVIEW

**Comment by hamishwillee** [comment]
@mrpollo Who can get board stuff like this reviewed?

**Comment by booo** [comment]
Could you please squash your changes into one commit. Apart from that I guess it is fine to merge.

**Comment by ThePeach-kr** [comment]
@booo I squashed it with one commit. Can you review the merge?

**Comment by booo** [comment]
Thanks a lot. Unfortunately I don't have merge permission. But looks ok to me.

**Comment by Davidsastresas** [comment]
Looks good to me, the author is the vendor of the board and the changes are straightforward, merged!

**Pull request merged**
