### PR TITLE
Make AnalyzeView controllers persistent

### PR DESCRIPTION
**Pull request by NaterGator**
For #4909

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dogmaphobic I think this is fine, but can you look?

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Ok, for log download?

**Comment by dogmaphobic** [comment]
> Ok, for log download?

Sorry, I've been swamped. I looked through the code and it all seems fine. Nothing special is done during construction/destruction so I don't see any issues keeping it alive. 

I only went through the code. I did not actually test it.

**Comment by DonLakeFlyer** [comment]
Crap. @NaterGator Can you rebase?

**Comment by NaterGator** [comment]
Sure thing, just a sec.

**Comment by DonLakeFlyer** [comment]
Travis passed. Appveyor seems to have gone bonkers. Should be ok.

**Pull request merged**
