### PR TITLE
Remove windows only zlib

### PR DESCRIPTION
**Pull request by DonLakeFlyer**

### CODE REVIEW

**Comment by hamishwillee** [comment]
@julianoes This isn't what MAVSDK was expecting to exist for component information file decompression right?

**Comment by julianoes** [comment]
@hamishwillee yes it is but I don't know what this change exactly does.

**Comment by DonLakeFlyer** [comment]
What does MAVSDK have to do with QGC code?

**Comment by dogmaphobic** [comment]
I'm assuming the discussion is around mavftp compression. Don removed this binary, which is only for Windows, to replace it with a submodule to provide zlib to all platforms.

**Comment by DonLakeFlyer** [comment]
Correct. Which also I believe turned out to be wrong to remove since zlib is supposedly available by default on all platforms except Windows. Hence you only need a windows lib. I'm working on verifying that right now to see if it will work.

**Comment by julianoes** [comment]
Sorry, it's not about MAVSDK. It's just the MAVLink spec.

**Pull request merged**
