### PR TITLE
PX4 Setup - Power: Fix broken voltage/current divider calculators

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Broken by previous multi-battery pull

### CODE REVIEW

**Comment by bys1123** [comment]
Fixed https://github.com/PX4/Firmware/issues/15986

**Comment by bys1123** [comment]
Do you have any idea that why old 3.5.6 version can load these new BATn_* parameters? Thanks!

**Comment by DonLakeFlyer** [comment]
> Do you have any idea that why old 3.5.6 version can load these new BATn_* parameters?

It can't. The firmware syncs BAT1_* params to BAT_ behind the scenes.

**Comment by bys1123** [comment]
Oh, can't, right, sorry, typo.
So, new firmware can't compatible on battery settings/messages with old QGC? It didn't syncs BAT_* params to BAT1_* backwards.

**Comment by DonLakeFlyer** [comment]
> It didn't syncs BAT_* params to BAT1_* backwards.

I believe there is still a bug on that in firmware which was fixed here: https://github.com/PX4/Firmware/pull/15985.

Stable should be able to sort of work with single battery setup if the firmware parameter sync stuff works correctly. It is missing setup for BAT1_SOURCE though so in reality not so sure if that causes a problem.

**Pull request merged**
