### PR TITLE
Add TCP-Mpeg2TS support to available video feeds

### PR DESCRIPTION
**Pull request by zthorson**
This adds Mpeg2 Transport stream over TCP support as a possible video feed in the gstreamer pipeline.

This is used in cases where a local ground station receives the video feed from the aircraft, and rebroadcasts it out to multiple ground stations or devices over a wireless link.   Since the network is local and broadcast to more than a single client, occasional packet drops between the ground station and devices occur, which TCP helps to mitigate.

It is not recommended to use TCP/MPEG2_TS as a datalink to directly to the aircraft, since the re transmits that occur over TCP can build up during a loss of link condition causing additional bandwidth overhead and latency issues.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dogmaphobic @jaxxzer Video folks, can you take a look for code review?

**Comment by dogmaphobic** [comment]
I'm way too swamped to test this properly right now. @jaxxzer if you could take a look, that would help a lot. You might want to look into #5436 too :P

**Comment by NaterGator** [comment]
Just doing a read through the code looks sane. I'm not entirely sure the pipelineUp change  / assuming the pipeline will unref everything is necessary but we'll just watch for leaks I guess.

The thing I'm less convinced of is that TCP is _ever_ appropriate for real time video streaming applications. The only thing you can accomplish here is accumulated latency in the pipeline with occasional skips to get back to realtime. For real time streaming I have never seen MPEG2-TS work more effectively over TCP than it does over UDP. 

I suppose there is no harm in having the option for TCP and I certainly like MPEG2-TS as a streaming container format, I just feel like we should be steering users towards UDP for a better experience.

**Comment by zthorson** [comment]
@NaterGator 

The piplineUP change was done when I started getting a bunch of warning messages after the pipeline failed to link.  It would get the pipeline setup, then fail to link resulting in a teardown.  During the teardown, the logs would be flooded with warnings not to dereference the components directly, and instead let the pipline do it.  It is probably not strictly necessary, but removed some unhelpful log spam during certain fault conditions.

I agree that for a standard aircraft ---> qgroundcontrol that TCP is not the way to go due to the issues that you mentioned.   This was added mostly for the situation described below, where rebroadcasting data is done over a somewhat lossy link, resulting in higher than normal image tearing at the qgroundcontrol end.    For our particular application (fixed wing aircraft, not manually flown), reducing image tearing was given a higher priority than increased latency.


                        UDP Aircraft Feed                       Local Network (can be lossy)
aircraft ---[UDP|MPEG2TS|H264]---> receiver ----[TCP|MPEG2TS|H264]----> QgroundControl
                                                                          |---[TCP|MPEG2TS|H264]----> Mobile Video Player #1
                                                                          |---[TCP|MPEG2TS|H264]----> Mobile Video Player #2

**Comment by DonLakeFlyer** [comment]
Going to wait a little bit more till Gus has some free time to look through this.

**Comment by DonLakeFlyer** [comment]
@jaxxzer Did you have a chance to look through this?

**Comment by jaxxzer** [comment]
I won't have the time for this for another week or so.

**Comment by NaterGator** [comment]
@zthorson for the network topology you describe you'd be *much* better off using multicast if your networking equipment will cooperate.

**Comment by zthorson** [comment]
@NaterGator

We had experimented with multicast in the past, and found that wifi implementation of multicast was spotty at best across different routers.  In many routers, broadcast of a multicast from a wired link through to the wireless clients was not implemented at all.

The TCP local rebroadcasting also helped to negate some interference issues that can occur in ground stations that are near other sources of 2.4Ghz interference (DJI transmitters, cell towers, etc)

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Gus are you clearer now?

**Comment by DonLakeFlyer** [comment]
I did a code review through. Even though I don't know much about how video works it all seems to make sense and it's been sitting here forever so I'm going to merge this in.

**Pull request merged**
