### PR TITLE
Mission Plan Tweaks

### PR DESCRIPTION
**Pull request by NaterGator**
For #3456.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@NaterGator Does this have the height display item fix in it as well?

**Comment by NaterGator** [comment]
Forgive me, is that the one about altitude input + focus weirdness or the one about the altitude preview at the bottom not tracking?  (Or something else I missed entirely)

**Comment by DonLakeFlyer** [comment]
See my comments on your pervious pull with image showing the problem.

**Comment by DonLakeFlyer** [comment]
Height display is showing blank space for items without coordinates.

**Comment by NaterGator** [comment]
Sorry, didn't see that image before. I'll get a fix in right now...

**Comment by DonLakeFlyer** [comment]
Want to do some testing with this then I'll merge.

**Comment by DonLakeFlyer** [comment]
The height display at the bottom doesn't scroll as new items are added outside of the view. Should that be working?

**Comment by DonLakeFlyer** [comment]
@NaterGator I'm merging this since it works for what it does. But it would be great if you could add the change to height display to auto-scroll to current item as well.

**Comment by NaterGator** [comment]
@DonLakeFlyer that auto scroll on the bottom status is working for me on Windows. What OS are you experiencing it not working on?

**Comment by DonLakeFlyer** [comment]
OSX. Let me try windos to make sure it's working there.

**Comment by NaterGator** [comment]
@DonLakeFlyer any news on this?

**Comment by DonLakeFlyer** [comment]
Not working on Windows either for me.

**Pull request merged**
