### PR TITLE
Mission Editor usability changes

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Too many to remember:
screenshot_2015-10-16-20-10-06

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dagar Could you show me how to debug the fact that the mac builds are just sitting there with no builds started on them? Can't seem to find any info on travis.

**Comment by DonLakeFlyer** [comment]
Maybe just a backlog? https://www.traviscistatus.com

**Comment by dagar** [comment]
Yes it's a backlog. I was seeing the same thing with PX4/Firmware builds.

**Comment by DonLakeFlyer** [comment]
If I find some sort of problem is there a place to report issues?

**Comment by dagar** [comment]
> If I find some sort of problem is there a place to report issues?

twitter :wink: 

In this case I'm fairly certain they already know. The best thing we can do is reduce load on their infrastructure. Cancel builds we don't need or that have already failed on linux, revisit precompiled headers, etc.

**Comment by DonLakeFlyer** [comment]
Yeah I now. Just wanted to know for future. Twitter!

**Comment by dagar** [comment]
Partially joking. There's also support@travis-ci.com.

**Pull request merged**
