### PR TITLE
[WIP]: added important tuning parameters/sliders for plane

### PR DESCRIPTION
**Pull request by barzanisar**
These are all the tuning parameters Fixed Wing users find useful for tuning, as discussed with @RomanBapst.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
I don't necessarily agree with the direction this is heading. Setup pages are for parameters which are commonly changed. This seems like every fixed wing tuning parameter that is possible. Do most normal users really need to tune all of these things! Parameters which are rarely changed are left to be edited in the parameter editor.

Think of it this way:
* The user picks a standard fixed wing airframe which in turns sets various defaults.
* Beyond that what do they really need to tweak to get a flying vehicle.

There are multiple modes of tuning:
* Tuning from a standard airframe, for non-power users. This is what the tuning page is mostly now.
* PID tuning which is power user stuff and require charts and what not. This is what the Advanced thing from daily builds is heading towards.
* Power user tuning of all parameters. This is more left to the parameter editor. The current goal is not to have a page which contains a UI for every parameter on the vehicle.

**Comment by DonLakeFlyer** [comment]
The PID tuning and Power user tuning of all related params could theoretically go together on the UI. That way you have a simple ui for non-power users, and the advanced one for people who know whta they are doing.

**Comment by DonLakeFlyer** [comment]
I think something like this could work:
* Page: Simple tuning params (like throttle hover for multi-rotor)
* Page: PID Tuning
* Page: Full set of tunable params

Opinions?

@RomanBapst Is this list of params all really simple tuning, or could they be split up?

**Comment by barzanisar** [comment]
> Page: Full set of tunable params

Why do we need a page for full set of params when we have them in params? Maybe we can have just the commonly used ones in the "Page: PID Tuning".

**Comment by DonLakeFlyer** [comment]
> Why do we need a page for full set of params when we have them in params?

I'm not sure this is needed. I think you just do to parameter editor for that.

**Pull request closed without merging**
