### PR TITLE
correct spelling mistakes

### PR DESCRIPTION
**Pull request by nopeppermint**
-correct spelling mistakes found with https://github.com/lucasdemarchi/codespell

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
This needs to be more targeted:
- xbee libs are third party so we shouldn't be modifying those
- same issue for qwt changes

**Comment by DonLakeFlyer** [comment]
@nopeppermint You should just run this in the src directory so you don't hit thirdy party stuff. Any updates?

**Comment by nopeppermint** [comment]
@DonLakeFlyer now only corrections in the src directory and the file QGCCommon.pri
are there.

**Comment by DonLakeFlyer** [comment]
Awesome, thanks I'll go through it.

**Comment by DonLakeFlyer** [comment]
Great thanks.

**Comment by DonLakeFlyer** [comment]
Oops, wrong button.

**Pull request merged**
