### PR TITLE
localization: Organize the same line elements.

### PR DESCRIPTION
**Pull request by muramura**
I organized the same line elements.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Translation file are output by crowdin. So as far as I understand modifying the manually won't have an affect. Since the next push down from Crowdin to QGC will overwrite it (and possible cause merge conflicts).

**Comment by hamishwillee** [comment]
Correct. 
The extra line is in the **source** that crowdin is getting - so this is a .ts file generation issue. @dogmaphobic do you have any power over what is generated?

Gus, crowdin shows duplicate files - are they both valid? If not, which should we delete? 
image

**Comment by DonLakeFlyer** [comment]
> The extra line is in the **source** that crowdin is getting - so this is a .ts file generation issue.

I don't get where this "extra line" is? If I look at the diff it looks like the changes are maybe only in spaces or tabs or something? There is no change in the non-whitespace stuff.

Screen Shot 2020-08-24 at 8 41 46 AM

**Comment by hamishwillee** [comment]
@DonLakeFlyer The diff shows the file after the duplicate line has been removed. So the source has line with tag `location` twice.

image

**Comment by DonLakeFlyer** [comment]
Duh!

**Comment by DonLakeFlyer** [comment]
Which all still all comes back to not understanding why this pull is needed? @muramura? Are these extra lines causing some sort of problem?

**Comment by DonLakeFlyer** [comment]
Closing unless I get more info

**Comment by muramura** [comment]
It works fine even if there are multiple same lines.

**Pull request closed without merging**
