### PR TITLE
GPS/Drivers: Update submodule, fix RTK for F9P, fix RTK for Septentrino

### PR DESCRIPTION
**Pull request by julianoes**
This updates the GPS driver submodule to latest main. This includes a fix for RTK for the uBlox F9P where a config failed and prevent proper init of the GPS module.

Also, this includes the RTK config for Septentrino.

FYI @vincentpoont2

### CODE REVIEW

**Comment by HTRamsey** [comment]
@julianoes Is there any value in updating the actual GPS implementation using that driver? In the past I had considered going through and adding the other gps drivers, updating the structs that are implemented from the PX4 .msg files, etc.

**Comment by julianoes** [comment]
@HTRamsey do you mean creating a copy of it, and not sharing it with PX4 anymore? I sometimes considered that. On the other hand, it seems to work ok enough.

**Comment by HTRamsey** [comment]
@julianoes oh actually I see you already did some of what I had looked into previously in a Feb commit. Like I remember sensor_gps.h was missing some values that it seems you added. I don't think sensor_gnss_relative.h is used at all. GPSProvider.cc is missing some of the drivers that are available in the Drivers submodule. Stuff like that.

**Comment by julianoes** [comment]
Right, yes, I did a bit of updating there.

**Comment by HTRamsey** [comment]
Is it worth it to update the other stuff too? Like adding the missing drivers in GPSProvider.cc, and making use of the sensor_gnss_relative.h file?

**Comment by julianoes** [comment]
I don't know. Do we need anything from that? And what missing drivers would that be? I don't know if I have them to test it.

**Comment by HTRamsey** [comment]
Well right now it looks like it just supports ashtech, sbf, and ublox. I guess it supports NMEA through the Qt position source stuff instead of the GPSProvider. Not sure it gets all the same functionality thought. Also I don't know much about all those other drivers like emlid_reach, femtomes, mtk, unicore, etc.

**Comment by flyingthingsintothings** [comment]
It's nice to see an update to the RTCM setup for the SBF driver being added to QGC, as automatic base setup in the SBF driver is not working in the latest trunk version. I just wanted to ask how this submodule update had been tested in the latest version of QGC as the setting to choose between "survey-in" and "fixed position" that used to exist under application settings seems to be gone? I've quickly updated the submodule locally to test what happens, but I don't know where the configuration that is applied comes from. There is [this code](https://github.com/PX4/PX4-GPSDrivers/blob/3ea1d763a35d9b4a522e0c632db5bdfffad9ae23/src/sbf.cpp#L227C2-L241C3) in the PX4-GPSDrivers submodule that is used for RTCM setup, but I don't see either of the configs in the if or the else path being applied to the receiver. Instead another configuration seems to be applied.

**Comment by julianoes** [comment]
I think the settings have moved. Click on the GPS symbol in the top bar, then on the little arrow which unfolds a settings panel.

**Comment by flyingthingsintothings** [comment]
I ran this code with a debugger in Qt Creator, watching what happens in the SBF driver when `_base_settings.type` is set to `survey_in`. It does reach the correct path at the bottom of `SBFDriver::configure()`, but the configuration does not appear on the receiver. There are no checks whether `sendMessageAndWaitForAck()` completes correctly. I think something might go wrong in that function, as everything up to there works and is correctly applied on the receiver side.

**Configuration right after the call to `sendMessageAndWaitForAck(SBF_CONFIG_RTCM, SBF_CONFIG_TIMEOUT);`**

image

**Status of the debugger when the first screenshot was taken**

image

**Comment by julianoes** [comment]
@flyingthingsintothings I'm confused. It works for me. Can you tell me what's wrong and what needs changing?

**Comment by flyingthingsintothings** [comment]
I'm running QGroundControl 4.3.0-369-6f76a4063 (The branch for this PR). I'm also running PX4 v1.14.0 on a Pixhawk 6C. I clear all the configuration from both receivers (the rover, attached to the Pixhawk 6C, as well as the base, connected over USB to the laptop running QGroundControl). When I open QGroundControl and wait for a couple of minutes, this is the configuration I get on the base receiver:

**Configuration on base receiver after QGroundControl sets it up:**
image

This isn't the configuration I expect to show up, as the used configuration (in the drivers submodule) includes other instructions as well. From running the code with a debugger, I know it is supposed to use this string as the configuration for the base station. Here is an example of manually running the selected line from the driver configuration on the receiver:

**After manually running the blue line on the receiver:**
image

Now it shows up correctly in the runtime configuration (compare to first image). I don't know what needs to be changed exactly but I would expect the blue line to show up on the base receiver after QGroundControl automatically sets it up.

**Comment by julianoes** [comment]
Sorry, I'm still confused.

**Comment by flyingthingsintothings** [comment]
This is the base receiver (attached to laptop) configuration when running QGroundControl v4.3.0 instead of the branch for this PR. The value of `SBF_CONFIG_RTCM` didn't change between v4.3.0 and this PR, yet the applied configuration is different. Compare with the image above which is the configuration with this branch.

**Older automatically applied base configuration from QGroundControl v4.3.0:**
image

**Comment by julianoes** [comment]
And does v4.3.0 work?

**Comment by flyingthingsintothings** [comment]
The automatic configuration in v4.3.0 doesn't give a working RTK fixed position on the autopilot for me either. My comments were mostly about the difference between the two (v4.3.0 vs this PR) since the update in the submodule was meant to fix something that was removed by accident, but even after reintroducing the `SBF_CONFIG_RTCM` macro, it doesn't show the same functionality it did in v4.3.0. I guess it's OK if this is merged already, but some more work on the submodule will have to be done and a new PR will have to be made here to update it again, as the automatic base setup in the SBF driver seems to not be working correctly. Sorry for the confusing comments. I only wanted to point out the difference in automatic base setup behavior between this and v4.3.0.

**Comment by julianoes** [comment]
> as the automatic base setup in the SBF driver seems to not be working correctly.

So you confirm that it actually does work correctly now, right?

**Comment by flyingthingsintothings** [comment]
I can confirm that QGroundControl v4.3.0 sets up the base receiver (attached to the laptop running QGroundControl) automatically so that the rover receiver (attached to the Pixhawk) gets an RTK fixed position. QGroundControl compiled from this PR does not set up the base receiver in a way that the rover receiver gets an RTK fixed position.

**Comment by julianoes** [comment]
Ok, so that means I broke it and it was working before while I assumed it had been broken and I fixed it :smile:. Let me do more testing...

**Comment by flyingthingsintothings** [comment]
I tested this PR again today and now it does automatically apply the correct configuration and I get an RTK fixed position on the autopilot. I guess sometimes it works and sometimes it doesn't... I always reset the receivers to "factory default" settings (no configuration, soft reset) so that wouldn't have changed. Today I get this configuration on the base receiver, instead of [the configuration I got a few days ago](https://github.com/mavlink/qgroundcontrol/pull/11230#issuecomment-2003232872). It's the exact same build of QGroundControl I used back then so I have no clue why it works now.

image

**Comment by julianoes** [comment]
Ok, so what I found so far is that:

4.3.0:

- First startup/config from fresh receiver: works
- Subsequent startups: don't work

Config set:
```
setDataInOut, USB1, , RTCMv3+SBF
setSBFOutput, Stream1, DSK1
setSBFOutput, Stream2, USB1
setSBFOutput, Stream3, USB1
setSBFOutput, Stream1, , MeasEpoch+MeasExtra+EndOfMeas+OutputLink+GPSRawCA+GPSRawL2C+GLORawCA+GALRawINAV+GEORawL1+GPSNav+GPSAlm+GPSIon+GPSUtc+GLONav+GLOAlm+GLOTime+AuxAntPositions+GALNav+GALAlm+GALIon+GALUtc+GALGstGps+GALAuthStatus+AttEuler+GEONav+GEOAlm+BaseVectorGeod+PVTGeodetic+PosCovGeodetic+DOP+EndOfPVT+ExtEvent+DiffCorrIn+BaseStation+InputLink+ChannelStatus+ReceiverStatus+ReceiverSetup+Commands+BDSRaw+IPStatus+QZSRawL1CA+QZSRawL2C+PVTSupport+BDSAlm+BDSNav+QualityInd+NTRIPClientStatus+DiskStatus+NTRIPServerStatus+RFStatus+QZSNav+QZSAlm+RxMessage+DynDNSStatus+PVTSupportA+BDSIon+BDSUtc+P2PPStatus
setSBFOutput, Stream2, , VelCovGeodetic+DOP
setSBFOutput, Stream3, , PVTGeodetic
setSBFOutput, Stream1, , , msec100
setSBFOutput, Stream2, , , sec1
setSBFOutput, Stream3, , , msec200
setElevationMask, Tracking, 10
setElevationMask, PVT, 10
setSatelliteUsage, G01+G02+G03+G04+G05+G06+G07+G08+G09+G10+G11+G12+G13+G14+G15+G16+G17+G18+G19+G20+G21+G22+G23+G24+G25+G26+G27+G28+G29+G30+G31+G32+R01+R02+R03+R04+R05+R06+R07+R08+R09+R10+R11+R12+R13+R14+R15+R16+R17+R18+R19+R20+R21+R22+R23+R24+R25+R26+R27+R28+R29+R30+E01+E02+E03+E04+E05+E06+E07+E08+E09+E10+E11+E12+E13+E14+E15+E16+E17+E18+E19+E20+E21+E22+E23+E24+E25+E26+E27+E28+E29+E30+E31+E32+E33+E34+E35+E36+S120+S121+S122+S123+S124+S125+S126+S127+S128+S129+S130+S131+S132+S133+S134+S135+S136+S137+S138+S139+S140+S141+S142+S143+S144+S145+S146+S147+S148+S149+S150+S151+S152+S153+S154+S155+S156+S157+S158+C01+C02+C03+C04+C05+C06+C07+C08+C09+C10+C11+C12+C13+C14+C15+C16+C17+C18+C19+C20+C21+C22+C23+C24+C25+C26+C27+C28+C29+C30+C31+C32+C33+C34+C35+C36+C37+C38+C39+C40+C41+C42+C43+C44+C45+C46+C47+C48+C49+C50+C51+C52+C53+C54+C55+C56+C57+C58+C59+C60+C61+C62+C63+J01+J02+J03+J04+J05+J06+J07
setFileNaming, DSK1, Incremental
setFileNaming, DSK1, , "px4rtcm"
```

This pull request:

- First connection, works.
- Subsequent connection fail...
I'll dig further.

**Comment by julianoes** [comment]
@flyingthingsintothings ok, I did a bit of trial and error and it seems to be working for me now, the first time as well as subsequent times.

**Comment by flyingthingsintothings** [comment]
I quickly tested it as well and now it seems to work fine again. Thank you for fixing this and sorry for all the confusing comments 😄

**Comment by DonLakeFlyer** [comment]
@HTRamsey If you look at the CI android build failure I'm seeing that same thing in a number of pulls. Is that something that has been fixed already and folks need to rebase and run CI again?

**Pull request merged**
