### PR TITLE
Update SDL2 library

### PR DESCRIPTION
**Pull request by holden-zenith**
Allows use of new controllers like Sony Dualsense

### CODE REVIEW

**Comment by holden-zenith** [comment]
@mrpollo we need the compiled dll

**Comment by DonLakeFlyer** [comment]
Android and OSX also have SDL2 libraries in the repo. This should updated as well to match the windows version.

**Comment by holden-zenith** [comment]
Android does not

**Comment by mrpollo** [comment]
thanks @holden-zenith

**Pull request merged**
