### PR TITLE
Parameter Editor: Support editing of non-default component params

### LINKED ISSUE #6964: Parameter Editor: Doesn't show parameters from all components
Only shows default component.

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Fix #6964

screen shot 2018-11-07 at 12 42 04 pm

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
This got trashed a while back and was never put back.

**Comment by edwinhayes** [comment]
Is this supposed to be complete/working?  For me, the behaviour on daily build is a little weird: clicking on the first non-default component in the menu on the RHS works as expected, but then if you click on _another_ non-default component the parameters don't update.

**Comment by DonLakeFlyer** [comment]
Can you move that into a separate issue?

**Comment by edwinhayes** [comment]
Yep, just wanted to check it wasn't known unfinished first.

**Pull request merged**
