### PR TITLE
Use clearer languagee to differentiate between flight mode selection,…

### PR DESCRIPTION
**Pull request by LorenzMeier**
… remove a lot of the text in advanced config

### CODE REVIEW

**Comment by LorenzMeier** [comment]
screen shot 2016-03-06 at 17 42 39

screen shot 2016-03-06 at 17 36 55

**Comment by LorenzMeier** [comment]
screen_single

**Comment by LorenzMeier** [comment]
screen_multi

**Comment by DonLakeFlyer** [comment]
Yeah better. I wonder about pulling out PWM values. I guess they are evenly distributed so it may be ok.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer screens are up. I fixed the typos that you partially still find in them.

**Comment by LorenzMeier** [comment]
I pulled the PWM values out in simple. I don't think we should touch advanced for now.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Could you take over and add the channel monitor here? Then it would be good to go I guess.

**Comment by DonLakeFlyer** [comment]
I'm taking this one over

**Pull request closed without merging**
