### PR TITLE
Fix QGC icon (bloated Q)

### PR DESCRIPTION
**Pull request by gillamkid**
# Description
The QGC icon shown in the top left corner of the app did not match the typical QGC icon seen everywhere else (icon of QGC shortcut made after an install, icon branding on QGC website, etc). I replaced the instances of the extra-bloated Q with the more common QGC icon

## Sponsor
This contribution was sponsored by [Firestorm](https://www.launchfirestorm.com/)
654d4f9476ff2a38f37e9ab9_firestorm-homepage-share-img-2

## Before/After (icon in app)
before-icon-in-app
after-icon-in-app

## Before/After (icon in svg editor view to show outline change)
before-qgc-icon
after-qgc-icon

### CODE REVIEW

**Comment by mrpollo** [comment]
Where did you find the icon? Did you make a new one? I have a collection of those, perhaps we should start a repo. 

One tiny nitpick request, can you please run the SVGs through an optimizer and minifier? It will help get rid of metadata and clean it up

**Comment by gillamkid** [comment]
@mrpollo I modified the original icon using an svg editor (inkskape on Ubuntu). 

I ran the icons through a minifier and it reduced their size by about half!

**Review by dagar — APPROVED** [review]

**Review by MaEtUgR — APPROVED** [review]
Looks like a good find to me.
Matches the original Logo look more closely.
image

**Comment by mrpollo** [comment]
Thanks @gillamkid

**Pull request merged**
