### PR TITLE
Condition SDL counts so we don't pass negative numbers to new

### PR DESCRIPTION
**Pull request by NaterGator**
Should address #4425

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Thanks again Nate

**Comment by DonLakeFlyer** [comment]
@dagar Wonder if I could use you git prowess for a minute. Can you cherry pick this to Stable_V3.1 and then make a v3.1.2 label?

**Comment by dagar** [comment]
On the way - https://ci.appveyor.com/project/mavlink/qgroundcontrol/build/v3.1.2-3889

FYI all I did was switch to the Stable_V3.1 branch and cherry-pick Nate's commit (47a2ae1), then created a new tag (v3.1.2).

**Comment by DonLakeFlyer** [comment]
Could you detail out the git commands line by line and then morons like me can do it...

**Comment by dagar** [comment]
Ha, sure. You can do all of this is most graphical clients.

    git checkout Stable_V3.1
    git cherry-pick 47a2ae1
    git tag -s v3.1.2

    git push mavlink v3.1.2
    git push mavlink Stable_V3.1

    # this is the only weird bit
    # it makes the master version v3.1.2 + # new commits which Google play needs for the beta version
    git checkout master
    git merge v3.1.2 
    git push mavlink master

**Pull request merged**
