### PR TITLE
Vehicle: remove popup on regained connection

### PR DESCRIPTION
**Pull request by julianoes**
In my opinion this popup is just annoying and distracting. I can see if the connection has been regained by the color of the top bar already.

Just my opinion, you can close the PR if you disagree :smile:.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Unit test failing on merit:
```
FAIL!  : VehicleLinkManagerTest::_connectionRemovedTest() Compared values are not the same
   Actual   (spyVehicleInitialConnectComplete.wait(3000)): 0
   Expected (true)                                       : 1
   Loc: [/home/travis/build/mavlink/qgroundcontrol/src/Vehicle/VehicleLinkManagerTest.cc(249)]
QDEBUG : VehicleLinkManagerTest::_connectionRemovedTest() ~MockLink MockLink(0x559387a96550)
QDEBUG : VehicleLinkManagerTest::_highLatencyLinkTest() MockLink MockLink(0x559387a96550)
QDEBUG : VehicleLinkManagerTest::_highLatencyLinkTest() Sending 65536
QDEBUG : VehicleLinkManagerTest::_highLatencyLinkTest() _parametersReady true
QDEBUG : VehicleLinkManagerTest::_highLatencyLinkTest() say " manual flight mode"
QDEBUG : VehicleLinkManagerTest::_highLatencyLinkTest() say " armed"
QDEBUG : VehicleLinkManagerTest::_highLatencyLinkTest() MockLink MockLink(0x559387acfd80)
QDEBUG : VehicleLinkManagerTest::_highLatencyLinkTest() say " disarmed"
QDEBUG : VehicleLinkManagerTest::_highLatencyLinkTest() say "communication lost on primary link."
QDEBUG : VehicleLinkManagerTest::_highLatencyLinkTest() QGCApplication::showAppMessage unittest title:message "QGroundControl_unittest" "Communication lost on primary link."
QDEBUG : VehicleLinkManagerTest::_highLatencyLinkTest() say "switching communication to secondary link."
QDEBUG : VehicleLinkManagerTest::_highLatencyLinkTest() QGCApplication::showAppMessage unittest title:message "QGroundControl_unittest" "Switching communication to secondary link."
QDEBUG : VehicleLinkManagerTest::_highLatencyLinkTest() ~MockLink MockLink(0x559387acfd80)
QDEBUG : VehicleLinkManagerTest::_highLatencyLinkTest() ~MockLink MockLink(0x559387a96550)
PASS   : VehicleLinkManagerTest::_highLatencyLinkTest()
PASS   : VehicleLinkManagerTest::cleanupTestCase()
Totals: 5 passed, 2 failed, 0 skipped, 0 blacklisted, 25393ms
```

**Review by LorenzMeier — CHANGES_REQUESTED** [review]
Needs an update to the unit test as well.

**Comment by julianoes** [comment]
Right, I can fix the unit tests if the overall opinion is actually to remove this. If it should stay, I won't bother.

**Comment by bkueng** [comment]
+1

**Comment by LorenzMeier** [comment]
I would remove.

**Comment by julianoes** [comment]
@LorenzMeier please review again. It looks like CI was just a fluke.

**Comment by DonLakeFlyer** [comment]
> In my opinion this popup is just annoying and distracting.

In general I agree.

> I can see if the connection has been regained by the color of the top bar already.

But the problem is that this statement is only correct in the single link case. The example would be say a combination high latency and low latency link comm setup. The vehicle is currently using the low latency link as primary. Comm is lost on the high latency link and then regained. Since overall communication is not lost this has no affect on the showing indications in the toolbar on comm lost. You only get the popups and there is comm lost/available status in the link dropdown items.

I think something can be done here but it is going to require a more nuanced approach.

**Comment by DonLakeFlyer** [comment]
@julianoes I'm tracking the discussion on this in #9486.

**Comment by julianoes** [comment]
Ok, thanks for the response @DonLakeFlyer

**Pull request closed without merging**
