### PR TITLE
Fix Windows build with wrong character set

### PR DESCRIPTION
**Pull request by deiuch**
See reverted #8814.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
I don't understand what problem this fixes?

**Comment by deiuch** [comment]
> I don't understand what problem this fixes?



> I don't understand what problem this fixes?

The project did not build on MSVC due to "warnings as errors", and this flag fixes the warning that blocked the building process. I was able to fix the build with this flag.

**Comment by DonLakeFlyer** [comment]
Are you running latest master? If so, what language is your machine set to?

**Comment by DonLakeFlyer** [comment]
@deiuch I believe the bad characters in source files have been removed such that this is no longer needed. Can you retry building latest master.

**Pull request closed without merging**
