### PR TITLE
cmake add APMMavlinkStreamRateSettings.cc to Settings

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Ah, their in the individual directories. No wonder I couldn't find them.

**Comment by dogmaphobic** [comment]
Note that the addition of `APMMavlinkStreamRateSettings.cc/h` broke the builds where ArduPilot is disabled. I'm about to push a PR excluding all this code for builds that do not support ArduPilot. This will need to be reflected in cmake as well.

**Comment by dagar** [comment]
Tag me and I'll make the cmake change when I'm back.

**Comment by dogmaphobic** [comment]
Speaking of cmake, how does it handle "custom" builds?

**Comment by dogmaphobic** [comment]
I guess it doesn't. It's even hardcoded to "ardupilotmega". This doesn't seem it will work for custom builds where a lot of what is included/built can be changed based on custom configurations.

**Comment by dagar** [comment]
We should go over the full list for feature parity.

**Pull request merged**
