### PR TITLE
Limit output of camera and lights using brd_pwm_count

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Is BRD_PWM_COUNT a parameter which exists in older firmware versions as well?

**Comment by patrickelectric** [comment]
Exist since:
APMrover2-2.45
APMrover2-beta
APMrover2-beta-AVR
APMrover2-stable
APMrover2-stable-AVR
AntennaTracker-beta
AntennaTracker-beta-AVR
AntennaTracker-stable
AntennaTracker-stable-AVR
ArduCopter-3.1.5
ArduCopter-beta
ArduCopter-beta-apm1
ArduCopter-beta-apm2
ArduCopter-beta-heli
ArduCopter-stable
ArduCopter-stable-heli
ArduPlane-2.78
ArduPlane-2.78b
ArduPlane-beta
ArduPlane-beta-AVR
ArduPlane-stable-AVR
ArduSub-beta
Copter-3.3-rc5
Rover-3.2.0

**Comment by DonLakeFlyer** [comment]
Ok, those are older than the supported release so this is ok.

**Comment by patrickelectric** [comment]
Ps: the first commit with this parameters was ardupilot/ardupilot@b5822cd549f08186984990013bfca5c70b6fbbf9, ty @jaxxzer

**Pull request merged**
