### PR TITLE
Joystick: Add circle correction option

### PR DESCRIPTION
**Pull request by patrickelectric**
Some digital joysticks have already this correction
Add habilit to add or remove circle correction

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
I need way more details for these pulls. I don't have the time to figure out what this does by looking at the code. Screenshots, more explanation...

**Comment by patrickelectric** [comment]
This code allow the possibility to not use diagonal corrections in digital joysticks.
image
This image shows how the analog works, it's necessary to limit the X and Y distance to make the diagonal.
In digital joysticks this correction is not necessary.
In a analog joystick X and Y can have max value of 1, but in the diagonal it'll have 0.70710678118 ou cos(pi/4) for both. Meanwhile the digital joystick will have the maximum value 1 in the X, Y and in the diagonal :video_game:

**Comment by DonLakeFlyer** [comment]
Ok, so the user has to know whether they can turn this on or not based on the joystick they are using right? Looks like you added checkbox which shows up all the time? Can't quite tell without a screenshot. Seems like this would be better under Advanced to not clutter UI?

**Comment by DonLakeFlyer** [comment]
I guess it depends on how command it will be to use this setting?

**Comment by patrickelectric** [comment]
> Ok, so the user has to know whether they can turn this on or not based on the joystick they are using right? Looks like you added checkbox which shows up all the time? Can't quite tell without a screenshot. Seems like this would be better under Advanced to not clutter UI?
Yes, now with the last commit is in under advanced menu.

> I guess it depends on how command it will be to use this setting?
This allow any user to use a digital joystick without losing 30% of precision in each axis.

**Comment by DonLakeFlyer** [comment]
Ok, awesome thanks. Will merge in a bit. Hand holding some other stuff through rifght now.

**Comment by DonLakeFlyer** [comment]
@patrickelectric This pull is incorrect. Previously circle correction was on by default. Now it is off by default. Needs to go back to on by default. Can you fix this?

**Comment by patrickelectric** [comment]
Yep, I'll take a look.

**Comment by patrickelectric** [comment]
https://github.com/mavlink/qgroundcontrol/pull/6284

**Pull request merged**
