### PR TITLE
VTOL takeoff/land waypoints label VT/VL

### LINKED ISSUE #4035: VTOL takeoff/land icons should be T and L

### PR DESCRIPTION
**Pull request by dagar**
-fixes #4035

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Not sure that two character abbreviations will fit into the indicator on all OS/fonts?

**Comment by dagar** [comment]
I only looked on desktop linux. Is checking on an android phone sufficient? How would you check all OS/fonts?

**Comment by DonLakeFlyer** [comment]
Android would be a good check. I'll try OSX. The size of the indicators is 1.75 * font height. The width isn't taken into account.

**Comment by DonLakeFlyer** [comment]
Seems ok on OSX.

**Comment by DonLakeFlyer** [comment]
I thought you fixed the appveyor thing?

**Comment by dagar** [comment]
This branch doesn't have the fix.

**Comment by dagar** [comment]
Looks fine on my phone, although it's rather large.

**Comment by dagar** [comment]
Okay to merge? I can switch them to just T/L later if it doesn't work on a small device.

**Comment by DonLakeFlyer** [comment]
Just restarted one of the travis jobs. Then I'll merge after.

**Pull request merged**
