### PR TITLE
Plugin-ize geofence for multiple firmware support

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
This should be in a working state for ArduCopter and ArduPlane now.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@lvale This should take it to a workable state if you want to play around with it.

**Comment by DonLakeFlyer** [comment]
UI is still crappy but slightly better.

**Comment by lvale** [comment]
Thanks @DonLakeFlyer I'll report back :)

**Comment by DonLakeFlyer** [comment]
Sorry @lvale this pull is wrong. It will work for Plane but won't work for Copter. Closing to fix it.

**Pull request closed without merging**
