### PR TITLE
Simple mission terrain support

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
screen shot 2018-03-15 at 1 03 28 pm

The above example shows a plan which was done with all waypoints 20 meters above a varied terrain. You can see this as the consistent delta from the terrain bar for waypoints 2-4 at the bottom of the screen.

* Simple mission items can now specify an altitude to be above terrain
* Altitude mode is specified by a dropdown which has the options: Alt (rel), AMSL, Above Terrain
* If you select Above Terrain the altitude you specify is the height above terrain
* Creating/Updating plans which use Above Terrain altitude mode require an internet connection to communicate with the terrain server
* Once the plan is saved you no longer need an internet connection
* Below the Altitude field you will see the actual AMSL altitude for the item
* Until the terrain query returns Actual AMSL Alt will show --.--
* You will not be able to save/upload plans which use terrain data until all the values are updated based on terrain data from server
* The Altitude Mode, Altitude and Actual AMSL Alt values are persisted to saved Plan files
* If you load a plan back from the vehicle which uses Above Terrain Altitude Mode it will return back as an AMSL Altitude Mode item.
* Terrain is not currently supported by complex items
* This **does not** support the ArduPilot terrain following feature. It is just adjusting the actual heights of the mission items using terrain data.

Related to #6204

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
As always this is a fairly large scale new feature. So extra caution with initial usage would be a good idea :)

**Comment by terial** [comment]
Hey Don, any plans to support Ardupilot terrain following?

**Comment by Kelly-Foster** [comment]
+1.

**Comment by DonLakeFlyer** [comment]
Not at the moment.

**Pull request merged**
