### PR TITLE
Hardware: Add support for JFB110

### PR DESCRIPTION
**Pull request by jfbblue0922**
This adds support for the new JFB110 board of Japan Aviation Electronics Industry Ltd.

sorry, I closed PR by mistake, so I'll post it again.

### CODE REVIEW

**Comment by TSC21** [comment]
Is this board already supported and included in the PX4 repos?

**Comment by jfbblue0922** [comment]
@TSC21 

JFB110 is not supported yet by PX4 repository, but we plan to make a PR soon.
we made this PR first because we are using QGC in our current development.

**Comment by rmackay9** [comment]
This board is supported by [AP and our wiki is here](https://ardupilot.org/copter/docs/common-jae-jfb110.html).

I think this PR adds support for QGC to be able to upload AP firmware to the board perhaps?  In which case I think it should be OK to merge it even if PX4 support is not complete.

I've used the board successfully with AP, I haven't tried uploading using QGC with this PR applied (but I don't think that should necessarily hold up merging this change).

**Comment by rmackay9** [comment]
Thanks @HTRamsey!

**Comment by jfbblue0922** [comment]
@rmackay9
@HTRamsey

Thank you everyone for your support.

**Pull request merged**
