### PR TITLE
Use new SplitIndicator control

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
In QGCMapPolyline/gon visuals

### CODE REVIEW

**Comment by tilaktilak** [comment]
Playing with this new feature (create a flight plan, split my lines, erase and create one again) I ended up with a funny view like this :
image
The console says : 
```
Invalid index index:count 6 1
Invalid position position:count 6 2
```

**Comment by DonLakeFlyer** [comment]
How old was the build? I fixed a bunch of this yesterday.

**Comment by DonLakeFlyer** [comment]
@tilaktilak Also when reporting a bug create a new issue for it as opposed to adding comments to a merged pull.

**Comment by tilaktilak** [comment]
It's probably a hash from yesterday morning, I am not able to reproduce it now.

**Comment by DonLakeFlyer** [comment]
I don't doubt there are still bugs in here though. Will take some time to flesh them out.

**Comment by tilaktilak** [comment]
Noted, I'll keep an eye on it and track them on a related issue next time :-)

**Comment by DonLakeFlyer** [comment]
The way the arrows currently should be working:
* On first/last segment
* Every fifth segment in between
* Complex items manage their own arrows using custom logic

**Pull request merged**
