### PR TITLE
[WIP] try qtquickcompiler

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dogmaphobic** [comment]
Let's see how it goes. When I tried this earlier, it also required `QT += qml-private`. Also, I was under the impression this was only available for the commercial license?

**Comment by dagar** [comment]
It's in the open source version now.

**Comment by DonLakeFlyer** [comment]
Isn't a different license though?

**Comment by dagar** [comment]
Need license clarification.

**Pull request closed without merging**
