### PR TITLE
[WIP] First stab at GPS RTK indicator

### PR DESCRIPTION
**Pull request by LorenzMeier**
This is not yet ready for review / testing, but shows the direction I'm trying to take it into. @DonLakeFlyer If you beat me to it it would be fantastic to have an indicator in the toolbar representing the local RTK unit.

### CODE REVIEW

**Comment by bkueng** [comment]
I brought this into a first working state:
qgc_rtk_survey-in_toolbar

Needs more work on the UI and the status should be shown even if no vehicle is connected. Related: #5232

**Comment by DonLakeFlyer** [comment]
So awesome, thanks @bkueng

**Comment by hamishwillee** [comment]
That's cool. Is it just me who scans "Survey-in Active" as "Survey Inactive"?

**Comment by DonLakeFlyer** [comment]
@bkueng Could you:
* Move the RTK FactGroup to QGroundControlQmlGlobal
* Put RTK FactGroup into it's own source/header files
* #ifdef it to be out for mobile builds both in source and qgroundcontrol.pro

Then I think this is perfect for 3.2. For 3.3 we can make it work when no vehicle is connected.

**Comment by bkueng** [comment]
@DonLakeFlyer I'll do that.

@hamishwillee Yes it takes some time to get used to the term. To me it looks ok, but if you have somehing better, we can use that.

**Comment by bkueng** [comment]
I made the following updates:
- used QGroundControlQmlGlobal & moved the source into separate src/header files.
- added the ifdefs for mobile (I think the new source files don't need to be ifdefed)
- the icon is only visible if there is a GPS connected (and a vehicle)
- the icon is red during survey-in (meaning the user should wait), then turns white (meaning it's ready to be used)
- UI & labeling updates.

Looks like this:
qgc_rtk_gps_status2

Just to test I added the QML stuff to MainToolBar.qml, so that the icon is visible without a vehicle connection:
qgc_rtk_gps_status3
It works, but I think the icon is too large, and I did easily see how to change it. @DonLakeFlyer I think this way would be preferred, if we can make it work.

**Comment by hamishwillee** [comment]
@bkueng 
> Yes it takes some time to get used to the term. To me it looks ok, but if you have somehing better, we can use that.

Hard to say without knowing what this does? I am guessing you have a QGC planning mode called "survey-in" where you define  some boundaries and QGC auto-runs/plans a survey inside that boundary. How does RTK fit into that - just makes sure that you stick very closely to those boundaries?

Anyway, without knowing anything about this you could try "Survey-Within Active"

**Comment by bkueng** [comment]
@hamishwillee survey-in is an RTK-related term, coined by u-blox. It describes the startup procedure to get an accurate position for the base station. It is described here: https://docs.px4.io/en/advanced_features/rtk-gps.html. I'll update that once we get this merged.

@DonLakeFlyer CI failure is a build timeout. I tried restarting several times, but always the same problem.

**Comment by hamishwillee** [comment]
Thanks @bkueng . Doing a search on RTK and survey-in shows up nothing useful, so my guess is that from an end user perspective this is an unhelpful term. 

Perhaps "RTK Calibration Active", "RTK GPS Calibration Active", "RTK GPS Setup Active", "Precision GPS Setup Active". I admit not as pithy, but actually meaningful (and there is a chance that they will find something useful if they search on RTK GPS"

**Comment by bkueng** [comment]
Ok, so the u-blox term hasn't caught on. I agree then it should be something meaningful. How about "Acquiring Precise Position"?

The settings page needs updating as well then:
qgc_rtk_survey-in_settings
We can say: "Required position accuracy" instead of "survey in accuracy".

**Comment by hamishwillee** [comment]
I don't mind "Acquiring Precise Position"? but it sounds like something you do only once, and in fact what I think we're doing is calibrating our equipment or setting it up to get precision position information. 

Perhaps "Initiating Precision Positioning", "Starting Precision Location", "Precision Location Setup", "Precision Location Activation" (I quite like the last one, though of course this would be the text on the prompt, not "Precision Location Activation Active" :-)

For the settings page, sure! Alternatives there, maybe "Positional accuracy"  or "Minimal accuracy" (my preference)

**Comment by bkueng** [comment]
Yes you only do it once, then you can fly as many flights as you want, with different vehicles, etc, as long as you keep the base GPS running and at the same location. For that it's an accurate description of what's happening (the base station is actually determining an accurate position by averaging and converging over time).
Either of your suggestions works as well. I think you should see it in action, then you would see that the "Current Accuracy" converges towards 0 over time.

**Comment by DonLakeFlyer** [comment]
@antiheavy For folks doing surveys with RTK they tend to know what "survey-in" means don't they?

**Comment by DonLakeFlyer** [comment]
@bkueng Just getting back in town. I'll look at this tonight.

**Comment by hamishwillee** [comment]
@bkueng - lets see what @Antiheavy says to @DonLakeFlyer. If this is only ever going to be shown to users with knowledge of RTK then Survey-in is OK. We'd make the link for ordinary users in the docs.

**Comment by DonLakeFlyer** [comment]
@bkueng For showing with no vehicle available it should still be small like a toolbar indicators. It's just that it would require more changes to MainToolbarIndicators to make it work since that only shows when there is a vehicle.

**Comment by DonLakeFlyer** [comment]
@bkueng Looks great. Big thanks. Also for 3.3: https://github.com/mavlink/qgroundcontrol/issues/5319

**Comment by Antiheavy** [comment]
The "Survey-in" term isn't a universally understood thing, but in the context of these specific uBlox GPS receivers I think it is fine to use since that is the term uBlox uses.  This could be revisited in the future if Qgroundcontrol is extended to support more/other RTK systems.

"Base Station" is a fairly universally understood term in the world of RTK GPS referring to the (usually stationary) GPS receiver/equipment on the ground side.  To avoid the "Survey Inactive" wording problem I probably would have said something like "Base station status: Surveying-In" and "Base station status: sending RTCM" or something along those lines.

At any rate, what you have here is better than watching a stream of text print to the console so thanks.

As a future improvement I suggest making it more clear what GPS is for the vehicle and what GPS icon is for the "Base Station".   Or better yet, just combine them into 1 toolbar indicator that is typically vehicle centric, but when clicked on for details provides details of both the vehicle GPS and also the base station GPS.

**Comment by DonLakeFlyer** [comment]
Forgot to enter icon issue for 3.2: https://github.com/mavlink/qgroundcontrol/issues/5324. @dogmaphobic?

**Comment by DonLakeFlyer** [comment]
Also added a new issue for RTK wording which copies Todd's comment above: https://github.com/mavlink/qgroundcontrol/issues/5325

**Comment by Francklin2** [comment]
Hi 
I worked on a RTKlib interface on raspberry( RTKLIB_Touchscreen_GUI ), for the base I use a image showing a groundstation, to be more clear you may use a icon like the second one upper left here for the ground base.
image

Thanks for your nice work on RTK intégration

**Comment by DonLakeFlyer** [comment]
@Francklin2 Thanks. Could you move these images into a separate Issue for the RTK icon. And then I'll look at changing it.

**Comment by Francklin2** [comment]
I put them  in the icon issue #5324 (looks like the correct one)

**Pull request merged**
