### PR TITLE
Code correction, Qt5.10 compatibility 

### PR DESCRIPTION
**Pull request by patrickelectric**
This is the new QGeoMapType constructor.
```
QGeoMapType();
    QGeoMapType(const QGeoMapType &other);
    QGeoMapType(MapStyle style, const QString &name, const QString &description, bool mobile,
                bool night, int mapId, const QByteArray &pluginName,
                const QGeoCameraCapabilities     &cameraCapabilities,
                const QVariantMap &metadata = QVariantMap());
```

Code tested and working :)

### CODE REVIEW

**Comment by dogmaphobic** [comment]
Have you tried building with 5.9.1 and 5.9.2? They should remain compatible.

**Comment by patrickelectric** [comment]
:shipit:

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Review?

**Comment by patrickelectric** [comment]
A christmas gift !

**Pull request merged**
