### PR TITLE
MAVLink Inspector: add hygrometer message display

### PR DESCRIPTION
**Pull request by gitfishup**
MAVLink Inspector: add hygrometer message display.
the frequency is 5Hz. 

https://user-images.githubusercontent.com/69180601/130941687-83ff1f51-5ce0-4984-8f63-ec34da8863eb.mp4

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Seems to me that this should go into its own hygrometer FactGroup instead of being values at the top of the Vehicle property hierarchy.

**Comment by gitfishup** [comment]
> Seems to me that this should go into its own hygrometer FactGroup instead of being values at the top of the Vehicle property hierarchy.

Could you please give me an example?

**Comment by DonLakeFlyer** [comment]
https://github.com/mavlink/qgroundcontrol/blob/master/src/Vehicle/Vehicle.h#L302

**Comment by gitfishup** [comment]
@DonLakeFlyer How about this? I have changed.

**Comment by gitfishup** [comment]
The flight controller receive the hygrometer message from CAN device and flight controller send hygrometer message to the ground station.

background:
CUAV developed a new airspeed sensor that can be heated.The airspeed sensor heats up according to the set temperature, so as to prevent airspeed failure due to ice on the head of the airspeed sensor when the fixed-wing UAV is used in high and cold places.The temperature and humidity sensor is used to detect the temperature and humidity of the pitot tube head. If the measured temperature is lower than the set temperature, the airspeed sensor will enable heating to prevent ice.

**Comment by gitfishup** [comment]
> https://github.com/mavlink/qgroundcontrol/blob/master/src/Vehicle/Vehicle.h#L302

@DonLakeFlyer Could you please have a review?

**Comment by gitfishup** [comment]
@DonLakeFlyer @patrickelectric Is this ready to be merged?

**Comment by DonLakeFlyer** [comment]
This is failing build. Does this need a mavlink submodule bump to go along with it?

**Comment by DonLakeFlyer** [comment]
Rebase this pull to master and it should hopefully pass CI

**Comment by gitfishup** [comment]
> Rebase this pull to master and it should hopefully pass CI

@DonLakeFlyer Continued in https://github.com/mavlink/qgroundcontrol/pull/9944.

**Pull request closed without merging**
