### PR TITLE
Improve parameter bitmask value on parameter widget

### PR DESCRIPTION
**Pull request by patrickelectric**
Show a list of selected bit and the string value for each one over the "Unknown: X" string

https://user-images.githubusercontent.com/1215497/126830106-ae5157a0-c66d-454e-917c-e0886db4ea0f.mp4

### CODE REVIEW

**Comment by patrickelectric** [comment]
ping @DonLakeFlyer

**Comment by jaxxzer** [comment]
I think it's better and more user friendly.

**Review by jaxxzer — APPROVED** [review]

**Comment by DonLakeFlyer** [comment]
Seems to me that this new text should just be returned directly in `valueString` for this case instead of adding a new property.

**Comment by DonLakeFlyer** [comment]
> Seems to me that this new text should just be returned directly in `valueString` for this case instead of adding a new property.

@patrickelectric Can you update?

**Comment by DonLakeFlyer** [comment]
Good enough for now

**Pull request merged**
