### PR TITLE
update fixed wing cmd default values

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dagar Just checking that I understand. These are just in order to get a different default for loiter radius for Fixed Wing right? Kind of crappy to have to dupe all of it just for a default, but no other way right now. Need to consider partial override capability at some point.

**Comment by dagar** [comment]
Yes, everything in src/FirmwarePlugin/PX4/MavCmdInfoFixedWing.json is just for better fixed wing defaults. I believe all of it could be shared with APM if there's a way.

**Comment by DonLakeFlyer** [comment]
No it can't shared now. But you should dup this stuff to the APM side as well for now. I've added an issue for a better way to do this in 3.1

**Comment by dagar** [comment]
PX4 fixed wing metadata duplicated for APM.

**Pull request merged**
