### PR TITLE
Defer loading and binding of mission editing QML components

### PR DESCRIPTION
**Pull request by NaterGator**
Also should finally fix mission editor view sync when changing current waypoint.

During creation of a very large mission with 100s of points I noticed the mission editor was getting really laggy. QML profiler showed the editor bindings for the simple mission item delegate were extremely expensive and slow.

Instead, load them only for each point when it is selected. This makes the ListView scroll smoothly with a ton of points too.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
I should have some time to take a look a this later today.

**Comment by DonLakeFlyer** [comment]
Thanks Nate

**Comment by NaterGator** [comment]
No problem. This ties in tightly with #2638. **Especially** for anything that is a delegate of a model view we should adopt this (or a similar) approach to reduce the number and complexity of bindings. I don't think I fully appreciated how expensive some of these bindings are. Glad we're hacking away at the CPU hog though.

**Comment by DonLakeFlyer** [comment]
We'll have to look at how expensive the smaller lists are. This is one of the few places where you can end up with a large list. That said in 3.1 this big list will likely all go away and I'll move to something like click in the map to show a single item to edit model.

**Pull request merged**
