### PR TITLE
Add camera tracking functions

### PR DESCRIPTION
**Pull request by chris-hagen**
This adds camera tracking functionality for rectangle and point based tracking requests as well as the tracking status responses to the video display.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
This really needs screenshots and a lot more explanation of what it is in order to be considered.

**Comment by chris-hagen** [comment]
This PR implements [MavLink's camera tracking protocol](https://mavlink.io/en/services/camera.html#camera-tracking) into QGC. Therefore a new button have been added to the PhotoVideoControl, which will be displayed if the camera signals to support tracking functionality.

By activating the button the user can either click within the video stream or drag & drop a rectangle around an object. The clicked relative coordinates are sent to the camera using [MAV_CMD_CAMERA_TRACK_POINT](https://mavlink.io/en/messages/common.html#MAV_CMD_CAMERA_TRACK_POINT) or [MAV_CMD_CAMERA_TRACK_RECTANGLE](https://mavlink.io/en/messages/common.html#MAV_CMD_CAMERA_TRACK_RECTANGLE) MavLink messages. 

The camera's tracker sends back the object's position in the current video frame by using the [CAMERA_TRACKING_IMAGE_STATUS](https://mavlink.io/en/messages/common.html#CAMERA_TRACKING_IMAGE_STATUS) MavLink message. These coordinates are drawn in QGC's video stream display with a red box around the object.

By disabling the tracking button a [MAV_CMD_CAMERA_TRACK_STOP](https://mavlink.io/en/messages/common.html#MAV_CMD_CAMERA_STOP_TRACKING) MavLink message is sent to the camera's tracker to stop tracking. The red box will disappear in QGC's video stream display.

See attached a short sample using AirSim simulation and a simulated MavLink camera with tracking functionality.

https://github.com/mavlink/qgroundcontrol/assets/65018757/66e4c346-40af-453d-8c4f-a146c84dba0a

**Comment by chris-hagen** [comment]
Agree. Added the label.

Camera Tracking label

**Comment by DonLakeFlyer** [comment]
I'll take a look at cleaning this up since I believe I stomped all over it.

**Comment by chris-hagen** [comment]
Thanks @DonLakeFlyer! Let me know if I can give any assistance.

**Comment by DonLakeFlyer** [comment]
@chris-hagen Can you double-check and test my replacement pull?

**Comment by chris-hagen** [comment]
@DonLakeFlyer thanks for taking care. From code side it looks perfect. Currently I am not able to build and verify the changes using Qt6. Is there a way to build QGC using the docker build pipeline or just use the prebuilt version from your change?

**Comment by DonLakeFlyer** [comment]
You can just install the artifact from my pull.

**Comment by chris-hagen** [comment]
@DonLakeFlyer seems like there was no Artifact generated:
image

**Comment by DonLakeFlyer** [comment]
You have to be logged in to get artifacts: https://github.com/mavlink/qgroundcontrol/actions/runs/7433641358?pr=10947

**Comment by chris-hagen** [comment]
Thanks for the hint, download worked. Currently I have the issue, that the video stream provided over the MavLink camera interface is not displayed anymore. Seems like there has been a change with the latest version. I increased the GStreamer Log Level and currently  the decoder pipeline isn't even started. I am using H264 over UDP (RTP) for testing.

**Comment by DonLakeFlyer** [comment]
Oh, crap. Forgot video isn't working in master yet with Qt6 move.

**Comment by DonLakeFlyer** [comment]
New video support is in now. So'll I'll rebase my replacement pull and after that I could use your help re-testing this.

**Comment by Midren** [comment]
@DonLakeFlyer @chris-hagen 

Target selection on the quadrotor drone is quite challenging with the current approach, because the image is moving quite a lot. However, I haven't found any timestamp data on the video steam in QGC (usually, people are using MPEG-TS with KLV metadata), and also it seems that MavLink protocol does not have timestamp when sending [MAV_CMD_CAMERA_TRACK_RECTANGLE](https://mavlink.io/en/messages/common.html#MAV_CMD_CAMERA_TRACK_RECTANGLE). Is there any plan to mitigate that?

**Comment by DonLakeFlyer** [comment]
@chris-hagen Pull is ready/built for testing

**Comment by chris-hagen** [comment]
@DonLakeFlyer I tested the new artifact. Within all tests the added features are working.

https://github.com/mavlink/qgroundcontrol/assets/65018757/2b1ee6f2-16c9-4e39-b8c7-3bc5aad92195

**Comment by chris-hagen** [comment]
@Midren I agree with you. Neither the default H264 video stream nor the Mavlink tracking messages offer a time synchronization capability yet. This makes it quite hard to get a synchronized setup running in QGC. I implemented that for some customer a while ago and used the PTS within the video stream to transmit the reference time of the tracking system. Within the Mavlink messages I missused a non used command field to transmit the timestamp as well and synchronized both in the GCS (not QGC).
The above setup worked but I really don't recommend doing it like that. From my point of view a clean implementation would result in an extension of the existing Mavlink tracking messages to offer the capability of referencing image frames/time basis/... and using MPEG-2 over UDP/H264. But that is definitely way beyond the scope of this PR.

**Comment by DonLakeFlyer** [comment]
My pull is merged in, closing this one

**Pull request closed without merging**
