### PR TITLE
Run SerialLink on main thread

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
@dogmaphobic Can you give this a try on android? It's not quite ready for prime time, but I've been running with it on my tablet now for a few minutes over radio connection to my Iris without any crashes. I did a radio cal, played around with the map. Futzed will params. All still up and running!? At least for the last 5 minutes. Of course as I finish typing this it will crash. Fingers crossed.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Ran for another 5 minutes without problems. Configured my Flight Modes on the tablet. Then gave up waiting for it to crash and disconnected. I think this may really work.

**Comment by dogmaphobic** [comment]
Interesting. I figured it had something to do with threading but I never got this far. Please, go ahead and merge it in. I will take a look tomorrow.

**Comment by DonLakeFlyer** [comment]
It's just a hacked up version at this point. I need to redo it for real.

**Comment by DonLakeFlyer** [comment]
Don't merge this. Leaving here as reminder to fix this up for real.

**Comment by DonLakeFlyer** [comment]
I updated my tablet OS and now serial seems to be broken even worse then it was before. Even with this pull. Looking into it.

**Comment by DonLakeFlyer** [comment]
Closing since I have a real version of this pull going up

**Pull request closed without merging**
