### PR TITLE
Fixed 4156 Power: If UAVCAN is turned on, show UAVCAN settings by def…

### PR DESCRIPTION
**Pull request by richerlariviere**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
In looking at the implementation of the uavcan ui again as well as the parameter definition for UAVCAN_ENABLE it currently seems wrong. I think it should be changed to this:
* Show uavcan settings checkbox should always be visible
* Uavcan settings should be a dropdown with all options not a checkbox with just one option

@LorenzMeier You know more about this stuff. Agree?

**Comment by DonLakeFlyer** [comment]
Fix for #4156

**Comment by LorenzMeier** [comment]
Makes sense

**Comment by DonLakeFlyer** [comment]
@richerlariviere Could you update this pull to match the above discussion?

**Comment by DonLakeFlyer** [comment]
@richerlariviere Any update on this?

**Comment by richerlariviere** [comment]
I'm short in time but I can do it. Just give me a few days.

**Comment by DonLakeFlyer** [comment]
Closing since no activity. Will do myself

**Pull request closed without merging**
