### PR TITLE
Enable ROI and MOUNT support for PX4

### PR DESCRIPTION
**Pull request by thedevleon**
This can be merged to enable ROI and CMD_DO_MOUNT messages support for PX4 once https://github.com/PX4/Firmware/issues/4584 has been merged.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Unit tests are failing

**Comment by DonLakeFlyer** [comment]
@thedevleon The camera stuff is all under the "Camera" category. "Mount" just doesn't really mean anything to mere mortals. Not sure it makes sense to create a new "Mount" category.

**Comment by thedevleon** [comment]
@DonLakeFlyer I mean in theory the mount commands are not specifically meant for cameras only.
They can be used for gimbals, antenna trackers, stabilizing a fpv camera with servos, headtracking and aiming lasers, flamethrowers or cannons ;)
These are also quite advanced, so I don't think a mere mortal would use those :)

**Comment by DonLakeFlyer** [comment]
Put them in the "Advanced" category then instead of a whole new category? Don't want to clutter the UI with little used stuff.

**Comment by thedevleon** [comment]
@DonLakeFlyer you're totally right, sorry. Changed it to Advanced.

**Comment by LorenzMeier** [comment]
@thedevleon Please note that all new contributions to QGC have to be made under a dual license including Apache 2.0 + GPLv3. Just so you're aware that this PR now has to fulfil this requirement.

**Comment by DonLakeFlyer** [comment]
@thedevleon All good now, thanks.

**Pull request merged**
