### PR TITLE
fix warning C5208(lead to error 2220) with vs 2019 compiler

### PR DESCRIPTION
**Pull request by kemen209**
Simple fix for warning C5208 with vs 2019 compiler. Maybe we should add an ignore entry in build script for this warning.

### CODE REVIEW

**Comment by mrpollo** [comment]
@DonLakeFlyer  looks like CI is failing, looks unrelated to me, are the failures timeouts?

https://travis-ci.org/github/mavlink/qgroundcontrol/jobs/753774731#L1951

**Comment by DonLakeFlyer** [comment]
Yes, there is an intermittent failure in VehicleLinkManagerTest that I haven't figured out yet.

**Comment by mrpollo** [comment]
@DonLakeFlyer thanks I just noticed you opened issue #9346, hopefully, we can document the timeouts and come up with a fix soon. **For this PR are we ready to merge?**

**Review by LorenzMeier — APPROVED** [review]

**Comment by patrickelectric** [comment]
@kemen209 can you solve the conflict ?

**Comment by kemen209** [comment]
This has been fixed in commit 037569876363d34e78d3d5f5a9a75178d20540fa, so drop this merge request

**Pull request closed without merging**
