### PR TITLE
flight mode support for ArduPilot

### PR DESCRIPTION
**Pull request by pritamghanghas**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks! I presume you have seen the CI errors and are aware how to analyze and fix them?

**Comment by pritamghanghas** [comment]
I couldn't figure out why these failed. I compiles find on ubuntu on my desktop. Any hints how to find out what failed. I checked details of the failure. Couldn't find anything. This has happened to me for the first time. I may need a little help here.

**Comment by pritamghanghas** [comment]
All I could understand was unit test is failing. It points to this line 
IMPLEMENT_QGC_SINGLETON(ArduPlaneFirmwarePlugin, ArduPlaneFirmwarePlugin)
putting an assert for Null. 

I had some doubt about how the plugin singleton is initialized. But I left it the way it was before. They are being initialized in QGCApplication.cc 587 without any checks. So all plugins are initialized regardless we will need them or not. I don't see the merit in that. instance() call should create it first time when its called.

**Comment by DonLakeFlyer** [comment]
You should be able to repro this since by running qgroundcontrol --unittest in the debugger. It doesn't repro for you?

**Comment by DonLakeFlyer** [comment]
> So all plugins are initialized regardless we will need them or not.

You are correct. But that this point the singleton architecture doesn't support that.

**Comment by pritamghanghas** [comment]
I will try. I never ran unit tests till now.

On Thu, Oct 15, 2015 at 10:07 PM, Don Gagne <notifications@github.com>
wrote:

> You should be able to repro this since by running qgroundcontrol
> --unittest in the debugger. It doesn't repro for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mavlink/qgroundcontrol/pull/1987#issuecomment-148448798>
> .
>



-- 
Regards,
pritam

**Comment by DonLakeFlyer** [comment]
You should make sure you pass them before you submit your pull.

**Comment by pritamghanghas** [comment]
From now on I will. Thanks

On Thu, Oct 15, 2015 at 10:35 PM, Don Gagne <notifications@github.com>
wrote:

> You should make sure you pass them before you submit your pull.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mavlink/qgroundcontrol/pull/1987#issuecomment-148458636>
> .
>



-- 
Regards,
pritam

**Comment by DonLakeFlyer** [comment]
Another one bites the dust.

**Pull request merged**
