### PR TITLE
rally point upload and download functionality

### PR DESCRIPTION
**Pull request by arwagoner**
Adds the ability to upload rally points to and download from the vehicle.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Ah awesome, thanks. Never quite completed. Did you check this against GeoFenceManager? It should just follow the same pattern/code that is in there.

**Comment by arwagoner** [comment]
Yes, I tried to follow as closely to GeoFenceManager as possible.

**Comment by DonLakeFlyer** [comment]
Did you have anything to test this against? MockLink supports Rally Points. But is the PX4 Firmware pull for Rally Points in master now?

**Comment by arwagoner** [comment]
I tested it with this branch of PX4 firmware https://github.com/PX4/Firmware/pull/7743 It isn't in master yet.

**Comment by DonLakeFlyer** [comment]
Great, thanks. Merging

**Pull request merged**
