### PR TITLE
Terrain Provider step 1 : Generic MapProviders

### PR DESCRIPTION
**Pull request by tilaktilak**
Issue related : https://github.com/mavlink/qgroundcontrol/issues/7774
I started to work on the integration of a new providers for terrain.
I also want to have the ability add/remove custom providers for both map and terrain.

So this is to make room for a big coming job :
- Make a generic interface for a MapProvider
- Subscribe new map provider by adding a new `MapProvider` to a hash table
- Remove duplicate/hard coded list of providers from backend / ui sides. The ui will retrieve all necessary info from the hash table, simple way to insure consistency between front and back.

Now we can :
- Implement several Terrain providers with several protocols and use still use the cache offline feature.
- Improve OfflineMaps menu to cache terrain tiles at different zoom, from several providers.
- Create a UI menu to add custom map provider (WMS compatible for instance), this will instantiate and subscribe a MapProvider.

@edwinhayes

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
"Improve OfflineMaps menu to cache terrain tiles at different zoom, from several providers."

I don't quite get how this would be used. To me you always want the best terrain information available. Also say you are planning a mission which follow terrain, there is no way in that process to say I want to use terrain at a specific soom level.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Gus is going ot have to look at this.

**Comment by tilaktilak** [comment]
> "Improve OfflineMaps menu to cache terrain tiles at different zoom, from several providers."
> 
> I don't quite get how this would be used. To me you always want the best terrain information
available. 
 
 I agree with the fact that we want best terrain info most of the time, but depending on the area covered and the precision of the provider (can be up to 5m, or even more if a custom DEM is used), it make sense to choose a relevant zoom level / definition to the mission.

> Also say you are planning a mission which follow terrain, there is no way in that process to say I want to use terrain at a specific soom level.

I am referring to the "Offline Maps" menu as the way to cache elevation tiles.

**Comment by edwinhayes** [comment]
> I don't quite get how this would be used. To me you always want the best terrain information
available.

- Imagine the case of planning a mission that covers 500km: you don't necessarily want to sample at 30m intervals; you might want to instead perform some kind of regionation so that you're only 'following' the highest point in each 1km square.

- Sometimes, you might want to load in a custom DEM; for instance, flying around a building site; but the DEM might be at a really high resolution - 1-2cm for instance.

- This allows rendering elevation information on the map.

**Comment by edwinhayes** [comment]
> Also say you are planning a mission which follow terrain, there is no way in that process to say I want to use terrain at a specific soom level.

This is definitely a legit consideration; we will need to give some consideration to what we might need to do about this, but that'll be a separate thread.

**Comment by DonLakeFlyer** [comment]
I'm not saying that all terrain tiles stored need to be at the same resolution. When I'm saying is that I don't understand why you would store multiple tiles for the same area at differing resolution with some being lower.

> * Imagine the case of planning a mission that covers 500km: you don't necessarily want to sample at 30m intervals; you might want to instead perform some kind of regionation so that you're only 'following' the highest point in each 1km square.

That sort of thing isn't going to be supported by the feature which sends tiles to the vehicle. At least I don't think that's the case. The ability to build such a mission is more of a new feature of planning. You don't need multiple levels of tile information to do that. You just need the abilityu to query a maximum height for a certain area.

**Comment by DonLakeFlyer** [comment]
> but depending on the area covered and the precision of the provider (can be up to 5m, or even more if a custom DEM is used), it make sense to choose a relevant zoom level / definition for the mission.

That would be a feature of the mission generation not necessarily a feature of storing zoom levels on elevation tiles. Given the fact that I don't see the cases where you want to use lower levels of terrain resolution as being something used very often. I don't seen storing a lot of additional information to support a rarely used thing to be a good idea.

Also I you implement such a thing based on elevation tile zoom it means it will only work if you have the lower resolution data. That doesn't seem like a good thing either. You want it to work with whatever data you have and it is possible to support that. If you support building lower resolution terrain missions from higher resolution data why would you need to do it any other way then that?

**Comment by DonLakeFlyer** [comment]
Wait, I'm thinking about this wrong. I've been thinking only of why you want lower resolution data.  If you want to store a smaller area of higher resolution data while you still have existing say normal resolution coverage in that area you need to do that using a higher zoom level which may cover a smaller tile size geographically than the lower tile. Ok, I get that.

**Comment by tilaktilak** [comment]
The thing is we also want to take advantage of what is present in the code at the moment in term of tiling/caching. The way it was started with the support of airmap elevation in Offline was great ( Using the cache from the map engine through OfflineMaps menu, so tiles are stores in the sql database).
My approach here is simply to create a generic interface for map providers from several sources and either for a base map or an elevation map. So it become fairly easy to change from a terrain provider to another, same for the basemap.
It's also a refactor to avoid hard-coded list of map providers in QGCMapEngine.cc QGCMapEngineManager.cpp, QGCMapUrlEngine.h and all the `if "Airmap Elevation"` in several places as well.
I also think that it's a good method to smooth the transition from Airmap to the next solution that will be decided. It's an open door to custom DEM for mapping purpose, caching options , add custom basemap and all of this at run time !

**Comment by DonLakeFlyer** [comment]
@tilaktilak Yeah all makes great sense. Gus, who wrote the original map code is on vacation now. When he gets back I'll ping him to look at this. I know very little about this code unfortunately.

**Comment by tilaktilak** [comment]
Following discussion here : #7864

@cosmarc 
So I rework a little bit the TerrainQuery code + create a generic class for MapProvider ( Then a big hash table contains all providers ). 
This is beneficial for both map/elevation. We can create a child of MapProvider that will fetch data from a WMS server, or even a SRTM mirror, same for 
I ended up adding gdal to QGC to open geotiff and apply transformation, so with gdal onboard theorically we can open what we want (See here : https://gdal.org/api/raster_c_api.html#_CPPv48GDALOpenPKc10GDALAccess) ! 
On my current version QGC search in a folder for .tiff files to try to retrieve elevation data from it, if it's not available fallback to Airmap elevation.
My current working branch is really messy (include some UI changes on OfflineMap that are just random experiments to connect things together) but it's here : https://github.com/Aeronavics/qgroundcontrol/tree/MapProviders_step2
I Also had in mind adding the ability to manage several elevation provider ( and class them by priority ) and same thing with the map provider (Adding the ability to overlay maps and put an orthophoto on the top of a basemap as it appear useful for our customers, that is basically the purpose of my messy UI changes in MapProviders_step2 branch).

There is a first PR related to the creation of a generic class for MapProviders here : https://github.com/mavlink/qgroundcontrol/pull/7818

My work/challenges at the moment : 
- Link gdal statically to optimize QGC binary size.
- I manage to compile my code on Windows, Linux and Android with dynamic libs but have no access to an OSX platform.
- I need a nice UI menu to connect this backend ( How to add  elevation providers map layers from a given list, add custom element in this list (with a WMS url or a local folder of tile), handle layers ordering, opacity for basemap. Integrate the ability to overlay maps in FlightMap item ( I though about a repeater of FlightMap items somewhere between the current map and the items on the map ).

**Comment by dogmaphobic** [comment]
@tilaktilak Can you update the PR so I can merge it?

**Comment by tilaktilak** [comment]
Done ! :-)

**Comment by dogmaphobic** [comment]
There are some build errors:
```
compiling src/QtLocationPlugin/ElevationMapProvider.cpp
1695/home/travis/build/mavlink/qgroundcontrol/src/QtLocationPlugin/MapProvider.cpp:66:59: error: use of undeclared identifier 'pow'
1696    return static_cast<int>(floor((lon + 180.0) / 360.0 * pow(2.0, z)));
```

**Comment by tilaktilak** [comment]
Let me have a look

**Pull request merged**
