### PR TITLE
update android versionCode and google play instructions

### PR DESCRIPTION
**Pull request by dagar**
@DonLakeFlyer @LorenzMeier 

Opening this to provide basic instructions for updating the google play app.

To update the android app on google play the `versionCode` in android/AndroidManifest.xml must be incremented. The versionName is displayed, but versionCode is what android uses to update. I'll start committing this change everytime I update the build so that it's easier for others.

    android:versionName="2.7.1-548-g9417909" android:versionCode="6"

The app must be built in release mode and signed with the keystore `android/android_release.keystore`. I'll send the password.

Once a release apk is built you just login to https://play.google.com/apps/publish and select 'Upload new APK' under APK. I'm currently only uploading to the beta channel, although I've been calling it alpha.

Ideally this would be automated from travis-ci, but due to the way androiddeployqt works it's currently difficult.

### CODE REVIEW

**Comment by dogmaphobic** [comment]
Given that I can't seem to be able to have a functioning Android (local) build, how do I get QGC from the PlayStore? Searching for it doesn't yield any results (within my very limited knowledge of Android).

**Comment by dagar** [comment]
@dogmaphobic It's currently an opt in beta test.
https://play.google.com/apps/testing/org.mavlink.qgroundcontrol

**Comment by dogmaphobic** [comment]
> It's currently an opt in beta test.

Got it. It has the same behavior as the one I build locally. It's stuck on the boot process. I guess we have an issue with Nexus 7...

The log output:

```
W/linker  ( 9212): libqtquick2plugin.so: unused DT entry: type 0x1d arg 0x4bd
W/linker  ( 9212): libqtquickcontrolsplugin.so: unused DT entry: type 0x1d arg 0x4147
W/linker  ( 9212): libdeclarative_positioning.so: unused DT entry: type 0x1d arg 0x2123
W/linker  ( 9212): libdialogplugin.so: unused DT entry: type 0x1d arg 0x2474
W/linker  ( 9212): libdeclarative_location.so: unused DT entry: type 0x1d arg 0x9612
D/QGroundControl( 9212): (null):0 ((null)): Mapping cache directory: "/data/data/org.mavlink.qgroundcontrol/cache/QGCMapCache55"
W/linker  ( 9212): libqtquickcontrolsandroidstyleplugin.so: unused DT entry: type 0x1d arg 0x1726
W/linker  ( 9212): libqdds.so: unused DT entry: type 0x1d arg 0xb88
W/linker  ( 9212): libqgif.so: unused DT entry: type 0x1d arg 0x7cd
W/linker  ( 9212): libqicns.so: unused DT entry: type 0x1d arg 0xcb5
W/linker  ( 9212): libqico.so: unused DT entry: type 0x1d arg 0xb25
W/linker  ( 9212): libqjp2.so: unused DT entry: type 0x1d arg 0xc02
W/linker  ( 9212): libqjpeg.so: unused DT entry: type 0x1d arg 0x10ca
W/linker  ( 9212): libqmng.so: unused DT entry: type 0x1d arg 0x919
W/linker  ( 9212): libqsvg.so: unused DT entry: type 0x1d arg 0xb96
W/linker  ( 9212): libqtga.so: unused DT entry: type 0x1d arg 0x8cd
W/linker  ( 9212): libqtiff.so: unused DT entry: type 0x1d arg 0xc5e
W/linker  ( 9212): libqwbmp.so: unused DT entry: type 0x1d arg 0x996
W/linker  ( 9212): libqwebp.so: unused DT entry: type 0x1d arg 0xab7
W/linker  ( 9212): libwindowplugin.so: unused DT entry: type 0x1d arg 0x493
W/linker  ( 9212): libqquicklayoutsplugin.so: unused DT entry: type 0x1d arg 0x1967
W/QGroundControl( 9212): qrc:qml/MainToolBar.qml:227 ((null)): qrc:qml/MainToolBar.qml:227: TypeError: Cannot read property 'width' of null
W/Adreno-EGL( 9212): <qeglDrvAPI_eglSwapInterval:3971>: EGL_BAD_SURFACE
```

**Comment by DonLakeFlyer** [comment]
> qrc:qml/MainToolBar.qml:227 ((null)): qrc:qml/MainToolBar.qml:227: TypeError: Cannot read property 'width' of null

That's a bug in MainToolBar.qml. I'll fix it. Don't think this is what is preventing it from going further though. Unless somehow your tablet is crashing out on every qWarning due to some strange settings. Could you have QT_FATAL_WARNINGS=1 environment variable somehow set on there. I don't think that's possible.

**Comment by dogmaphobic** [comment]
> W/QGroundControl( 9212): qrc:qml/MainToolBar.qml:227 ((null)): qrc:qml/MainToolBar.qml:227: TypeError: Cannot read property 'width' of null

No, that's a red herring. This error just started now (within the past few pulls). It wasn't there earlier. The overall behavior is the same though. There is something funky with the Nexus 7, regardless of the MainToolBar error.

**Comment by dogmaphobic** [comment]
@DonLakeFlyer What kind of Galaxy tablet do you have? Do you know what @LorenzMeier has?

**Comment by dagar** [comment]
I do a quick test on my devices before updating the build on google play, but I only have a nexus 6 phone and nexus 9 tablet running android 6.

**Pull request merged**
