### PR TITLE
travis-ci linux tests

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
@DonLakeFlyer tests running on linux again. Currently one failure in  _testGimbalRecalc.

    FAIL!  : MissionControllerTest::_testGimbalRecalc() Compared doubles are not the same (fuzzy compare)
    Actual   (visualItem->missionGimbalYaw()): nan
    Expected (0.0)                           : 0
    Loc: [/home/travis/build/mavlink/qgroundcontrol/src/MissionManager/MissionControllerTest.cc(224)]

It's also full of VideoReceiver errors. @dogmaphobic FYI
    VideoReceiver::start() failed. Error with data source for gst_element_factory_make()
    QSYSTEM: MissionControllerTest::_testGimbalRecalc() VideoReceiver::start() failed

**Comment by DonLakeFlyer** [comment]
Huge thanks Daniel.

So I'll clean up the failure. Then re-run this and merge?

**Comment by dagar** [comment]
Yes, you can push the fix to this branch (travis-linux) and merge once passing.

**Comment by dagar** [comment]
@DonLakeFlyer rebased on master and now a lot more tests are failing.

**Comment by DonLakeFlyer** [comment]
Going to merge this and keep going on testing unit tests

**Comment by DonLakeFlyer** [comment]
Crap, wrong button!

**Pull request merged**
