### PR TITLE
New Solo video handshake sequence

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
* Fix for #9125
* Previous handshake was based on flaky parsing of status text messages to determine if you were connected to a Solo
* Now works based on selecting 3DR Solo as you video source
* Also added Parrot Discovery as a video source
* Both Solo and Parrot set up the internal video source and ports automatically without needing to know the specifics
* Solo video handshake occurs at vehicle connect time only. So you need to have video source set to 3DR Solo prior to vehicle connection for it to work

Screen Shot 2020-10-30 at 11 02 46 AM

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@AndKe Can you validate this with tomorrow's daily?

**Comment by AndKe** [comment]
Yes, I can do it Monday, - or maybe tomorrow.

**Comment by AndKe** [comment]
@DonLakeFlyer I just tested current master
Selected a Solo as video source, no video appeared.
Then I opened a connection in terminal (nc 10.1.1.1 5502)
QGC crashed.
Starting QGC again, crashes it:


```
 ./qgroundcontrol-start.sh 
Settings location "/home/andre/.config/QGroundControl.org/QGroundControl Daily.ini" Is writable?: true
Filter rules "*Log.debug=false\nGStreamerLog.debug=true\nLinkManagerLog.debug=true\n"
GStreamerLog: Disable bcmdec
System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en-US"
serialnmea: No known GPS device found. Specify the COM port via QT_NMEA_SERIAL_PORT.
MAVLinkLogManagerLog: MAVLink logs directory: "/home/andre/Documents/QGroundControl Daily/Logs"
Map Cache in: "/home/andre/.cache/QGCMapCache300" / "qgcMapCache.db"
qml: QGCCorePlugin(0x564bc8162c60) []
qrc:/qml/PreFlightCheckList.qml:161:21: Cannot assign to non-existent property "tooltip"
QGridLayoutEngine::addItem: Cell (0, 2) already taken
QGridLayoutEngine::addItem: Cell (0, 2) already taken
QGridLayoutEngine::addItem: Cell (0, 2) already taken
QGridLayoutEngine::addItem: Cell (0, 2) already taken
QGridLayoutEngine::addItem: Cell (0, 2) already taken
QGridLayoutEngine::addItem: Cell (0, 2) already taken
QGridLayoutEngine::addItem: Cell (0, 2) already taken
QGridLayoutEngine::addItem: Cell (0, 2) already taken
QGridLayoutEngine::addItem: Cell (0, 2) already taken
QGridLayoutEngine::addItem: Cell (0, 2) already taken
QGridLayoutEngine::addItem: Cell (0, 2) already taken
QGridLayoutEngine::addItem: Cell (0, 2) already taken
QGridLayoutEngine::addItem: Cell (0, 2) already taken
QGridLayoutEngine::addItem: Cell (1, 2) already taken
QGridLayoutEngine::addItem: Cell (1, 2) already taken
QGridLayoutEngine::addItem: Cell (1, 2) already taken
QGridLayoutEngine::addItem: Cell (1, 2) already taken
QGridLayoutEngine::addItem: Cell (1, 2) already taken
QGridLayoutEngine::addItem: Cell (1, 2) already taken
QGridLayoutEngine::addItem: Cell (1, 2) already taken
QGridLayoutEngine::addItem: Cell (1, 2) already taken
QGridLayoutEngine::addItem: Cell (1, 2) already taken
QGridLayoutEngine::addItem: Cell (1, 2) already taken
QGridLayoutEngine::addItem: Cell (1, 2) already taken
QGridLayoutEngine::addItem: Cell (1, 2) already taken
QGridLayoutEngine::addItem: Cell (1, 2) already taken
QGridLayoutEngine::addItem: Cell (0, 5) already taken
QGridLayoutEngine::addItem: Cell (0, 5) already taken
QGridLayoutEngine::addItem: Cell (0, 5) already taken
QGridLayoutEngine::addItem: Cell (0, 5) already taken
QGridLayoutEngine::addItem: Cell (0, 5) already taken
QGridLayoutEngine::addItem: Cell (0, 5) already taken
QGridLayoutEngine::addItem: Cell (0, 5) already taken
QGridLayoutEngine::addItem: Cell (0, 5) already taken
QGridLayoutEngine::addItem: Cell (0, 5) already taken
QGridLayoutEngine::addItem: Cell (0, 5) already taken
QGridLayoutEngine::addItem: Cell (0, 5) already taken
QGridLayoutEngine::addItem: Cell (0, 5) already taken
QGridLayoutEngine::addItem: Cell (0, 5) already taken
QGridLayoutEngine::addItem: Cell (1, 5) already taken
QGridLayoutEngine::addItem: Cell (1, 5) already taken
QGridLayoutEngine::addItem: Cell (1, 5) already taken
QGridLayoutEngine::addItem: Cell (1, 5) already taken
QGridLayoutEngine::addItem: Cell (1, 5) already taken
QGridLayoutEngine::addItem: Cell (1, 5) already taken
QGridLayoutEngine::addItem: Cell (1, 5) already taken
QGridLayoutEngine::addItem: Cell (1, 5) already taken
QGridLayoutEngine::addItem: Cell (1, 5) already taken
QGridLayoutEngine::addItem: Cell (1, 5) already taken
QGridLayoutEngine::addItem: Cell (1, 5) already taken
QGridLayoutEngine::addItem: Cell (1, 5) already taken
QGridLayoutEngine::addItem: Cell (1, 5) already taken
QGridLayoutEngine::addItem: Cell (0, 8) already taken
QGridLayoutEngine::addItem: Cell (0, 8) already taken
QGridLayoutEngine::addItem: Cell (0, 8) already taken
QGridLayoutEngine::addItem: Cell (0, 8) already taken
QGridLayoutEngine::addItem: Cell (0, 8) already taken
QGridLayoutEngine::addItem: Cell (0, 8) already taken
QGridLayoutEngine::addItem: Cell (0, 8) already taken
QGridLayoutEngine::addItem: Cell (0, 8) already taken
QGridLayoutEngine::addItem: Cell (0, 8) already taken
QGridLayoutEngine::addItem: Cell (0, 8) already taken
QGridLayoutEngine::addItem: Cell (0, 8) already taken
QGridLayoutEngine::addItem: Cell (0, 8) already taken
QGridLayoutEngine::addItem: Cell (0, 8) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (1, 1) already taken
QGridLayoutEngine::addItem: Cell (0, 0) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 0) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (1, 4) already taken
QGridLayoutEngine::addItem: Cell (0, 0) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (0, 7) already taken
QGridLayoutEngine::addItem: Cell (1, 0) already taken
qrc:/qml/MainRootWindow.qml:412:13: QML ColumnLayout: Possible anchor loop detected on vertical anchor.
Adding target QHostAddress("10.1.1.1") 48998
LinkManagerLog: New auto-connect UDP port added
Adding target QHostAddress("10.1.1.1") 48998
Temp log "/tmp/FlightData058707.mavlink"
libpng warning: iCCP: known incorrect sRGB profile
Segmentation fault (core dumped)

```

**Comment by AndKe** [comment]
Updated info: maybe this is only something only appearing on Intel drivers ?
```
qrc:/qml/MainRootWindow.qml:412:13: QML ColumnLayout: Possible anchor loop detected on vertical anchor.
[New Thread 0x7fff7ffff640 (LWP 54300)]
Adding target QHostAddress("10.1.1.1") 58275
LinkManagerLog: New auto-connect UDP port added
[New Thread 0x7fff7f7fe640 (LWP 54302)]
[New Thread 0x7fff7effd640 (LWP 54303)]
Adding target QHostAddress("10.1.1.1") 58275
[New Thread 0x7fff7d613640 (LWP 54304)]
[Thread 0x7fff7d613640 (LWP 54304) exited]
[New Thread 0x7fff7d613640 (LWP 54305)]
[New Thread 0x7fff7ce12640 (LWP 54306)]
[New Thread 0x7fff63fff640 (LWP 54307)]
[New Thread 0x7fff637fe640 (LWP 54308)]
[New Thread 0x7fff62ffd640 (LWP 54309)]
[New Thread 0x7fff627fc640 (LWP 54310)]
[New Thread 0x7fff61847640 (LWP 54311)]

Thread 13 "queue0:src" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd4d4c640 (LWP 54289)]
0x00007fff7d887bc5 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
(gdb) 

```


Same result for H264 UDP (not the Solo profile)-  Ubuntu 20.10 , with kernel's intel drivers.

**Comment by AndKe** [comment]
second post (please see previous too)
The same build, executed on a computer with Nvidia GPU works perfectly.
Using 3DR Solo works for Solo  
Using h264 UDP and nc 10.1.1.1 5502 works too.

The Intel graphics crashing should be fixed, because many typical field GCS laptops is very likely to run Intel video.

**Comment by DonLakeFlyer** [comment]
> The Intel graphics crashing should be fixed, because many typical field GCS laptops is very likely to run Intel video.

Bummer. A large point of the new video stuff in daily was to fix those crashes. That's not good news. That said running a pre-built version of Daily on 20.10 is still questionable since it was build for 18.04. There are still some problems with that. So may be related.

**Comment by AndKe** [comment]
fwiw: I built it from master on the same Ubuntu 20.10

**Comment by AndKe** [comment]
@DonLakeFlyer  please notify me whenever you wish that I test the new build on Intel GPUs

**Comment by AndKe** [comment]
@DonLakeFlyer 
The segvault in Intel is still an issue on Intel video. every other app I tried to stream show the stream works fine, but QGC crashes.
This is verified with both today's master, and the latest appimage download.
Can you please look into it?

**Comment by DonLakeFlyer** [comment]
@AndKe Can you create a separate issue with the segfault with details on your hardware? Then I can have the video folks look at it.

**Pull request merged**
