### PR TITLE
Video Source Options

### PR DESCRIPTION
**Pull request by dogmaphobic**
Based on discussion #3982
Adding code to allow the user to specify a USB video source. This uses the QML *Camera* item to display video. Any source that shows itself to the OS as a Camera can be used.
http://doc.qt.io/qt-5/qml-qtmultimedia-camera.html

* Renamed `FlightDisplayViewController` to `VideoManager`
* Made `VideoManager` into a singleton (accessible through `QGroundControlQmlGlobal`)
* Addes a combobox to the General Settings allowing the user to chose a video source.

Known Issue:

If you have more than one USB device, for some reason the QML code is not respecting the change. That is, it keeps showing the first used USB *camera*. Switch from USB to UDP Streaming is working fine. UDP Streaming is the default and it did not change.

This is still experimental. I don't have any USB Video Capture device to test with. I tested with a USB camera and it worked. On mobile, the UI shows both front and back cameras but switching between them is not working (discussed above). It requires a restart.

### CODE REVIEW

**Comment by cda725** [comment]
Bug being caused by video pipeline not being closed before selecting a new one. I am attempting to patch the bug now.

Notes: This addition allows for a broad range of USB video devices - Good work my friend!

**Comment by cda725** [comment]
I Fixed the bug but am a noob to github. The Fix for selecting video is as follows:

Starting at line 105 of VideoManager.cc Pasts this...

//-----------------------------------------------------------------------------
void
VideoManager::setVideoSource(QString vSource)
{
    _videoSource = vSource;
    QSettings settings;
    settings.setValue(kVideoSourceKey, vSource);
    emit videoSourceChanged();
    QList<QCameraInfo> cameras = QCameraInfo::availableCameras();
    foreach (const QCameraInfo &cameraInfo, cameras) {
        if(cameraInfo.description() == vSource) {
            _videoSourceID = cameraInfo.deviceName();
            VideoManager::disconnect();

            emit videoSourceIDChanged();
            qCDebug(VideoManagerLog) << "Found USB source:" << _videoSourceID << " Name:" << _videoSource;
            break;
        }
    }
    emit isGStreamerChanged();
    qCDebug(VideoManagerLog) << "New Video Source:" << vSource;
}

**Comment by dogmaphobic** [comment]
@cda725 I fixed the issue within the QML code. See #3986. It handles both turning off the camera when not in use and stop/start the camera during changes.

**Comment by GlidLov** [comment]
Hi guys,

i think the bug is still there: i'm trying a UVC device with my win10 laptop, i can see image thru VLC, then when i go into QGC, i select the device, and it shows my front webcam instead of the UVC video stream.

news about it?

**Comment by DonLakeFlyer** [comment]
Can you put in a new Issue for that? Also make sure you are testing with a daily build

**Pull request merged**
