### PR TITLE
Turn "Sync" menu into a proper "File" menu

### PR DESCRIPTION
**Pull request by dogmaphobic**
First stab at reworking the _Sync_ menu:

The _Sync_ menu within the Plan View tool strip is basically a regular _File_ menu. As such, let's call it what it is.

* Renamed _Sync_ to _File_
* Moved it to the top of the list as this is the standard for _File_ menus
* Renamed _Remove All_ to _New_ (and moved it to the top of the list as this is the standard)
* Renamed _Load_ to _Open_
* Added a _Save_ (current) and renamed the existing one to _Save As_ (to new file)
* Hide both _Download_ and _Upload_ buttons if you are not connected (offline)
* Disable the _New_ button if the plan is empty
* Disable save options if there is nothing to save

In addition, I've adjusted the width of the tool strip so long words such as _Waypoint_ or _Checklist_ would fit within it.

Blank mission and not connected to anything:
screen shot 2018-06-19 at 11 46 44 am

Selecting _New_ with a plan loaded/created:
screen shot 2018-06-19 at 10 02 23 am

Connected to a vehicle:
screen shot 2018-06-19 at 10 04 10 am

Android for reference:
screen

### CODE REVIEW

**Comment by dogmaphobic** [comment]
@DonLakeFlyer When I load a plan file, why isn't it editable?

**Comment by DonLakeFlyer** [comment]
The problem is that the Sync menu isn't really just a "File" menu. It is a file menu and a sync menu. It may make sense to separate the two functions into separate buttons? 

That problem shows up the most with getting rid of "Remove All" and replacing it with New. In reality you want both of these. The reason is that there needs to be a simple mechanism to clear a plan fully from the vehicle. This is what "Remove All" does. You can't really replace it with "New".

**Comment by DonLakeFlyer** [comment]
Another thing would be whether Plan and KML open/save should be separate buttons. I still think so. But these could be collapsed so that you picked the file type in the file dialog, but that would be harder to do with thee mobile dialogs.

**Comment by DonLakeFlyer** [comment]
> When I load a plan file, why isn't it editable?

No idea. Is that happening on master?

**Comment by DonLakeFlyer** [comment]
> It may make sense to separate the two functions into separate buttons?

Or maybe break the File menu drop panel into two separate sections. The file part and the sync part.

**Comment by DonLakeFlyer** [comment]
Also just to be clearer on the difference between New and Remove All. Remove All is basically a "New" which begins creation of an new Plan, and also clears the Plan from the Vehicle. Whereas I would expect New to just begin creation of a Plan and not affect the vehicle. That is if it follows normal file menu semantics.

**Comment by dogmaphobic** [comment]
> The reason is that there needs to be a simple mechanism to clear a plan fully from the vehicle. This is what "Remove All" does. You can't really replace it with "New".

I think it makes more sense to have a specific button to reset/clear a mission within the vehicle. It's more obvious than "creating a blank mission" and "uploading it to the vehicle", which is the current model.

>Or maybe break the File menu drop panel into two separate sections. The file part and the sync part.

With an extra button to clear a mission from the vehicle, that may not be necessary. These buttons (Download/Upload/Reset) would only show up if connected. I think they still fit within the context of a file menu.

>Another thing would be whether Plan and KML open/save should be separate buttons. I still think so. 

I thought about that but the complexity of dealing with it for mobile wasn't worth the effort. At least not in this first shot.

**Comment by DonLakeFlyer** [comment]
@antiheavy FYI. Gus is working to make the Plan view more "normal" with respect to file management.

**Comment by dogmaphobic** [comment]
> No idea. Is that happening on master?

Yes, I had never done that so I didn't know if it was by design or not. When I load a plan, there are no editable "dots".

screen shot 2018-06-19 at 1 08 09 pm

(this is my current Airmap branch, which is synced to master but does not include the changes in this PR)

**Comment by dogmaphobic** [comment]
For clearing a mission from the vehicle. Something like this? (I haven't put too much thought on the layout and wording yet)

screen shot 2018-06-19 at 1 27 08 pm

**Comment by DonLakeFlyer** [comment]
> For clearing a mission from the vehicle. Something like this?

Sure.

Also for disable versus invisible. I tend towards disable since it makes the UI stable. It also gives people a hint as to what is possible to do. Or tehy may be confused when the buttons are not there.

**Comment by dogmaphobic** [comment]
> Also for disable versus invisible.

The idea was to maintain the separation of offline versus connected and active. It follows the rest of the UI, which transforms itself when you have a vehicle connected. Buttons that are always present in all states are never hidden, but disabled instead (Save, Save As, New, etc.)

**Comment by DonLakeFlyer** [comment]
> It follows the rest of the UI, which transforms itself when you have a vehicle connected.

Some does, some doesn't. All the DropPanel implementations follow the disable when no vehicle model. Looks at things like Center tool and so forth.

**Comment by Antiheavy** [comment]
> I tend towards disable since it makes the UI stable. It also gives people a hint as to what is possible to do. Or tehy may be confused when the buttons are not there.

I came here to say this.  Greyed out is better than disappearing.

**Comment by dogmaphobic** [comment]
Ok, new iteration:

* Create new, specific button for clearing mission from vehicle
* Adjust sizing of DropPanel

@DonLakeFlyer, the _Clear Vehicle Mission_ button calls `masterController.removeAllFromVehicle()`, which also clears the mission within the plan view. How do I only reset the autopilot but leave the mission in plan view alone? Also, is there a way to tell if there is a mission currently loaded in the autopilot? That way, the button is only enabled if that's the case. Otherwise it should be disabled.

screen shot 2018-06-20 at 9 00 18 am

**Comment by DonLakeFlyer** [comment]
> the Clear Vehicle Mission button calls masterController.removeAllFromVehicle(), which also clears the mission within the plan view. How do I only reset the autopilot but leave the mission in plan view alone?

PlanMasterController::removeAll

> Also, is there a way to tell if there is a mission currently loaded in the autopilot? That way, the button is only enabled if that's the case. Otherwise it should be disabled.

No current way to determine that from the Plan view.

**Comment by dogmaphobic** [comment]
> PlanMasterController::removeAll

That, like the others, clears everything. I couldn't find one that simply cleared the vehicle and left the mission within the Plan View in place.

**Comment by dogmaphobic** [comment]
I phrased the confirmation dialog in such a way that it will tell you both the existing mission and the vehicle will be cleared.

screen shot 2018-06-20 at 3 10 53 pm

**Comment by DonLakeFlyer** [comment]
> That, like the others, clears everything. I couldn't find one that simply cleared the vehicle and left the mission within the Plan View in place.

Could be added easily.

**Comment by dogmaphobic** [comment]
> Could be added easily.

For you! :P

**Comment by Antiheavy** [comment]
> Also, is there a way to tell if there is a mission currently loaded in the autopilot?

@dagar remember our discussions about need for mission sync status communication between firmware and ground station?  another example of why.

**Comment by DonLakeFlyer** [comment]
> remember our discussions about need for mission sync status communication between firmware and ground station? another example of why.

This is a bit different. This is just a missing API in QGC. The Fly View knows if there is a mission on the Vehicle but the Plan View does not.

**Comment by dogmaphobic** [comment]
I'm assuming this is good as it is. The only pending issue was the ability to clear the mission on a vehicle without affecting an existing mission within the Plan View. I could not think of a scenario where that would be important. If something comes up, we can tweak it in further PRs.

**Pull request merged**
