### PR TITLE
Remove RemoteID Configurations from Toolbar

### PR DESCRIPTION
**Pull request by bytesByHarsh**
Description
-----------
Remove a few config settings related to remote ID as they are now shifted to Application Settings.

Test Steps
-----------
1) Start Mocklink
2) Toolbar -> Remote ID -> Extended Menu

image

Related Issue
-----------
https://github.com/mavlink/qgroundcontrol/issues/12018

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Couple things...

There is a bug which is causing the empty group layout box at the top. This is the group box for Arm Status Error. The 'visible: labelText !== ""' in there should be on the SettingsGroupLayout control not the Labelled Label. This way the whole group goes away when not needed. This bug might also be in the full settings page.

The expanded page should include a "Configure" button which takes you to the full setup page. You can see it here inthe Battery page:
Screenshot 2024-12-09 at 9 44 48 AM

**Comment by bytesByHarsh** [comment]
> The expanded page should include a "Configure" button which takes you to the full setup page. You can see it here in the Battery page:

Already on clicking `Arm Status`, `GCS GPS` etc it is taking to the configuration page. Then should we add it again?


> There is a bug which is causing the empty group layout box at the top. This is the group box for Arm Status Error. The 'visible: labelText !== ""' in there should be on the SettingsGroupLayout control not the Labelled Label. This way the whole group goes away when not needed. This bug might also be in the full settings page.

image

image

If the above changes seem fine then I'll push the updated code.

**Comment by bytesByHarsh** [comment]
@DonLakeFlyer let me know if this way is fine:

image

**Comment by DonLakeFlyer** [comment]
Yup, perfect

**Pull request merged**
