### PR TITLE
Fix object de-reference crash on deletion

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Fix for Issue #1255

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@Susurrus Can you give this a try?

**Comment by Susurrus** [comment]
I'll start testing it now. In the future can you leave your style changes for a different commit, makes it really hard to see the real changes to the code. And that makes it easier to make sure the style changes are purely cosmetic.

**Comment by Susurrus** [comment]
Doesn't crash anymore, so that's fixed. But two follow-up issues:
  * After deleting the UAS the Unmanned Systems widget now shows the "Connect Link" button, which doesn't do anything when pressed.
  * Closing still pops up the "active connections to vehicles" dialog.

**Comment by DonLakeFlyer** [comment]
Can you enter an Issue assigned to me on the Connect thing. I need to pull that out of there and replace it with some ui to say no current UAS or something like that.

For the other problem, here is what I tried:
- Boot
- Connect to Pixhawk over USB
- Switch to Plan where I have the widget
- Disconnect
- Got save flight log dialog, cancel
- Right click Delete UAS
- Quit app
- No connection dialog, just shuts down

Do you have different steps to repro this?

**Comment by Susurrus** [comment]
I don't disconnect in QGC, I just stop the serial stream on the UAS end:

  1. Boot
  2. Connect to UAS
  2. Switch to Plan where I have the widget
  2. Stop the serial stream on the UAS end
  2. Right click Delete UAS
  2. Quit QGC
  2. Got save flight log dialog, cancel
  2. App quits

**Comment by DonLakeFlyer** [comment]
Delete is incorrectly made available when the heartbeat times out. It should only be there when the UAS is disconnected.

**Comment by Susurrus** [comment]
So is fixing the remove action not going to be part of this PR? I'm firing up my test station to check this out.

**Comment by DonLakeFlyer** [comment]
No it won't. That ends up being way more involved. It's related the the rest of the UI which falss on it's face when it tries to work against a disconnected UAS. I removed the delete action and added Issue #1275 to fix it and put it back at some point.

Also FYI: With the new serial port code step #4 will no longer disconnect the link which is why you will still get #7.

**Comment by Susurrus** [comment]
So is deleting a UAS is not supported at all anymore? If that's the case, then I imagine this commit is r+ by me.

**Comment by DonLakeFlyer** [comment]
Nope. I think if you delete the link after you disconnect it may go away, but can't remember.

**Comment by DonLakeFlyer** [comment]
Thanks @Susurrus

**Pull request merged**
