### PR TITLE
Joystick: Default to ThrottleModeDownZero

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Related to #4293.

@jaxxzer Does this affect you guys. Down Zero makes way more sense as default for fixed wing and multi-rotor.

### CODE REVIEW

**Comment by jaxxzer** [comment]
I'll check

**Comment by jaxxzer** [comment]
Is this safe/desireable? My understanding was that center is the default so that there is no throttle applied on an idle center-sprung throttle stick (which most gamepads have).

**Comment by DonLakeFlyer** [comment]
The majority use case for joystick is multi-rotor. With a multi-rotor center throttle is essentially hover in most flight modes. That's the reason most commerical multi-rotor controllers work the same way. Spring loaded centered throttle stick.

**Comment by jaxxzer** [comment]
OK. This change is fine/ non-functional for ArduSub. I don't know if this will interfere with takeoff or pre-arm checks on other vehicles, but I suspect it might.

**Comment by DonLakeFlyer** [comment]
You have to hold the throttle down to arm like a regular transmitter.

**Pull request merged**
