### PR TITLE
PX4 FW default landing altitude 0m

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dagar Does this work correctly? There is some code inside MissionItem i think which defaults altitude  from the C++ side of things. Not sure if the order is correct in that the json will change alt after that default is set.

**Comment by dagar** [comment]
It worked in the one case I tried it, which was adding a series of waypoints and changing the last to a land. Is this the correct way to be setting defaults, or do we need to figure out how it works with the MissionItem code?

**Comment by DonLakeFlyer** [comment]
Ok, the special altitude handling thing only applies to MAV_CMD_NAV_WAYPOINT so this will work fine.

**Comment by DonLakeFlyer** [comment]
@dagar Looking at this some more. Shouldn't this apply to everything: PX4/APM all vehicle types?

**Comment by DonLakeFlyer** [comment]
Related to #4426

**Comment by dagar** [comment]
Yes, I suppose it should.

**Comment by DonLakeFlyer** [comment]
Can you put in a issue for this pointing back to here. Then I'll fix it up.

**Pull request merged**
