### PR TITLE
Fix connected link check

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Fix for Issue #1458 (I think)

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Hm, I'm not sure if the general logic works - you can be connected via multiple links to the same system, which would be a valid state. I think its ok to refuse config with multiple links, but then the error message should say that it doesn't like the multiple links. In general I'd prefer to check if you have multiple UAS in the UASManager instead.

**Comment by DonLakeFlyer** [comment]
> you can be connected via multiple links to the same system

Will UAS id be the same for the links if multiple links connected to same system? 

The reason for this check is that it does a disconnect all. I don't want to disconnect some other vehicle the person may be flying.

**Comment by LorenzMeier** [comment]
The UAS ID is globally unique, and if your list count() is 1 then there is not a 2nd system talking to QGC.

**Comment by DonLakeFlyer** [comment]
Ok, let me fix it.

**Comment by DonLakeFlyer** [comment]
I wasn't initially getting what your were saying. Look now. This is what you were talking about right?

**Comment by LorenzMeier** [comment]
I can't see a pushed commit?

**Comment by DonLakeFlyer** [comment]
Oops

**Comment by LorenzMeier** [comment]
yes, looks good!

**Pull request merged**
