### PR TITLE
Android joystick

### PR DESCRIPTION
**Pull request by gregd72002**
Joystick support for Android devices

https://github.com/mavlink/qgroundcontrol/issues/3049

- only one joystick is supported on Android

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks! I just re-started the CI systems. Your diff is fairly large. Is this because your editor is changing line endings?

**Comment by LorenzMeier** [comment]
@dagar You will like this for your use case!

**Comment by dagar** [comment]
@gregd72002 can you rebase on master?

**Comment by gregd72002** [comment]
new (rebased) pull request created: https://github.com/mavlink/qgroundcontrol/pull/3305

**Pull request closed without merging**
