### PR TITLE
Qstr qml v4

### PR DESCRIPTION
**Pull request by tcanabrava**
Make sure unittest passes, rebased against latest master.

### CODE REVIEW

**Comment by tcanabrava** [comment]
Huh?
Em 12 de abr de 2016 21:14, "Don Gagne" <notifications@github.com> escreveu:

**Comment by DonLakeFlyer** [comment]
Close/Re-Open to pull in travis changes from master. Didn't work since there are merge conflicts.

**Comment by tcanabrava** [comment]
Will fix those tomorrow, since I'm touching too many strings, it's really
easy to have merge conflicts.
Em 12 de abr de 2016 21:54, "Don Gagne" <notifications@github.com> escreveu:

**Comment by tcanabrava** [comment]
closed befause of a new one opened with fixes merge conflicts.

**Pull request closed without merging**
