### PR TITLE
Allow altitude change with Pause command

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
The Pause command was only half useful as an "Oh shit!" button. To make it more useful it now allows you to changed altitude at the same time. This way you could say duck over or under something that was coming at you while flying a mission.

screen shot 2018-04-05 at 2 30 13 pm

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Related to #5826 sort of

**Comment by DonLakeFlyer** [comment]
@antiheavy This could use some fixed wing SITL testing if you have time once it's through. I managed to trash my gazebo environment so I can test fixed wing right now.

**Comment by Antiheavy** [comment]
> This could use some fixed wing SITL testing if you have time once it's through.

sounds good.  i have a bunch of other things I need to test in FW PX4 SITL this weekend anyway.

**Comment by Antiheavy** [comment]
I finally was able to get a fixed wing simulator working in Windows (thanks to https://github.com/mavlink/qgroundcontrol/pull/6366).  The altitude slider presented immediately upon Pause goes a long way to improving the "oh sh*t" reaction time in QGC.  It works great and is pretty intuitive.  thanks @DonLakeFlyer

**Pull request merged**
