### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
* Show advanced ui confirmation now mentions possible voiding of warranty
* Max alt for missions settings is 400ft, you can Force Save to go higher

### CODE REVIEW

**Comment by kikislater** [comment]
Max 400ft is very limited. Why choosing this value ?

**Comment by DonLakeFlyer** [comment]
400ft is max allowed in US. In reality the altitude in unlimited you just need to use Force Save to override the max.

**Comment by kikislater** [comment]
Ok I will force it in that case ... 
But there is not only US users, is it only for US ?

**Comment by dogmaphobic** [comment]
According to this, your limit is around 492' (150m)
http://www.mlvdrone.fr/rules-for-flying-recreational-drones
Each country will have their own rules. The question is how to make it "global"?

**Comment by DonLakeFlyer** [comment]
I needed to pick some max to prevent fly away from bad values. Also keep in mind that this is Mission Settings only. It's mainly a simple stop-gap. You can still adjust individual waypoints to what you want.

**Comment by kikislater** [comment]
I don't fly only in France, so it's not only 150m but you're right, make it global or not that is a question ...

**Pull request merged**
