### PR TITLE
fix survey center position editing

### PR DESCRIPTION
**Pull request by julled**
This fixes the not working editing of the center position of a survey pattern.

With this fix, the user can edit the center position of the survey pattern through the mission item list "Edit position..." mechanism.

This was tested on the stable_v4.1 branch. I cant build on the current master branch due to error #9864 .

**EDIT**: was able to build and test my patch on the master branch (== julled:fixSurveyPosEditMaster) so therefore its tested on current master.

### CODE REVIEW

**Comment by booo** [comment]
Tested. Works. Nice job.

Could you please add a commit body that explains what you did and why you did it. Thanks.

**Comment by booo** [comment]
Could someone please approve the test workflows? Thanks a lot.

**Comment by booo** [comment]
Tested on Android. Works fine.

**Comment by julled** [comment]
The windows build failes due to
` qrc_qgcresources.cpp(607595): fatal error C1060: compiler is out of heap space`
I dont think this is related to this patch, as other builds dont fail. How should i proceed to bring the patch upstream?

**Comment by booo** [comment]
We are doing sea trials in a day or two. It would be awesome to get this feature upstream. Can someone from the dev team comment and/or merge?

**Comment by DonLakeFlyer** [comment]
I think this may be out of date with master. I thought that resource thing was fixed now. If you rebase to master I think CI will pass then.

**Comment by DonLakeFlyer** [comment]
Either way, resource thing is unrelated I'll merge.

**Pull request merged**
