### PR TITLE
ArduPIlot: Don't show/calibrated compass which are turned off

### PR DESCRIPTION
**Pull request by DonLakeFlyer**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Fixed: 
https://github.com/ArduPilot/ardupilot/issues/7058
https://github.com/mavlink/qgroundcontrol/issues/5754

**Comment by AndKe** [comment]
merged into stable_V3.2 only,not available in HEAD ?

**Comment by DonLakeFlyer** [comment]
Working on it.

**Comment by AndKe** [comment]
thanks, I were not sure I followed correct branch :)

**Comment by DonLakeFlyer** [comment]
No you have it right. It was pretty screwed up so I wanted in Stable as well.

**Pull request merged**
