### PR TITLE
Switching back to Development 2.6

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Though I was going to pull a Stable but that is delayed for now

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I'm actually happy with the current state to cut a new stable. No known issues and all critical fixes to survive the next weeks.

**Comment by DonLakeFlyer** [comment]
Just trying to remove confusion around naming. Since I'm not going to have time to cut a stable myself. 

You could make a Stable yourself if you want:

1) Push a change to move to Stable 2.7 in QGCConfig.h
2) Wait for the next nights daily build to go through
3) Take those daily builds, download and push it back to AWS using the stable build naming scheme
4) Update the wiki
5) Push a change to move to Development 2.8 in QGCConfig.h

**Comment by LorenzMeier** [comment]
I'll do that then, thanks!

**Comment by porcoesphino** [comment]
You forgot to tag the commit that the 2.7 binary was built from. What commit was it?

The message on this one looks correct but its one the master branch:

https://github.com/mavlink/qgroundcontrol/commit/cece2650077fd468a77631e8f8c7481331eed088

**Pull request closed without merging**
