### PR TITLE
Adding a crash guard for when a command resend timeout occurs with an…

### PR DESCRIPTION
**Pull request by dogmaphobic**
… empty command queue.

### CODE REVIEW

**Comment by dogmaphobic** [comment]
@DonLakeFlyer I'm pushing this in as I need it elsewhere. I'm not sure what is going on. I didn't have time to take a thorough look at the code that starts the timer. In situations like this, I make sure to set the timer to single shot and only start on demand so it doesn't repeat when you don't expect.

Something like (off my own code):

```
connect(&_timer, &QTimer::timeout, this, &MyClass::_stateManager);
_timer.setSingleShot(true);
```

That way, only when I need it to go off I execute `_timer.start()` and it runs only once.

**Comment by DonLakeFlyer** [comment]
This is already fixed in master. Can't remember which pull.

**Comment by DonLakeFlyer** [comment]
Can you pull this out now?

**Comment by dogmaphobic** [comment]
Technically it doesn't hurt to have a crash guard in there just in case.

**Pull request merged**
