### PR TITLE
add terrain to survey plan

### PR DESCRIPTION
**Pull request by mohammada315**
add terrain to survey plan

### CODE REVIEW

**Comment by mohammada315** [comment]
add terrain mode to survey plan

**Comment by DonLakeFlyer** [comment]
This pull is not correct. Supporting terrain frame in Survey is way more complex than this to fully implement. I'm in the process of working my way towards it. Hopefully done in a few weeks.

**Comment by mohammada315** [comment]
That's right, but it works for us

**Comment by mohammada315** [comment]
I want to add this
https://github.com/mavlink/qgroundcontrol/issues/9639
There is a guide for me ؟
Thank you

**Comment by DonLakeFlyer** [comment]
There is no guide other than looking through the current Survey code. Also going to be quite complex to support.

**Pull request closed without merging**
