### PR TITLE
Implement click-to-retask via MISSION_SET_CURRENT in flight view for #2275

### PR DESCRIPTION
**Pull request by NaterGator**
Initial implementation. Would love feedback from mobile testers. 

Also raises the issue: in my opinion on desktop we should be changing the cursor to clue the user that an action will be taken if they click on something. Currently the cursor never changes and it is a wild guess. 

Related issue: #2275

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
I can't remember is MissionItemView only used in Fly and not Plan? Plan click behavior needs to stay the same.

**Comment by NaterGator** [comment]
Correct, MissionItemView is only used for fly. Plan uses MissionItemIndicator directly.

**Comment by DonLakeFlyer** [comment]
I think this needs confirmation. If you look at how I do guided mode goto you should be able to use the same mechanism. I tried testing it in SITL, but master SITL seems to be a basket case right now.

**Comment by NaterGator** [comment]
@DonLakeFlyer by "confirmation" do you mean mean closed loop packet delivery?

**Comment by DonLakeFlyer** [comment]
No I mean that you should ask the user if this is what they really wanted to do. Example below for change altitude in guided mode. Same prompt happens in guided mode if you click on the map to move the vehicle to a new position.
screen shot 2016-03-09 at 3 13 58 pm

**Comment by DonLakeFlyer** [comment]
@NaterGator If you want I can merge this then I'll add the confirmation check.

**Comment by DonLakeFlyer** [comment]
Awesome, thanks Nate

**Pull request merged**
