### PR TITLE
MainWindowHybrid: Close app if something goes wrong with item

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by dogmaphobic** [comment]
Makes sense

**Comment by DonLakeFlyer** [comment]
It causes the mainwindow to be closed before shutdown dialog prompt is displayed. So if you cancel shutdown you are left in a state where QGC is running but there is no main window.

**Comment by patrickelectric** [comment]
This approach solved some issues that I was having. If something goes wrong with QGC, it's almost impossible to close it, the close signal is handled by it owns components. Theoretically this PR should not give any problems, sorry about that.

**Comment by DonLakeFlyer** [comment]
The thing is that ```mainWindowInner.item.attemptWindowClose()``` does next to nothing. All it does it pop a yes/no dialog and then set a flag. So hard to see how that would ever throw an exception.

**Pull request merged**
