### PR TITLE
Support of ComponentInformation for more User-Friendly Component Handling

### PR DESCRIPTION
**Pull request by olliw42**
It's now about 1/2 year ago that I've suggested to extend the concept of a definition file which underlies the MAVLink Camera microservice - which I consider a really very cool concept! - to components in general, in order to facilitate GUIs to present more user-friendly interfaces to the user also for components. We are at the brink of 2020, right? :)

Besides the initial positive comment by @LorenzMeier, saying "_Cool proposal! I totally agree that it would make things a lot easier to automate and allow to build proper UI without having to change the GCSs_", and implementing support by the STorM32  gimbal controller soon after, not much has happened. This PR is about trying to change this.

Some references for background:
* https://github.com/mavlink/mavlink/issues/1133, "Proposal for Improving User-fiendliness of Component Handling"
* https://github.com/mavlink/mavlink/issues/1169, "Support for a component version"
* https://github.com/mavlink/mavlink/pull/1176, "COMPONENT_INFORMATION"
* https://github.com/mavlink/qgroundcontrol/issues/7503, "Proposal for Improving User-friendliness of Component Handling, GCS Side"

This PR does already do a lot and has it working. There are some tiny itches with the fact system, e.g. it seems that decimal is not supported for int valued parameters, Refresh needs to be considered, etc. But the screen shots below should demonstrate what kind of improvements it brings as is.

What I want to stress however is that this of course isn't the end of it! The definition file concept is so cool since it's so flexible and extensible, and it will allow many things in the future! IMHO.

BTW: Reproducing the below is really simple, you just need a naked STorM32 board, e.g. a v1.3, a v3.3, or a micro, without any IMU or anything, else, just need to flash its latest firmware do 2 settings and are ready to go. I will be happy to guide anyone through :).

Have fun, and looking forward for your suggestions, 
Olli

UPDATE 2019-12-01: pics updated to reflect latest
FYI, xml involved in the below: www.olliw.eu/downloads/storm32/xml/storm32_compdef_nonfoc_v247.xml
UPDATE 2019-12-11: mavlink module updated, and rebased => this PR does work now.

Watch out for the "!!!!", "$$$$", and "ZZZZ" to trace the handling:
qgc-compinfo-wip07-01

Note this:
1) The groups list has nice names, which exactly correspond to that of the native GUI of that component
2) The parameters have nice names which exactly correspond to that of the native GUI, and not these MAVlink-ish short hand names
3) The parameters have meaningful values, units, and so on, as well as short descriptions. 

qgc-compinfo-wip07-02

The parameters also have long descriptions. and meaningful edit and/or dropdown fields. I also updated the editor qml layout a bit to be more user friendly.
qgc-compinfo-wip07-03
qgc-compinfo-wip07-04

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@olliw42 This should up for discussion in the mavlink repo not here. Since it is a mavlink spec change isn't it?

**Comment by olliw42** [comment]
It's an addition to the MAVLink spec, not a change in the sense of changing anything existing.

You are right. However, I believe this step had been passed already. It's all revealed in the links I've given in the above, but I perfectly understand that one doesn't want to wade through them, so let me pl summarize.

This had been discussed in a MAVLink dev call ca 1/2 years ago, and the conclusions in my understanding were (@hamishwillee @julianoes @LorenzMeier, pl intercept and correct me where I'm inaccurate):
* the concept was positively received by MAVLink, and we agreed on this approach to move forward:
* I was supposed to suggest a draft of a MAVLink message, which resulted in PR https://github.com/mavlink/mavlink/pull/1176
* I was supposed to implement the draft in the STorM32 gimbal controller as test environment, as well as MAVLinkFTP support as much as possible, which I both did
* it was suggested that I get into contact with you, the QGC guys (@julianoes actually suggested @dogmaphobic), which resulted in issue https://github.com/mavlink/qgroundcontrol/issues/7503

(it was not suggested I should do a QGC PR, LOL) 

So, I think it has passed the MAVLink side, and I'd like to add that the PR https://github.com/mavlink/mavlink/pull/1176 on the COMPONET_INFORMATION message appears to be on the brink of being merged.

Hope this helps a bit,
Olli

**Comment by hamishwillee** [comment]
@DonLakeFlyer FWIW @olliw42 recollection of the discussion matches mine. We liked the proposal to generalise the camera definition file to other components and created messages to support that. 

I wasn't part of the discussion around the actual XML file definitions for gimbals (that probably needs to go in docs once this is finalised).

So you can take the broad concept as agreed by MAVLink and supported by appropriate messages. However it is AFAIK all WIP so if there are flaws in our logic w.r.t. best ways of working this is not set in stone.

What else you need to be able to review this?

**Comment by olliw42** [comment]
thx @hamishwillee

**Comment by olliw42** [comment]
I'm here BTW not asking for a full-fledged review, but rather guide into which direction to go where the direction is not yet optimal.

**Comment by DonLakeFlyer** [comment]
@olliw42 Can you rebase this to latest master?

**Comment by olliw42** [comment]
>  Can you rebase this to latest master?

sure. I will do this evening.

I think that  currently it would however be more important to push the MAVLink guys to finally merge the COMPONENT_INFORMATION, so that the latest mavlink could be included into QGC, so that I could provide a really functioning PR. As it currently is, one can't produce working code by just compiling this PR, since it will complain about the missing COMPONENT_INFORMATION.

Btw: I improved things further (or at least I think so LOL) by introducing a ComponentManager class, which ties to the vehicle class, i.e., the handling of the MAVlink messages isn't through the UAS class anymore (which I understand should eventually go). It also slims the ParameterManager class.

**Comment by DonLakeFlyer** [comment]
So directionally I think this is the way to go (for both main autopilot and secondary components). I'm only in town for a couple more days, then I"m gone for three weeks. When I come back I'll work to push through the all the mavlink COMPONENT_INFORMATION spec changes.

**Comment by olliw42** [comment]
fantastic
thx for sharing your time scale, it's good to know
in three weeks I think things should have further matured and COMPONET_INFORMATION hopefully be merged, so that it's easier to test
have fun :)

**Comment by DonLakeFlyer** [comment]
> COMPONET_INFORMATION hopefully be merged

Can you hold off pushing on that. I want to have time to review it again and possibly propose additional changes before it goes in. I just don't have time to do that right now.

**Comment by olliw42** [comment]
:)

**Comment by olliw42** [comment]
rebased to latest master, which thankfully has the mavlink module updated so that this branch/PR can now be compiled out of the box. Updated the 1st post accordingly.

:)

**Comment by hamishwillee** [comment]
@DonLakeFlyer Ping on this one; appreciate you've processed millions of PRS issues in last few days. Just don't want this one to fall off the list.

Not sure what the linux build error means.

**Comment by DonLakeFlyer** [comment]
I'm wrapping up a new Stable right now. This is going to be too big of a change to late in the game to go in. It's going to have to wait until we branch Stable and then can go into master.

**Comment by olliw42** [comment]
I would add that it's not mature enough to go into stable. It would be great to have in master so those who want can use/test, but it's very sensible IMHO to not put into stable.

**Comment by DonLakeFlyer** [comment]
Also mid next week if you don't see me getting back to reviewing this stuff including mavlink message spec. Ping me. I'm still in Kenya now, but will be back next week. I may forget. Takes a while to dig out from being gone.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer This is now implemented based on the parallel MAVLink proposal, so I presume this could be closed and @olliw42 could work off the implementation in that new PR?

**Comment by holden-zenith** [comment]
should this be closed?

**Pull request closed without merging**
