### PR TITLE
MissionItemStatus: Below altitude color change according to vehicle

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
It seem like the real change here would be to not show terrain values for a sub?

**Comment by DonLakeFlyer** [comment]
@patrickelectric @jaxxzer ?

**Comment by patrickelectric** [comment]
The terrain alttitude will be removed when using AUV or ASV.
This PR will be updated.

**Comment by patrickelectric** [comment]
Moving to #5891

**Pull request closed without merging**
