### PR TITLE
Fix GStreamer package for macos

### LINKED ISSUE #9478: QGC 4.1.1 video on macos is not working
## Expected Behavior
Video should show

## Current Behavior
Video is not showing

## Steps to Reproduce:
1. Open QGC
2. Video does not show

## System Information
When posting bug reports, include the following information
- Operating System: MacOs 11.2.1
- QGC Version: 4.1.1
- QGC build: stable
- Flight Controller: None
- Autopilot (with version): None

## Log Files and Screenshots
It appears that the problem is that it can't find qmlglsink, from log:
```
 GST_ELEMENT_FACTORY gstelementfactory.c:456:GstElement *gst_element_factory_make(const gchar *, const gchar *): no such element factory "qmlglsink"!
```

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix #9478

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Are all OS on 18.3 or just OSX?

**Comment by DonLakeFlyer** [comment]
Ah, "Draft" I can't keep track of all the new GitHub stuff!

**Comment by patrickelectric** [comment]
> Are all OS on 18.3 or just OSX? These should be consistent. Also I don't want to reference third party locations. If you give me all the files I can upload to S3.

Yep, I'll move to 1.18.1 after I get it working, I believe that I have figure out how to create the tar files with @rpath configuration for the dlls. I'll write a script for us that will create such files without human intervention, and document all the process

**Comment by DonLakeFlyer** [comment]
> I believe that I have figure out how to create the tar files with @rpath configuration for the dlls.

Isn't that https://github.com/mavlink/qgroundcontrol/blob/master/tools/prepare_gstreamer_framework.sh?

**Comment by DonLakeFlyer** [comment]
I think that is run from the travis script after install.

**Comment by patrickelectric** [comment]
> > I believe that I have figure out how to create the tar files with @rpath configuration for the dlls.
> 
> Isn't that https://github.com/mavlink/qgroundcontrol/blob/master/tools/prepare_gstreamer_framework.sh?

This is done to configure the libraries for the dmg after it gets the QGC binary done.

I'm working with the gstreamer installation based in a specific version (since we don't use official gstreamer installation binaries), for that is necessary to remove the @rpath with a fixed path from what I understood after studying the previous zip folder for older QGC .dmg files.
This is done with the helper of https://github.com/mavlink/qgroundcontrol/blob/master/tools/osxrelocator.py

**Comment by DonLakeFlyer** [comment]
That is all Gus's stuff. You could try getting a hold of him if you need help.

**Comment by patrickelectric** [comment]
@dogmaphobic do you remember something about it ? can you point how to create the .tar for gstreamer CI ?

**Comment by DonLakeFlyer** [comment]
osxrelocator is used at build time not when creating the package for S3.

**Comment by DonLakeFlyer** [comment]
You could also try pinging Gus on slack he might see it there more quickly.

**Comment by patrickelectric** [comment]
> osxrelocator is used at build time not when creating the package for S3. As far as I always understood the S3 package is just the framework zipped up with no changes.

Is a post link step, after the build is done when macdeployqt finishes, it's used to remap gstreamer libraries to create the dmg file.

**Comment by patrickelectric** [comment]
> You could also try pinging Gus on slack he might see it there more quickly.

I'll get in touch with him, meanwhile I'm trying to remove the necessity of the tar.gz file and use the gstreamer .pkg directly.

**Comment by DonLakeFlyer** [comment]
> I'm trying to remove the necessity of the tar.gz file and use the gstreamer .pkg directly.

That's just to save build time from the download.

**Comment by DonLakeFlyer** [comment]
I'm not sure who changed that. I think it used to be .pkg directly since those older packages are still up on S3. So tar may be recent.

**Comment by DonLakeFlyer** [comment]
@patrickelectric Any update on this?

**Comment by mrpollo** [comment]
@patrickelectric Move to GH, please!

**Comment by DonLakeFlyer** [comment]
@patrickelectric This has been verified as working. Can you give me a 1.18.1 version of GST tarball and I can put it up on S3 for you.

**Comment by patrickelectric** [comment]
@DonLakeFlyer, can you try this one: https://s3.us-east-1.amazonaws.com/downloads.bluerobotics.com/QGC/dependencies/gstreamer-osx-1.18.1.tar.bz2 ?

**Comment by DonLakeFlyer** [comment]
It's uploaded to S3. Both travis and github actions will need to be updated.

**Comment by DonLakeFlyer** [comment]
And then this will need to go to Stable

**Comment by DonLakeFlyer** [comment]
@patrickelectric Can you get this into master and Stable and then I can trigger a new Stable.

**Comment by patrickelectric** [comment]
> It's uploaded to S3. Both travis and github actions will need to be updated.

Can you provide the URL ?

**Comment by DonLakeFlyer** [comment]
https://qgroundcontrol.s3.us-west-2.amazonaws.com/dependencies/gstreamer-osx-1.18.1.tar.bz2

**Comment by DonLakeFlyer** [comment]
I posted the new 1.18.3 version to S3 and fixed up the links.

**Comment by patrickelectric** [comment]
I did some tests this morning and it appears to be not working. I believe
that some work is necessary in the post link part to fiz the relative
reference.

**Comment by acxz** [comment]
@patrickelectric can you make a macos build for gstreamer-1.20.0? It is required for #10153

**Comment by fredowski** [comment]
The current build artefacts for MacOS from CI are not working with respect to video streaming. I have prepared and tested PR #10396 for this. I reuse the patches from this PR here from @patrickelectric but everything is updated from 1.18.1 to 1.18.6. I use the official gstreamer package.

**Comment by booo** [comment]
The proposed change is superseded by https://github.com/mavlink/qgroundcontrol/commit/984e9f23795bc19d81ddb948d4f130c58782c8ec as far as I can see. Closing this therefore. Please reopen or create another PR/issue if there is still stuff to do.

**Pull request closed without merging**
