### PR TITLE
Add battery voltage in Toolbar's Instrument Panel

### PR DESCRIPTION
**Pull request by zdanek**
For most of pilots it's more beneficial to know current voltage. They know their batteries / hardware the best so they know how to react on battery voltage more than on percentage only.

Those are  examples, with two batteries, second one has voltage unavailable, but adds a description instead.
image

image

image

image

### CODE REVIEW

**Comment by zdanek** [comment]
Btw, looking at those examples, bear in mind that they were based on SITL, that simulates percentage drop, but not voltage. So don't look for an error in displaying save voltage value at every screen even though percentage drops :)

**Comment by zdanek** [comment]
If you need bigger screen slice for better understanding
image

**Comment by DonLakeFlyer** [comment]
Could you horizontal center the multiple text parts in the column? I think it would look nicer that way.

**Comment by DonLakeFlyer** [comment]
I integrated this into #10909

**Pull request closed without merging**
