### PR TITLE
RTSP video crash，use  old  function

### PR DESCRIPTION
**Pull request by yl5006**

### CODE REVIEW

**Comment by dogmaphobic** [comment]
What crashed? This was working fine.

**Comment by yl5006** [comment]
software  crash ，May my software version not correct。 but when I start connect rtsp video .software  crash

**Comment by dogmaphobic** [comment]
Do you have the error output when it crashes? Are you using GStreamer 1.5.2?

**Comment by yl5006** [comment]
gstreamer-1.0-x86-1.8.1 ,no out put

**Comment by dogmaphobic** [comment]
QGC only supports 1.5.2. There should be some output unless you are running Windows. The output would indicate if some library was missing or some pipeline error, which could indicate what to do to make it work.

**Pull request closed without merging**
