### PR TITLE
VTOL tilt-rotor airspeed sensor

### PR DESCRIPTION
**Pull request by Austriker**
Do not merge.
missing submodule pull request : https://github.com/mavlink/mavlink/pull/372

Added MAV_TYPE_VTOL_TILTROTOR for vtol tilt-rotor airspeed sensor calibration.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
What is going on with this pull?

**Comment by Austriker** [comment]
@DonLakeFlyer This PR works only if the mavlink MAV_TYPE_VTOL_TILTROTOR  is added but it's still not merged. @tumbili

**Comment by Austriker** [comment]
@DonLakeFlyer the new mav_type has been added to the mavlink so this PR should be good to go now.

**Comment by DonLakeFlyer** [comment]
The mavlink submodule is going to need to be updated to the latest as well in QGC. Can you do that?

**Comment by Austriker** [comment]
yes i will do that.

**Comment by Austriker** [comment]
@DonLakeFlyer Good to go.

**Comment by DonLakeFlyer** [comment]
Perfect, thanks.

**Pull request merged**
