### PR TITLE
Fixed Wing Landing Pattern

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
* Correct cross track value loiter to be tangent exit for item sent to vehicle
* Visuals shows tangent flight path
* Fix mission item editor command json for xtrack enum

screen shot 2017-03-03 at 2 45 14 pm

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Related to #4635

**Comment by DonLakeFlyer** [comment]
Please, no more geometry for a while!

**Comment by NaterGator** [comment]
For what it is worth you can also just project the coordinate by radius meters from the origin of the loiter at a bearing of bearing(loiter,land) (+/-) 90° (where the sign is determined by loiter being anti/clockwise. 

Anyways, you did it the hard way and that is fine too ;)

**Comment by DonLakeFlyer** [comment]
I don't think that works in all case, like this one? The tangent isn't always at 90 degrees. Unless I'm seeing something wrong.
screen shot 2017-03-03 at 3 49 48 pm

**Pull request merged**
