### PR TITLE
Log handling

### PR DESCRIPTION
**Pull request by dogmaphobic**
Implementation of Log Download.
This needs an updated firmware to respond (https://github.com/PX4/Firmware/pull/3398)
I have not tested with APM. I need to flash something with it and generate some logs.
First shot at it. There is room for improvement. Waiting for feedback.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice! What is the testing state of this? Fully functional?

**Comment by LorenzMeier** [comment]
And how does it look like? 8)

**Comment by dogmaphobic** [comment]
> Nice! What is the testing state of this? Fully functional?

Fully functional with my firmware changes (PX4). Not tested with APM. I tested using direct USB and UDP. I don't have anything with a radio working at the moment. My UDP tests had tons of data loss and the recovery code worked perfectly. All logs received and 0 diffs.

**Comment by LorenzMeier** [comment]
Ok. I merged that, so I propose to merge this as well as it passes. Many thanks, great!

**Comment by LorenzMeier** [comment]
If issues persist we can fix them on the go. This will unblock a lot for developers. @pkocmoud This is something you will want to try with Pixracer Wifi once merged.

**Comment by dogmaphobic** [comment]
> Pixracer Wifi once merged.

All my UDP tests were done with the PixRacer.

**Comment by LorenzMeier** [comment]
Ah - I thought you have nothing wireless 8). Great!

**Comment by dogmaphobic** [comment]
No, I meant I don't have anything with a 3DR Radio connected at the moment. Therefore I didn't test it at low baud rates. High baud rates are being hit by the very small packet payload (only 90 bytes).

**Comment by dogmaphobic** [comment]
> And how does it look like? 8)

Spartan but functional :)

screen shot 2016-01-05 at 2 58 18 am

**Comment by dogmaphobic** [comment]
By the way, the dates are all close to the same because I kept "Erasing All" and re-copying the logs to the MicroSD card. The dates are of the last copy.

**Pull request merged**
