### PR TITLE
Penta Avioneo eVTOL

### PR DESCRIPTION
**Pull request by yvescharles**
Penta Avioneo eVTOL duo coax C/R on differential tiltwings + light1/10 front pitch turbine

---
name: New airframe group type based on avioneo prototype
about: Create a new image

---

**Describe the bug**
Providing the svg image for this group into the qgc repository

**Log Files and Screenshots**
see the png file

**Drone avioneo prototype on www.avioneo.com

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Not sure what this is about. Is there a new airframe showing up in the airframe.xml file? If so, where is that new file. Also new images need to be added to the resource file.

**Comment by hamishwillee** [comment]
@DonLakeFlyer I don't know anything about this either, but the PR in firmware is here: https://github.com/PX4/Firmware/pull/10914 (ie XML not generated yet). There are associated devguide changes too, but I don't propose to do anything about them until the Firmware PR is accepted.

**Comment by DonLakeFlyer** [comment]
Ok, so it is a new airframe. The whole new airframe.xml need to come across to QGC as well. And the resource needs to be added to the Qt resource file.

**Comment by hamishwillee** [comment]
So the airframe XML should magically come across as-per-usual when firmware is updated. I don't know about the Qt resource file updates - is there information/pointer on what has to happen there?

**Comment by DonLakeFlyer** [comment]
> So the airframe XML should magically come across as-per-usual when firmware is updated.

I'm not sure if PX4 build does that? Or if it needs to be hand carried across. I know it does it automatic for parameter meta data.

**Comment by hamishwillee** [comment]
> I'm not sure if PX4 build does that? Or if it needs to be hand carried across. I know it does it automatic for parameter meta data.

I'm pretty sure it does, based on this section on adding an airframe to QGC: http://dev.px4.io/en/airframes/adding_a_new_frame.html#add-new-airframe-to-qgroundcontrol

**Comment by DonLakeFlyer** [comment]
Airframe pictures resources should go in qgresources.qgc following the pattern below:
```
    <qresource prefix="/qmlimages">
        ...
        <file alias="Airframe/AirframeSimulation">src/AutoPilotPlugins/Common/Images/AirframeSimulation.svg</file>
        <file alias="Airframe/AirframeUnknown">src/AutoPilotPlugins/Common/Images/AirframeUnknown.svg</file>
        <file alias="Airframe/Boat">src/AutoPilotPlugins/Common/Images/Boat.svg</file>
        <file alias="Airframe/FlyingWing">src/AutoPilotPlugins/Common/Images/FlyingWing.svg</file>
        <file alias="Airframe/Helicopter">src/AutoPilotPlugins/Common/Images/Helicopter.svg</file>
        <file alias="Airframe/HexaRotorPlus">src/AutoPilotPlugins/Common/Images/HexaRotorPlus.svg</file>
        ....
```

**Comment by hamishwillee** [comment]
Thanks @DonLakeFlyer - Updated instructions in PR https://github.com/PX4/Devguide/pull/669 . Let me know if there is anything else needed to improve this. 
Probably would be good idea to explain the resource file organisation in the QGC devguide at some point.

**Comment by hamishwillee** [comment]
@yvescharles Please add link to this file in resources as per https://github.com/mavlink/qgroundcontrol/pull/7036#issuecomment-441806420 - note that this should be part of this same PR.

**Comment by DonLakeFlyer** [comment]
Not sure why this pull has a parameter meta data update in it? That shouldn't be the case.

**Pull request closed without merging**
