### PR TITLE
Update PX4 Firmware metadata Mon Oct 15 13:47:56 UTC 2018

### PR DESCRIPTION
**Pull request by dagar**
Latest auto generated PX4 airframe metadata. Adds the X-UAV Mini Talon.

### CODE REVIEW

**Comment by dagar** [comment]
@tony3dr fyi

**Comment by dagar** [comment]
@fredowski @hamishwillee - something's not quite right with the metadata. We're missing the Plane V-Tail image.
https://github.com/mavlink/qgroundcontrol/pull/6852

We'll need to get this sorted out across Firmware, user guide, QGC.

**Comment by dagar** [comment]
This is safe to merge, but the core issue still needs to be looked at.

**Comment by dagar** [comment]
> What is the procedure to introduce the image file?

Good question. I don't know, but let's find out.

As for the metadata we should let the bot update it automatically from the source.

**Comment by fredowski** [comment]
Maybe the bot will keep the image info once it is there. I will make a new PR with the image name added.

**Comment by fredowski** [comment]
I opened a new PR #6925 which fixes the autogenerated code. It adds the image and fixes the class info.

**Pull request merged**
