### PR TITLE
Do not send virtual joystick commmands over high latency links

### PR DESCRIPTION
**Pull request by acfloria**
This can block a high latency link. In addition due to the latency it does not make sense to send control commands anyway over that link.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
I wonder about adding checks for high latency for these things. You have the same problem with a regular joystick. A high latency link is a pretty high end usage pattern that I would think the user kind of needs to know what they are doing to some extent. I"m worried about adding a lot more checks all over the place which could lead to bugginess in mainline usage.

**Comment by acfloria** [comment]
I partially agree, only an experienced user will operate Satcom. Nevertheless I think some checks are good because those actions could really block the link. Those are the mission upload, parameter synch and the virtual joystick. For the first two we have checks, for the last one not, that is why I wanted to fix it.

With regards to the regular joystick we don't use one. But if someone is flying using SatCom and the regular Joystick then transmitting the joystick commands must be stopped or the link will be blocked by the joystick commands.

**Comment by acfloria** [comment]
@DonLakeFlyer any decision/update from your side?

**Comment by DonLakeFlyer** [comment]
I think what would be better here would be to also hide the virtual sticks in this case. That way the user at least wouldn't expect them to do something. They may be confused as to why they aren't visible but I think that's ok for this case.

**Comment by acfloria** [comment]
@DonLakeFlyer I implemented your suggestions, can you have a look at them?

**Comment by acfloria** [comment]
I missed to check if the active vehicle exists in FlightDisplayView.qml, this is now fixed.

**Pull request merged**
