### PR TITLE
Show stock image as background when Waiting For Video

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Before:
Screen Shot 2023-02-25 at 21 42 21

After:
Screen Shot 2023-02-25 at 21 38 14

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Since this is just a normal QGC resource, custom builds can override it to anything they want.

**Comment by mrpollo** [comment]
Hey @DonLakeFlyer, I like the addition of the background image. Would it be possible to adjust the text color to increase contrast? Another trick to increase contrast would be to add background to the text or a text-shadow.


NoVideoBackground-BG

NoVideoBackground-SHADOW

**Comment by kibidev** [comment]
I assume this is a 3rd party stock photo? Could you include license and credits in some form? I assume this is not included in the general project Apache/GPL license.

**Comment by DonLakeFlyer** [comment]
The photo has no licensing and/or attribution requirements.

**Comment by DonLakeFlyer** [comment]
> Would it be possible to adjust the text color to increase contrast?

Done:
Screen Shot 2023-03-29 at 08 21 43

**Review by mrpollo — APPROVED** [review]
lgtm

**Comment by DonLakeFlyer** [comment]
Thanks @mrpollo

**Pull request merged**
