### PR TITLE
Cleanup record button

### PR DESCRIPTION
**Pull request by jaxxzer**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
What exactly does this do?

**Comment by jaxxzer** [comment]
It's non-functional. Just refactoring. I'll amend it to rid of the whitespace changes in a moment.

**Comment by jaxxzer** [comment]
This was in a branch we used to fix some problems with the blinking animation during state changes, but those same problems were resolved when @dogmaphobic moved the video record button to a widget. Sorry if the branch name is misleading here.

**Comment by jaxxzer** [comment]
Actually, this does change the visual style slightly (it will make the camera picture fade with the red background). I like the way it is currently better. I'm closing this, sorry for the noise.

**Comment by jaxxzer** [comment]
Thanks @dogmaphobic for the visibility->opacity change, I think it is a good improvement.

**Pull request closed without merging**
