### PR TITLE
Exception created to improve TTS saying ADSB

### PR DESCRIPTION
**Pull request by lvale**
To improve the way that TTS engines say ADSB

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Can't these be "I D" and " A D S B"?

**Comment by lvale** [comment]
I tried " A D S B " and didn't sound right, so had to opt to some "phonetic" approach
Using both AVA, SAMANTHA and ALLISON TTS voices

**Comment by lvale** [comment]
the ID substitution was from @dogmaphobic and it also sounds right

**Comment by DonLakeFlyer** [comment]
Ok, got it.

**Pull request merged**
