### PR TITLE
APM: Mission Flight Speed

### PR DESCRIPTION
**Pull request by dakejahl**
APM firmware does indeed support the MAV_CMD_DO_CHANGE_SPEED command for changing the speed for a mission. I tested this in sim against Copter-4.0.7 and QGC master as of today.

### CODE REVIEW

**Comment by julled** [comment]
@booo interesting for us?

**Comment by booo** [comment]
Yes, of course this is of interest for the SearchWing project too.

**Comment by DonLakeFlyer** [comment]
> APM firmware does indeed support the MAV_CMD_DO_CHANGE_SPEED command for changing the speed for a mission.

Yeah, that was known but there was some problem which I seem to remember related to inconsistent use of the values in that message. I'll have to look and see if I can remember. I specifically didn't support it because of some problem I ran into, not because I didn't think it existed.

**Comment by DonLakeFlyer** [comment]
The problem related to DO_CHANGE_SPEED.param1 support for 0=airspeed and 1=groundspeed. Ages ago when I originally implement I vaguely remember ArduPilot not supporting param1 and forcing to one or the other (don't remember which). QGC requires param1 support for it to work. Does ArduPilot support this now?

**Comment by dakejahl** [comment]
>Does ArduPilot support this now?

Yes it supports all 4 options.

**Speed type (0=Airspeed, 1=Ground Speed, 2=Climb Speed, 3=Descent Speed)**

**Comment by holden-zenith** [comment]
It forces to [groundspeed](https://github.com/ArduPilot/ardupilot/blob/b2f00d469e0549742a20030f97b85bd9af03c2cd/ArduCopter/mode_auto.cpp#L1522). Also in [doc](https://ardupilot.org/copter/docs/common-mavlink-mission-command-messages-mav_cmd.html#mav-cmd-do-change-speed)

**Comment by DonLakeFlyer** [comment]
Ok, so according to @holden-zenith (and the code) this won't work since only groundspeed is supported. I'm closing for now until there is other proof that it does work.

**Comment by julled** [comment]
Wouldnt groundspeed also be useful for various of applications already? 
At least for me it would help alot and could be pointed out to the user via GUI or documentation.

**Comment by DonLakeFlyer** [comment]
> Wouldnt groundspeed also be useful for various of applications already?

It would. But the way QGC works is when you change flight speed it changes airspeed for fixed wings and groundspeed for multi-rotors. There is no groundspeed only thing in current QGC code. Also groundspeed for fixed wing is dangerous I assume.

**Pull request closed without merging**
