### PR TITLE
Add support for v4 boards

### PR DESCRIPTION
**Pull request by LorenzMeier**
@davids5 @kd0aij This adds support to flash v4 boards through QGC.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Can you wait on this until I get auto connect through? This is all different there.

**Comment by LorenzMeier** [comment]
Rebased on master.

**Comment by DonLakeFlyer** [comment]
Are only the bootloader ids different? The serial port ids are the same?

**Comment by LorenzMeier** [comment]
Hm, in the current version yes. But we probably should fix it up in the string as well.

**Comment by DonLakeFlyer** [comment]
Can you make sure QGCSerialPortIds.h/cc is correct as well for the new boards.

**Comment by LorenzMeier** [comment]
Merging as change was trivial and previous runs finished. Works fine with v4 boards.

**Pull request merged**
