### PR TITLE
Handling proxies when fetching tiles.

### PR DESCRIPTION
**Pull request by dogmaphobic**
In response to #4320. I added proxy handling elsewhere but I missed one spot. Note that I can't test this as I don't have any proxy to test with.

### CODE REVIEW

**Comment by fiji3119** [comment]
@dogmaphobic  I tried your fix but did not work. I am behind proxy but can access internet via browser, git ,etc. I get "tile request error "Problem with tile image". My OS is ubuntu 16.04.

**Comment by DonLakeFlyer** [comment]
> I get "tile request error "Problem with tile image"

I can't find that text anywhere in the source. Is that exactly what comes out on the console?

**Comment by DonLakeFlyer** [comment]
Can you flash firmware to your board? That also does a download using proxy code. Can you see if that works?

**Comment by fiji3119** [comment]
The message "tile request ..." is produced by Qt Location lib. I can  flash released firmware with no problem. I also installed QGC in Windows to test  - works fine even though both computers are on same network. Confused...

**Comment by NaterGator** [comment]
@fiji3119 Can you clear your tile cache? That error is only present in the QGeoFileTileCache class.

**Comment by fiji3119** [comment]
I cleared .cache/QGCMapCache300 but issue still exists.

**Comment by DonLakeFlyer** [comment]
So you're saying on a Windows build tiles load. But on a Linux build they don't. And these are both the same version of QGC?

**Comment by NaterGator** [comment]
Can you check these locations: https://code.qt.io/cgit/qt/qtlocation.git/tree/src/location/maps/qabstractgeotilecache.cpp?h=v5.6.2#n115

**Comment by fiji3119** [comment]
@DonLakeFlyer Yes. On linux, it may have to do with proxy or certificates. My co-worker claims it works when no proxy is used on network (example from home). I am building QGC v3.1.0 with Qt5.6.1.

**Pull request merged**
