### PR TITLE
 -DoAdd Fall rate percent in Landing Pattern editor [DO NOT MERGE till 3.3]

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by patrickelectric** [comment]
image

image

**Comment by DonLakeFlyer** [comment]
@patrickelectric Can you make the fall rate just a non-modifiable value which is calculated? It's way too late in the game to be changing the internals for Landing pattern calculation now. We can do that once 3.2 goes out the door. But right now things are locked down too tight to make this sort of change.

Other option is to just hold on to this until 3.2 is done and then put it through.

**Comment by DonLakeFlyer** [comment]
The more I think about it the more I think we just hold this till 3.2 goes out the door.

**Comment by patrickelectric** [comment]
No problem

**Comment by DonLakeFlyer** [comment]
Tested and works like a charm. Thanks @patrickelectric

**Comment by DonLakeFlyer** [comment]
I screwed this up and closed without merging!

**Comment by Antiheavy** [comment]
Is "Fall rate" the best term to use here?  "Glide ratio", "Landing slope", "Descent rate", or other variations might be more commonly used aircraft terminology.

**Comment by DonLakeFlyer** [comment]
Descent rate seems good?

**Comment by Kjkinney** [comment]
I think descent rate is the incorrect thing to use when planning a fixed wings landing path.

- Descent rate suggests that the aircraft is descending at a constant rate from the last waypoint to the land waypoint. This is false as both PX4 and Arduplane will change the descent rate to hit a glideslope.
- Using a percentage to describe a descent rate doesn't make sense.
- Descent rate is already used in unit/s to show how quickly the aircraft is descending at any given time. It is also used universally in the aviation community in unit/s to describe how quickly an aircraft will be ascending or descending



I suggest that this is switched to a glideslope in degrees.

- Glideslope/Glidepath is the universal aviation term when describing an airplane's path to a runway.
- Glideslope is also used in PX4 parameters to set the fixed wings path on landing, meaning that it will reject a mission if the glideslope is set too steep in px4. Arduplane uses glideslopes as well, however, I do not believe they are parameter defined. This would allow them to more accurately set a glideslope for landing rather than having to guess/do extra math.
- Glideslope would be defined in degrees to match aviation terms, as well as to match PX4 and Arduplane parameters and documentation.

Examples:
mls-vertical-coverage

main-qimg-5a23f17811f19b673d8204fab7184dea

glidang

**Comment by DonLakeFlyer** [comment]
@Kjkinney Could you move this to a new Issue and we can discuss there.

**Pull request merged**
