### PR TITLE
Move to pragma once

### PR DESCRIPTION
**Pull request by patrickelectric**
Move from ifdef to pragma once

### CODE REVIEW

**Comment by dogmaphobic** [comment]
As you are already changing a pile of files, you might as well do a `s/(c) 2009-2016/(c) 2009-2018/g;` (no escapes but you get the idea) through all .cc/.cpp/.h/.qml. I keep meaning to do it and never get around to it.

**Comment by patrickelectric** [comment]
@dogmaphobic 	I did the changes only in the files in this PR, will try to do the same across the next PRs.

**Comment by patrickelectric** [comment]
It appears that the jenkins machine is full
`No space left on device`

**Comment by DonLakeFlyer** [comment]
@dagar Jenkins failure

**Pull request merged**
