### PR TITLE
Flight Modes

### PR DESCRIPTION
**Pull request by dogmaphobic**
* Add access to all (unfiltered) flight modes.
* Have joystick use the unfiltered list of flight modes for button assignment.

Screen Shot 2019-09-03 at 11 28 21 AM

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
This is going to break existing custom implemenations which override FirmwarePlugin::flightModes to provide their own filtered list. It would be better to change the signature of the existing FirmwarePlugin::flightModes to add a flag to ignore vehicle type. This way custom builds will fail and need fix up. Otherwise they'll just change functionality silently.

**Comment by dogmaphobic** [comment]
I've added a new function to get all modes. The original one is still there unchanged. This was a direct result of the plugin implementing `FirmwarePlugin::flightModes()` but wanting all modes available for button assignment (not just the filtered list).

https://github.com/mavlink/qgroundcontrol/blob/qgc-centos/src/FirmwarePlugin/FirmwarePlugin.h#L82-L93

**Comment by DonLakeFlyer** [comment]
> but wanting all modes available for button assignment (not just the filtered list).

That will break custom builds where commercial vehicle operators don't want their users to see full flight mode list even in joystick setup. It was specifically changed a while back to do that on customer request.

**Comment by dogmaphobic** [comment]
Got it. I assumed the filtered list was for the Flight Mode indicator/selector UI (toolbar) only. Now we need to sort out how to enable all modes for joystick button assignment. That is, for when you want the UI selectable modes filtered but all modes available for joystick buttons.

**Comment by dogmaphobic** [comment]
For example, it doesn't make a whole lot of sense to have "Land" or "Take Off" available as a flight _mode_ within the selector (hence the filtered list) but you might want to assign a button to it.

**Comment by DonLakeFlyer** [comment]
> I assumed the filtered list was for the Flight Mode indicator/selector UI (toolbar) only.

It was originally was. Then I got complaints about it not affecting joystick.

> That is, for when you want the UI selectable modes filtered but all modes available for joystick buttons.

That would seem like a custom build tweak by overriding flightModes. To me the default behavior of filter everywhere is better for upstream.

**Comment by dogmaphobic** [comment]
>That would seem like a custom build tweak by overriding flightModes. To me the default behavior of filter everywhere is better for upstream.

The plugin would need to override joystick configuration not flight modes. You can't tell what you are filtering from `FirmwarePlugin::flightModes()`

**Comment by DonLakeFlyer** [comment]
> For example, it doesn't make a whole lot of sense to have "Land" or "Take Off" available as a flight _mode_ within the selector (hence the filtered list) but you might want to assign a button to it.

Hmm, a bit hard to say from an upstream standpoint as to how people are doing things. Not sure if things covered by guided actions should be removed from flight mode dropdown. Maybe...

**Comment by DonLakeFlyer** [comment]
> The plugin would need to override joystick configuration not flight modes. You can't tell what you are filtering from `FirmwarePlugin::flightModes()`

Hmm, yeah. I think flightModes usage is kind of getting hacked around for too many things. Maybe it's time to split into toolbarFlightModes and joystickFlightModes. Would need to review usage of flightModes to see if it is used anywhere else.

**Comment by dogmaphobic** [comment]
Instead of `FirmwarePlugin::allFlightModes()` rename it to `FirmwarePlugin::joystickFlightModes()`. Then it is clear what the list is for and the plugin can override it or just map it to its normal, filtered list.

**Comment by dogmaphobic** [comment]
:) We both came up with the same idea at the same time

**Comment by DonLakeFlyer** [comment]
I think trying Land/Takeoff out of the toolbar is an interesting thing as well. Less is more.

**Comment by dogmaphobic** [comment]
Are you saying we should filter out Land/Takeoff by default from the toolbar selector? I agree...

**Comment by DonLakeFlyer** [comment]
> Are you saying we should filter out Land/Takeoff by default from the toolbar selector?

yup

**Pull request merged**
