### PR TITLE
update Docker install Instructions

### PR DESCRIPTION
**Pull request by Claudio-Chies**
update Docker install Instructions

Description
-----------
The deploy/docker/Dockerfile-build-linux seems to have changed to deploy/docker/Dockerfile-build-ubuntu, which was not reflected in the install instructions

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by HTRamsey** [comment]
Would you want to update the rest to reflect run-docker.sh too

**Comment by Claudio-Chies** [comment]
ah, didnt know this script existed.
then the whole build process simplyfies to running `./deploy/docker/run-docker.sh` from the root folder?
i'll wait for https://github.com/mavlink/qgroundcontrol/issues/11644 to be solved, as i cant test it while having this issue.

**Comment by HTRamsey** [comment]
What's the issue? It seems to build fine for me

**Comment by Claudio-Chies** [comment]
> What's the issue? It seems to build fine for me, granted it is missing some gstreamer stuff

i get following errors:
```-- Running output plugin: appimage -- 
[appimage/stdout] Found appimagetool: /tmp/.mount_linuxdkLuzAh/usr/bin/appimagetool
[appimage/stdout] 
[appimage/stderr] Running command: /tmp/.mount_linuxdkLuzAh/usr/bin/appimagetool "/project/build/AppDir"
[appimage/stderr] 
[appimage/stderr] appimagetool, continuous build (commit 5735cc5), build <local dev build> built on 2023-03-08 22:52:04 UTC
[appimage/stdout] WARNING: appstreamcli command is missing, please install it if you want to use AppStream metadata
[appimage/stderr] Desktop file not found, aborting
[appimage/stdout] WARNING: gpg2 or gpg command is missing, please install it if you want to create digital signatures
ERROR: Failed to run plugin: appimage (exit code: 1) 
```

**Comment by Claudio-Chies** [comment]
@HTRamsey Updated the Docs with the script. building works for me with the newest main branch

**Comment by HTRamsey** [comment]
Sorry forgot about this

**Pull request merged**
