### PR TITLE
add qt5-qtlocation-devel for fedora

### PR DESCRIPTION
**Pull request by marbug**
+ fix "Unknown module(s) in QT: location-private positioning-private"

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by nanthony21** [comment]
I'm getting this same issue on Ubuntu with QT 5.5.1. The full output is ":-1: error: Unknown module(s) in QT: location positioning qml quick quickwidgets svg serialport location-private positioning-private"

Did I forget to install something?

**Comment by DonLakeFlyer** [comment]
You must follow the instructions in the readme to install Qt using the online installer.

**Comment by nanthony21** [comment]
Hmm, I'm fairly certain that I did. I think I know what happened. After installing from the online installer I got this error: http://stackoverflow.com/questions/26499404/qtcreator-no-valid-kits-found

I fixed it using the first listed solution (sudo apt-get install qt5-default) when I probably should have done the second listed solution (QT Maintenance Tool).

Anyway, it's working now.

**Comment by DonLakeFlyer** [comment]
Do you install Qt per the README instructions or are you trying to use the Qt that comes with Ubuntu?

**Comment by nathantsoi** [comment]
I did attempt to follow the readme, however I could not find the online
installer, if that matters?

I noted what I had to do differently here:
https://github.com/mavlink/qgroundcontrol/compare/master...nathantsoi:ubuntu-build-instruction-updates

**Comment by DonLakeFlyer** [comment]
You have to work your way through the screens:
* Go Open Source
* Then Download

Buy using the online installer you get the right stuff.

**Pull request merged**
