### PR TITLE
Introduce obstacle distance overlay

### PR DESCRIPTION
**Pull request by valbok**
It receives mavlink message obstacle_distance and shows distances in a circular array fashion.
    
Added a setting in Safety/Object Detection section to show the overlay.
Can be used independently to collision prevention features.
    
There are two overlays in different styles: Video and Map overlay
The styles could be changed in particular qml file.
    
https://github.com/mavlink/qgroundcontrol/issues/7670

### CODE REVIEW

**Comment by valbok** [comment]
obstacle_distance_overlay

**Comment by DonLakeFlyer** [comment]
@valbok Can you explain what the differing shape of the overlay means? Some of them are pointy and some are not. What does the difference mean?

Pointy:
Screen Shot 2021-06-25 at 9 34 04 AM

Not pointy:
Screen Shot 2021-06-25 at 9 34 09 AM

**Comment by valbok** [comment]
> @valbok Can you explain what the differing shape of the overlay means? Some of them are pointy and some are not. What does the difference mean?
> 
> Pointy:
> Screen Shot 2021-06-25 at 9 34 04 AM
> 
> Not pointy:
> Screen Shot 2021-06-25 at 9 34 09 AM

it is an approximation, using bezier curves, 4 dots, to have smoothed corners

**Comment by valbok** [comment]
Screenshot_2021-06-28_16-24-05
Screenshot_2021-06-28_16-18-26

**Comment by valbok** [comment]
Screenshot_2021-06-28_16-41-42
Screenshot_2021-06-28_16-41-54

**Comment by DonLakeFlyer** [comment]
@valbok Is the video overlay somehow different? If it's simple to explain differences can you do that? Otherwise include a screenshot of that as well?

**Comment by valbok** [comment]
> @valbok Is the video overlay somehow different? If it's simple to explain differences can you do that? Otherwise include a screenshot of that as well?
@DonLakeFlyer decided to have 2 different styles for video and map overlays, but they are switched off/on by the same setting under Safety section.

The video overlay is more like proposed on mockup in the issue. Can be see on screenshots.

Also styles can be easily changed on particular qml files

**Comment by DonLakeFlyer** [comment]
> Can be see on screenshots.

Sorry I missed the fact that was a real video example.

**Pull request merged**
