### PR TITLE
Precompile a handful of Qt headers to speed up compilation time

### PR DESCRIPTION
**Pull request by NaterGator**
In my experience this is going to dramatically improve compile times. I tested on windows and saw ~6x speedup using MSVC 2013. Curious to see if the CI builds all complete and what their timing looks like.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Ooh, hope it works!

**Comment by DonLakeFlyer** [comment]
4-5 minutes faster on Windows. But something strange going on with OS X.

**Comment by NaterGator** [comment]
A bit disappointing but we can certainly work on improving the included headers for better performance and fixing other OSes. I don't have a Mac to compile on but I'll work on fixing that build.

**Comment by DonLakeFlyer** [comment]
It's a good win on Windows. I'd consider just turning it on for Windows builds.

**Comment by NaterGator** [comment]
@DonLakeFlyer for some reason AppVeyor was glitching out today and didn't pick up the new commit to trigger a build, but things should be good to merge if you are okay with the default behavior being precompiled headers only on windows.

**Pull request merged**
