### PR TITLE
Enhance MockLink for Multiple ADS-B Vehicle Simulation

### PR DESCRIPTION
**Pull request by Paschalis**
Description
-----------
This PR addresses the limitations of the current MockLink implementation by enabling the simulation of five ADS-B vehicles, providing a more realistic and consistent flight path on the QGroundControl map. The following changes were made:
  - Updated `MockLink.cc` and `MockLink.h` to allow the addition of five vehicles that simulate realistic movements and smooth transitions.
  - Ensured that the heading of each ADS-B vehicle aligns with its movement direction, improving the overall accuracy of the simulation.
  - The existing `ADSB_Simulator.py` script remains in the project to facilitate testing of SDR hardware faults and antenna issues. This redundancy is crucial for users who require a fallback method for ADS-B simulation via TCP link, mimicking a real ADS-B server setup.

https://github.com/user-attachments/assets/567f1c41-ef7e-4d06-a51a-6426f5183813

Checklist:
----------

- [x] [Review Contribution Guidelines](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CONTRIBUTING.md).
- [x] [Review Code of Conduct](https://github.com/mavlink/qgroundcontrol/blob/master/.github/CODE_OF_CONDUCT.md).
- [x] I have tested my changes.

Related Issue
-----------
#12006

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by HTRamsey** [comment]
As it seems like you are actively using ADSB, do you think it would be valuable to parse more ADSB messages for info like velocity, distance, etc?

**Comment by Paschalis** [comment]
> As it seems like you are actively using ADSB, do you think it would be valuable to parse more ADSB messages for the remaining data not currently used in mavlink_adsb_vehicle_t? Like hor_velocity, ver_velocity, tslc, etc

I agree that parsing additional ADS-B messages would be beneficial. In addition to the mentioned fields, we would like to add:

- **Groundspeed** (`hor_velocity`) in knots.
- **Climbing/Descending Indicator**: A small icon (such as `^` for climbing and `v` for descending) to visually indicate the vertical velocity of the aircraft.
- **Emergency Squawk Status**: Indicate emergency squawks (7500, 7600, 7700) with visual markers, such as changing the vehicle icon to a red version, to allow easy identification.

Suggest displaying these details in a **hover field** when the mouse is over each vehicle, allowing users to access relevant information only as needed.

Additionally, should adding appropriate vehicle images based on aircraft type to help distinguish between **planes** and **helicopters**, as discussed on [Aviation Stack Exchange](https://aviation.stackexchange.com/questions/98331/distinguish-between-planes-and-helicopters-with-ads-b-messages).

**Comment by HTRamsey** [comment]
Could you make a feature request for that and any other thoughts you have on it? Adding the messages is very quick and easy, visual stuff might take a slight bit more

**Comment by DonLakeFlyer** [comment]
> Suggest displaying these details in a **hover field** when the mouse is over each vehicle, allowing users to access relevant information only as needed.

I would make this show up with a click on the vehicle. Hover stuff doesn't work on mobile.

**Comment by DonLakeFlyer** [comment]
Nice stuff. Thanks for the pull

**Pull request merged**
