### PR TITLE
DO NOT MERGE: Fix coordinate scaling bug regarding MAVLink specs

### PR DESCRIPTION
**Pull request by LorenzMeier**
@DonLakeFlyer If merge now this will lead to fly-aways to Africa, so this can only go in once we have a minimum Firmware version check in and enforced.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@LorenzMeier You need to tell me what the min version is

**Comment by LorenzMeier** [comment]
Thanks for the reminder. I get the wrong version displayed right now in QGC and need to work out why the decoding in QGC is different from mine. And I probably also need to put that particular version on stable then.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Firmware version is not showing in SITL, but is implemented in PX4 SITL. Any reason QGC is not pulling the version in that case?

screen shot 2016-07-01 at 09 53 58

**Comment by DonLakeFlyer** [comment]
Check that it’s getting the VERSION mavlink message in mavlink inspector. If so, something wrong with QGC. If not, something wrong with SITL.

**Comment by LorenzMeier** [comment]
I never receive MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES on the autopilot side. This is because PX4 does not allow commands to be handled until it has finished the network discovery, which requires a heartbeat from the GCS. But QGC is sending the command right after it got the first heartbeat.

The proper approach would be to retry on the QGC side. The slightly less involved version of this would be to send a GCS heartbeat immediately on creating a new vehicle instance, then backing off 50 ms and only then starting to send commands.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Minimum version required should be 1.4.1rc1 (its ok if you just check for 1.4.1, any build using that number has the fix)
https://github.com/PX4/Firmware/releases/tag/v1.4.1rc1

It probably makes sense to put this onto this branch and merge it, just implies that anyone using the QGC 3.0.0 RC needs beta or master of PX4, which seems fair.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier I can't do the version number check without the firmware version number mavlink change.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Can you please re-test with master? It all works for me here.

**Comment by DonLakeFlyer** [comment]
Yup, my screwup.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier How come when I run SITL master against QGC **without** this change, goto goes to the right spot. Shouldn't it go to the wrong place since QGC isn't sending the right format?

**Comment by LorenzMeier** [comment]
Px4 supports old and new spec, since I could tell them apart.

**Comment by DonLakeFlyer** [comment]
Ok. Got it. I'm going to take control of this pull and make a new one to merge into both Stable 3.0 and master.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Wait: If firmware can detect old/new why the version check then?

**Comment by LorenzMeier** [comment]
It is safe to use new firmware with old and new QGC. It is *NOT* safe to use old firmware which does not contain the check. So when QGC ships with this fix, it needs to make sure it talks to *NEW* Firmware. Makes sense?

**Comment by DonLakeFlyer** [comment]
Duh!

**Pull request closed without merging**
