### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by PX4BuildBot**

### CODE REVIEW

**Comment by HTRamsey** [comment]
@DonLakeFlyer So what happens when these are committed out of order? Does the newer one include the changes from this too?

**Comment by DonLakeFlyer** [comment]
> So what happens when these are committed out of order? Does the newer one include the changes from this too?

Only if this pull includes the same languages from a previous pull. I believe in general they should be merged in from the oldest to newest if there are multiple.

**Comment by HTRamsey** [comment]
I don't know how to merge this cleanly now. I think theres a way to resync from crowdin?

**Comment by DonLakeFlyer** [comment]
I'll figure out how to get a new full dump from crowdin

**Pull request closed without merging**
