### PR TITLE
move continuous s3 builds

### PR DESCRIPTION
**Pull request by dagar**
I'm moving the continuous builds from the top level of the qgc bucket to builds/$branch to enable auto expire.

### CODE REVIEW

**Comment by dagar** [comment]
@DonLakeFlyer this changes the URL to the continuous/daily builds. Note the **builds** directory now included before the branch name. 
OLD: https://s3-us-west-2.amazonaws.com/qgroundcontrol/master/qgroundcontrol-installer.exe
NEW: https://s3-us-west-2.amazonaws.com/qgroundcontrol/builds/master/qgroundcontrol-installer.exe

All branches pushed to the main repo are uploaded to s3 and will now auto expire about 90 days.

Can you update the daily build links on http://qgroundcontrol.org/downloads? Tagged releases are unchanged.

**Comment by DonLakeFlyer** [comment]
Can you update to Wiki?

**Comment by dagar** [comment]
Sorry, I still don't have access and the registration is busted. There's no CAPTCHA and I've tried all the browsers.

screenshot from 2016-06-12 13 52 43

**Comment by NaterGator** [comment]
@dagar should this apply to OS X? I updated all three but I get 404 for OS X build.

**Comment by dagar** [comment]
screenshot from 2016-06-12 15 50 24

It looks like something else broke the OSX deploy.

**Comment by NaterGator** [comment]
Hmm. I put the OS X daily link back until that gets sorted.

**Comment by dagar** [comment]
Issue created #3543

**Pull request merged**
