### PR TITLE
Horizon level cal

### PR DESCRIPTION
**Pull request by LorenzMeier**
@DonLakeFlyer This implements the horizon levelling and there is a matching Firmware PR coming.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Tested, works with current Firmware master.

**Comment by DonLakeFlyer** [comment]
Could this just be the first step of a standard accel cal? When you do a right-side up accel cal you are 99% of the way to a level cal. Why not combine the two to simplify?

**Comment by LorenzMeier** [comment]
Accel cal is the input to level. It does scale and offsets, level does rotation

**Comment by LorenzMeier** [comment]
This means the level step will often have the autopilot at an angle, which is the one we're compensating in the final step

**Comment by DonLakeFlyer** [comment]
Add it at the end then? Just trying to remove confusion over additional steps/buttons.

**Comment by DonLakeFlyer** [comment]
Also from looking at this code it appears that leveling is non-optional since it is using a red/green indicator and testing a param for being modified. Is that correct? If so, I'll need to add that param to the sensor component as a trigger for the component setup being complete. Otherwise sensor component will show overall green when level has not been completed.

**Pull request merged**
