### PR TITLE
[WIP] videonode: Do not finish if material is different

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix bluerobotics/qgroundcontrol#164

Signed-off-by: Patrick J.P <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by patrickelectric** [comment]
This was crashing video popup in windows :)
I hope that solves the problem with Linux also, @jaxxzer.

**Comment by dogmaphobic** [comment]
> Is the original source of this code in another repository?

```
/**
 * @file
 *   @brief Extracted from QtGstreamer to avoid overly complex dependency
 *   @author Gus Grubba <mavlink@grubba.com>
 */
```

**Comment by patrickelectric** [comment]
@dogmaphobic this is in WIP, can you revert the merge please ?

**Comment by dogmaphobic** [comment]
Well, returning seemed better than asserting. Sure!

**Comment by dogmaphobic** [comment]
Reverted

**Comment by patrickelectric** [comment]
ty !

**Pull request merged**
