### PR TITLE
Fixed 'Sensors Setup' page not showing GUI

### PR DESCRIPTION
**Pull request by stepan14511**
Fixed Vehicle Setup -> Sensors page for PX4 not showing GUI, made to help user with calibration.

Description
-----------
Used to be:
image
Now it works correctly:
image

Test Steps
-----------
Go to Vehicle Setup -> Sensors. Start, for example, accelerometer calibration and you will see no changes in the right part of the screen. Now it works the same way, as it does in the stable verison (correctly).

Related Issue
-----------
There might be the same issue with others autopilots. I don't not have ability to check.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
I see what was changed but I don't understand why it was needed. The signals should have worked there way through the new mechanism:
* https://github.com/mavlink/qgroundcontrol/blob/master/src/MAVLink/StatusTextHandler.cc#L338
* https://github.com/mavlink/qgroundcontrol/blob/master/src/Vehicle/Vehicle.cc#L4004
* And then the changes to the text parsing seem like a no-op to me.

@stepan14511 Could you help with debugging this to determine why the current code doesn't work?

**Comment by stepan14511** [comment]
@DonLakeFlyer 

- > The signals should have worked there way through the new mechanism

In the mechanism all the signals work absolutely fine. `StatusTextHandler::textMessageReceived` signals are coming to the `Vehicle` object. But `SensorsComponentController` is not connecting to `StatusTextHandler::textMessageReceived`, but to `Vehicle::textMessageReceived`, which is never emited in a `Vehicle` object.

The other solution could be to subscribe straightly to the `StatusTextHandler::textMessageReceived`, but `StatusTextHandler *m_statusTextHandler` is private in the Vehicle class. And it's getter function is removed for some reason:
https://github.com/mavlink/qgroundcontrol/blob/2d4bb34805a338cd1259664018d281850136be99/src/Vehicle/Vehicle.h#L1339

- > And then the changes to the text parsing seem like a no-op to me.

https://github.com/mavlink/qgroundcontrol/blob/2d4bb34805a338cd1259664018d281850136be99/src/AutoPilotPlugins/PX4/SensorsComponentController.cc#L233
The expression in the if statement is always false, since the text variable is following (for example):
`[cal] progress &lt;20&gt;`

Because of this the progress bar is not working.

**Comment by HTRamsey** [comment]
Good catch, I probably missed the PX4 issue when making StatusTextHandler because previously I only tested on ArduPilot but at least it helped catch the SensorsComponentController issue. Connecting to the Vehicle signal is the correct way as I had intended for it to be used.

**Comment by DonLakeFlyer** [comment]
Ok, so isn't one of the fixes to add:
```
    (void) connect(m_statusTextHandler, &StatusTextHandler::textMessageReceived, this, &Vehicle::textMessageReceived);
```
This will get the signal up through Vehicle.

As far as the "<" versus "&lt" stuff. It looks like this changed on the PX4 firmware side of things at some point. Since in the past the "<" certainly worked. My concern is with back compat with older version of firmware. @HTRamsey Is there some Qt magic to get these strings to replace the "&" stuff which real chars? If so, then the cal stuff could jam the strings through that first and then use the non "&" chars for comparison. This would then in turn work on all firmware versions.

**Comment by stepan14511** [comment]
@DonLakeFlyer 
This idea sound better. But it requires a bit more changes. It can be seen here: https://github.com/stepan14511/qgroundcontrol/commit/affe648c3962abe72983bccd1e71eced0b0bd515
If we will agree on this approach, I will merge it to my master to appear in this pull request.

> Is there some Qt magic to get these strings to replace the "&" stuff which real chars?

I couldn't find anything apart from the straightforward replace function.

**Comment by DonLakeFlyer** [comment]
> If we will agree on this approach

I believe this is the way to go.

For converting the &gt things:
https://stackoverflow.com/questions/7696159/how-can-i-convert-entity-characterescape-character-to-html-in-qt

**Comment by stepan14511** [comment]
@HTRamsey
Is there any particular reason why in the line below you are using `toHtmlEscaped()`?
https://github.com/mavlink/qgroundcontrol/blob/3bceda063c591d12663dac7b7a49512eb0614356/src/MAVLink/StatusTextHandler.cc#L338

Removing it solves the issue.

**Comment by HTRamsey** [comment]
Not that I recall, I believe that's what was there already before I moved it into StatusTextHandler

**Comment by stepan14511** [comment]
This is exactly the reason, why old if is not working:
image

Then what would be better: to convert it back in the autopilots or just remove it?

**Comment by DonLakeFlyer** [comment]
Hmm, interesting. I believe somewhere along the the way PX4 starting sending status text messages which were HTML. So the message display starting using a rich text field to display status text.

Could someone find the "blame" on the original toHtmlEscaped? I only vaguely remember those changes. Need to understand why that was put in there. I think maybe @bkueng was involved?

**Comment by DonLakeFlyer** [comment]
I just went backwards through blame. Looks like it was @bkueng. Hopefully he can help explain why this is necessary.

**Comment by DonLakeFlyer** [comment]
So I looked through the code and I believe it's correct that the toHtmlEscaped (somewhere) because both the critical vehicle message popup and and vehicle message dropdown use a richtext control If you don't escape then some things could be assumed to be HTML when they are not. That said I think the place where this escaping should happen should not be at a global level. It should only be when the status text is about to be displayed in one of those control. For generic signaling out from Vehicle of status text. I think it should not be escaped at that point.

I'm pawing through code right now to figure out exactly where that should be.

**Comment by HTRamsey** [comment]
@stepan14511 Is this still necessary? I don't know if this was replaced by the other PR or if this is different

**Comment by DonLakeFlyer** [comment]
Sorry I should have closed this. It was replaced by my pull

**Pull request closed without merging**
