### PR TITLE
Custom gimbal control

### PR DESCRIPTION
**Pull request by dogmaphobic**
Showing how to implement a custom gimbal control (re-using the virtual joystick control)
Also adding a setting so the user can enable/disable the control.

Screen Shot 2019-07-27 at 5 16 21 PM

### CODE REVIEW

**Comment by hamishwillee** [comment]
@dogmaphobic Pretty cool. 
1. How do I enable this if I want it on my customer version
2. How do  you expect people discover this example? (and similarly the navigation item you created)?

Perhaps a page in the dev guide? https://dev.qgroundcontrol.com/en/

**Comment by dogmaphobic** [comment]
> 1. How do I enable this if I want it on my customer version

Just rename "custom-example" to "custom" before loading the project in Qt Creator. If you had a build already, you will need to delete the build directory (run qmake again). If you do this all the time, it's simpler to just create a symlink (`ln -s custom-example custom`).



> 2\. How do  you expect people discover this example? (and similarly the navigation item you created)?

Good question. Not sure what the best way to document it.

Yasen did a cool PR today updating the entire color palette for the custom build to show how it's done: https://github.com/mavlink/qgroundcontrol/pull/7633

**Comment by hamishwillee** [comment]
> Not sure what the best way to document it.

I am. See https://github.com/mavlink/qgc-dev-guide/issues/70

In theory could "seed" this in a week or so. But I don't know enough about what makes a custom control and how it gets hooked into the system - ie what does someone else need to know to extend this vs fully replace it vs just learn how to create an arbitrary control.

Further, this is a modified joystick control. Does it play nice if someone adds a joystick?

**Comment by zeev-mindali** [comment]
> Showing how to implement a custom gimbal control (re-using the virtual joystick control) Also adding a setting so the user can enable/disable the control.
> 
> Screen Shot 2019-07-27 at 5 16 21 PM

Dear Friend,

how i can get this plugin???

**Pull request merged**
