### PR TITLE
Fix setting the baud rate.

### LINKED ISSUE #1212: QGC cannot connect at 115200 baud
Been wasting the last week trying to connect to my board, but it turns out QGC won't connect at any baud rate besides the default 57600. This also applies to the databits and stopbits settings.

### PR DESCRIPTION
**Pull request by Susurrus**
There's also a partial fix for the databits and stopbits. I'm unsure how to deal with the logic
around the 'is_cdc' variable, as I can't really follow what it's for.

Closes #1212

### CODE REVIEW

**Comment by Susurrus** [comment]
@LorenzMeier @DonLakeFlyer This breaks things pretty hard for non-57600 modem use, which I think is a lot of systems besides the PX4. Can you guys help me out here?

**Comment by LorenzMeier** [comment]
Sure! Good to merge? @DonLakeFlyer do you just merge if you're happy?

**Comment by DonLakeFlyer** [comment]
Haven't had time to look at it yet. Give me a couple minutes.

**Comment by Susurrus** [comment]
Well, the problem is that this doesn't work for the stop bits and data bits from my testing and I don't know why. It has something to do with the `is_cdc` member variable, but without documentation I haven't really figured out how that functionality is supposed to work. Looks like you put it in @LorenzMeier so I was hoping you could help out with fixing that code path.

**Comment by LorenzMeier** [comment]
I don't think I put that in, and I would guess it can be removed. It probably tries to imply that setting the baud rate is pointless for true CDC devices, and/or it might have been a workaround for something else. If you remove it, I'd like to cross-check with Pixhawk, but otherwise I would assume it can go.

**Comment by DonLakeFlyer** [comment]
Right. It's checking for px4 in the device description in which case it assumes it's a cdc device and in turn doesn't really set baud rate, stop bits etc. It just stores the values and makes believe they were set. 

@Susurrus This cdc thing shouldn't be affecting your code path since your device should not have px4 in the description. Are you hitting this path? Also what was the original bug? I don't see from this pull what was previously wrong?

**Comment by Susurrus** [comment]
What is a CDC device first of all?

@DonLakeFlyer The problem was that the UI for the baud rate didn't actually trigger changing the settings in the SerialLink object. This is because the signals/slots are incorrect. You can't correct a SerialLinkInterface object to slots in a subclass, so they were failing at runtime and never being triggered. I fixed that by moving the slot to the same class as the UI and having that call into the proper SerialLinkInterface functions.

So this fixes the baud rate. But in the commit you'll see I tried to do the same fix for the data and stop bits, but it doesn't work. I stepped through the code until I ran into the SerialLink code that checks its `is_cdc` member and uses defaults if it detects it. I got lost about here so I decided to turn to you two for help.

**Comment by LorenzMeier** [comment]
http://en.wikipedia.org/wiki/USB_communications_device_class

Most likely the CDC check doesn't account for your corner case. We could try to disable the special case handling and see what happens in that case.

**Comment by Susurrus** [comment]
It sets it to false unless it's a PX4 device. So it's false for me. The thing is I don't see why the CDC code should even be kicking in, this is before I've even finished configuring the SerialLink! At this point there is no link, so it couldn't detect if it's a CDC device or not.

**Comment by LorenzMeier** [comment]
Is the CDC init value maybe just wrong and set to true?

**Comment by Susurrus** [comment]
I think it is true by default.

**Comment by DonLakeFlyer** [comment]
It's called in a number of places: constructor, setportname, .... If the port name is available it will do it's thing. If not it ends up a no-op.

It defaults to true but as soon as you name the port it will get reset to the right value.

**Comment by DonLakeFlyer** [comment]
The fact that it hits the cdc case for stop bits shouldn't matter should it? If you are not connected it just saves the values and uses it at hardware connect time. At hardware connect time cdc should be set correctly since port name is set correctly at that time and will make the right setDataBits calls. Did you find that setDataBits was not being set in the hardwareConnect call?

**Comment by Susurrus** [comment]
I watched the console debugging output which says what connections are used for the SerialLink object. When I hit connect it never changed the stop or data bits.

**Comment by DonLakeFlyer** [comment]
It won't specifically out the set data bits thing. If it is working correctly you should have gotten:
        qDebug() << "Configuring port";
At connect time.

**Comment by Susurrus** [comment]
It looks like removing the CDC logic as done in #1215 fixed the data/stop bits problem. So this PR appears to do its job so I'd like to merge it. And I'd like to propose pushing this PR and cleaning up the stop/databits in #1215.

**Comment by DonLakeFlyer** [comment]
Need to talk with Lorenz on removing the retry stuff.

**Comment by Susurrus** [comment]
Can we merge this in the meantime? This will at least fix the baudrate for now and is technically correct.

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Up to Gus since he has already root-tilled this code. I would probably just make sure he has your connect fixes in his pull.

**Comment by dogmaphobic** [comment]
> Up to Gus since he has already root-tilled this code. I would probably just make sure he has your connect fixes in his pull.

I'm fine given that it will be a couple of days before I can have something properly cleaned up and documented to push. I can manually deal with the conflicts after this goes through.

**Comment by Susurrus** [comment]
Since this passes and it fixes this issue, I'd like to merge it then. @LorenzMeier @DonLakeFlyer Just want one final confirmation as things are pretty crazy with the comms code right now.

**Comment by LorenzMeier** [comment]
I think we can merge it in. I will try a bit with it merged and see how it does.

**Comment by DonLakeFlyer** [comment]
Good to go. Likely blow up with a merge conflict with my other pull but I'll deal with that.

**Pull request merged**
