### PR TITLE
Fly: Hide waypoint indicators unless they are really needed

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Here is what we have now:
Screen Shot 2019-09-05 at 4 16 40 PM

That's a massive amount of crap in front of the users faces most of which has no value.

So instead we hide the waypoint indicators except for the one the vehicle is travelling towards:
Screen Shot 2019-09-05 at 4 14 09 PM
Screen Shot 2019-09-05 at 4 14 24 PM

The waypoints indicators show up if you Pause the vehicle. This allows you to then do a GoTo Waypoint by clicking on one:
Screen Shot 2019-09-05 at 4 14 40 PM

Next step: Direction Arrows like I have working in Plan view.

### CODE REVIEW

**Comment by tilaktilak** [comment]
Is it working when the flight plan is retrieved from the drone ?
Is the drone always on top of the WP layer ? 
As mentionned in https://github.com/mavlink/qgroundcontrol/issues/7775 what do we show in PlanView ?

**Comment by DonLakeFlyer** [comment]
> Is the drone always on top of the WP layer ?

I think there are still z-order problems there.

> Is it working when the flight plan is retrieved from the drone ?

Not sure what you mean. Is "what" working? These visuals work this way in Fly view no matter where the items came from.

> As mentionned in #7775 what do we show in PlanView ?

Plan view always shows waypoint indicators since you need to be able to select them to edit and/or drag them around.

**Comment by DonLakeFlyer** [comment]
The changes in this pull affect Fly view only.

**Comment by sanderux** [comment]
@DonLakeFlyer Not showing the sequence numbers is very much affecting our workflow when using external analyzers. We indicate problems based on these numbers.

Could i request to enable them with a setting?

**Comment by DonLakeFlyer** [comment]
Make sense, can you add a separate issue

**Pull request merged**
