### PR TITLE
ArduPilot: Don't starts streams from QGC side. Assume firmware side does the right thing

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Related to #7104

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@jaxxzer This assumes ArduSub doesn't need them either. Ok?

**Comment by edwinhayes** [comment]
Oh, is this why QGC daily build is not longer streaming for me?!  What is the reason for this?

**Comment by tridge** [comment]
@DonLakeFlyer this will break ArduPilot badly. We don't yet support message intervals, although the PR for that is likely to go in soon. We will need the stream rates set for quite a while though, for all the stable releases

**Comment by jaxxzer** [comment]
> this will break ArduPilot badly.

It looks like [Plane](https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/GCS_Mavlink.cpp#L520), Rover, Tracker stream by default. [Copter](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/GCS_Mavlink.cpp#L347) and Sub do not. They should though.

If the idea is that the user will have to select their own streamrates depending on their link, then they may still do that via the parameters menu. Not necessarily 'broken' as much as forcing this configuration step on the user instead of making assumptions for them about their application.

**Comment by DonLakeFlyer** [comment]
> It looks like [Plane](https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/GCS_Mavlink.cpp#L520), Rover, Tracker stream by default.

Not quite. For example Plane streams by default but not at a rate appropriate for a gcs link. So gcs still needs to setup for that as well.

**Comment by DonLakeFlyer** [comment]
> They should though.

I thought so to. And in all honesty I still don't quite get why that can't be done. You'll have to talk with @tridge about that part. For now I'm going to quickly add an option which allows the end user to turn off GCS requesting stream starts.

**Comment by jaxxzer** [comment]
> Not quite. For example Plane streams by default but not at a rate appropriate for a gcs link. So gcs still needs to setup for that as well.

True. This was a lapse on my part when I tested this. I was not working with fresh firmware defaults!

**Comment by DonLakeFlyer** [comment]
@noircogi FYI

**Comment by Noircogi** [comment]
Thanks.  I saw the discussion with Tridge.  As long as there is a way to either specify the values in QGC or opt out of the initialization, my problem will be addressed.

**Pull request merged**
