### PR TITLE
Show firmware version if the vehicle is connected

### PR DESCRIPTION
**Pull request by tcanabrava**
screenshot_20160427_163523
Display the firmware version if the vehicle is already connected
and the user clicks on Firmware Upgrade.

Signed-off-by: Tomaz Canabrava <tomaz.canabrava@intel.com>

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
The firmware version info on Vehicle should be exposed as properties (if not already there, can't remember) not invokable.

**Comment by dogmaphobic** [comment]
> The firmware version info on Vehicle should be exposed as properties (if not already there, can't remember) not invokable.

It seems it's a response to `MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES`

http://mavlink.org/messages/common#AUTOPILOT_VERSION

**Comment by tcanabrava** [comment]
The firmware version is a text message from mavlink, not transformed into a
fact. There was already a method to parse and store the text on the vehicle
class, I just added a invokable to be able to show it on qml.
Em 28 de abr de 2016 21:34, "Gus Grubba" <notifications@github.com>
escreveu:

**Comment by tcanabrava** [comment]
adding it as property...

**Comment by tcanabrava** [comment]
closing because of a new one opened;

**Pull request closed without merging**
