### PR TITLE
Add ardupilot parameter repository

### PR DESCRIPTION
**Pull request by patrickelectric**
Move ArduPilot parameters to a single place and avoid people to copy and track such files manually around projects.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Heading out of town now. I'll take a look when I get back on Thursday.

**Comment by booo** [comment]
Can we ask the ArduPilot project to provide these files?

Does it make sense to track these in a git? I guess a download of all files would be fine too.

**Comment by patrickelectric** [comment]
> Can we ask the ArduPilot project to provide these files?

ArduPilot provides https://firmware.ardupilot.org/Tools/MissionPlanner/MetaData/ that is not updates since 2020. It also only provides xml files (that is not a problem for QGC)

> Does it make sense to track these in a git? I guess a download of all files would be fine too.

Having the files under a git submodule makes it zero effort to integrate with existing projects. Besides that, having it as a git repository will allow people to collaborate, improve and create solutions around the possibility to have a dedicated project for it.

**Comment by DonLakeFlyer** [comment]
Seems fine. But I would either ask the ardupilot people if you can put this in their repo hierarchy or the other place would be under the mavlink hierarchy. It should be under someones personal location.

Also in the long run Ardupilot should support the COMPONENT_INFORMATION spec and then all this goes away and the parameter specs come from the vehicle, not compiled into QGC. This has been supported on the PX4 side for quite a while now.

**Comment by patrickelectric** [comment]
@DonLakeFlyer done, moved to ardupilot

**Comment by patrickelectric** [comment]
ping @DonLakeFlyer

**Comment by patrickelectric** [comment]
Ping @DonLakeFlyer @booo

**Comment by booo** [comment]
Does it make sense to add a few bits of documentation about the repo and its purpose somewhere?

**Comment by patrickelectric** [comment]
> Does it make sense to add a few bits of documentation about the repo and its purpose somewhere?

It's already on the README of the repository

**Comment by booo** [comment]
> > Does it make sense to add a few bits of documentation about the repo and its purpose somewhere?
> 
> It's already on the README of the repository

Well that documentation is quite minimal :) I thought more about documentation in the QGC repos/documentation somehwere. But I'm not sure where to put. Also not that important right now.

**Comment by patrickelectric** [comment]
ping @DonLakeFlyer @mrpollo

**Comment by booo** [comment]
@patrickelectric I think it is fine if you just merge this PR. I don't see any objects to the change and we can always revert if something is terribly wrong.

**Comment by patrickelectric** [comment]
I was just waiting for the someone approval, but 🤷

**Pull request merged**
