### PR TITLE
Only run unit tests on pull requests

### PR DESCRIPTION
**Pull request by DonLakeFlyer**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dagar Does this look right?

**Comment by dagar** [comment]
I think you want to use TRAVIS_PULL_REQUEST

    TRAVIS_PULL_REQUEST: The pull request number if the current job is a pull request, “false” if it’s not a pull request.

**Comment by dagar** [comment]
I could have sworn we already did something like this already.

**Comment by DonLakeFlyer** [comment]
Thanks

**Pull request merged**
