### PR TITLE
Cache new metadata if versions are equal

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Fixes for https://github.com/PX4/Firmware/issues/11072, #4485

### CODE REVIEW

**Comment by NuclearManD** [comment]
This does not appear to be in the latest release - when do you think this will reach a release of QGroundControl?

**Comment by DonLakeFlyer** [comment]
> latest release

This is in daily builds, it is not in stable. What is your definition of "latest release"?

**Comment by NuclearManD** [comment]
I suppose if it's available here:
https://docs.qgroundcontrol.com/en/getting_started/download_and_install.html

Yea, sorry, that was sort of vague.  I suppose I'm really asking "When will this PR make it into the version of QGC we download from your docs or website"

**Comment by DonLakeFlyer** [comment]
Both Stable and Daily builds are available for download from the website.

**Pull request merged**
