### PR TITLE
README: Add unit tests information

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
This should go into the dev guide instead of the README

**Comment by patrickelectric** [comment]
Can you point the correct file ? I searched for *.md but none appears the correct one.

**Comment by DonLakeFlyer** [comment]
There may not be one. You may need to add a new category. @hamishwillee can help

**Comment by patrickelectric** [comment]
Maybe a github wiki page in the repository may help to organize all .md files.

**Comment by DonLakeFlyer** [comment]
The dev guide is here: https://dev.qgroundcontrol.com/en/

**Comment by hamishwillee** [comment]
@patrickelectric I understand why you are confused - there isn't a link to the dev guide on the README.  

@DonLakeFlyer This is why it is important to have a single source for developer material - either the repo or the docs. I tend to prefer docs.

I'm going to merge this now as is, and then create another PR for all this material to move into the developer guide (you said previously you did not particularly care where this lived).

**Comment by hamishwillee** [comment]
FYI, the updated devguide work is happening here: https://github.com/mavlink/qgc-dev-guide/pull/36

**Comment by patrickelectric** [comment]
Thank you for the updates and the information !

**Comment by hamishwillee** [comment]
@patrickelectric You're welcome! The PR is now ready for review (has some questions for Don and/or you). The info you put in on unit tests appears in both the "Getting Started" and I also updated the unit tests doc.

**Pull request merged**
