### PR TITLE
Enabling the option of using Compass and Attitude Widgets or HUD.

### PR DESCRIPTION
**Pull request by dogmaphobic**
Following issue #1772, I've added a way for the user to define the use of *Widgets* or *HUD* for both the Compass and the Attitude Indicator. In the process, I've also cleaned up the naming of those controls to avoid confusion.

*Widget*: A floating UI element that can be moved around and resized
*HUD*: A fixed, overlay in the center of the screen

Here is a screen grab (sorry for the mess in my office) showing with the HUD enabled. Note that HUD and Widgets are exclusive. You can have one or the other but not both. You can however, disable both so nothing is shown.

screen shot 2015-08-14 at 9 16 37 am

The (right-click) context menu now shows the options to enable/disable these UI elements:

screen shot 2015-08-14 at 9 25 21 am

### CODE REVIEW

**Comment by dogmaphobic** [comment]
TC failure is on a file I did not change: UAS.cc (and it's Windows only). It would appear master was already messed up before I added these changes. I can take a look at it but it won't be until much later.

**Comment by dogmaphobic** [comment]
The issue was introduced with #1773. These *double* to *float* warnings are typical Windows. You need to add the *f* suffix to the values assigned to a *float* type variables. Otherwise it assumes is a double and it spits out this truncation warning. Hopefully this fixes it (didn't try a Windows build).

**Comment by DonLakeFlyer** [comment]
TC is running again? Not sure how that happened! From this run it looks like master is ok though since this passed?

**Comment by dogmaphobic** [comment]
It did run, it failed (as shown in the red X in a656c2467c93eeac9cad81598dde280d2742036c above) and I fixed it :)

**Comment by DonLakeFlyer** [comment]
@dogmaphobic So you have master fixed up with this right?

**Comment by dogmaphobic** [comment]
> So you have master fixed up with this right?

No, the fix is in this PR. It's in d06c1906eaf9db497c213277230f88006cda174d above.

**Comment by DonLakeFlyer** [comment]
Right that's what I meant

**Pull request merged**
