### PR TITLE
appveyor install gstreamer

### PR DESCRIPTION
**Pull request by dagar**
TODO
 - [x] copy gstreamer libs to installer

### CODE REVIEW

**Comment by dagar** [comment]
@DonLakeFlyer windows gstreamer is working.

**Comment by DonLakeFlyer** [comment]
Is this good to merge now?

**Comment by dagar** [comment]
Yes, I've tested the installer on windows. Just be aware that we're copying a hand picked list of gstreamer dlls into the installer. I don't know how brittle this is going to be longer term. 
Also please check that I got rid of the proper flightgear directory.

**Comment by DonLakeFlyer** [comment]
I don't know much about flightgear so not sure I can verify that.

**Comment by DonLakeFlyer** [comment]
Seems correct from the .pri changes to resources.

**Comment by dagar** [comment]
It was the exact same directory of flightgear stuff duplicated at the top level and in resources. If something broke it'll be a trivial fix.

**Pull request merged**
