### PR TITLE
Fix QString, QStringLiteral and tr calls

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Comment by patrickelectric** [comment]
@dogmaphobic any update ?

**Comment by dogmaphobic** [comment]
> @dogmaphobic any update ?

As a comment to this PR? It all looks good to me. You are by now, the official QGC _cleaner upper_ :P

**Comment by patrickelectric** [comment]
Well, thank you for the _title_ hehe,but probably @tcanabrava 	will take it for me soon. 
Be free to merge at will.

**Comment by patrickelectric** [comment]
@dogmaphobic 	any update ?

**Comment by dogmaphobic** [comment]
Sorry, I was out and missed this.

**Pull request merged**
