### PR TITLE
Pattern Preset support

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
This allows you to save settings for a Pattern item as a named reusable preset. So for example if you fly a lot of say NDVI surveys at the same altitude and overlap settings you can save that as a preset. Then you create a new survey for a new area, you just select that Preset and you are done setting up the Survey.

Althought the internal archiecture for this is set up to work with all pattern types it is only supported by Survey now. Once we work through the usability of this on Survey then I'll implement in other Patterns.

Screen Shot 2019-04-26 at 10 31 18 AM

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
The docs for this don't seem to be building correctly right now. But they are here: https://docs.qgroundcontrol.com/en/PlanView/PatternPresets.md

**Comment by DonLakeFlyer** [comment]
Also this was a pretty major change to support this. So be careful when using a preset to make sure it really changed the settings to what they should be by switching back to Custom to check the actual settings.

**Comment by DonLakeFlyer** [comment]
For now you can read the .md file directly: https://docs.qgroundcontrol.com/en/PlanView/PatternPresets.md which is somewhat helpful.

**Comment by DonLakeFlyer** [comment]
This greatly simplifies the UI if you are using a preset:
Screen Shot 2019-04-26 at 11 20 58 AM

Further support will be added such that custom build can define their own presets as built in from the start.

One question is whether there is some useful presets which could be included with regular QGC as well.

**Comment by Antiheavy** [comment]
After playing around with it, the functionality is there and seems to work quite well.  I'm trying to decide whether the camera is a subset of the preset or if the preset is a subset of the camera...  arguments both ways....

**Comment by DonLakeFlyer** [comment]
Yeah, the camera thing is a little wierd. I see the need, but I'm not sure it's quite correct as it currently stands.

**Comment by Antiheavy** [comment]
Also, this ability for the user to save custom profiles for things could be useful for Preflight Checklist.

**Pull request merged**
