### PR TITLE
CameraPageWidget: Timelapse indicator, nicer widget

### PR DESCRIPTION
**Pull request by olliw42**
**EDIT 15.11.2019**: I removed the WIP label because I think I sorted it all out now, and the PR is fine IMHO. I also updated the screenshots to reflect the current.

This makes the camera manager widget to be "nicer". No real functional change, just nicer.

1) Adds an indicator to the CameraManager widget when in photo timelapse mode, to indicate this mode and show the current timelapse interval. This addresses point (2) of #7471.

See the first pic below.

2)  In the page widget moves the timelapse fields to the top before the settings field. For cameras with many settings such as a gopro I found it quite inconvenient (annoying) having to have to scroll to the bottom to find them.

3) Adds separators between the standard top and bottom fields, to make the camera specific settings more sticking out.

4) Makes the switches for bool settings to look better by adjusting the spacing such that they align better horizontally

5) Changes title in photo mode from "Camera Settings" to "Photo Settings"

6) Some NFC formatting and some clean up

For changes 2,3,4,5 see the 2nd and 3rd pic below.

cheers, Olli

qgc-nice-001

qgc-nice-002

qgc-nice-003

### CODE REVIEW

**Comment by olliw42** [comment]
would anymone mind giving advice on 
* how to add a new image to the code base/build system/resources?
* where to get svg from? Need to be dawn by our own, could be taken from the web,...?

Thx

**Comment by olliw42** [comment]
sorted it, updated first post, and rebased
is IMHO worth considering now :)

**Comment by olliw42** [comment]
would you guys mind dropping a short note if this is of any interest at all, or not? 

if it's likely it never won't be considered for merging pl close right away. So I at least know :)

**Comment by hamishwillee** [comment]
@dogmaphobic FWIW I think this looks good. I think it is helpful to differentiate title for photo vs video settings. I have a slight personal bias towards Image Settings rather than Photo Settings.

**Comment by olliw42** [comment]
I would wish this PR would be added to the 4.0 MileStone :):):)

It's really not a very complicated PR.

**Comment by hamishwillee** [comment]
@dogmaphobic Can you please look at this?

**Pull request closed without merging**
