### PR TITLE
R.Pi2 Support

### PR DESCRIPTION
**Pull request by ChukRhodes**
Allows QGC to run on Raspberry Pi 2 with direct framebuffer (X/startx not needed). Memory split seems to need 128 for GPU. Qt5 needs to be configured with "-opengl es2 -qpa eglfs -device linux-rasp-pi2-g++".

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dagar Could you look at these build file changes? Looks like they change some of the installer stuff.

**Comment by dogmaphobic** [comment]
At first glance, it just isolates things for the RPI. In theory, the rest seems unchanged.

**Comment by ChukRhodes** [comment]
libicu* was not in the Qt5 dir. In the system dir, they don't seem to need to be "installed".

$ locate libicudata.so
/usr/lib/arm-linux-gnueabihf/libicudata.so
/usr/lib/arm-linux-gnueabihf/libicudata.so.52
/usr/lib/arm-linux-gnueabihf/libicudata.so.52.1

The main change needed was QOpenGLFunctions_ES2

**Comment by ChukRhodes** [comment]
The real trouble was building Qt... without going into a huge list of prereqs, most found searching online, the following was needed to build on the pi (takes a day or so).

wget http://download.qt.io/official_releases/qt/5.5/5.5.1/single/qt-everywhere-opensource-src-5.5.1.tar.gz
tar -zxf qt-everywhere-opensource-src-5.5.1.tar.gz
cd qt-everywhere-opensource-src-5.5.1
echo "DEFINES += MESA_EGL_NO_X11_HEADERS" >> qtbase/src/plugins/platforms/eglfs/deviceintegration/eglfs_brcm/eglfs_brcm.pro
echo "INCLUDEPATH += /opt/vc/include" >> qtbase/src/plugins/platforms/eglfs/deviceintegration/eglfs_brcm/eglfs_brcm.pro
echo "INCLUDEPATH += /opt/vc/include/interface/vcos/pthreads" >> qtbase/src/plugins/platforms/eglfs/deviceintegration/eglfs_brcm/eglfs_brcm.pro
echo "INCLUDEPATH += /opt/vc/include/interface/vmcs_host/linux/" >> qtbase/src/plugins/platforms/eglfs/deviceintegration/eglfs_brcm/eglfs_brcm.pro

./configure -v -opengl es2 -qpa eglfs -device linux-rasp-pi2-g++ -nomake tests -nomake examples \ -device-option CROSS_COMPILE=/usr/bin/ -sysroot / -opensource -confirm-license \ -optimized-qmake -reduce-exports -release -qt-pcre -make libs -prefix /usr/local/qt5 | tee \ configure_output

make && sudo make install

**Comment by dagar** [comment]
@ChukRhodes Is your intention to create a tar.bz2 package that works on the raspberry pi without qt installed separately, or is your build just breaking during installer creation?

@DonLakeFlyer if you merge #2527 then the qt libs will only be copied during the end of the installer CONFIG and this might not matter.

**Comment by ChukRhodes** [comment]
My intention was to see *if* it works... as is, this compiles and can be run from the build/release folder. It's about 90% functional, and works with a touchscreen! There appears to be some UI issues to sort out - probably related to ES2/EGLFS instead of full x11 support. I have a debug build of Qt running now, with more libs so runtime options like "-platform eglfs" or "-platform linuxfb" should work.

**Comment by LorenzMeier** [comment]
Sounds pretty cool! Do you have a screenshot of that?

**Comment by LorenzMeier** [comment]
Or maybe even video from the whole assembly?

**Comment by dagar** [comment]
@DonLakeFlyer qmake changes are good if you want to merge.

**Comment by ChukRhodes** [comment]
I was thinking of doing a video eventually, need to move another monitor so I have this 22" Touch (with 12V adapter, ideal for the field) to use with it... and set to auto-login / start the app. Not sure how to get console screenshot, and when running, it looks the same as any other full screen version.

**Comment by ChukRhodes** [comment]
I also compiled this on windows, so changes *shouldn't* effect other builds. Leaves a define for any other code changes needed.

**Comment by DonLakeFlyer** [comment]
Great, thanks for the pull and the review everyone

**Comment by x923386210** [comment]
@ChukRhodes  Can you cross compile for QGC? Successfully？

**Pull request merged**
