### PR TITLE
Add support for UTM adapter (https://github.com/Dronecode/utm-adapter) functionality in qgroundcontrol

### PR DESCRIPTION
**Pull request by govindsi**
This PR adds support for basic functionality of utm-adapter( https://github.com/Dronecode/utm-adapter) , which is configurable adapter for QGCS to enable it to exchange relevant data with a opensource UTMSP.

Specification: (https://github.com/Dronecode/utm-adapter/blob/main/ussp-api/utm-adapter.yaml)
High Level Design:: https://github.com/Dronecode/utm-adapter/tree/main/utm-adapter-architecture-diagrams)
Tested UTMSP: (https://github.com/openutm/flight-blender)
Supported Services: :flight authorization and Network Remote ID

### CODE REVIEW

**Comment by govindsi** [comment]
Initial Draft PR and comments was @ https://github.com/mavlink/qgroundcontrol/pull/10892

**Review by bkueng — APPROVED** [review]
As discussed, let's bring this in now, as all of it is behind a build-time config option (`CONFIG_UTM_ADAPTER`), disabled by default.
[Outstanding points](https://github.com/mavlink/qgroundcontrol/pull/10892#pullrequestreview-1775291010) will then iteratively be addressed.

**Comment by DonLakeFlyer** [comment]
@bkueng You're going to need to add a dummy qml module or something to make this work behind a build flag. Hopefully, can be done quickly. I'm hosed now without a working master.

**Comment by DonLakeFlyer** [comment]
I tried commenting things out to make forward progress but it's all over the place in the Qml. If it can't be dealt with quickly this pull is going to need to be reverted until a workaround is created. Maybe leave the Qml side in with C++ side off.

**Comment by DonLakeFlyer** [comment]
Would also be good to squash commits into something reasonable before pulls get merged in.

**Comment by bkueng** [comment]
This works for me, and I don't get the `qrc:/qml/MainRootWindow.qml:23:1: module "QGroundControl.UTMSP" is not installed` error (w/o `CONFIG_UTM_ADAPTER` - there is a dummy qml for that). Do you use qmake or cmake? And did you do a clean build?

**Comment by DonLakeFlyer** [comment]
I did a cmake. Maybe that's it?

**Comment by bkueng** [comment]
Indeed it was cmake only. I have a fix here: https://github.com/mavlink/qgroundcontrol/commit/44fcecb619f68337e6edae696de811d1e2ad2e3c

**Comment by DonLakeFlyer** [comment]
Thanks @bkueng

**Pull request merged**
