### PR TITLE
Pr small video tweaks

### PR DESCRIPTION
**Pull request by tcanabrava**
Some changes on top of @andrewvoznytsa `pr-small-video-tweaks` as he's no longer active.

### CODE REVIEW

**Comment by tcanabrava** [comment]
@MatejFranceskin @andrewvoznytsa  @DonLakeFlyer @dogmaphobic  Please review. This is work on top of @andrewvoznytsa latest work fixing some issues. needed to fix video issues on 4.0 and also for the multiple video stream.

**Comment by andrewvoznytsa** [comment]
@tcanabrava my private opinion is that it would be best to finish with https://github.com/mavlink/qgroundcontrol/pull/8596 first and then continue with everything else (video related).

**Comment by tcanabrava** [comment]
> @tcanabrava my private opinion is that it would be best to finish with #8596 first and then continue with everything else (video related).

this is the continuation of #8596, there's no code here besides fixes on that PR. because you have limited time now I wanted to help @MatejFranceskin on it.

**Comment by andrewvoznytsa** [comment]
@tcanabrava - yes, I see that it is continuation. But I prefer to have my piece of work to be merged as I left it - that makes it easier to find my PR sets and use them as needed (just yet another Lego brick).

Regarding helping @MatejFranceskin - there is VideoManager which was sanitized just to be able to work with new VideoReceiver. IMHO if you finish what we've discussed during multiple calls and slack conversation then it will be biggest improvement since last VideoReceiver upgrade. I'm open to find some time to help with VideoReceiver API and behavior, if needed.

**Comment by tcanabrava** [comment]
Sure, I can leave this open and just rebase on top of yours when yours land. this is more of a "gus, we are waiting for you".

**Comment by andrewvoznytsa** [comment]
Unbelievable but fact - https://github.com/mavlink/qgroundcontrol/pull/8596 was merged. IMO time to rebase your changes. From my side your changes look good enough for this sample app.

**Comment by jaxxzer** [comment]
Closing in favor of https://github.com/mavlink/qgroundcontrol/pull/8759

**Pull request closed without merging**
