### PR TITLE
Remove Deprecated QMake Build System

### PR DESCRIPTION
**Pull request by HTRamsey**
Remove everything related to qmake or no longer needed. Left the git submodules however in the event we end up using them

### CODE REVIEW

**Review by DonLakeFlyer — APPROVED** [review]

**Comment by DonLakeFlyer** [comment]
Yay!

**Comment by DonLakeFlyer** [comment]
Moving from qmake to cmake has been in the works for years now.  This is both from a QGC standpoint and also from the standpoint of Qt itself. During that transition time we have maintained both build systems. With the move of daily to Qt6 we have changed fully to cmake only.

**Comment by simiken1234** [comment]
So what is now the recommended way to create an appimage of a customized version please?

**Comment by HTRamsey** [comment]
> So what is now the recommended way to create an appimage of a customized version please?

That's in the docs

**Pull request merged**
