### PR TITLE
Handle settings when armed

### PR DESCRIPTION
**Pull request by dogmaphobic**
Instead of blocking all settings if the vehicle is armed, check the provided `VehicleComponent::allowSetupWhileArmed()` method. This change not only disables the settings button, but also shows @jaxxzer's overlay only when appropriate.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
The button shouldn't disable. It should stay enabled so the user can see the message which says unavailable when armed. Otherwise they don't know what is going on. This matches how it worked before.

**Comment by dogmaphobic** [comment]
> The button shouldn't disable.

Are you sure about that? I would assume that's expected that some things change state when a vehicle is present and/or armed. That overlay is a bit messy. I didn't do anything because it was only shown in rare cases where you somehow were in it when the vehicle was armed. If the buttons are to remain enabled, I need to come up with something a little more polished.

Note the "Firmware" button disabled. I left it here for contrast. It should be obvious you can't do certain things when the vehicle is armed.

screen shot 2018-01-16 at 7 43 36 pm

**Comment by dogmaphobic** [comment]
Alright, buttons back to enabled. I can make it "pretty" later.

**Comment by jaxxzer** [comment]
Consider you may also want to check on something in one of those pages while the vehicle is armed. Before, the overlay was opaque, I made it transparent for this reason. This way, you can see the settings, but you can't edit them.

**Comment by dogmaphobic** [comment]
I've tweaked the UI. The semi opaque overlay remains the same but the "Disable while armed" text is now next to the title and away from the middle of the screen.

screen shot 2018-01-17 at 12 00 37 pm

**Comment by DonLakeFlyer** [comment]
Old code didn't use opaque. It just had a rectangle with the working. I'd rather not change the semantics from the way it worked before. I don't want to have to explain over and over again why the buttons are disabled. The message saves me customer support.

**Comment by dogmaphobic** [comment]
The message is there in red. Should I change this? To what? I don't know what this used to look like before @jaxxzer's change.

**Comment by DonLakeFlyer** [comment]
I think what you have is fine. What jaxxzer says about sort of seeing values is intersting. 

Previous was a black rectangle that said some centered words in white. Look in old pull if you want to know exact. Yours is better.

**Comment by jaxxzer** [comment]
For convenience: https://github.com/mavlink/qgroundcontrol/commit/f11f006b1b3c41a44ea8777413e6b4dd464b9a37#diff-9592a40212849f1b9dc1e22e173496a7

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Can you rebase this to master to get units test working?

**Pull request merged**
