### PR TITLE
[WIP] QGCApplication: set style for all OS

### PR DESCRIPTION
**Pull request by jaxxzer**
Following up with https://github.com/mavlink/qgroundcontrol/pull/8736 in regard to https://github.com/mavlink/qgroundcontrol/issues/8484

This ui fix was previously applied to linux only, but windows was still demonstrating the same problem

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
I"m confused. This was stated to me as a Linux only problem?

**Comment by jaxxzer** [comment]
There was a bit of a mixup. The original ticket applied to android specifically.
We should have opened a new issue for the https://github.com/mavlink/qgroundcontrol/pull/8736 fix, as it focused on a similar ui issue that arose on desktop after the 4.0 stable release.

This is what users are currently seeing in windows on 4.0.6:
image

**Comment by DonLakeFlyer** [comment]
> This is what users are currently seeing in windows on 4.0.6:

What I don't understand is why this changes fix it? Things should be positioned and sized based on default font point sizes. I don't see how that is affected by this change?

**Comment by DonLakeFlyer** [comment]
So I see two things here:
* The sizing problems which I will take a look at but just look like implementation bugs with respect to ratio based sizing/positioning. Changing a control style may move things around and make these bugs appear to be gone but in reality they are not. Even after whatever is screwed up with sizing/positioning is fixed things can still end up not fitting. Anything that has the possibility of happening should be in a flickable so you can still get to everything. Users can bump the font size up which can easily cause things to get bigger than the available space. And the user should still be able to interact with all the parts of the ui.
* The control style thing. According to docs there is a "Default Style" which is what you get if you don't specify a specific style. QGC doesn't want to have it's ui changed based on some environment variable. Hence I would say that the correct change is to always set to default style to bast over any random environment variable setting. And that Universal Style is incorrect since that is some fancy Microsoft guidelines style.

**Comment by DonLakeFlyer** [comment]
The problem with the Video Page is that it uses a TextField instead of a QGCTextField:
```
        TextField {
            id: videoFileName
            visible: QGroundControl.videoManager.isGStreamer
            width: 100
        }
```

 This TextField then comes from the control "style" and hence is affected by whatever style is selected. When you switch to a "Universal Style" that style just happens to have a smaller control for TextFields which all of a sudden makes things fit. Also page isn't in a flickable which means it can grown larger than it's bound without the suer being able to get to what they need to go to. 

I'll fix all of this up in Stable and bring across.

**Comment by DonLakeFlyer** [comment]
Also the file name label is randomly in a different size font than everything else!

**Comment by jaxxzer** [comment]
@DonLakeFlyer thanks for all of that. This was a bit of a shot in the dark on my part.

**Comment by jaxxzer** [comment]
For what it's worth, the build artifact for windows is working better after this fix.

**Comment by DonLakeFlyer** [comment]
It smelled funny right from the start. I should have went with my gut initially.

**Comment by DonLakeFlyer** [comment]
> the build artifact for windows is working better after this fix.

Just dumb luck on the TextField implementation in Universal Style being smaller and letting things fit.

**Comment by DonLakeFlyer** [comment]
This is all fixed up now

**Pull request closed without merging**
