### PR TITLE
Windows UX improvement: improve the windows 1.5s closing workaround

### PR DESCRIPTION
**Pull request by stefandunca**
Fix application hanging on windows for 1.5s when closing.
The PR removes the old workaround that's not needed anymore.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@stefandunca Did you verify that the hack was still needed at all on Windows? This was likely for a version of Qt which is years gone.

**Comment by stefandunca** [comment]
@DonLakeFlyer I did not check. I will test it and remove the hack if it's not needed anymore. Thanks.

**Comment by DonLakeFlyer** [comment]
@stefandunca Any updates?

**Comment by stefandunca** [comment]
I lost my windows dev setup. I'm going to do it allover again and get some progress on this.

**Comment by DonLakeFlyer** [comment]
So close this pull?

**Comment by stefandunca** [comment]
@DonLakeFlyer I've rebased and tested the change. QGC works as expected on windows. You can merge the patch now. Thanks

**Comment by DonLakeFlyer** [comment]
@stefandunca I'm going to take over you pull and create a new one so I can see if I can handle #7754 as well as your changes and test it all together.

**Comment by DonLakeFlyer** [comment]
@stefandunca Nope, I'll merge this first.

**Pull request merged**
