### PR TITLE
VehicleSetup: firmware upgrade use static map of px4 boards names

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
Tested on a few random boards like the CUAV v5+, CubeOrange, etc.

**Comment by DonLakeFlyer** [comment]
Yeah, much simpler thanks. But can you leave the board ids in the header and use them in `px4_board_name_map `? Having raw numbers there just seems really odd. Also having them in a separate header provides a consistent place for them which is firmware independent. I often look up a board id when I'm debugging things.

**Comment by DonLakeFlyer** [comment]
Fix for #9215

**Comment by DonLakeFlyer** [comment]
@dagar Could you get this working? I need it for Stable.

**Comment by dagar** [comment]
Needs fmu-v2/v3 testing.

**Comment by DonLakeFlyer** [comment]
> Needs fmu-v2/v3 testing.

I'll do that today.

**Pull request merged**
