### PR TITLE
Better help for alt mode

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
What each one looks like:
screen shot 2018-05-23 at 3 20 40 pm
screen shot 2018-05-23 at 3 20 47 pm
screen shot 2018-05-23 at 3 20 52 pm
screen shot 2018-05-23 at 3 20 57 pm

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@AndKe FYI...

**Comment by AndKe** [comment]
Great, once you are at it, please mention the difference between source of data, and where it is applied for AGL and terrf (at GCS, incorporated into waypoints, Vs onboard, based on terr messages.)

**Comment by DonLakeFlyer** [comment]
That's going to be end up being way too much text. @hamishwillee Do you have any ideas where. There is small space for text, but not too much.

**Comment by DonLakeFlyer** [comment]
Merging this since it's better. Then we can discuss with Hamish for something even better.

**Comment by AndKe** [comment]
What about something short like:
"Calculated from terrain data" ->  "GCS add Google's altitude data"  (or other vendor, or "internet")
"Using terrain reference frame" -> "Above terrain reference in AP"

In both cases, it's clear where the calculation is done, and it's not very long.

**Pull request merged**
