### PR TITLE
Update flight mode naming

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Replacement for #3009

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Looks like its good to go.

**Comment by DonLakeFlyer** [comment]
Yup

**Comment by DonLakeFlyer** [comment]
Hmm, it won't compile without that. I don't see where was it getting the defines in your version?

**Comment by DonLakeFlyer** [comment]
I'm gonna merge and we can figure out the other part later.

**Pull request merged**
