### PR TITLE
Move ArduPilot preflight check handling to generic QGC

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Replacement for #6436

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dagar Can you do some testing with this?

**Comment by bkueng** [comment]
I tested this against https://github.com/PX4/Firmware/pull/10586: it works, but can we check the log level? Some messages are only warnings and will still allow arming (and thus should not appear on the screen).

Can you add a semitransparent background box around the text? It's a bit hard to read depending on the location.

**Comment by DonLakeFlyer** [comment]
@bkueng What severity should show on the map?

**Comment by bkueng** [comment]
>= critical

**Comment by DonLakeFlyer** [comment]
@bkueng Can you try it again.

**Comment by bkueng** [comment]
It works, thanks. I noticed that github rendered my reply not as expected. I meant to say `>= critical`.

**Comment by DonLakeFlyer** [comment]
> I meant to say `>= critical`.

I'll change that.

**Pull request merged**
