### PR TITLE
Adding access to the vehicle hobbs meter

### PR DESCRIPTION
**Pull request by dogmaphobic**
Finally, in response to https://github.com/mavlink/qgroundcontrol/issues/4506

Added access to a string containing the vehicle's hobbs meter.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Could you instead plumb this through as one of the Vehicle FactGroup things. THen it will be available from the instrument panel.

**Comment by dogmaphobic** [comment]
>Could you instead plumb this through as one of the Vehicle FactGroup things. THen it will be available from the instrument panel.

I will need to figure out how to do that. What can I use as a starting point (something to copy)?

**Comment by DonLakeFlyer** [comment]
If you look in Vehicle.h you'll find:
```
    // FactGroup object model properties

    Q_PROPERTY(Fact* roll               READ roll               CONSTANT)
    Q_PROPERTY(Fact* pitch              READ pitch              CONSTANT)
    Q_PROPERTY(Fact* heading            READ heading            CONSTANT)
    Q_PROPERTY(Fact* groundSpeed        READ groundSpeed        CONSTANT)
    Q_PROPERTY(Fact* airSpeed           READ airSpeed           CONSTANT)
    Q_PROPERTY(Fact* climbRate          READ climbRate          CONSTANT)
    Q_PROPERTY(Fact* altitudeRelative   READ altitudeRelative   CONSTANT)
    Q_PROPERTY(Fact* altitudeAMSL       READ altitudeAMSL       CONSTANT)
    Q_PROPERTY(Fact* flightDistance     READ flightDistance     CONSTANT)
    Q_PROPERTY(Fact* distanceToHome     READ distanceToHome     CONSTANT)
```

Those are the top level facts exposed to the instrument panel through the vehicle FactGroup. Just pull the string on any of those and you should find the places. It's basically a variant of Fact and Fact meta data setup.

**Comment by dogmaphobic** [comment]
I've added but I don't think that system handles a "string" value. It shows up as a single "0" instead of the actual (valid) string. I will take a look at it later...

**Comment by dogmaphobic** [comment]
For what's worth, the value comes into separate 32-bit parameters. They must be computed and transformed from a 64-bit time in microseconds to a string representing hhhh:mm:ss. That's what the current `hobbsMeter` property returns. A QString value.

While at it, as they are parameters, they are only updated when you connect. It doesn't increment until you request the parameters again. I also don't understand how the parameter cache works when this value changes each time you connect.

**Comment by DonLakeFlyer** [comment]
If you set the type to string in the meta data and Fact creation it should work. It could be a bug in Fact::enumOrValueString which that page uses.

> I also don't understand how the parameter cache works when this value changes each time you connect.

I basically means the cache is now broken and will never hit.

**Comment by DonLakeFlyer** [comment]
Supporting volatile parameters and keeping the cache working is going to be a bunch of work.

**Comment by dogmaphobic** [comment]
I've plumbed it through Vehicle FactGroup (in addition to the existing *property*). The issue I was having was one of initialization. I need to signal a value change when all parameters are loaded.

**Comment by dogmaphobic** [comment]
And this is what it looks like for now:

screen shot 2017-11-12 at 3 30 48 pm

**Comment by DonLakeFlyer** [comment]
Nice

**Pull request merged**
