### PR TITLE
Fix cmake build

### PR DESCRIPTION
**Pull request by s-lisovenko**
-Increase C++ standard to C++17 as for qmake build
-Add missing files for remote id
-Add missing files for custom action

### CODE REVIEW

**Comment by sypaq-nexton** [comment]
Thanks. I didn't realise I broke the CMake build when I added the Custom Actions...

**Comment by booo** [comment]
Could we split this up in multiple commmits?

What are the implications of the C++ standard change?

**Comment by s-lisovenko** [comment]
> Could we split this up in multiple commmits?
> 
> What are the implications of the C++ standard change?

I split the commit into two separate commits.

About С++17 еhere are 2 reasons for increasing the standard
1. qmake build uses c++17
2. Compilation errors
For example for QGCCachedFileDownload.cc file deduction type error
Screenshot from 2023-04-06 07-37-06

**Comment by booo** [comment]
Thanks a lot for your contribution!

**Pull request merged**
