### PR TITLE
Preflight checklist when no vehicle is connected

### PR DESCRIPTION
**Pull request by dakejahl**
Rather than using the DefaultChecklist when no vehicle is connected, we can first check to see if we have an idea about which vehicle type is expected by first checking **QGroundControl.settingsManager.appSettings.offlineEditingVehicleType**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
This ends up being a little wierd from a code duplication standpoint. You should be able to do something like this:
```
var vehicle = activeVehicle
if (!vehicle) {
   vehicle = QGroundControl.multiVehicleManager.offlineEditingVehicle
}
```

And then fall through to the existing code tweaked to use vehicle instead of activeVehicle. Does that make sense?

**Comment by DonLakeFlyer** [comment]
Perfect thanks

**Comment by dakejahl** [comment]
Yes that's a much simpler way to do it, I didn't realize the multi vehicle manager exposed that

**Comment by dakejahl** [comment]
Should I open a PR into master for this as well or does v4.0 get merged
back in to master?

**Comment by DonLakeFlyer** [comment]
I'll merge Stable_V4.0 across to master today sometime. There a pile of stuff in there that needs to come across.

**Pull request merged**
