### PR TITLE
Better Mavlink 2.0 handshake code

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Fix for #4198:
* State of decode for first mavlink packet is kept on link by link basis instead of single value for all of QGC.
* QGC will switch to outbound Mav 2 if it gets inbound Mav 2
* QGC will swich to outbound Mav 2 if Vehicle reports Mav 2 capability
* QGC will **not** switch back to outbound Mav 1 from Mav 2 if it gets inbound Mav 1

Note: Multi-vehicle Mav 2 issues are still not fixed / figured out.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@LorenzMeier @bkueng I could use review / testing on this.

**Comment by bkueng** [comment]
This looks good, I'll test it tomorrow.

**Comment by NaterGator** [comment]
> Multi-vehicle Mav 2 issues are still not fixed / figured out.

Is keeping a hash table of system_id (plus maybe component_id) as a key for mavlink channels that are independently spec'd to 1.0 vs 2.0 viable? Technically we should be able to support up to 256 channels through defining MAVLINK_COMM_NUM_BUFFERS.

**Comment by DonLakeFlyer** [comment]
@NaterGator It's a bit more complicated than that. The issue is that on the inbound direction you don't know system id until after you parse the message. You need the mavlink channel before you parse the message, hence for inbound it can only be associated a link and not a specific vehicle.

**Comment by NaterGator** [comment]
Ok, could you not run 2 parallel receive channels per link (both mavlink versions), then store the preferred outbound channel version in a hash table? Sorry I know I'm kinda hit-and-running on this...

**Comment by DonLakeFlyer** [comment]
It's more that you need to do a dance with mavlink_status_t structures replacing ones back and forth, copying stuff in/out for inbound/outbound channels/vehicles. Right now things like the message sequence numbers and so forth are all out of whack with the channel == link semantic and multiple vehicles on same link. It needs to move to channel == vehicle, but that requires not using the standard channel/mavlink_status_t support that comes from the headers. I think I know how to do it, just haven't done it yet. Or gotten far enough through it identify additional gotchas.

**Comment by NaterGator** [comment]
Understood; I'll be looking for distractions this weekend so I may see if I can come up with a clean PR as well.

**Comment by DonLakeFlyer** [comment]
It's also a little complicated since you need to take into account / support FirmwarePlugin::adjust[Incoming|Outgoing]MavlinkMessage as well. You need to be able to do that without screwing channel status info.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier Given the SiK Radio Mav 2 problem it seems like this change will break a lot of things since new PX4 firmware announces mav 2 availaility in all cases. Doesn't seem like a good idea to push this through at this point?

**Comment by LorenzMeier** [comment]
Yeah, this is indeed a problem. Since we can't detect the radio's Firmware version the best we can do is probably to introduce a param to not send the flag if the link is on a 3DR radio.

**Comment by DonLakeFlyer** [comment]
Ok. So then I say QGC does this:
* QGC will switch to outbound Mav 2 if it gets inbound Mav 2
* QGC will **not** switch to outbound Mav 2 if Vehicle reports Mav 2 capability
* QGC will not switch back to outbound Mav 1 from Mav 2 if it gets inbound Mav 1

**Pull request closed without merging**
