### PR TITLE
travis-ci try ccache on OSX and android

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
@DonLakeFlyer do you have any experience with ccache on OSX? If we can override QMAKE_CXX I think it would really help build times.

**Comment by DonLakeFlyer** [comment]
Nope, don't know anything about it

**Comment by NaterGator** [comment]
@dagar just add:
`QMAKE_CXX = ccache $$QMAKE_CXX` 

[here](https://github.com/mavlink/qgroundcontrol/blob/53a49fdcd28fbe74a6fdce5d47779bb1541891f7/QGCCommon.pri#L53)

**Comment by dagar** [comment]
Replaced by #3631

**Pull request closed without merging**
