### PR TITLE
Maps:Added Statkart Topo2 (very useful norwegian topographic map)

### PR DESCRIPTION
**Pull request by AndKe**
This map is an absolute necessary for navigating the northern part of the country, steep mountains and deep valleys.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Can you take a look at this?

**Comment by AndKe** [comment]
BTW: due to groundcontrol not saving last map position&zoom (and even if it did)   - when you open the application with this map, you need to zoom out a *lot*  - until Norway can be seen, then zoom in.

**Comment by dogmaphobic** [comment]
Implementation looks correct. I understand the usefulness for someone in Norway but I wish there was a way for this not to be *global*. That is, it's an option for 0.06% of the population. If we start adding specialized maps for everything, we will end up with a rather large list of map sources. With that said, I can't think of a way to narrow the options so it is what it is.

**Comment by AndKe** [comment]
I don't think others will be bothered by it, after all, it's just something in a droplist in settings.

**Comment by DonLakeFlyer** [comment]
I'll do some testing of this tomorrow.

**Comment by DonLakeFlyer** [comment]
Tested and looks good. Thanks @AndKe

**Pull request merged**
